### ISSUE TITLE
ConnectionClosed: SSLWantWriteError

### ISSUE THREAD

**Issue by will3942** [pika/pika#1003]
Connection Adapter: BlockingConnection
Pika version: 0.11.2

Since moving to an AMQP setup with SSL when trying to use basic_publish with a large message I get the following error:

`pika.exceptions.ConnectionClosed: (-1, "SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2074)')")`

Messages are able to be consumed correctly still.

Previously when using no SSL we were not getting any errors.

I've tried searching for causes but can't seem to find anyone having a similar problem!

Partial Traceback:

```
    send_result = output_channel.basic_publish("", next_plugin, json.dumps(payload), pika.BasicProperties(content_type='text/plain', delivery_mode=2))
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2127, in publish
    self._flush_output(self._message_confirmation_result.is_ready)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2074)')")
```

**Comment by will3942** [comment]
This appears to have fixed it (for now?):

```
from gevent import monkey
monkey.patch_all()
```

**Comment by jstasiak** [comment]
I believe this is fixed in https://github.com/pika/pika/commit/32723b851c966042fac6304a6e6c79480c5e298e (not released yet).

Be advised that gevent monkey patching is absolutely not an answer here, it has significant consequences other than silencing this issue (it does so because gevent's ssl socket write() implementation retries internally).

**Comment by will3942** [comment]
cc: @bauhausbadguy

**Comment by stuartspotlight** [comment]
I've tried git cloning and installing using setup.py on 32723b8 and I get the error:-

```
No module named 'pika.compat'
```
Is this a known issue with that commit?

**Comment by lukebakken** [comment]
@stuartspotlight yes that was fixed by https://github.com/pika/pika/commit/973ebc3a9191214b0c500a7332d50876f8e48cde

**Comment by stuartspotlight** [comment]
I've git cloned version 1.0.0b1 and that does seem to have fixed the issue

**Comment by stuartspotlight** [comment]
large messages sent over ssl also appear to be working
