### ISSUE TITLE
[v.1.0.0] Channel.basic_consume, etc. completion callback should be passed the Channel instance as first arg

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#1005]
`Channel.basic_consume()`'s `callback` arg should be called with callback(Channel, pika.frame.Method) for consistency with other such callbacks, where Channel is the instance of the channel on which the consumer was requested.

Ditto for:
* `Channel.basic_cancel()`
* queue_declare()
* queue_delete()
* ... probably others, need to review all `Channe`l methods accepting callbacks (there aren't that many)

This can be easily accomplished via `functools.partial()` before passing the callback to `self._rpc()`.

**Also, the documentation for both functions needs to make it clear what the callback signature is (e.g., `basic_cancel()` does not appear to provide a signature at all in the docstring.

**Comment by lukebakken** [comment]
Looks like we missed the boat to ensure that channel is always passed, but I'll make sure the docstrings are accurate.

**Comment by vitaly-krugl** [comment]
Thanks for the update Luke.


Best,
Vitaly
