### ISSUE TITLE
Heartbeats active even though client configured with heartbeat=0

### ISSUE THREAD

**Issue by levsa** [pika/pika#1014]
I have a pika client configured with heartbeat=0, but I still see this in the logs:

`pika.exceptions.ConnectionClosed: (320, 'Too Many Missed Heartbeats, No reply in 120 seconds')`

I've skimmed through the code, and it looks like that if the client's heartbeat is 0 and a connection tune occurs, the negotiation will set the client's heartbeat to what the server reports if it is > 0. Although I may be missing something else in the code. Is this a bug or a usage error on my side?

Code that creates the connection:
```
    def create(self):
        credentials = pika.PlainCredentials(username=self.configuration.username,
                                            password=self.configuration.password)
        parameters = pika.ConnectionParameters(host=self.configuration.hostname,
                                               port=self.configuration.port,
                                               credentials=credentials,
                                               heartbeat=0)
        return pika.BlockingConnection(parameters)
```

**Comment by lukebakken** [comment]
Please give the [`0.12.0b2`](https://github.com/pika/pika/releases/tag/0.12.0b2) release a test. Packages are available on pypi, and can be installed using this command

```
pip install pika --pre
```

**Comment by lukebakken** [comment]
Thank you for letting us know.
