### ISSUE TITLE
Queue size

### ISSUE THREAD

**Issue by bhack** [pika/pika#1021]
Add an easy method to check the queue size (i.e. exit when the queue is empty).

**Comment by lukebakken** [comment]
Queue length is available via the HTTP API 

https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.4/priv/www/api/index.html

https://stackoverflow.com/q/24402399

**Comment by bhack** [comment]
I meant if we can automate message count with res.method.message_count like in https://stackoverflow.com/a/13629296

**Comment by bhack** [comment]
Other API has http://pyrabbit.readthedocs.io/en/latest/api.html#pyrabbit.api.Client.get_queue_depth

**Comment by lukebakken** [comment]
@bhack since doing a passive queue declare accomplishes what you need, you should do that. Pika is a pretty low-level library that in general does not support superfluous convenience features -

```
# Re-declare the queue with passive flag
res = channel.queue_declare(
        callback=on_callback,
        queue="test",
        durable=True,
        exclusive=False,
        auto_delete=False,
        passive=True
    )
print 'Messages in queue %d' % res.method.message_count
```

**Comment by luiscoms** [comment]
is it possible to get queue size without declare it?

**Comment by lukebakken** [comment]
@luiscoms - please ask on the [`pika-python`](https://groups.google.com/forum/?pli=1#!forum/pika-python) or [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list so others can learn from the answer. Thanks for using Pika.
