### ISSUE TITLE
Some documentation typos

### ISSUE THREAD

**Issue by nikolaevigor** [pika/pika#1022]
[Here](https://github.com/pika/pika/blob/master/docs/examples/asynchronous_consumer_example.rst) I noticed some typos.
In `def setup_queue(self, queue_name)` last line:
* should be: `self._channel.queue_declare(self.on_queue_declareok, queue_name)`
* now: `self._channel.queue_declare(queue_name, self.on_queue_declareok)`

In `def start_consuming(self)` last line:
* should be: `self._consumer_tag = self._channel.basic_consume(self.on_message, self.QUEUE)`
* now: `self._consumer_tag = self._channel.basic_consume(self.QUEUE, self.on_message)`

Otherwise:
`ValueError: callback must be a function or method` is raised

Can fix this with PR

**Comment by lukebakken** [comment]
Please see my comment [here](https://github.com/pika/pika/pull/1017#issuecomment-381596452): [link](https://github.com/pika/pika/pull/1017#issuecomment-381596452)

The examples and documentation are in-sync with the state of development. By default, GitHub will show `master`. If you are using Pika `0.11.2`, you must **first** select that tag in the GitHub UI, then navigate to the documents or examples you wish to use.

**Comment by lukebakken** [comment]
Are you testing the `master` branch of Pika?

If you'd like to open a PR, please do so. Thanks!

**Comment by nikolaevigor** [comment]
You are right, I am using 0.11.2 version, which documentation is correct. Sorry for bothering :)

**Comment by lukebakken** [comment]
No problem!
