### ISSUE TITLE
[Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by ajayimade** [pika/pika#1027]
```
import pika
import json
from config import RABBITMQ

class Producer(object):
    def __init__(self, queue_name, host='localhost', port=5672,
                 username='guest', password='guest'):
        self.queue_name = queue_name
        credentials = pika.credentials.PlainCredentials(username, password)
        self.connection = pika.BlockingConnection(pika.ConnectionParameters(
            host=host, port=port, credentials=credentials))
        self.channel = self.connection.channel()
        self.channel.queue_declare(queue=self.queue_name, durable=True)

    def call(self, queuing_job):
        self.channel.basic_publish(exchange='',
                                   routing_key=self.queue_name,
                                   body=json.dumps(queuing_job),
                                   properties=pika.BasicProperties(
                                       delivery_mode=2)
                                   )

    def close(self):
        self.connection.close()

```
It works very well but now throwing error.
/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.pyc in _flush_output(self, *waiters)
    464                                      maybe_exception)
    465                         if isinstance(maybe_exception, Exception):
--> 466                             raise maybe_exception
    467                         else:
    468                             raise exceptions.ConnectionClosed(maybe_exception)

error: [Errno 11] Resource temporarily unavailable

Rabbitmq server is running. Couldn't understand why this error thrown

**Comment by lukebakken** [comment]
There's not enough information to diagnose this. If you can provide the following, re-open this issue.

* What version of Pika and Python?
* What version of RabbitMQ and Erlang?
* What operating system?
* Can you provide reproduction steps? This is not an issue that has been reported before and is probably specific to your environment.

**Comment by lukebakken** [comment]
Please use a newer version of RabbitMQ and Erlang.
