### ISSUE TITLE
Remove adapters/twisted_connection.py due to lack of test coverage. (pika v1.0.0 release target)

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#1031]
The `twisted_connection` module was added in 2011, but to this date still has no meaningful test coverage. It's unmaintainable without comprehensive test coverage and therefore pika cannot release v1.0.0 with `twisted_connection` in it.

We literally don't know whether it works at all at this point and which API methods are working/broken.

I am hoping that this issue will inspire someone with interest in the twisted adapters to add comprehensive test coverage shortly. Barring that, `twisted_connection` must be removed from the package.

See the following for examples of pika acceptance test suites:
* https://github.com/pika/pika/blob/master/tests/acceptance/async_adapter_tests.py
* https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py

See also issues #615 and #616.

**Comment by vitaly-krugl** [comment]
cc @lukebakken

**Comment by wulczer** [comment]
Hey, as the original author of the adapter I'm OK with removing it if no one (including me) finds the time to add test coverage.

I'll do my best to get something written, but I can't promise anything and if you decide it's time to cut a 1.0.0 and I haven't gotten my act together, go ahead and get rid of it.

**Comment by cellscape** [comment]
I no longer use pika with twisted, removing is fine by me.

**Comment by Zephor5** [comment]
Thx for the information, it's ok for me. Maybe I'll get something done in the future.

**Comment by glyph** [comment]
Does #1069 cover the code that resolves this?

**Comment by vitaly-krugl** [comment]
Yes, it does.

**Comment by glyph** [comment]
Thanks so much to @abompard for keeping the Twisted dream alive! 🎉

**Comment by wulczer** [comment]
Thank you indeed @abompard - and apologies for not keeping up with the maintenance of the adapter. Three cheers for the Twisted community!
