### ISSUE TITLE
Warning Connection, Connection to ::1:5672 failed: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by msudgh** [pika/pika#1037]
I used pika as RabbitMQ driver and while on initiation of my class I'll create a new instance of `BlockingConnection` but when running the app I got below log:

```bash
(DC) ↳ INFO - Connecting to ::1:5672
(DC) ↳ WARNING - Connection to ::1:5672 failed: [Errno 111] Connection refused
(DC) ↳ INFO - Connecting to 127.0.0.1:5672
(DC) ↳ INFO - Created channel=1
```
Should be worried about that and what's wrong exactly?

**Comment by vitaly-krugl** [comment]
Looks normal to me. Pika gets both IPv6 and IPv4 addresses from DNS address resolution. Your RabbitMQ broker is most likely not listening on IPv6, so pika was unable to connect to it.

Please submit a pika pull request that changes the logging level of that message from warning to info.

Cheers!
