### ISSUE TITLE
[Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by ajayimade** [pika/pika#1038]
```
import pika
import json
from config import RABBITMQ

class Producer(object):
    def __init__(self, queue_name, host='localhost', port=5672,
                 username='guest', password='guest'):
        self.queue_name = queue_name
        credentials = pika.credentials.PlainCredentials(username, password)
        self.connection = pika.BlockingConnection(pika.ConnectionParameters(
            host=host, port=port, credentials=credentials))
        self.channel = self.connection.channel()
        self.channel.queue_declare(queue=self.queue_name, durable=True)

    def call(self, queuing_job):
        self.channel.basic_publish(exchange='',
                                   routing_key=self.queue_name,
                                   body=json.dumps(queuing_job),
                                   properties=pika.BasicProperties(
                                       delivery_mode=2)
                                   )

    def close(self):
        self.connection.close()

```
It works very well but now throwing error.
/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.pyc in _flush_output(self, *waiters)
    464                                      maybe_exception)
    465                         if isinstance(maybe_exception, Exception):
--> 466                             raise maybe_exception
    467                         else:
    468                             raise exceptions.ConnectionClosed(maybe_exception)

error: [Errno 11] Resource temporarily unavailable

Rabbitmq server is running. Couldn't understand why this error is thrown.

### System Info:
Python version: 2.7.14
Pika:  0.11.0
RabbitMQ: 3.2.4
Erlang: R16B03
OS-  Ubuntu 14.04

**Comment by vitaly-krugl** [comment]
This sounds like something on the broker side. Take a look at the broker's (RabbitMQ?) logs.

**Comment by michaelklishin** [comment]
See server logs and if you can reproduce, [take a traffic dump](http://www.rabbitmq.com/amqp-wireshark.html). Very likely it's an environment-specific issue.

**Comment by michaelklishin** [comment]
Two hypotheses that immediately come to mind:

 * A socket is no longer in a functional/connected state but [heartbeats](http://www.rabbitmq.com/heartbeats.html) were not enabled or the interval is too high
 * Client is [out of file descriptors](https://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections-open-file-handles-limit)

Both should be reasonably quick to verify.

**Comment by ajayimade** [comment]
When i tried to create object of above class, it throws error at `BlockingConnection` line
    `producer = Producer(QUEUE_NAMES[queue_name], **RABBITMQ)`.

**Comment by vitaly-krugl** [comment]
@ajayimade , a traceback usually consists of multiple lines. Post the entire traceback - i.e., all the frames.

Also, turn on pika debug logging in your app like this: `import logging, sys; l = logging.getLogger('pika'); l.setLevel(logging.DEBUG); l.addHandler(logging.StreamHandler(sys.stderr))` and post the entire log.
