### ISSUE TITLE
No exception is raised when deleting non-existing exchange

### ISSUE THREAD

**Issue by 9dogs** [pika/pika#1040]
Hi,

I try to delete a non-existing exhange with `channel.exchange_delete` method. My understanding is that an exception should be raised, but the method returns `DeleteOk`:

> The client MUST NOT attempt to delete an exchange that does not exist. Error code: not-found
(https://www.rabbitmq.com/amqp-0-9-1-reference.html#exchange.delete)

Is it expected behavior?
I'm using pika 0.10.0, `BlockingChannel`

**Comment by vitaly-krugl** [comment]
This is a feature of RabbitMQ that deviates from AMQP 0.9.1. See http://www.rabbitmq.com/specification.html

**Comment by 9dogs** [comment]
Oh, I've missed that, thanks!

**Comment by michaelklishin** [comment]
The `queue.delete` and `exchange.delete` behavior was changed in 3.0 IIRC.
