### ISSUE TITLE
Publishing Messages at will when using SelectConnection

### ISSUE THREAD

**Issue by razasaad** [pika/pika#1051]
Following the link  for [Async Publisher Example](https://pika.readthedocs.io/en/0.10.0/examples/asynchronous_publisher_example.html), I could not find how publishing a message at will could be achieved when using `SelectConnection`. Is this something that could be achieved? 
My use-case is that I'm trying to publish a message whenever a certain event fires. 

P.S: I know this isn't an issue, but any help would be worth it. :-)

**Comment by vitaly-krugl** [comment]
Closing - rabbitmq-users Google group is a more suitable forum for usage questions.
