### ISSUE TITLE
Set channel max to 2047

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#1054]
See this PR in RabbitMQ: rabbitmq/rabbitmq-server#1594

**Comment by vitaly-krugl** [comment]
@lukebakken, as far as I can tell, no change is necessary in Pika. Pika supports the max defined by AMQP for use with other brokers, but accepts a smaller value from the broker during connection tuning - see https://github.com/pika/pika/blob/61cbdbbd6a1d4fae19e486fe22a06c16c7821bdf/pika/connection.py#L2016-L2018.

**Comment by michaelklishin** [comment]
While that is true, we try to reflect the default in client libraries as well for two reasons:

 * Newer clients can be used against older server versions. It would be nice to have a safer default combination.
 * Developers are likely to check the client's default when in doubt.

**Comment by vitaly-krugl** [comment]
Michael, but that's the whole point of the negotiation that picks the
smallest. Apps should be able to check the negotiated value after
connection establishment and take whatever action necessary. I don't see
any benefit in crippling the client with specific limits from a specific
version of a specific broker implementation when the existing mechanism
already serves that purpose dynamically :)

**Comment by michaelklishin** [comment]
@vitaly-krugl we just want to use a safer default regardless of the server/client combination. It is definitely common to see clients upgrade before the server they connect to. This only changes the default and I don't see how it "cripples the client".

**Comment by michaelklishin** [comment]
@vitaly-krugl would you object if I submit a PR that changes the default to 2047?

**Comment by vitaly-krugl** [comment]
@mklishin, it still doesn't make sense to me, given that there is already a
negotiation mechanism that works. Given that, it wouldn't be right for me
to accept such a PR. However, I won't object if Luke or someone else
accepts it.

**Comment by lukebakken** [comment]
Since Pika will use `2047` from RabbitMQ if a user does not provide a value for `channel_max` **or** if the user provides a value greater than `2047` (or `0`), I think we're safe. If we decrease `pika.channels.MAX_CHANNELS` then validation [here](https://github.com/pika/pika/blob/e2f26db4f41ac7ea6bdc50964a766472460dce4a/pika/connection.py#L227-L229) won't technically be correct anymore since the AMQP spec allows up to 65K channels.
