### ISSUE TITLE
HeartbeatChecker is confused about heartbeat timeouts

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#1055]
cc @lukebakken, the fix should probably be back-ported to the 0.12 release candidate.

`HeartbeatChecker` constructor presently accepts an interval value and an `idle_count` which defaults to 2. `Connection` class instantiates `HeartbeatChecker` with `interval=hearbeat_timeout` and default `idle_count`.

So, if the connection is configured with a heartbeat timeout of 600 (10 minutes), it will pass 600 as the `interval` arg to `HeartbeatChecker`. So, `HearbeatChecker` will emit heartbeats to the broker only once every 600 seconds. And it will detect heartbeat timeout after 1200 seconds.

So, in the event that receipt of the heartbeat by the broker is slightly delayed (and in absence of any other AMQP frames from the client), the broker can erroneously conclude that connection with the client is lost and prematurely close the connection.

This is clearly not what was intended. `HeartbeatChecker` should be detecting a heartbeat timeout after 600 seconds of inactivity. And it should be sending a heartbeat to the broker more often than just once within the heartbeat timeout window.

I see two problems here:

1. Given `HeartbeatChecker`'s present interface, `Connection` should be instantiating it as`HeartbeatChecker(self, interval=float(self.params.heartbeat) / 2, idle_count=2) or something like that (how often does RabbitMQ broker send heartbeats within one heartbeat timeout interval?)
2. `HeartbeatChecker` is not abstracting the internals of heartbeat processing sufficiently. It's constructor should accept the heartbeat timeout value directly (no interval/idle_count business) and encapsulate the frequency of heartbeats internally without bleeding that detail to the `Connection`.

**Comment by lukebakken** [comment]
Just for kicks I will see what the Java client does with regard to heartbeat interval.

**Comment by lukebakken** [comment]
Yep, the Java client divides the heartbeat interval by 2 - [code](https://github.com/rabbitmq/rabbitmq-java-client/blob/71d378eed81b8e8667ee9d7da8d4dbc6307e0eb8/src/main/java/com/rabbitmq/client/impl/HeartbeatSender.java#L79-L87)

**Comment by lukebakken** [comment]
[Here](https://github.com/rabbitmq/rabbitmq-java-client/blob/71d378eed81b8e8667ee9d7da8d4dbc6307e0eb8/src/main/java/com/rabbitmq/client/impl/nio/NioLoop.java#L75) is where a missed server heartbeat exception is determined.
