### ISSUE TITLE
Permission to generate stubs for Pika in typeshed

### ISSUE THREAD

**Issue by waseem18** [pika/pika#1059]
Hi Folks,

I would like to add stubs for Pika to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the Python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

These stubs will be used by mypy and Pycharm. I'll start working on creating stubs after I get permission from the owners of Pika.

Thanks

**Comment by lukebakken** [comment]
Does this require changes to this codebase?

**Comment by waseem18** [comment]
No @lukebakken.  The stubs go into https://github.com/python/typeshed. To create stubs for a third party package, the policy is to get permission of the package owner first. That's why I created this issue.

**Comment by lukebakken** [comment]
Seems fine to me - @vitaly-krugl @gmr any opinions?

**Comment by lukebakken** [comment]
@waseem18 since there hasn't been feedback this should be OK.

**Comment by vitaly-krugl** [comment]
Please keep in mind that pika API will undergo additional tweaks on the way to 1.0 release. Cheers!

**Comment by waseem18** [comment]
Thanks for the information @vitaly-krugl 

I guess I'll wait till the changes happen so that the stubs doesn't break for folks who try to use it.
