### ISSUE TITLE
AttributeError: module 'pika.exceptions' has no attribute 'ConnectionClosedByBroker'

### ISSUE THREAD

**Issue by bolshoydi** [pika/pika#1076]
`pika=0.11.2`
I'm trying to test  this code from README.md

```import pika
while(True):
    try:
        connection = pika.BlockingConnection(parameters)
        channel = connection.channel()
        channel.basic_consume('queue-name', on_message_callback)
        channel.start_consuming()
    # Do not recover if connection was closed by broker
    except pika.exceptions.ConnectionClosedByBroker:
        break
    # Do not recover on channel errors
    except pika.exceptions.AMQPChannelError:
        break
    # Recover on all other connection errors
    except pika.exceptions.AMQPConnectionError:
        continue
```

and it gives me an error `AttributeError: module 'pika.exceptions' has no attribute 'ConnectionClosedByBroker'`
I suppose it's not a bug and you need just repair README.md, according to  [this](http://pika.readthedocs.io/en/0.11.2/_modules/pika/exceptions.html) docs there is class named `ConnectionClosed`.

**Comment by lukebakken** [comment]
Hi @bolshoydi - you are reading the `README.rst` file that corresponds to the `master` branch of Pika, which will become version `1.0.0`. That example is correct for the in-progress development of Pika. You will have to adjust your code to use `ConnectionClosed` - the `README` is correct.

If you view the version of `README.rst` that corresponds to the version of Pika that you are using, you will notice that example isn't there ([file](https://github.com/pika/pika/blob/0.11.2/README.rst)).
