### ISSUE TITLE
Read the Docs redirects to 0.10.0, not newest version

### ISSUE THREAD

**Issue by RasmusWL** [pika/pika#1077]
https://pika.readthedocs.io redirects me to https://pika.readthedocs.io/en/0.10.0/, which then tells me 
> You are not using the most up to date version of the library. 0.11.2 is the newest version.

It would be nice if https://pika.readthedocs.io would just redirect me to the newest version straight away :)

**Comment by lukebakken** [comment]
Searching the issues in this repository for `readthedocs` would have directed you to issue #1000 where I explained that there is nothing we can do about that behavior.

**Comment by RasmusWL** [comment]
My bad. I was only look at open issues. Too bad that RTD are using this weird sorting behavior :(

**Comment by lukebakken** [comment]
Fixed in #1102
