### ISSUE TITLE
Support for consumer priority 

### ISSUE THREAD

**Issue by pawelmarkowski** [pika/pika#1083]
I found old discussion here: http://grokbase.com/t/rabbitmq/rabbitmq-discuss/141e9gw320/consumer-priorities-in-python 

https://www.rabbitmq.com/consumer-priority.html

Is it a functionality that will be implemented in pika in closest future? I believe it will be enough if you add headers parameter to pika.ConnectionParameters(...headers = {}, **kwargs)

We can add to headers["x-priority"] =  10 to implement desired feature. That solves potentially a lot of other issues.

**Comment by lukebakken** [comment]
Hello!

[`basic_consume`](https://github.com/pika/pika/blob/0.12.0/pika/channel.py#L274) already supports arguments. This should accomplish what you want. Give it a try and let me know if it doesn't work and I will re-open this issue.
