### ISSUE TITLE
0.12 release seems to be missing documentation

### ISSUE THREAD

**Issue by 7er** [pika/pika#1085]
pika.readthedocs.io redirects to https://pika.readthedocs.io/en/0.10.0/

https://pika.readthedocs.io/en/0.10.0/ says that latest release is https://pika.readthedocs.io/en/0.11.2/

https://pika.readthedocs.io/en/latest refers to version 1.0.0b1 2018-02-01 and has no mention of 0.12

By some poking around I found that going to https://pika.readthedocs.io/en/stable will give me the 0.12 release docs.

**Comment by lukebakken** [comment]
This is a RTD issue, not Pika's. Please see issue #1077 as well as the other issues linked to there.

**Comment by lukebakken** [comment]
Fixed in #1102
