### ISSUE TITLE
pika.adapters.libev_connection.LibevConnection is incompatible with Python 3.7

### ISSUE THREAD

**Issue by sky-code** [pika/pika#1091]
pika does not work with python 3.7.
```
  File "/Users/macbook/virtualenvs/natrix_env/lib/python3.7/site-packages/pika/__init__.py", line 22, in <module>
    from pika.adapters import BaseConnection
  File "/Users/macbook/virtualenvs/natrix_env/lib/python3.7/site-packages/pika/adapters/__init__.py", line 39, in <module>
    from pika.adapters.libev_connection import LibevConnection
  File "/Users/macbook/virtualenvs/natrix_env/lib/python3.7/site-packages/pika/adapters/libev_connection.py", line 105
    self.async = None
             ^
SyntaxError: invalid syntax
```
starting from python 3.7 `async` [is keyword](https://docs.python.org/3/whatsnew/3.7.html), rename this attribute for fix compatibility with 3.7

**Comment by michaelklishin** [comment]
@sky-code that's a little light on details. I don't see LibevConnection mentioned anywhere in Pika master. Other adaptors don't seem to use `async` for attribute name or similar. Please provide a way to reproduce and save the maintainers some time.

**Comment by sky-code** [comment]
this is because I install dramatiq library
```
pip install dramatiq[rabbitmq,watch]==1.2.0
```

**Comment by lukebakken** [comment]
@sky-code if you have time to submit a PR that addresses new keywords in Python 3.7 like `async`, I would review it. Thanks!

**Comment by sky-code** [comment]
where is this file ?
https://github.com/pika/pika/commits/d4bdaaa75805cb7899ed53cf684bbaa8bf026449/pika/adapters/libev_connection.py

why if i install clear `pika` package i not have this file in `site-packages/pika/adapters` but when pika installed with additional packages, this file appears from nowhere?

**Comment by lukebakken** [comment]
@sky-code I apologize, I forgot that `libev` support was removed in 3ce691b01bc567531aee96c0fd55d94bc3226061

If there is enough interest, we would consider re-adding it to Pika `1.0.0` and would welcome a PR to do so.
