### ISSUE TITLE
heartbeat connection parameter has no effect

### ISSUE THREAD

**Issue by carlosefr** [pika/pika#1093]
The [docs](https://pika.readthedocs.io/en/latest/modules/parameters.html) have this to say about the `heartbeat` connection parameter:

> AMQP connection heartbeat timeout value for negotiation during connection tuning or callable which is invoked during connection tuning. None to accept broker’s value. 0 turns heartbeat off. Defaults to DEFAULT_HEARTBEAT_TIMEOUT.

However, `heartbeat` doesn't seem to work as expected. It has no effect whatsoever, but the timeout suggested by the server isn't being honored either.

Consider the test case below, a publisher publishing messages at the rate of about 1 msg/sec, and the following settings:

  * `HEARTBEAT=60` / `WAIT_TIME=50`: exits on the first message.
  * `HEARTBEAT=60` / `WAIT_TIME=20`: exits on the second message.
  * `HEARTBEAT=60` / `WAIT_TIME=10`: no longer exits

Setting `HEARTBEAT` to `0` or `3600` changes nothing: the behavior is the same as above. The same with using Pika **0.12.0** or **0.11.2**.

Also, changing the heartbeat value in RabbitMQ has no effect (and I've confirmed that the client gets the changed value by using a callable instead of an integer for the `heartbeat` parameter):

```
%% /etc/rabbitmq/rabbitmq.config
[
  {rabbit,
    [
      {heartbeat, 90}
    ]
  }
].
```

I'm using RabbitMQ **3.7.4** and Python **3.6.5** on Linux for all these tests.

## Test Case

```python3
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import pika

HEARTBEAT=60
WAIT_TIME=25

def receive_message(channel, method, properties, body):
    print("Got message! Sleeping %d seconds" % WAIT_TIME)
    time.sleep(WAIT_TIME)
    channel.basic_ack(delivery_tag=method.delivery_tag)
    print("Acknowledged message! Timeout NOT triggered.")

print("Connecting: heartbeat=%d" % HEARTBEAT)
cs = pika.PlainCredentials("guest", "guest")
ps = pika.ConnectionParameters(host="127.0.0.1", credentials=cs, heartbeat=HEARTBEAT)
conn = pika.BlockingConnection(ps)
chan = conn.channel()

chan.exchange_declare(exchange="example_exchange", exchange_type="topic", durable=True)
chan.queue_declare(queue="example_queue", durable=True)
chan.queue_bind(exchange="example_exchange", queue="example_queue", routing_key="example_key.*")

chan.basic_consume(receive_message, queue="example_queue")
chan.start_consuming()
```

**Comment by lukebakken** [comment]
Thank you for the complete report, I will check this out.

But, a question - what do you think happens when your `receive_message` blocks the thread by calling `sleep`? How are heartbeats supposed to be processed?

**Comment by carlosefr** [comment]
I understand that when `receive_message` blocks the thread, heartbeats are not processed at all, which is why I wanted to change the default heartbeat interval (or, in this case, timeout).

**Comment by lukebakken** [comment]
> I have long-running processes for which I do not want the server to tear down the connection while they're doing something.

That's exactly why `add_callback_threadsafe` was added to Pika `0.12.0` - it is even called out in the [release notes](https://github.com/pika/pika/blob/master/CHANGELOG.rst#0120-2018-06-19). This is what you should be using to send acks when your long-running process completes.

Here's what I see in my environment when I use a slightly modified version of your code, which I have attached here: [repro.py.txt](https://github.com/pika/pika/files/2171752/repro.py.txt). I am testing with RabbitMQ `3.7.7` and Erlang `21.0.2`, Python `3.6.5` and Pika `0.12.0`. Notice that I am using a fresh `virtualenv`:

```
lbakken@shostakovich ~/issues/pika/gh-1093 (master *%)
$ source venv/3.6.5/bin/activate
(3.6.5) lbakken@shostakovich ~/issues/pika/gh-1093 (master *%)
$ pip list
Package    Version
---------- -------
pika       0.12.0 
pip        10.0.1 
setuptools 39.2.0 
wheel      0.31.1 
```

`HEARTBEAT=0` correctly disables heartbeats. Using a 50 second wait time the channel and connection are not closed abruptly. Here is what I see in the console:

```
$ python ./repro.py 
Connecting: heartbeat=0
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
```

I ran [PerfTest](https://github.com/rabbitmq/rabbitmq-perf-test/) with the following arguments to publish messages:

```
--queue gh-1093 --predeclared --consumers 0 --publishing-interval 10
```

You can see the packet capture here: [repro-heartbeat-0-wait-50.pcapng.gz](https://github.com/pika/pika/files/2171759/repro-heartbeat-0-wait-50.pcapng.gz)

Older versions of Pika did not / could not disable heartbeats... maybe there's something amiss in your environment?

**Comment by carlosefr** [comment]
The results I posted in the initial comments are what I'm seeing. The publisher I'm using is below, for completeness. I've since upgraded RabbitMQ to 3.7.7 in my test VM. I'm also (was already) using a fresh virtualenv:

```
$ pip list
Package    Version
---------- -------
pika       0.12.0 
pip        10.0.1 
setuptools 39.0.1 
```

Perhaps is something that only happens with the specific settings I'm using?

## Test Publisher

```python3
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import pika

cs = pika.PlainCredentials("guest", "guest")
ps = pika.ConnectionParameters(host="127.0.0.1", credentials=cs)
conn = pika.BlockingConnection(ps)
chan = conn.channel()

try:
    count = 1
    while True:
        print("Publishing... %d" % count)
        chan.basic_publish(exchange="example_exchange", routing_key="example.key", body="%d" % count)
        count += 1

        time.sleep(1)
except KeyboardInterrupt:
    conn.close()
```

**Comment by lukebakken** [comment]
@carlosefr please provide a packet capture from port `5672` using `HEARTBEAT=0` and `WAIT_TIME=50`. That will be the fastest way for me to see differences between your environment and mine.

**Comment by carlosefr** [comment]
Here's capture done with `sudo tcpdump -i lo tcp port 5672 -w pika-gh-1093.pcap`:

[pika-gh-1093.pcap.gz](https://github.com/pika/pika/files/2171932/pika-gh-1093.pcap.gz)

**Comment by lukebakken** [comment]
Please take a look at this packet:

```
9	0.002314	127.0.0.1	5672	127.0.0.1	45358	AMQP	86	Connection.Tune 
```

I have taken a screenshot of this packet:

![pika-gh-1093-connection-tune-heartbeat-90](https://user-images.githubusercontent.com/514926/42399767-f74024ba-8123-11e8-946b-309f82b53893.png)

You can see that a 90 second heartbeat is being requested by your application. Could you please double-check your code to ensure you are requesting a heartbeat of `0`?

**Comment by lukebakken** [comment]
Actually, that is your publisher requesting a `90` second heartbeat. But, in packet `47`, the consumer requests the same value:

![pika-gh-1093-connection-tune-heartbeat-90-consumer](https://user-images.githubusercontent.com/514926/42399871-4bf3ef6e-8124-11e8-949a-e1d88fbb3b78.png)

**Comment by lukebakken** [comment]
One second, I'm re-checking this.

**Comment by carlosefr** [comment]
The code I'm using is what I've pasted above. Both for the publisher and the subscriber. No other clients are using this RabbitMQ server (this is all running inside a test VM).

The 90 second heartbeat also matches what I've pasted above: it's probably the heartbeat set in my `rabbitmq.config` file.

**Comment by carlosefr** [comment]
I've changed the default heartbeat in RabbitMQ to `87`. Here's another capture:
[pika-gh-1093.pcap.gz](https://github.com/pika/pika/files/2171963/pika-gh-1093.pcap.gz)

**Comment by lukebakken** [comment]
There may be an issue in the Pika logic when it comes to using the server vs client heartbeat value. It'll take a while to get to the bottom of it, and I'm multitasking with [this](https://groups.google.com/d/topic/rabbitmq-users/ZtiqGwD9TOs/discussion) at the moment.

**Comment by lukebakken** [comment]
Nope, everything appears to be correctly negotiated in your packet captures as well as mine. In your latest capture, you can see RabbitMQ suggest an 87 second heartbeat in packet 41, while Pika responds with 0 (as expected) in packet 42.

Again, I can't reproduce your issue locally. I have configured RMQ to request a 90 second heartbeat. Here's the output from my consumer:

```
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
Acknowledged message! Timeout NOT triggered.
Got message! Sleeping 50 seconds
```

What is in your RabbitMQ log? If the connection is dropped unexpectedly, it will be logged.

**Comment by lukebakken** [comment]
Can you describe your VM more? Have you tried reproducing this without running RabbitMQ in a VM? That is one difference between your environment and mine - I am running RMQ and the test applications on my Arch Linux workstation.

**Comment by carlosefr** [comment]
I'm running CentOS 7.5 in VirtualBox 5.2.12 set up by Vagrant 2.1.2 on macOS 10.12.6. The base box is this one: https://app.vagrantup.com/centos/boxes/7/versions/1804.02

```
$ rpm -qa | egrep 'erlang|rabbitmq'
rabbitmq-server-3.7.7-1.el7.noarch
erlang-20.3.7-1.el7.centos.x86_64
```

Unfortunately I don't have any physical Linux machine to try. But I can try other distros in a VM, if needed.

```
2018-07-07 14:27:40.269 [info] <0.572.0> accepting AMQP connection <0.572.0> (127.0.0.1:52248 -> 127.0.0.1:5672)
2018-07-07 14:27:40.271 [info] <0.572.0> connection <0.572.0> (127.0.0.1:52248 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
2018-07-07 14:28:11.046 [warning] <0.572.0> closing AMQP connection <0.572.0> (127.0.0.1:52248 -> 127.0.0.1:5672):
{writer,send_failed,{error,timeout}}
```

**Comment by lukebakken** [comment]
@carlosefr - thank you for providing that log message. It explains the TCP window full message I see in your Wireshark logs, as well as the behavior you're In my environment, the TCP buffer sizes for RabbitMQ, the test apps, combined with the larger MTU for `localhost` all provide enough buffering for the issue to not present itself as RabbitMQ is able to write data to the socket. Had something filled up sooner, I would see the same thing. Re-visiting #753 and [my comment](https://github.com/pika/pika/issues/753#issuecomment-318119222) I guess I already said the same thing.

If you'd like to open a pull request with that documentation change, that would be great.
