### ISSUE TITLE
Pika tries to perform a deepcopy of SSLOptions

### ISSUE THREAD

**Issue by celestialorb** [pika/pika#1098]
I've been getting the following error message: `TypeError: can't pickle SSLContext objects`, when using Python 3.6.4 with Pika 0.12.0 due to pika, specifically in `pika/connection.py`, line 535 (in `ssl_options`):

```python
self._ssl_options = copy.deepcopy(value)
```

According to this Python bug report, SSLOptions shouldn't be able to be copied:

> This is rather a feature than a bug. It is not possible to make a copy of a SSLContext object because OpenSSL doesn't support the operation. A context contains elements that can't be cloned easily, e.g. session resumption tickets.

I was following the documentation on [this page](https://pika.readthedocs.io/en/latest/examples/tls_mutual_authentication.html), which still seems to be relevant, so I believe this needs to be fixed, and quickly as this is breaking anyone trying to use AMQPS / SSL / TLS with Pika.

**Comment by lukebakken** [comment]
This is a consequence of the documentation being updated for the `master` branch of this project. When you visit [this link](https://pika.readthedocs.io/en/latest/examples/tls_mutual_authentication.html), you are viewing the docs for Pika `1.0.0`, which is yet to be released, and what the `master` branch 

You should instead view [the `stable` version](https://pika.readthedocs.io/en/stable/examples/tls_mutual_authentication.html) of the documentation on that site, which corresponds to version `0.12.0`.

Or, better yet, just choose the `0.12.0` tag on GitHub and read the docs [here](https://github.com/pika/pika/tree/0.12.0/docs).

`readthedocs.io` has been a real pain in our side. I have yet to find the time to figure out why it "works" the way it does. I have considered dropping it to use GitHub pages or just markdown files in this repo.

I'll close this but if you have issues, follow up here.
