### ISSUE TITLE
pika.exceptions.ConnectionClosed: Connection to 127.0.0.1:5671 failed: timeout

### ISSUE THREAD

**Issue by gmshiot** [pika/pika#1100]
when  I test RabbitMQ SSL Connection Example,(https://github.com/pika/pika/blob/0.12.0/docs/examples/tls_mutual_authentication.rst), I've been getting the following error message:

Traceback (most recent call last):
  File "ssl_rpc_server.py", line 34, in <module>
    connection = pika.BlockingConnection(cp)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/blocking_connection.py", line 471, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
pika.exceptions.ConnectionClosed: Connection to 127.0.0.1:5671 failed: timeout

//version  pika:  0.12.0,python:3.4,os:Debian 9.4,RabbitMQ:3.7.7
// the same error in the python3.6.6 version 
use openssl  connect  to broker is success.
openssl s_client -connect localhost:5671 -cert /etc/rabbitmq/ssl/client/clienta.cert.pem -key /etc/rabbitmq/ssl/client/clienta.key.pem  -CAfile /etc/rabbitmq/ssl/ca/cacert.pem
the result as shown:CONNECTED(00000003)

//python code as below:
import ssl
import pika

cp = pika.ConnectionParameters(
    host="127.0.0.1",
    ssl=True,
    ssl_options=dict(
        ssl_version=ssl.PROTOCOL_SSLv23,
        ca_certs="/etc/rabbitmq/ssl/ca/cacert.pem",
        keyfile="/etc/rabbitmq/ssl/client/clienta.key.pem",
        certfile="/etc/rabbitmq/ssl/client/clienta.cert.pem",
        cert_reqs = ssl.CERT_REQUIRED))

connection = pika.BlockingConnection(cp)
ch = connection.channel()
print(ch.queue_declare("sslq"))
ch.publish("", "sslq", "abc")
print(ch.basic_get("sslq"))

// end part rabbitmq log as below:
2018-07-21 20:19:28.739 [info] <0.334.0> Started message store of type transient for vhost '/'
2018-07-21 20:19:28.740 [info] <0.341.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
2018-07-21 20:19:28.748 [info] <0.334.0> Started message store of type persistent for vhost '/'
2018-07-21 20:19:28.753 [info] <0.376.0> started TCP Listener on [::]:5672
2018-07-21 20:19:28.755 [info] <0.392.0> started SSL Listener on 127.0.0.1:5671
2018-07-21 20:19:28.757 [info] <0.408.0> started SSL Listener on 192.168.31.250:5671
2018-07-21 20:19:28.803 [info] <0.270.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@DebianTest
2018-07-21 20:19:28.803 [info] <0.270.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@DebianTest
2018-07-21 20:19:28.847 [info] <0.463.0> Management plugin started. Port: 15672
2018-07-21 20:19:28.847 [info] <0.569.0> Statistics database started.
2018-07-21 20:19:28.931 [notice] <0.108.0> Changed loghwm of /var/log/rabbitmq/rabbit@DebianTest.log to 50
2018-07-21 20:19:29.327 [info] <0.7.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch

**Comment by lukebakken** [comment]
> use openssl connect to broker is success

No, that isn't true. When `openssl` connects successfully to RabbitMQ via TLS, and _completes the TLS handshake_, this is the output:

```
$ openssl s_client -connect localhost:5671 -CAfile /home/lbakken/development/michaelklishin/tls-gen/basic/result/ca_certificate.pem
CONNECTED(00000003)
depth=1 CN = TLSGenSelfSignedtRootCA, L = $$$$
verify return:1
depth=0 CN = shostakovich, O = server
verify return:1
140576545571264:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1407:SSL alert number 40
---
Certificate chain
 0 s:/CN=shostakovich/O=server
   i:/CN=TLSGenSelfSignedtRootCA/L=$$$$
 1 s:/CN=TLSGenSelfSignedtRootCA/L=$$$$
   i:/CN=TLSGenSelfSignedtRootCA/L=$$$$
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDJzCCAg+gAwIBAgIBATANBgkqhkiG9w0BAQsFADAxMSAwHgYDVQQDDBdUTFNH
ZW5TZWxmU2lnbmVkdFJvb3RDQTENMAsGA1UEBwwEJCQkJDAeFw0xODA3MTAxNzUz
MzhaFw0yODA3MDcxNzUzMzhaMCgxFTATBgNVBAMMDHNob3N0YWtvdmljaDEPMA0G
A1UECgwGc2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnD6C
ctyI4SkB34avDU9oR/ohieElcwj12fCMEMx24NEgW8+9kwzwh43OeIL3D16FJYH5
6ryq+HpnGBGTnEcEQYpGBCSJ3cVUxRG52wZd71MM8A00qBx5q3JNJhcI6RpVljL+
f7aRCvjsftKVBf+q+XnQwPxFAlbD6iGIbGzsoA7rVgqqbPaJlfHQudWDvb2M3Btn
bXLFxCh5QE3qH9mtrf/fA6N2ts9fx1AWxmsm4upxOwFz4cmJLD1BuYDkLI+D91Pz
TjS2G+i2k/+aCzoci+Ck3CqUYCvzLMp+iDN7wwuM6LNxNogZ0MRJPJg8XfjlVjyR
l2CtGyoLdTeBiYwGgwIDAQABo1MwUTAJBgNVHRMEAjAAMAsGA1UdDwQEAwIFoDAT
BgNVHSUEDDAKBggrBgEFBQcDATAiBgNVHREEGzAZggxzaG9zdGFrb3ZpY2iCCWxv
Y2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAViYkgeIXs0m54Y91SqT/zlPbGqng
6bZtzN/5iLHFAFhdHcjfZZ3wDGya2TJDiBmJvXj8n/t9JFYdgJAOA4c/UmJOKCxj
5iMuEAZC3H8w4JYtMv8eVGtuvzj4l58kaPhUUYUEfZjX4jwC9WSw9zWHpya2x8MC
aBSXRhAx/Faz4Z0zVRTpfms64dQE6lG5mHOvcoTQRUn1PrLGxR15C7QlP6Lj05qF
JRfU3fBrP0XQeiWYPcp+kDpzerJfF8N4saFH2bQZSJ1xvsmQn+jffJvXSdjJX0l0
CVpITK72zIH6Bkb0yH3U/h7usHwPE6GlKfndCv4xUXnBK9MHPcJ3Nh60IQ==
-----END CERTIFICATE-----
subject=/CN=shostakovich/O=server
issuer=/CN=TLSGenSelfSignedtRootCA/L=$$$$
---
Acceptable client certificate CA names
/CN=TLSGenSelfSignedtRootCA/L=$$$$
Client Certificate Types: ECDSA sign, RSA sign, DSA sign
Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:ECDSA+SHA224:RSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2141 bytes and written 314 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 94AC404AAF9FCCA199918B11FF84A903BD911B17303E28E02EC0D581D0154A75
    Session-ID-ctx: 
    Master-Key: 029BBA17C9AFEF83CA95E40C55793D6E3F24C1780D87CD5A1F5A09647CD7A2BDC2D4A33A8839DB00B7ED0BD4AC17F1FD
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1532987184
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

I don't see anything in your RabbitMQ logs indicating that a connection attempt was made. The TLS handshake is not completing which means you are probably having certificate or connection issues, this isn't a Pika issue. I suggest reading these documents:

* https://www.rabbitmq.com/troubleshooting-networking.html
* https://www.rabbitmq.com/troubleshooting-ssl.html
