### ISSUE TITLE
Exceptions not updated in pip release 

### ISSUE THREAD

**Issue by JayPeeTeeDee** [pika/pika#1101]
In the docs and github repo, there are exceptions such as `ConnectionClosedByBroker` within `exceptions.py`.

However, the pip release (at the latest version: 0.12.0) does not have these exceptions included.

**Comment by lukebakken** [comment]
`ConnectionClosedByBroker` does not exist in `0.12.0`. Please be sure you are selecting the correct tag in GitHub before browsing code, otherwise you are looking at `master`, which will become `1.0.0`
