### ISSUE TITLE
Question about best consumer strategy.

### ISSUE THREAD

**Issue by moelius** [pika/pika#1110]
Hi. Can you help me? What is the best strategy for a situation where there are many queues:

- One connection and more then one subscriber using this connection (shared connection) 
- One connection for one subscriber
- No difference

P.S. I'm using `SelectConnection` in one thread.

**Comment by lukebakken** [comment]
I recommend not sharing connections. Use a thread per consumer - it's the simplest way.

In the future, please ask questions on either the [`pika-python`](https://groups.google.com/forum/#!forum/pika-python) or [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. Thanks.

**Comment by moelius** [comment]
Thank you, sorry for the issue, did not find these links

**Comment by lukebakken** [comment]
It's no problem at all! Thanks for using Pika and don't hesitate to ask questions on either mailing list. Have a great day :smile:
