### ISSUE TITLE
Freezing method calls for creating queues, exchanges and bindings

### ISSUE THREAD

**Issue by maggyero** [pika/pika#1112]
In both Pika 0.13.0 and 1.0.0b1, some method calls for creating queues, exchanges and bindings are _freezing_ (blocking forever instead of returning or raising an exception) with some arguments. These unexpected behaviours are emphasized in bold below.

`queue_declare`

- `queue_declare()`
OK, raises _TypeError: queue_declare() missing 1 required positional argument: 'queue'_ in Pika 1.0.0b1, creates a queue with a unique name in Pika 0.13.0.
- `queue_declare(queue=None)`
**Unexpected, freezes instead of creating a queue with a unique name**.
- `queue_declare(queue="")`
OK, creates a queue with a unique name.

`exchange_declare`

- `exchange_declare()`
**Unexpected, freezes instead of raising _TypeError: exchange_declare() missing 1 required positional argument: 'queue'_**.
- `exchange_declare(exchange=None)`
**Unexpected, freezes instead of raising _pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')_**.
- `exchange_declare(exchange="")`
OK, raises _pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')_.

`queue_bind`

- `queue_bind()`
OK, raises _TypeError: queue_bind() missing 2 required positional arguments: 'queue' and 'exchange'_;
- `queue_bind(queue=None, exchange=None, routing_key=None)`
**Unexpected, freezes instead of raising _pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')_**.
- `queue_bind(queue="", exchange="", routing_key="")`
OK, raises _pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')_.

`exchange_bind`

- `exchange_bind()`
**Unexpected, freezes instead of raising _TypeError: exchange_declare() missing 2 required positional arguments: 'destination' and 'source'_**.
- `exchange_bind(destination=None, source=None, routing_key=None)`
**Unexpected, freezes instead of raising _pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')_**.
- `exchange_bind(destination="", source="", routing_key="")`
OK, raises _pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')_.

I used a `BlockingChannel` for all the method calls. For instance:

```
import pika

parameters = pika.ConnectionParameters()

with pika.BlockingConnection(parameters) as connection:
    channel = connection.channel()
    channel.queue_declare(queue=None)
```

**Comment by lukebakken** [comment]
Hi Géry -

Thanks for giving the latest Pika code a try. Please provide the code you're using to demonstrate this. By "freezes" I'm assuming you mean that no exceptions are raised, correct? What would you expect to happen in the above situations?

I see that in several of the scenarios a `ChannelClosed` exception is raised, which is the expected result.

Again, please provide the code you're using. I'm interested to see what connection type you're using. Thanks - Luke

**Comment by maggyero** [comment]
Hi @lukebakken,

> By "freezes" I'm assuming you mean that no exceptions are raised, correct? What would you expect to happen in the above situations?

By "freezes" I mean that the method call blocks (hangs) instead of returning or raising an exception.

> Again, please provide the code you're using. I'm interested to see what connection type you're using.

I used a `BlockingChannel` for all the method calls:

```
import pika

parameters = pika.ConnectionParameters()

with pika.BlockingConnection(parameters) as connection:
    channel = connection.channel()
    queue = channel.queue_declare()
```

> I see that in several of the scenarios a ChannelClosed exception is raised, which is the expected result.

Yes, this is the expected result.

**Comment by lukebakken** [comment]
> queue_declare() -> raises TypeError: queue_declare() missing 1 required positional argument: 'queue' in Pika 1.0.0b1

This is an expected API change. If you want a server-named queue, you must use the empty string `''`

> queue_declare(queue=None) -> Unexpected, freezes instead of creating a queue with a unique name.

`1.0.0b2` -> throws `ValueError`, as do (almost all) the rest of the "Unexpected" scenarios. I had to update validation for `exchange_bind`. Thanks for testing, and please feel free to re-test when the next beta is available.

**Comment by maggyero** [comment]
@lukebakken Okay thanks. So if I understood well you added validation for solving the case:

- `exchange_bind(destination=None, source=None, routing_key=None)`

That way instead of freezing it will correctly raise:

> pika.exceptions.ChannelClosed: (403, 'ACCESS_REFUSED - operation not permitted on the default exchange')

which solves one of the six unexpected behaviours that I listed.

Any reason why you did not add validation for solving the following symmetric case?

- `exchange_declare(exchange=None)`

And two of the four remaining cases could have been solved as well by simply removing the default `None` arguments in the definitions:

```
def exchange_declare(self,
                     exchange=None,  # to be replaced by: exchange
                     exchange_type='direct',
                     passive=False,
                     durable=False,
                     auto_delete=False,
                     internal=False,
                     arguments=None):
```

and

```
def exchange_bind(self,
                  destination=None,  # to be replaced by: destination
                  source=None,       # to be replaced by: source
                  routing_key='',
                  arguments=None):
```

That way the call `exchange_declare()` would correctly raise:

> TypeError: exchange_declare() missing 1 required positional argument: 'exchange'

and the call `exchange_bind()` would correctly raise:

> TypeError: exchange_bind() missing 2 required positional arguments: 'destination' and 'source'

which is consistent with the calls `queue_declare()` and `queue_bind()` which already raise a `TypeError`.

**Comment by maggyero** [comment]
@michaelklishin I don't think you should close this issue as #1163 does not resolve it totally (see my previous answer).

**Comment by lukebakken** [comment]
@maggyero I will make those changes, thanks.

**Comment by maggyero** [comment]
@lukebakken Thank you.
