### ISSUE TITLE
Really slow publishes in asynchronous processing

### ISSUE THREAD

**Issue by nimamahmoudi** [pika/pika#1115]
Hi,

I am trying to implement some kind of robust RPC using the Async Consumer and Publisher example. The problem is that when I try to use the publisher example and instead of sending a message using add_timeout I use channel.publish(), for some reason my messages get buffered for 4-5 seconds and they get sent at the same time. I am trying to implement a distributed queue for a web service and cannot afford more than 40ms of delay. What can I do regarding this problem? Is this an issue of the library?

Thanks

**Comment by lukebakken** [comment]
Hello - this isn't a library issue. Please provide *all* of the code you are using, or similar code that can reliably reproduce the issue. That is by far the most efficient way to determine what is happening.
