### ISSUE TITLE
basic_get with explicit no_ack=True, ack message, it should not

### ISSUE THREAD

**Issue by ProPheT777** [pika/pika#1118]
Hey

The following example below auto ack message - rabbitmq receive a get auto_auto ack whereas it should receive get manual_ack. Until I do not call myself ack the message should stay in the queue. 

channel init : 
```python
        connection:pika.BlockingConnection = pika.BlockingConnection(pika.URLParameters(amqp_url))

        self._channel:BlockingChannel = connection.channel()
        self._channel.confirm_delivery()
        self._channel.queue_declare(queue=self._queue, durable=True, passive=True, auto_delete=False)
```

```python
        while(True):
            method_frame, header_frame, body = self._channel.basic_get(queue=self._queue, no_ack=True)
```

Here the result payload of my debug : 

![rabbit-error](https://user-images.githubusercontent.com/1763341/45639173-906e7000-baaf-11e8-8831-9e78dfd2ef5e.png)

> b'\x00<\x00F', b'\x00\x00', b'\x1f', b'el.support.destination.ingester', b'\x01'
> marshal result : b"\x01\x00\x01\x00\x00\x00'\x00<\x00F\x00\x00\x1fel.support.destination.ingester\x01\xce"

What's the problem ? or what i'm doing wrong ?

**Comment by lukebakken** [comment]
`no_ack=True` indicates that the message does not require an acknowledgement and will be instantly acknowledged on delivery. You should use `no_ack=False` if you need to manually ack messages.

`confirm_delivery` turns on publisher confirms, which is a different feature.

Please see the documentation here:

https://www.rabbitmq.com/confirms.html

**Comment by ProPheT777** [comment]
I already tried with False, it's the exactly same result on rabbitmq side, on consume with False have the expected behavior (Deliver manual_ack).

**Comment by lukebakken** [comment]
OK, so you're saying that with this code the message is auto-acknowledged:

```
self._channel.basic_get(queue=self._queue, no_ack=False)
```

What version of Pika, Python, RabbitMQ and Erlang are you using?

For what it's worth, you should prefer using `basic_consume` anyway instead of `basic_get`.

**Comment by ProPheT777** [comment]
> self._channel.basic_get(queue=self._queue, no_ack=False)

yes

* Pika version : 0.12.0
* Rabbitmq : v3.7.6
* Erlang 20.1.7
* Python 3.6.6

**Comment by lukebakken** [comment]
@ProPheT777 - here is the code I am using to test: [blocking_basic_get.py.txt](https://github.com/pika/pika/files/2688219/blocking_basic_get.py.txt)

During the `time.sleep(30)` call, the message *is* in the "Unacked" category in RabbitMQ. Then, when the application exits, the channel and connection are closed which indicates to RabbitMQ that the message should be re-en-queued. I suspect your application is doing something similar.

**Comment by deeplearningboy** [comment]
here is fix

import pika

class RabbitMQ():
    def __init__(self):
        connection = pika.BlockingConnection()
        self.channel = connection.channel()
        # del connection
        self.channel.confirm_delivery()
        self.body = None

    def publish(self, routing_key, body, exchange='' ):
        try:
            self.channel.basic_publish(
                exchange=exchange,
                routing_key=routing_key,
                body=body)
        except Exception as ex:
            print('Error Message could not be confirmed: ' + ex.args[0])
            print(f'Message [{exchange}] [{routing_key}] [{body}]')

    def get_data(self, queue ):
        data = []
        while True:
            method_frame, header_frame, body = self.channel.basic_get( queue )
            if method_frame:
                data.append( body )
            else:
                return data

    def close(self):
        self.channel.stop_consuming()
        self.channel.connection.close()


if __name__ == '__main__':
    rabbit = RabbitMQ()
    for i in range(6):
        rabbit.publish('test',f'Hello World!  {i}')
