### ISSUE TITLE
Intermittent test failures of 

### ISSUE THREAD

**Issue by mcepl** [pika/pika#1119]
From time to time this test fails in the openSUSE build service, even on x86_64. It passes perfectly nicely on my local machine (all using the latest openSUSE/Tumbleweed, our rolling distro):
```
[  142s] ======================================================================
[  142s] FAIL: Setup timers, sleep and start polling (epoll)
[  142s] ----------------------------------------------------------------------
[  142s] Traceback (most recent call last):
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/tests/unit/select_connection_ioloop_tests.py", line 311, in start_test
[  142s]     self.start()
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/tests/unit/select_connection_ioloop_tests.py", line 73, in start
[  142s]     self.ioloop.start()
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/pika/adapters/select_connection.py", line 461, in start
[  142s]     self._poller.start()
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/pika/adapters/select_connection.py", line 722, in start
[  142s]     self._process_timeouts()
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/pika/adapters/select_connection.py", line 413, in process_timeouts
[  142s]     self._timer.process_timeouts()
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/pika/adapters/select_connection.py", line 268, in process_timeouts
[  142s]     timeout.callback()
[  142s]   File "/home/abuild/rpmbuild/BUILD/pika-0.12.0/tests/unit/select_connection_ioloop_tests.py", line 210, in on_timer
[  142s]     self.assertEqual(val, self.timer_stack.pop())
[  142s] AssertionError: 4 != 3
[  142s]     '4 != 3' = '%s != %s' % (safe_repr(4), safe_repr(3))
[  142s]     '4 != 3' = self._formatMessage('4 != 3', '4 != 3')
[  142s] >>  raise self.failureException('4 != 3')
[  142s]     
[  142s] -------------------- >> begin captured logging << --------------------
```
[Complete build log of the failed run](https://github.com/pika/pika/files/2404849/python-pika-x86_64-log.txt)

**Comment by lukebakken** [comment]
Hello, thanks for using Pika.

I don't have access to "openSUSE build service", nor do I know what it is. You can see that Pika passes tests on Travis CI using several different Python versions.

Since you don't give any information, like openSUSE version, Python version, or even what test is failing, I will close this issue.

**Comment by mcepl** [comment]
Sorry, Open Build Service is the system which produces packages for (among other) openSUSE Linux distribution. I am a general maintainer of Python packages there, which is the reason why I got in contact with pika package. The page of the package on OBS is https://build.opensuse.org/package/show/devel:languages:python/python-pika . Yes, I guess it uses VMs, but generally they shouldn't be too slow (we build all openSUSE packages there, and I don't think we have too many timeout-related problems).

**Comment by lukebakken** [comment]
What is my action item here?

As I mentioned, Pika passes on Travis CI using several different versions of Python. The build log you gave me does not show the error (I can't find `FAIL` in the file). It shows that Python 2.7.15 is being used while 2.7.14 is used on Travis.

**Comment by mcepl** [comment]
I just hoped that perhaps you would have some idea what could be wrong. Apparently, you don't.

**Comment by lukebakken** [comment]
If you can provide the log of the failed run, maybe that will provide more information. There is a good chance that increasing [this value](https://github.com/pika/pika/blob/master/tests/unit/select_connection_ioloop_tests.py#L246) to `0.10` or `0.25` will fix this issue.

Do you have the ability to run this process using a branch from GitHub?

**Comment by mcepl** [comment]
Well, I can add any patch to the package.

**Comment by lukebakken** [comment]
You can view the diff here:

https://github.com/pika/pika/compare/pika-1119-experiment

I believe the following is in the correct patch format. I generated it with `git diff 0.12.0...` within the checked out `pika-1119-experiment` branch:

[pika-1119-experiment.patch.txt](https://github.com/pika/pika/files/2406135/pika-1119-experiment.patch.txt)

**Comment by mcepl** [comment]
OK, the patch applied, and no luck. I tried to run tests in ``for`` loop, but it hasn't passed even once. See [the full log](https://github.com/pika/pika/files/2406540/python-pika-x86_64-log.txt).

**Comment by lukebakken** [comment]
That's a different error at least, let me check it.

**Comment by lukebakken** [comment]
Try this updated patch:

[pika-1119-experiment.patch.txt](https://github.com/pika/pika/files/2406595/pika-1119-experiment.patch.txt)

**Comment by lukebakken** [comment]
Have you encountered the issue again? I'd like to verify before committing the fix.

**Comment by mcepl** [comment]
Yup, seems to be more stable. Thank you.

**Comment by lukebakken** [comment]
@mcepl thanks!
