### ISSUE TITLE
BlockingConnection multiple hosts report parameters error

### ISSUE THREAD

**Issue by guanzydev** [pika/pika#1122]
node1 = pika.URLParameters('amqp://node1')
node2 = pika.URLParameters('amqp://node2')
node3 = pika.URLParameters('amqp://node3')

all_endpoints = [node1, node2, node3]
connection = pika.BlockingConnection(all_endpoints)

then report parameters error, expect instance but all_endpoints is a list.

Expected instance of Parameters, not [.........]

**Comment by lukebakken** [comment]
Hello, thanks for using Pika. This is behaving as designed - you can only connect to one broker at a time. If you would like to use a different node upon an error or other condition, you will have to implement that yourself.

**Comment by guanzydev** [comment]
I have 3 nodes as rabbitmq cluster, pika use vip from haproxy to connect rabbitmq, but got error log as:
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
INFO:pika.connection:Disconnected from RabbitMQ at 10.22.42.1:5672 (-1): EOF
ERROR:pika.connection:Incompatible Protocol Versions
ERROR:pika.connection:Connection setup failed due to The protocol returned by the server is not supported: (-1, 'EOF')
DEBUG:pika.callback:Processing 0:_on_connection_error
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa589388950>> for "0:_on_connection_error"
DEBUG:pika.callback:Processing 0:_on_connection_closed
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7fa589398dd0>> for "0:_on_connection_closed"
DEBUG:pika.callback:Incremented callback reference counter: {'callback': <bound method SelectConnection._on_connection_start of <SelectConnection CLOSED socket=None params=<URLParameters host=10.22.42.1 port=5672 virtual_host=/ ssl=False>>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 2}
DEBUG:pika.callback:Incremented callback reference counter: {'callback': <bound method SelectConnection._on_connection_close of <SelectConnection CLOSED socket=None params=<URLParameters host=10.22.42.1 port=5672 virtual_host=/ ssl=False>>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 2}
ERROR:pika.adapters.blocking_connection:Connection open failed - The protocol returned by the server is not supported: (-1, 'EOF')
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    connection = pika.BlockingConnection(node1)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 466, in _flush_output
    raise maybe_exception
pika.exceptions.IncompatibleProtocolError: (-1, 'EOF')

So I want to find a way to use host list in pika, and it would connect other host when current is down.

**Comment by lukebakken** [comment]
> So I want to find a way to use host list in pika, and it would connect other host when current is down.

You must fix your haproxy installation, or you have to code a "host list" yourself. This would involve catching exceptions and reacting to them by closing the current set of channels and connections and re-opening them to the next host in the list.

**Comment by alice17** [comment]
> Hello, thanks for using Pika. This is behaving as designed - you can only connect to one broker at a time. If you would like to use a different node upon an error or other condition, you will have to implement that yourself.

Why put this code in the examples if it does not work?
