### ISSUE TITLE
Can the delivery_tag in delivery_confirmations rollover to 0 or 1

### ISSUE THREAD

**Issue by taybin** [pika/pika#1125]
In a long running process, can the delivery_tag for delivery confirmations grow larger than an int/long and rollover to 1 or even -1?  If so, what's the best technique for dealing with this?  Resetting the internal message publish count for that channel?  Or maybe closing and opening a new channel periodically or at the number of messages to force a reset of the count?

**Comment by lukebakken** [comment]
Hello,

Thanks for using Pika! Pika's maintainers prefer that users ask questions via the [`pika-python`](https://groups.google.com/forum/#!forum/pika-python) or [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing lists. Thanks.

To answer your question, `delivery_tag` is sent by the broker, so don't worry about it. Long-running processes will work fine without any need to manage that value.

Thanks -
Luke
