### ISSUE TITLE
Test coverage builds failed for last PRs

### ISSUE THREAD

**Issue by romantolkachyov** [pika/pika#1131]
I found that travis coverage build failed for last PRs with:

```
$ aws s3 cp --recursive s3://com-gavinroy-travis/pika/$TRAVIS_BUILD_NUMBER/ coverage
fatal error: Unable to locate credentials
```
https://travis-ci.org/pika/pika/jobs/436202105#L673

We can use codecov for coverage as a simpliest solution. But I found codecov installed and found builds here https://codecov.io/gh/pika/pika (the last was a month ago).

I think we just need to:

- re-integrate repo with codecov to make it working again (github dropped legacy integration api sometime ago — this must be a reason)
- remove coverage steps for PRs from .travis-ci.yml (looks like it may be used to prevent publishing to pypi, I need approvement to do so @lukebakken FYI)

or we can just restore credentials to AWS (I didn't found how it maden and see no difference between PR and master builds; so I have no advices here).

**Comment by lukebakken** [comment]
Fixed by #1138
