### ISSUE TITLE
Question about using multiprocessing in pika

### ISSUE THREAD

**Issue by clippered** [pika/pika#1133]
Using this code https://github.com/pika/pika/blob/master/examples/basic_consumer_threaded.py

How come it is not working for multiprocessing if I replace
`t = threading.Thread(target=do_work, args=(connection, channel, delivery_tag, body))`
with
`t = multiprocessing.Process(target=do_work, args=(connection, channel, delivery_tag, body))` ?

The `ack_message` is not invoked. Any idea why?

**Comment by lukebakken** [comment]
Hello, thanks for using Pika!

Going forward, please use one of these mailing lists to ask questions:

* https://groups.google.com/forum/#!forum/rabbitmq-users
* https://groups.google.com/forum/#!forum/pika-python

Pika isn't compatible with the `multiprocessing` library. It might be possible to make it compatible but it would involve a lot of research. At this point, we recommend that each sub-process establish its own set of connections and channels.

Thanks

**Comment by clippered** [comment]
Thanks for your quick response @lukebakken . I'll remember to use the google groups next time.

**Comment by lukebakken** [comment]
No problem! It's not very obvious. I don't mind answering here with a re-direct 😄
