### ISSUE TITLE
Program execution halted until closing of pika connection/channel

### ISSUE THREAD

**Issue by octohedron** [pika/pika#1134]
Pika version: `pika-0.12.0`

The X: Trying to receive messages from code integrated with [scrapy](https://github.com/scrapy/scrapy) which is providing the class that the below code is inheriting from, calling the methods, etc.

The issue with pika: I'm having the same or a similar issue as #1112 , as something is blocking everything (the program stops execution) until I close the channel/connection.

For example, something like

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import pika
import logging

class TestRBMQ(TestClass):
    """RabbitMQ Test"""
    rbmqrk = 'data'
    rmq = pika.BlockingConnection(
        pika.ConnectionParameters(host='localhost'))
    rmqc = rmq.channel()
    def __init__(self, *args, **kwargs):
        super(TestRBMQ, self).__init__(*args, **kwargs)
        self.rmqc.queue_declare(queue=self.rbmqrk)

    def start(self):
        s = []
        for method_frame, properties, body in self.rmqc.consume(self.rbmqrk):
            # This prints only after the next break!
            logging.info(body.decode())
            s.append(body.decode())
            self.rmqc.basic_ack(method_frame.delivery_tag)
            if method_frame.delivery_tag == 10:
                # Only here the messages get logged!
                break
        self.rmqc.close()
        self.rmq.close()
        # Only after here, I can use the mesages!
        for m in s:
            logging.info(m)
```

Problem with the above code is that, beside the fact that it only prints the 10 messages after the 10 messages have been received and it breaks out of the loop, the real issue is that everything is frozen until I close the connection, as in, the whole python program stops execution, so I would need to connect/reconnect, etc every x amount of messages, and I haven't even tried that yet but doesn't seem like the right way to do it.

**Comment by lukebakken** [comment]
It would be extremely helpful to have a set of code that reproduces this issue every time it is run. That will lead to the fastest fix.

**Comment by octohedron** [comment]
There you go @lukebakken https://github.com/octohedron/pikatest follow the instructions in the readme and let me know if you need anything else.

To see the issue, run the `send.py` and notice that it doesn't run the first request, it waits until x number of messages were received to yield the request in the `start_requests` method.

Just to give you an idea of why it's broken, scrapy's `start_request` method yields instantaneously when passing a list of urls, i.e. `["http://example.com"]` so, it shouldn't wait until x number of messages are received to start yielding requests, something is stopping the function.

**Comment by lukebakken** [comment]
@octohedron thank you for the code.

This is almost certainly a conflict between Pika's I/O loop and how `scrapy` uses `twisted`. I recommend switching [this code](https://github.com/octohedron/pikatest/blob/master/pikatest/pikatest/spiders/pikatestspider.py) to using Pika's twisted connection adapter. There is some related example code [here](https://github.com/pika/pika/blob/0.12.0/examples/twisted_service.py).

If changing the code doesn't resolve your issue, please update your example repo and make a note on this issue. Thanks!
