### ISSUE TITLE
Incorrect multiple flag on publisher confirms

### ISSUE THREAD

**Issue by Vanlightly** [pika/pika#1137]
pika==0.12.0
OS Fedora 28

When I publish a series of messages to a single queue, then the acks come back as expected. But when I publish a series of messages to a topic exchange, with multiple bound queues, then the multiple flag on the acks is often wrong. 

For example, I create 6 queues bound to amq.topic: 
q1 with routing key "x"
q2 with routing key "y"
q3 with routing key "y"
q4 with routing key "y"
q5 with routing key "y"
q6 with routing key "y"

Then I send 100 messages, alternating between routing "x" and "y". I get the following delivery confirmations:

Delivery tag: 1 Multiple: True
Delivery tag: 3 Multiple: False
Delivery tag: 2 Multiple: False
Delivery tag: 5 Multiple: True
Delivery tag: 7 Multiple: False
Delivery tag: 6 Multiple: False
Delivery tag: 9 Multiple: False
Delivery tag: 11 Multiple: False
Delivery tag: 13 Multiple: False
Delivery tag: 15 Multiple: False
Delivery tag: 17 Multiple: False
Delivery tag: 19 Multiple: True
Delivery tag: 21 Multiple: False
Delivery tag: 23 Multiple: False
Delivery tag: 25 Multiple: False
Delivery tag: 27 Multiple: False
Delivery tag: 29 Multiple: False
Delivery tag: 31 Multiple: False
Delivery tag: 33 Multiple: False
Delivery tag: 35 Multiple: False
Delivery tag: 37 Multiple: False
Delivery tag: 39 Multiple: False
Delivery tag: 36 Multiple: True
Delivery tag: 41 Multiple: False
Delivery tag: 43 Multiple: False
Delivery tag: 45 Multiple: False
Delivery tag: 47 Multiple: False
Delivery tag: 40 Multiple: True
Delivery tag: 49 Multiple: False
Delivery tag: 50 Multiple: True
Delivery tag: 52 Multiple: False
Delivery tag: 54 Multiple: False
Delivery tag: 55 Multiple: True
Delivery tag: 57 Multiple: False
Delivery tag: 59 Multiple: False
Delivery tag: 61 Multiple: False
Delivery tag: 63 Multiple: False
Delivery tag: 65 Multiple: False
Delivery tag: 66 Multiple: True
Delivery tag: 67 Multiple: True
Delivery tag: 69 Multiple: False
Delivery tag: 71 Multiple: False
Delivery tag: 72 Multiple: True
Delivery tag: 74 Multiple: False
Delivery tag: 76 Multiple: False
Delivery tag: 78 Multiple: False
Delivery tag: 80 Multiple: False
Delivery tag: 82 Multiple: False
Delivery tag: 84 Multiple: False
Delivery tag: 86 Multiple: False
Delivery tag: 88 Multiple: False
Delivery tag: 90 Multiple: False
Delivery tag: 92 Multiple: False
Delivery tag: 94 Multiple: False
Delivery tag: 95 Multiple: True
Delivery tag: 97 Multiple: False
Delivery tag: 99 Multiple: False
Delivery tag: 100 Multiple: True

Reordered so it is easier to see the multiple flag issue:

Delivery tag: 1 Multiple: True
Delivery tag: 2 Multiple: False
Delivery tag: 3 Multiple: False
Delivery tag: 5 Multiple: True
Delivery tag: 6 Multiple: False
Delivery tag: 7 Multiple: False
Delivery tag: 9 Multiple: False
Delivery tag: 11 Multiple: False
Delivery tag: 13 Multiple: False
Delivery tag: 15 Multiple: False
Delivery tag: 17 Multiple: False
Delivery tag: 19 Multiple: True
Delivery tag: 21 Multiple: False
Delivery tag: 23 Multiple: False
Delivery tag: 25 Multiple: False
Delivery tag: 27 Multiple: False
Delivery tag: 29 Multiple: False
Delivery tag: 31 Multiple: False
Delivery tag: 33 Multiple: False
Delivery tag: 35 Multiple: False
Delivery tag: 36 Multiple: True
Delivery tag: 37 Multiple: False
Delivery tag: 39 Multiple: False
Delivery tag: 40 Multiple: True
Delivery tag: 41 Multiple: False
Delivery tag: 43 Multiple: False
Delivery tag: 45 Multiple: False
Delivery tag: 47 Multiple: False
Delivery tag: 49 Multiple: False
Delivery tag: 50 Multiple: True
Delivery tag: 52 Multiple: False
Delivery tag: 54 Multiple: False
Delivery tag: 55 Multiple: True
Delivery tag: 57 Multiple: False
Delivery tag: 59 Multiple: False
Delivery tag: 61 Multiple: False
Delivery tag: 63 Multiple: False
Delivery tag: 65 Multiple: False
Delivery tag: 66 Multiple: True
Delivery tag: 67 Multiple: True
Delivery tag: 69 Multiple: False
Delivery tag: 71 Multiple: False
Delivery tag: 72 Multiple: True
Delivery tag: 74 Multiple: False
Delivery tag: 76 Multiple: False
Delivery tag: 78 Multiple: False
Delivery tag: 80 Multiple: False
Delivery tag: 82 Multiple: False
Delivery tag: 84 Multiple: False
Delivery tag: 86 Multiple: False
Delivery tag: 88 Multiple: False
Delivery tag: 90 Multiple: False
Delivery tag: 92 Multiple: False
Delivery tag: 94 Multiple: False
Delivery tag: 95 Multiple: True
Delivery tag: 97 Multiple: False
Delivery tag: 99 Multiple: False
Delivery tag: 100 Multiple: True

The multiple flag value is reversed in some cases. When I publish to a single queue then I get expected values for the multiple flag:

Delivery tag: 1 Multiple: False
Delivery tag: 2 Multiple: False
Delivery tag: 3 Multiple: False
Delivery tag: 6 Multiple: True
Delivery tag: 25 Multiple: True
Delivery tag: 49 Multiple: True
Delivery tag: 61 Multiple: True
Delivery tag: 100 Multiple: True

The code that prints out the above is:
```
def on_delivery_confirmation(frame):
    print(f"Delivery tag: {frame.method.delivery_tag} Multiple: {frame.method.multiple}")
```

**Comment by Vanlightly** [comment]
I think I may have misunderstood how the multiple flag works. Let me know if this interpretation matches yours:
If we consider we have sent 10 messages which are pending, then we can think of those 10 messages existing in a set of pending messages. 
Each ack/nack we get back with a multiple=false, we simply remove that message from the pending set.
When we get a multiple=true, then we remove all messages in the pending set with a sequence number equal or lower.
So, if the pending set starts as [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
ack delivery tag 1, multiple false. [2, 3, 4, 5, 6, 7, 8, 9, 10]
ack delivery tag 3, multiple false. [2, 4, 5, 6, 7, 8, 9, 10]
ack delivery tag 5, multiple false. [2, 4, 6, 7, 8, 9, 10]
ack delivery tag 6, multiple true. [7, 8, 9, 10]
ack delivery tag 8, multiple false. [7, 9, 10]
ack delivery tag 10, multiple true. []

**Comment by lukebakken** [comment]
Hello!

Thanks for using Pika and (presumably) RabbitMQ. We prefer to keep GitHub issues free of discussion and only use them for tracking actionable work. In the future, please post questions to either the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) or [`pika-python`](https://groups.google.com/forum/#!forum/pika-python) mailing lists.

Your understanding in your second comment is correct, that's how `multiple` works ([docs](https://www.rabbitmq.com/confirms.html#consumer-acks-multiple-parameter)).

**Comment by Vanlightly** [comment]
Ok, will do. Thanks.
