### ISSUE TITLE
basic_publish return value

### ISSUE THREAD

**Issue by azmeuk** [pika/pika#1141]
Hi.
The documentation page [Using Delivery Confirmations with the BlockingConnection](https://pika.readthedocs.io/en/0.12.0/examples/blocking_delivery_confirmations.html) shows that `channel.basic_publish` returns a boolean indicating a success status, but [the code of basic_publish](https://pika.readthedocs.io/en/0.12.0/_modules/pika/channel.html#Channel.basic_publish) do not return any value.

Is is a bug or is the documentation outdated?

**Comment by azmeuk** [comment]
Nevermind, BlockingChannel does have a return value.
https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L2223

**Comment by lukebakken** [comment]
Thanks for using Pika. In the future, please use the [`pika-python`](https://groups.google.com/forum/#!forum/pika-python) or [`rabbitmq-users`]() mailing list for questions instead of GitHub issues. We use issues to track verified bugs and features to work on only, not discussions.

**Comment by azmeuk** [comment]
Ok thanks!
