### ISSUE TITLE
Why I can't find any 'fanout' type of rabbitmq exchange 

### ISSUE THREAD

**Issue by yutiansut** [pika/pika#1143]
the rabbitmq still support the 'fanout' exchange type, however the pika 1.0+ version cannot find any example or code of 'fanout' type,( only  'topic' and 'direct'), is 'fanout' model be deprecated?

**Comment by lukebakken** [comment]
Yes, `fanout` is supported. Please ask questions on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) or [`pika-python`](https://groups.google.com/forum/#!forum/pika-python) mailing list.
