### ISSUE TITLE
QoS all_channels?

### ISSUE THREAD

**Issue by decaz** [pika/pika#1145]
I think `all_channels` parameter of `Channel.basic_qos` method is confusing because according to https://www.rabbitmq.com/consumer-prefetch.html it means applying QoS across all consumers on the channel (not "applying to all channels").

Should it not be called `global_` according to https://github.com/pika/pika/blob/e76e2eaeb1ea8b903934dc45bb843ff0fd315fc7/pika/spec.py#L1309-L1311

**Comment by lukebakken** [comment]
We could consider changing this for `1.0.0`. Do you use this feature?

**Comment by decaz** [comment]
Thanks! Currently I don't use this feature, just noticed this when researched.

**Comment by michaelklishin** [comment]
This is a good catch, we should rename it to `global` and de-emphasize in the docs (like we will do for other clients). The reason being is that quorum queues coming in 3.8 won't support every single QoS/prefetch feature classic queues have accumulated over the years.
