### ISSUE TITLE
how to deliver files by using pika

### ISSUE THREAD

**Issue by caibojun** [pika/pika#1149]
I'm a new hand and I want to use pika build a server and a client. It figures out `basic_publish` cann't take byte stream as its body parameter, but I also cann't convert my files to json object because of encode/decode issue. So how can I transport my files by pika ,can pika handle this problem? thx!

**Comment by lukebakken** [comment]
> It figures out basic_publish cann't take byte stream as its body parameter

Yes it can - `body` is a `str` which can be a sequence of bytes.

**Comment by caibojun** [comment]
It seems some where is still wrong,
`ch.basic_publish(exchange='',
                     routing_key=props.reply_to,
                     properties=pika.BasicProperties(correlation_id = props.correlation_id,
                                                     headers = header_data),
                     body=response)` 
In that code,`response` is a binary string converted by Excel file(*.xls) , and the code dosen't raise any wrong but I cann't get any  returns in my client .

**Comment by lukebakken** [comment]
@caibojun you should ask on a Python-specific help forum how to convert binary data correctly. Since you haven't shared any code, I can't help.
