### ISSUE TITLE
 Partial write, requeing remaining data

### ISSUE THREAD

**Issue by wxyhcr** [pika/pika#1150]
我在执行一个耗时的任务结束后，准备将数据写入到rabbitmq时，队列写不进去。任务执行完时，数据存入队列就出现 Partial write, requeing remaining data

**Comment by lukebakken** [comment]
Hello, Pika's maintainers use english to communicate. I can't help out here.

**Comment by aqparks** [comment]
Via Google translate...
"After I finish executing a time-consuming task, I am ready to write data to rabbitmq, the queue can not write. When the task is finished, the data appears in the queue."

**Comment by lukebakken** [comment]
@aqparks I should have mentioned that I did the same thing, and the user's message is still not helpful. @wxyhcr - the only suggestion I can make is to provide code to reproduce what you are seeing, and post it as a message (in English, if possible) to the [`pika-python`](https://groups.google.com/forum/?pli=1#!forum/pika-python) or [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. Please let us know what version of RabbitMQ, Python and Pika you are using, and please attach your RabbitMQ logs.

**Comment by lukebakken** [comment]
@wxyhcr - There is a chance that studying this **example** code may show you how to correctly acknowledge a message after a long-running task:

https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py
