### ISSUE TITLE
Connection error to rabitmq

### ISSUE THREAD

**Issue by ilias1995** [pika/pika#1151]
i have the problem with connection rabitmq.
log:
`Traceback (most recent call last):
File "manual_payment_processing.py", line 70, in send_pay
connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 130, in init
super(BlockingConnection, self).init(parameters, None, False)
File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 72, in init
on_close_callback)
File "/usr/local/lib/python3.6/site-packages/pika/connection.py", line 596, in init
self.connect()
File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
error = self._adapter_connect()
File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 301, in _adapter_connect
raise exceptions.AMQPConnectionError(error)
pika.exceptions.AMQPConnectionError: Connection to ::1:5672 failed: [Errno 99] Address not available`

code:
`connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))`

can some one help me?
Thank's!

**Comment by lukebakken** [comment]
You need to configure DNS or `/etc/hosts` on your workstation. The hostname `localhost` isn't resolving, which is indicative of a serious problem.

Please post questions to the [mailing list](https://groups.google.com/forum/#!forum/pika-python) next time. Thanks.

**Comment by lukebakken** [comment]
If you are on a system with an `/etc/hosts` file, what is its contents?

**Comment by ilias1995** [comment]
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters


> If you are on a system with an `/etc/hosts` file, what is its contents?

**Comment by lukebakken** [comment]
What is happening is that by using `localhost` Pika is trying to connect over IPv6, which isn't correctly configured on your system. You should change `/etc/hosts` so that the second line is this:

```
::1	localhost6 ip6-localhost ip6-loopback
```

Then, using `localhost` will use the IPv4 address.
