### ISSUE TITLE
pika does not work with AIX system from v0.11.0

### ISSUE THREAD

**Issue by Chinmay1412** [pika/pika#1152]
Apparently, PollPoller is broken on AIX system. So pika does not work with AIX system from v0.11.0. 
https://metacpan.org/pod/distribution/EV/libev/ev.pod#AIX-POLL-BUG

One solution is to use only SelectPoller in case of AIX system. And I tried that and it is working fine. Let me know when do you want the PR for the issue. And also looking for some other possible thoughts.

**Comment by lukebakken** [comment]
I don't have access to any AIX systems to even test a PR. Quoting the link you provided ...

> AIX is dead anyway

... if a user must use Pika on AIX, they will have to modify the library on their own as you have done.
