### ISSUE TITLE
Requeue order

### ISSUE THREAD

**Issue by maggyero** [pika/pika#1153]
According to the RabbitMQ documentation on [_Consumer Acknowledgements_](https://www.rabbitmq.com/confirms.html#consumer-nacks-requeue):

> When a message is requeued, it will be placed to its original position in its queue, if possible. If not (due to concurrent deliveries and acknowledgements from other consumers when multiple consumers share a queue), the message will be requeued to a position closer to queue head.

So with a single client consumer, if the server queue is initially

> tail [c b a] head

and the client consumer consumes the head message ("a"), the server queue becomes:

> tail [c b] head

Then if the client consumer nacks the processed message, the message gets requeued in the server queue at the head (its "original position" as per the documentation) and the server queue should become:

> tail [c b a] head

Finally the client consumer should consume again the same head message ("a").

But that is not what I observed using the Python library Pika. What I observed is that nacked messages gets requeued at the tail of the server queue, not at the head (the "original position"). Is the RabbitMQ documentation correct or is the library Pika correct?

Sample code:

```
import logging

import pika

logging.basicConfig(level=logging.INFO)
logging.getLogger("pika").propagate = False
parameters = pika.ConnectionParameters()


# Produce messages

for body in ["a", "b", "c"]:
    with pika.BlockingConnection(parameters) as connection:
        queue = "foobar"
        routing_key = queue
        channel = connection.channel()
        channel.queue_declare(queue=queue)
        channel.publish(exchange="", routing_key=routing_key, body=body)
        logging.info("Produced message %r with routing key %r", body, routing_key)


# Consume messages

def handle(channel, method, properties, body):
    logging.info("Consumed message %r from queue %r", body.decode(), queue)
    channel.basic_nack(method.delivery_tag)


with pika.BlockingConnection(parameters) as connection:
    queue = "foobar"
    channel = connection.channel()
    channel.queue_declare(queue=queue)
    channel.basic_consume(queue=queue, on_message_callback=handle)
    channel.start_consuming()
```

Output:

> INFO:root:Produced message 'a' with routing key 'foobar'
> INFO:root:Produced message 'b' with routing key 'foobar'
> INFO:root:Produced message 'c' with routing key 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'c' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'c' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'c' from queue 'foobar'

**Comment by lukebakken** [comment]
Hello, thank you for using Pika and RabbitMQ.

Please note the "if possible" in the documentation. You shouldn't depend on the position at which a message is re-enqueued. Since you are consuming messages without any prefetch setting, by the time you nack message `a` messages `b` and `c` have already been de-queued and are probably already on the network or in your client application's TCP buffers.

Try setting `channel.basic_qos(prefetch_count=1)` to see if the behavior is different.

Finally, GitHub issues are used by the Pika team to track work. If you'd like to ask questions like this one, please use the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

**Comment by maggyero** [comment]
Thank you Luke! With `channel.basic_qos(prefetch_count=1)` I get the documented behaviour:

> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
