### ISSUE TITLE
Heartbeat timeout bug on Pika 1.0.0b

### ISSUE THREAD

**Issue by maggyero** [pika/pika#1154]
According to the [RabbitMQ documentation](https://www.rabbitmq.com/heartbeats.html#heartbeats-interval):

>  Heartbeat frames are sent about every heartbeat timeout / 2 seconds. This value is sometimes referred to as the heartbeat interval. After two missed heartbeats, the peer is considered to be unreachable. Different clients manifest this differently but the TCP connection will be closed. When a client detects that RabbitMQ node is unreachable due to a heartbeat, it needs to re-connect.
> It is important to not confuse the timeout value with the interval one. RabbitMQ configuration exposes the timeout value, so do the officially supported client libraries. However some clients might expose the interval, potentially causing confusion. 

On Pika 1.0.0b (latest)—but not on Pika 0.12.0 (stable) which behaves correctly—there is a bug: the heartbeat _timeout_ given to Pika is interpreted as an heartbeat _interval_. In other words, heartbeat frames are sent every heartbeat timeout seconds instead of every heartbeat interval seconds.

Sample code:

```
import logging
import time

import pika

logging.basicConfig(level=logging.DEBUG)
parameters = pika.ConnectionParameters(heartbeat=10)  # heartbeat frames should be sent every 5 s


# Produce messages

with pika.BlockingConnection(parameters) as connection:
    queue = "foobar"
    routing_key = queue
    body = "a"
    channel = connection.channel()
    channel.queue_declare(queue=queue)
    channel.publish(exchange="", routing_key=routing_key, body=body)
    logging.info("Produced message %r with routing key %r", body, routing_key)


# Consume messages

def handle(channel, method, properties, body):
    logging.info("Consumed message %r from queue %r", body.decode(), queue)
    time.sleep(1)
    channel.basic_nack(method.delivery_tag)


with pika.BlockingConnection(parameters) as connection:
    queue = "foobar"
    channel = connection.channel()
    channel.basic_qos(prefetch_count=1)
    channel.queue_declare(queue=queue)
    # replace on_message_callback=handle with consumer_callback=handle to test on Pika 0.12.0
    channel.basic_consume(queue=queue, on_message_callback=handle)
    channel.start_consuming()
```

Relevant output on Pika 1.0.0b (here a heartbeat frame is sent incorrectly every 10 s):

> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> DEBUG:pika.heartbeat:Received 0 heartbeat frames, sent 0
> DEBUG:pika.heartbeat:Sending heartbeat frame
> DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x0000018812F82470> with deadline=1547588424.950964 and callback=<bound method HeartbeatChecker.send_and_check of <pika.heartbeat.HeartbeatChecker object at 0x0000018812F82710>>; now=1547588414.950964; delay=10
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> INFO:root:Consumed message 'a' from queue 'foobar'
> DEBUG:pika.heartbeat:Received 0 heartbeat frames, sent 1
> DEBUG:pika.heartbeat:Sending heartbeat frame
> DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x0000018812F829E8> with deadline=1547588435.046924 and callback=<bound method HeartbeatChecker.send_and_check of <pika.heartbeat.HeartbeatChecker object at 0x0000018812F82710>>; now=1547588425.046924; delay=10

Relevant output on Pika 0.12.0 for comparison (here a heartbeat frame is sent correctly every 5 s):

> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> DEBUG:pika.heartbeat:Sending heartbeat frame
> DEBUG:pika.heartbeat:Sending heartbeat frame
> DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x000002116D36CB00> with deadline=1547587885.1495485 and callback=<bound method HeartbeatChecker._send_heartbeat of <pika.heartbeat.HeartbeatChecker object at 0x000002116D36CAC8>>; now=1547587880.1495485; delay=5.0
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> INFO:root:Consumed message 'b' from queue 'foobar'
> DEBUG:pika.heartbeat:Sending heartbeat frame
> DEBUG:pika.heartbeat:Sending heartbeat frame
> DEBUG:pika.adapters.select_connection:call_later: added timeout <pika.adapters.select_connection._Timeout object at 0x000002116D36CC18> with deadline=1547587890.1964712 and callback=<bound method HeartbeatChecker._send_heartbeat of <pika.heartbeat.HeartbeatChecker object at 0x000002116D36CAC8>>; now=1547587885.1964712; delay=5.0

**Comment by lukebakken** [comment]
I can't reproduce this using `1.0.0b` and your code. Heartbeats are sent from Pika to RabbitMQ every 5 seconds.

[pika-1.0.0b1-trace.pcapng.gz](https://github.com/pika/pika/files/2765808/pika-1.0.0b1-trace.pcapng.gz)

**Comment by maggyero** [comment]
@lukebakken But why on Pika 1.0.0b1 do I see groups of _10 lines_ like this in the log:

> INFO:root:Consumed message 'a' from queue 'foobar'

while on Pika 0.12.0 I see groups of _5 lines_? Do you get the same output as me?

**Comment by maggyero** [comment]
@lukebakken Okay I have found the issue: the version Pika 1.0.0b1 on PyPI that you get when you type:

> pip install pika-dev

is from [21 March 2018](https://pypi.org/project/pika-dev/#description), and I see on Github that the _same version_ was released on [28 Sep 2018](https://github.com/pika/pika/pull/1057)! So there is a version mismatch with PyPI. Could you upload the latest version on PyPI?

And it makes sense that I have this heartbeat timeout issue since this issue was actually solved on [6 June 2018](https://github.com/pika/pika/pull/1057).

**Comment by lukebakken** [comment]
I am not responsible for `pika-dev`. If you'd like to install the correct version of `1.0.0b1` from pypi, use the instructions [here](https://pypi.org/project/pika/1.0.0b1/):

```
pip install pika==1.0.0b1
```

**Comment by lukebakken** [comment]
@jstasiak - would you mind deleting the [`pika-dev`](https://pypi.org/project/pika-dev/) project on PyPi as it has caused confusion for @maggyero ?

**Comment by maggyero** [comment]
@lukebakken Thank you very much, it works like a charm now!
