### ISSUE TITLE
Pika 1.0.0b1 version mismatch on PyPI

### ISSUE THREAD

**Issue by maggyero** [pika/pika#1155]
The version Pika 1.0.0b1 on PyPI that you get when you type:

> pip install pika-dev

is from [21 March 2018](https://pypi.org/project/pika-dev/#description), and I see on Github that the _same version_ was released on [28 Sep 2018](https://github.com/pika/pika/pull/1057)! So there is a version mismatch with PyPI. Could you upload the real Pika 1.0.0b1 version on PyPI?

**Comment by lukebakken** [comment]
Please re-read the commentary on #1154. `pika-dev` is in no way associated with this project.
