### ISSUE TITLE
A way to continuously provision latest Erlang and RabbitMQ on CI

### ISSUE THREAD

**Issue by michaelklishin** [pika/pika#1158]
I recently revisited how Langohr, Bunny, March Hare and RabbitMQ Objective-C clients provision RabbitMQ on CI. I'd be happy to submit a PR that does the same thing for Pika if there's interest (I am not sure why the `.travis.yml` is so extensive, very likely there are reasons for that).

The gist of the idea can be found [in this Debian/Ubuntu-specific script](https://github.com/ruby-amqp/bunny/blob/master/bin/ci/install_on_debian.sh). Another trick I adopted from the original author of the Objective-C client is [using `lsof -i` to determine service availability](https://github.com/ruby-amqp/bunny/blob/master/.travis.yml#L7).

Lastly, I migrated to Ubuntu Xenial for all of the above [except the Objective-C client].

@lukebakken would you agree this would be an improvement for Pika? My favorite part is that we will be testing with the latest versions of Erlang and RabbitMQ without the need to manually bump
versions.

**Comment by lukebakken** [comment]
Great idea!

**Comment by lukebakken** [comment]
It would be great if we didn't have to enable `sudo`, though. Builds are a lot faster without it.

**Comment by michaelklishin** [comment]
I don't think we can provision packages without `sudo`, so this is probably a no-go then.

**Comment by lukebakken** [comment]
@michaelklishin I will check the Travis docs, because they do allow some `apt` changes ... maybe you can add other sources? I'll let you know. It is a great idea.

**Comment by lukebakken** [comment]
Closing because we use GH actions now. Linux builds use Ubuntu docker images, and Windows builds depend on this file to know which versions to use:

https://github.com/pika/pika/blob/main/testdata/versions.json

The above file could be replaced with some GitHub API queries. I'll look into it.
