### ISSUE TITLE
Heartbeat value must be <65536

### ISSUE THREAD

**Issue by Avivsalem** [pika/pika#1194]
When you try to create a connection with heartbeat parameter larger then 65536, it will raise a pack exception on connect....

I've looked at the documentation and found no mention of this limit. 

Of course it is not a big bug, since this value is big enough for all intents and purposes, but it either should be documented, or raise a more clear exception... 

Thanks!

**Comment by lukebakken** [comment]
The spec documents heartbeat to be a [`short`](https://www.rabbitmq.com/amqp-0-9-1-reference.html#connection.tune.heartbeat). It's not clear whether it's signed or unsigned but, either way, the upper limit is far larger than any reasonable heartbeat timeout.

We try to not go overboard with validation in this library, so I think we'll skip validating this until at least one other person notices. Thanks.
