### ISSUE TITLE
twisted: basic_consume hangs indefinitely when errors occur

### ISSUE THREAD

**Issue by jeremycline** [pika/pika#1201]
If an error happens during a call to basic_consume (permission denied, queue doesn't exist, etc), the deferred returned by the Twisted adapter's basic_consume never has its errback or callback called, so anything awaiting results will get stuck forever.

A simple reproducer you can run with "twistd -n -y <file.py>", assuming you have a broker running on localhost:5672 and the "does_not_exist" queue truly doesn't exist:

```
from twisted.internet import reactor, endpoints, protocol, defer
from twisted.application import service, internet
from twisted.logger import Logger
from pika.adapters.twisted_connection import TwistedProtocolConnection
from pika.exceptions import ChannelClosedByBroker


log = Logger("hanging_consume")


@defer.inlineCallbacks
def on_connected(connection):
    yield connection.ready
    channel = yield connection.channel()
    log.info("Calling basic_consume")
    try:
        queue, tag = yield channel.basic_consume(queue="does_not_exist")
        log.info("Unexpectedly succeeded at basic_consume")
        reactor.crash()

    except ChannelClosedByBroker as e:
        log.info("Got the expected exception {e}; halting", e=e)
        reactor.stop()


application = service.Application("Demo AMQP Client")
amqp_endpoint = endpoints.clientFromString(reactor, 'tcp:localhost:5672')
amqp_factory = protocol.Factory.forProtocol(TwistedProtocolConnection)
amqp_service = internet.ClientService(amqp_endpoint, amqp_factory)
amqp_service.setServiceParent(application)
deferred_conn = amqp_service.whenConnected()
deferred_conn.addCallback(on_connected)
```

You'll find the ``yield channel.basic_consume(queue="does_not_exist")`` call gets stuck. This is because the broker sent a "Channel.Close" response. The fix is to add the Deferred to the set of pending Deferreds that error back when the channel is closed.

**Comment by lukebakken** [comment]
> The fix is to add the Deferred to the set of pending Deferreds that error back when the channel is closed.

It would be great if you could submit a PR for that. Thank you.

**Comment by lukebakken** [comment]
Thanks for the PR!

**Comment by jeremycline** [comment]
Haha, that was an incredibly fast response. No problem!
