### ISSUE TITLE
InvalidFieldTypeException when receiving messages with int values in headers dict

### ISSUE THREAD

**Issue by tsachi-guardicore** [pika/pika#1205]
Pika throws an InvalidFieldTypeException on messages produced by haigha Python package with int values in the headers dictionary. 

Notes:
RabbitMQ can handle the message generated by _haigha_ (See attached screenshot)
Pika can process similar messages that are published by pika

An example for a failing application_headers: 
```
{'compressed': False, 'sequence': 5}
```

Stack trace:
```
File " \venv\lib\site-packages\pika\adapters\blocking_connection.py", line 1688, in _basic_consume_impl
    self._flush_output(ok_result.is_ready)
File " \venv\lib\site-packages\pika\adapters\blocking_connection.py", line 1327, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
File " \venv\lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.StreamLostError: Stream connection lost: InvalidFieldTypeException
![pika + haigha messages](https://user-images.githubusercontent.com/47942606/56371619-18635680-6206-11e9-804a-fcf1a2e0d1de.PNG)

: Unsupported field kind b''
```

Attachments:
haigha_publisher.py : Publish messages that cause the error in pika
receiver_2.py: pika receiver code
publisher.py: pika publish code - receiver handles it
pika + haigha messages.PNG: A screenshot of the messages sent by haigha and pika.
[examples.zip](https://github.com/pika/pika/files/3095058/examples.zip)

The following application_header schemas were received succesfully by pika:
```
{'compressed': False, },
{'compressed': False, 'sequence': '5'},
{'compressed': False, 'sequence': None},
{'compressed': False, 'encoding': 'json'},
{'compressed': False, 'encoding': 'json', 'sequence': ''},
{'compressed': False, 'encoding': 'json', 'sequence': '5'}
```

**Comment by tsachi-guardicore** [comment]
[examples.zip](https://github.com/pika/pika/files/3095059/examples.zip)
![pika + haigha messages](https://user-images.githubusercontent.com/47942606/56371873-9a537f80-6206-11e9-8053-d42bc165b35d.PNG)

**Comment by lukebakken** [comment]
See this issue: https://github.com/rabbitmq/rabbitmq-common/issues/261

Then, this: https://www.rabbitmq.com/amqp-0-9-1-errata.html

Finally, the Java implementation of the `s` field type:

https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ValueReader.java#L193-L195

So, it looks like Pika is adhering to the 0.9.1 spec, while haigha, RabbitMQ and the Java client interpret `s` as a signed short int. Note that the Java client doesn't attempt to decode the `u` field type (@acogoluegnes is this worth investigating?)

@michaelklishin @gmr @vitaly-krugl any thoughts on Pika's behavior here?

**Comment by gmr** [comment]
I'd support it and do in [gmr/pamqp.](https://github.com/gmr/pamqp) FWIW I did intend on moving spec and the frame marshalling/unmarshalling bits in pika to use pamqp but hadn't had the bandwidth to do so. Perhaps it's worth considering or just stealing bits?
