### ISSUE TITLE
BlockingChannel.basic_publish does not return value.

### ISSUE THREAD

**Issue by potbunker** [pika/pika#1206]
[Documentation](https://pika.readthedocs.io/en/latest/examples/blocking_publish_mandatory.html) states that `basic_publish` with `mandatory` set to `True` returns a value for `bool` check. But it is always `None`

```python
import pika

# Open a connection to RabbitMQ on localhost using all default parameters
connection = pika.BlockingConnection()

# Open the channel
channel = connection.channel()

# Declare the queue
channel.queue_declare(queue="test", durable=True, exclusive=False, auto_delete=False)

# Enabled delivery confirmations
channel.confirm_delivery()

# Send a message
if channel.basic_publish(exchange='test',
                         routing_key='test',
                         body='Hello World!',
                         properties=pika.BasicProperties(content_type='text/plain',
                                                         delivery_mode=1),
                         mandatory=True):
    print('Message was published')
else:
    print('Message was returned')
```

**Comment by potbunker** [comment]
Pika version 0.12 behaves correctly, but not 1.0.0 and above

**Comment by lukebakken** [comment]
> Pika version 0.12 behaves correctly, but not 1.0.0 and above

Yes, `1.0.0` behaves correctly. If you need me to explain why, please ask.

**Comment by lukebakken** [comment]
@potbunker please see https://github.com/pika/pika/commit/61c3fb6ad3961bb3498ad32c70f89e097c0539f2

**Comment by potbunker** [comment]
Thanks for the reply. I was comparing with the documemt, which is
consistent with 0.12.

**Comment by potbunker** [comment]
Looks like the document (example code) was updated as well. For some
reason, the document site was still showing the original version.

**Comment by lukebakken** [comment]
> For some reason, the document site was still showing the original version

Yes, because I only changed it yesterday. Thanks for pointing out the old documentation.

**Comment by a523** [comment]
ya, I have the same problem.  but I have another related question .
I see this in the rabbitmq's doc:

> Using standard AMQP 0-9-1, the only way to guarantee that a message isn't lost is by using transactions -- make the channel transactional then for each message or set of messages publish, commit. In this case, transactions are unnecessarily heavyweight and decrease throughput by a factor of 250. To remedy this, a confirmation mechanism was introduced. It mimics the consumer acknowledgements mechanism already present in the protocol.

I wan to what  kind this  way  is transactional or confirmation mechanism ? if this way is in confirm mode.
I see this in the rabbitmq's doc again:
>Once a channel is in confirm mode, both the broker and the client count messages (counting starts at 1 on the first confirm.select). The broker then confirms messages as it handles them by sending a basic.ack on the same channel. The delivery-tag field contains the sequence number of the confirmed message. The broker may also set the multiple field in basic.ack to indicate that all messages up to and including the one with the sequence number have been handled.

My question is Where are the client count messages in this code, if this way is in confirm mode?
Thanks
