### ISSUE TITLE
Pika doesn't work on python <2.7.9

### ISSUE THREAD

**Issue by Avivsalem** [pika/pika#1211]
Pika 1.0.0 uses ssl.SSLContext which exists only in python 2.7.9 and higher...

You should reflect that in the documentation and version modifiers... 
Thanks!

**Comment by lukebakken** [comment]
Considering Python `2.7.9` was released over 4 years ago, and is no longer supported, I wouldn't expect anyone to use it in production.

I would be happy to accept a PR with documentation or other changes to make this clearer.

**Comment by AlexPham1988** [comment]
Hi.

I faced the same issue. The point is many companies has developed their internal production environment long time ago, and stabilized with old Python version (< 2.7.9). Moving to new version would cost a huge effort without visible benefit. Could you please consider the support for at least 2.7.2 ?

Thanks
Alex

**Comment by lukebakken** [comment]
@AlexPham1988 this project is maintained by volunteers who do so in their free time. We don't have the time or resources to support out-of-date Python versions.

Also, please note that Python 2 will be unsupported as of January, 2020 - https://endoflife.date/python
