### ISSUE TITLE
StreamLostError after upgrading from 0.13.1 to 1.0.1

### ISSUE THREAD

**Issue by sulsj** [pika/pika#1224]
Hi, 
As the title, after upgrading the pika version from 0.13.1 to 1.0.1, our production code prints out the below log. Any clue will be appreciated. 

Thanks,
Seung

> 2019-06-10 12:53:00,494 | jgi-task-manager | recv_hb_from_workers_thread | ERROR : Exception: Failed to get a message from _jtm_worker_hb_queue.cori.jtm.
Traceback (most recent call last):
  File "/.../venv/bin/jgi-task-manager", line 283, in recv_hb_from_workers_thread
    methodFrame, headerFrame, body = ch.basic_get(queue=hbQueueName, auto_ack=True)
  File "/.../venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2151, in basic_get
    self._basic_getempty_result.is_ready)
  File "/.../venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1327, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
  File "/.../venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
StreamLostError: Stream connection lost: error(104, 'Connection reset by peer')
2019-06-10 12:53:00,495 | jgi-task-manager | recv_hb_from_workers_thread | ERROR : Detail: Stream connection lost: error(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/.../venv/bin/jgi-task-manager", line 283, in recv_hb_from_workers_thread
    methodFrame, headerFrame, body = ch.basic_get(queue=hbQueueName, auto_ack=True)
  File "/.../venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2151, in basic_get
    self._basic_getempty_result.is_ready)
  File "/.../venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1327, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
  File "/.../venv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
StreamLostError: Stream connection lost: error(104, 'Connection reset by peer')

**Comment by lukebakken** [comment]
```
error(104, 'Connection reset by peer')
```

Something killed the TCP connection. What is logged by your AMQP broker  (assuming it is RabbitMQ) at the same time?

**Comment by sulsj** [comment]
The broker is running by our compute center so I am not sure how I can see the log. Is there any way I can retrieve the log via the management tools?
Thanks!

**Comment by lukebakken** [comment]
You have to have access to the server to retrieve the log.

If I had to guess, your code is blocking Pika's I/O loop, a heartbeat timeout is happening, and RabbitMQ is closing the connection abruptly. Or, a network device like a load balancer is causing the issue.

If you can share your code, please attach it in a response. Otherwise, there is not much more assistance I can give.

**Comment by sulsj** [comment]
Hmm. I need to comment out "heartbeat_interval" in the connection param to use v1.0.1. When I use v0.13.1, I set "heartbeat_interval=0".

> class RmqConnectionHB(object):
    __connection = None
    def __init__(self, hb): # return a pika connection
        atexit.register(rmqClose, rmqConnObj=self)
        if not self.__connection:
            creds = pika.PlainCredentials(RMQ_USER, RMQ_PASS)
            params = pika.ConnectionParameters(credentials=creds,
                                               host=RMQ_HOST,
                                               virtual_host=RMQ_VHOST,
                                               # heartbeat_interval=hb, 
                                               port=RMQ_PORT
                                               )
            self.__connection = pika.BlockingConnection(params)
        else:
            print("Already connected.")
...

**Comment by lukebakken** [comment]
That means with version `0.13.1` you disabled heartbeats (not recommended). When you upgraded to version `1.0.1`, you re-enabled them and now RabbitMQ thinks your connection is dead either because there isn't enough activity on it or because your code is blocking the I/O loop in Pika.

To fix this you can either [re-disable heartbeats](https://github.com/pika/pika/blob/1.0.1/pika/connection.py#L554) or ensure your code doesn't block Pika. If you'd like me to review your code to see where it is blocking Pika, I am happy to do so, just attach it.

Thanks for using Pika!

**Comment by sulsj** [comment]
Sure. This is receiving thread code.

`
# ----------------------------------------------------------------------------------------
def recv_hb_from_workers_thread(hbQueueName, parentPid, hbeatProc, logDestDir, resourceReport):
# ----------------------------------------------------------------------------------------
    """
    Receive hearbeats from all the workers running
    :param hbQueueName: queue name to listen to
    :param parentPid: to kill the parent for termination
    :param hbeatProc: sending hearbeat thread handle (to kill it)
    :param logDestDir: save resource usage log file
    :param resourceReport: enable resource report printing/saving
    :return: 
    """
    # TODO: change to event driven by ch.basic_consume and ch.start_consuming
    rabbitConnection = RmqConnectionHB(0)
    conn = rabbitConnection.open()
    ch = conn.channel()

    exchName = JTM_WORKER_HB_EXCH

    ch.exchange_declare(exchange=exchName,
                        exchange_type="direct",
                        durable=False,
                        auto_delete=False)

    # This queue can be declared from workers first.
    try:
        ch.queue_declare(queue=hbQueueName,
                         durable=False,
                         exclusive=False,
                         auto_delete=True)
    except Exception as detail:
        logger.exception("Exception: The queue, %s is in use.", hbQueueName)
        logger.exception("Detail: %s", str(detail))
        sys.exit(1)

    # Queue binding for the queue to receive hb from workers
    ch.queue_bind(exchange=exchName,
                  queue=hbQueueName,
                  routing_key=hbQueueName)

    bCleared = False
    bFound = False
    numWorkerCheck = 0
    interval = CLIENT_HB_RECV_INTERVAL

    # TODO: need to open/close in place to evade from locking. Any other solutions?
    # Note: tried connection pool but not working as expected
    # db = DbSqlLite(dbpath="jtm.db")
    db = DbSqlMy(db=MYSQL_DB)

    while 1:
        wids = {}
        try:
            if int(PIKA_VER[0]) < 1:  # v0.13.1
                methodFrame, headerFrame, body = ch.basic_get(queue=hbQueueName, no_ack=True)
            else:  # v1.0.1
                methodFrame, headerFrame, body = ch.basic_get(queue=hbQueueName, auto_ack=True)
        except Exception as detail:
            logger.exception("Exception: Failed to get a message from %s.", hbQueueName)
            logger.exception("Detail: %s", str(detail))
            ch.close()
            conn.close()
            sys.exit(1)

        if body and not bCleared:
            # To clear up any heartbeat messages left in the heartbeat queue.
            for i in range(int(methodFrame.message_count)):
                if int(PIKA_VER[0]) < 1:  # v0.13.1
                    _, _, _ = ch.basic_get(queue=hbQueueName, no_ack=True)
                else:  # v1.0.1
                    _, _, _ = ch.basic_get(queue=hbQueueName, auto_ack=True)

            bCleared = True

        elif body and bCleared:
            # To deal with the heartbeats from the worker(s). The workers send
            # each hostname and pid. Using "dict", get the number of unique
            # pids of the runninng workers.
            msgUnzipped = json.loads(zloads(body))
            # type conversion and sort by key
            msgUnzipped = {int(k): v for k, v in msgUnzipped.items()}

            # worker id is used to collect unique rootPid (= num of workers)
            wid = msgUnzipped[HB_MSG["worker_id"]]
            wids[wid] = msgUnzipped

            # NOTE: Workers send it"s hb interval to the client in the msg packet.
            # Set the checking heartbeat as (jtm-worker"s sending heartbeat
            # interval value * intervalIncRate)

            # Worker's hb should be more than one so consume all the hb's
            for i in range(int(methodFrame.message_count)):
                if int(PIKA_VER[0]) < 1:  # v0.13.1
                    methodFrame, headerFrame, body = ch.basic_get(queue=hbQueueName, no_ack=True)
                else:  # v1.0.1
                    methodFrame, headerFrame, body = ch.basic_get(queue=hbQueueName, auto_ack=True)

                msgUnzipped = json.loads(zloads(body))
                msgUnzipped = {int(k): v for k, v in msgUnzipped.items()}
                wid = msgUnzipped[HB_MSG["worker_id"]]
                wids[wid] = msgUnzipped

                ...

        elif not body and bCleared and bFound:
            # If we are here, unfortunately, we lost all the workers that we've been using.
            numWorkerCheck += 1
            g_nTotalWorkers.value = 0
            logger.info("Waiting for worker(s)...")

            if WORKER_HB_CHECK_MAX_COUNT != 0 and numWorkerCheck > WORKER_HB_CHECK_MAX_COUNT:  # hit the max checking limit
                # Close connection and kill parent and itself
                ch.close()
                conn.close()
                hbeatProc.terminate()
                os.kill(int(parentPid), signal.SIGTERM)
                sys.exit(1)

            # If there no workers alive after 5 checks, set lifeLeft to -1 for all
            if numWorkerCheck == 3:
                try:
                    db.execute(JTM_SQL["update_workers_lifeleft_for_last"])
                    db.commit()
                except Exception as e:
                    logger.critical(e)
                    logger.critical("Failed to update workers table for lifeleft.")
                    raise

        time.sleep(interval)



`

**Comment by lukebakken** [comment]
First thing, `basic.get` is not a recommended way to get messages from RabbitMQ, but we can work with it here.

There are several places that could block Pika. If your work takes too long to do (JSON parsing, db transactions), that could do it. The `time.sleep(interval)` call could do it as well.

As a first fix, replace `time.sleep(interval)` with `conn.process_data_events(time_limit=interval)` and ensure that `interval` is greater than `0`.

**Comment by sulsj** [comment]
And there are hundres of workers send msg to this thread by

```
rabbitConnection = RmqConnectionHB(0)
    conn = rabbitConnection.open()
    ch = conn.channel()

    exchName = JTM_WORKER_HB_EXCH
    workerHbQ = WORKER_HB_Q_POSTFIX
    hostName = socket.gethostname()

    ch.exchange_declare(exchange=exchName,
                        exchange_type="direct",
                        durable=False,
                        auto_delete=False)
    while 1:
      ...
      ch.basic_publish(exchange=exchName,
                           routing_key=workerHbQ,
                           body=msgZipped)

      time.sleep(float(interval))

```

**Comment by sulsj** [comment]
OK. I will try and keep you updated. Thanks for the help. :)

**Comment by sulsj** [comment]
Can I ask questions which seems like related?

I am running many workers and each worker gets a task and executes it.
This is the part waiting for a request in a worker.

`
    ch.basic_qos(prefetch_count=1)
    if int(PIKA_VER[0]) < 1:  # v0.13.1
        ch.basic_consume(on_request, queue=innerTaskReqQ, no_ack=False)
    else:  # v1.0.1
        ch.basic_consume(queue=innerTaskReqQ, on_message_callback=on_request, auto_ack=False)

    try:
        ch.start_consuming()
    except KeyboardInterrupt:
        ch.stop_consuming()`

And the handler looks like

`
def on_request(ch, method, props, body):
    msgUnzipped = json.loads(zloads(body))
    taskId = msgUnzipped["task_id"]
    ...
    response = run_something(msgUnzipped)
    ...
    try:
        logger.debug("Sent the result back to the client via '%s' queue.", props.reply_to)

        # Note: to keep result messages even the client is not alive.
        ch.queue_declare(queue=props.reply_to,
                         durable=True,
                         exclusive=False,
                         auto_delete=True)
                         # auto_delete=False)

        assert props.reply_to.endswith(CNAME)
        ch.basic_publish(exchange=JTM_INNER_MAIN_EXCH,
                         routing_key=props.reply_to,  # use the queue which the client created
                         properties=pika.BasicProperties(
                             delivery_mode=2,  # make message persistent
                             correlation_id=props.correlation_id),
                         body=response)

        ch.basic_ack(delivery_tag=method.delivery_tag)

    except Exception as e:
        logger.critical("Something wrong in on_request(): %s", e)
    ...
`

I've seen many connection disconnection errors like

> jtm-worker | on_request | CRITICAL : Something wrong in on_request(): (-1, "error(104, 'Connection reset by peer')")

. 

How can I fix it?

**Comment by lukebakken** [comment]
Please see [this code](https://github.com/pika/pika/blob/1.0.1/examples/basic_consumer_threaded.py) for how to run your task in a different thread and acknowledge the message correctly. Please note that you can't call any of Pika's instance methods from threads other than the I/O loop thread. The code sample shows the correct way to do so.

If you have further questions, move this discussion to [the mailing list](https://groups.google.com/forum/#!forum/pika-python) since there is no evidence of a bug in Pika.

When you post your question to the mailing list, please _attach_ your code as a file, and include the log messages from RabbitMQ that correspond to the "Connection reset by peer" errors.

**Comment by sulsj** [comment]
I have a few more time.sleep() in my codes. Do you recommend to replace those with conn.process_data_events(time_limit=interval)?

**Comment by lukebakken** [comment]
Please see [this comment](https://github.com/pika/pika/issues/1224#issuecomment-500951004). Further questions should be on the mailing list because other Pika users can learn from them.
