### ISSUE TITLE
can't install pika with "--no-binary :all:" and "LANG=C"

### ISSUE THREAD

**Issue by thefab** [pika/pika#1226]
Hi,

A little bug report. When we try to install pika without wheels, for example with 

```
pip install  --no-binary :all: pika
```

it works if `LANG=fr_FR.UTF-8`

But, on a blank virtualenv, if I do

```
export LANG=C
pip install  --no-binary :all: pika
```

it fails with:

```
Collecting pika
  Downloading https://files.pythonhosted.org/packages/ca/82/bb0e6c255575cbd8f57a8bd47aa2f29a2aa24f1363408abccd0690a3a244/pika-1.0.1.tar.gz (139kB)
    100% |################################| 143kB 2.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tb1sknpn/pika/setup.py", line 21, in <module>
        long_description=open('README.rst').read(),
      File "/home/fab/metwork/mfext/src/pikatest/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4550: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tb1sknpn/pika/
```

**Comment by lukebakken** [comment]
It looks like there is either an invalid character in `README.rst` and / or `setup.py` needs to be modified to take `--no-binary` into account. If you have time to submit a fix via a pull request, I would really appreciate it.

**Comment by thefab** [comment]
probably fixed in master by https://github.com/pika/pika/commit/e95001e480ec30f1617c47e77fb92e0384ff9e78

**Comment by lukebakken** [comment]
Thanks, fixed by #1207 

If you have a second to build the package from `master` and test using `pip` in your environment, that would be great. Thanks.

**Comment by thefab** [comment]
just done, it works with master

thank you!

**Comment by lukebakken** [comment]
Great and thank you for verifying
