### ISSUE TITLE
The query string parameter 'ssl' for URLParameters raises the exception

### ISSUE THREAD

**Issue by sokolovs** [pika/pika#1235]
The query string parameter 'ssl' for URLParameters raises the exception 'Unknown URL parameter: ssl'. This is a bug, because URLParameters does not contain the _set_url_ssl method :(

**Comment by lukebakken** [comment]
Hello and thanks for using Pika.

The correct parameter is called `ssl_options` and is documented [here](https://github.com/pika/pika/blob/1.1.0/pika/connection.py#L688-L692).
