### ISSUE TITLE
transactional message mechanism

### ISSUE THREAD

**Issue by wanguanfu** [pika/pika#1236]
Pika does not support rabbitmq's transactional message mechanism, or is there any guarantee other than the reply mechanism?

**Comment by lukebakken** [comment]
Hello and thanks for using Pika.

You should be using publisher confirmations. Please see the RabbitMQ documentation here: [link](https://www.rabbitmq.com/confirms.html).

If you have further questions, please do *not* use GitHub issues, but one of these mailing lists:

https://groups.google.com/forum/?pli=1#!forum/pika-python
https://groups.google.com/forum/?pli=1#!forum/rabbitmq-users
