### ISSUE TITLE
pika throws error 'IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)

### ISSUE THREAD

**Issue by Anaghamhetre16** [pika/pika#1247]
I am trying to connect with AMQP broker using pika library but it throws exception "IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)" . 

I shared my code

import pika
import ssl

credentials = pika.PlainCredentials(username,password)
parameters = pika.ConnectionParameters(host,5671,virtualhost,credentials)
try:
	connection = pika.BlockingConnection(parameters)
except pika.exceptions.IncompatibleProtocolError as err:
	print("IncompatibleProtocolError",err)
channel = connection.channel()

channel.queue_declare(queue=queuename)
print(' [*] Waiting for messages. To exit press CTRL+C')

def callback(ch, method, properties, body):
    print(" [x] Received %r" % body)
    
channel.basic_qos(prefetch_count=1)
channel.basic_consume(queue=queuename, on_message_callback=callback)

channel.start_consuming()

**Comment by lukebakken** [comment]
You are connecting to port `5671`, which is usually the TLS/SSL port for RabbitMQ. However, you have not configured Pika to use TLS/SSL. Pika won't do that automatically for you. Please see [the docs](https://github.com/pika/pika/blob/master/docs/examples/tls_server_authentication.rst), or [here](https://pika.readthedocs.io/en/stable/examples/tls_mutual_authentication.html)
