### ISSUE TITLE
AttributeError: module 'pika' has no attribute 'BlockingConnection'

### ISSUE THREAD

**Issue by grupoz** [pika/pika#1250]
```
Name: pika
Version: 1.1.0
```

```
python -V
Python 3.6.8
```
```python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(host='10.0.0.46'))
channel = connection.channel()

channel.exchange_declare(exchange='miniolidice',
                         exchange_type='fanout')

result = channel.queue_declare(exclusive=False)
queue_name = result.method.queue

channel.queue_bind(exchange='miniolidice',
                   queue=queue_name)

print(' [*] Waiting for logs. To exit press CTRL+C')

def callback(ch, method, properties, body):
    print(" [x] %r" % body)

channel.basic_consume(callback,
                      queue=queue_name,
                      no_ack=False)
```
```python
Traceback (most recent call last):
  File "pika.py", line 1, in <module>
    import pika
  File "/home/drm/app/pika.py", line 3, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='10.0.0.46'))
AttributeError: module 'pika' has no attribute 'BlockingConnection'
```

**Comment by lukebakken** [comment]
Either you have not installed the Pika library, or you should name your file something other than `pika.py`. Thanks for using Pika!

**Comment by cheikhatdiop00** [comment]
j ai aussi le meme probleme il semble que l erreur est lier a pika de python .
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    connection = pika.BlockingConnection(parameters)
  File "/home/odoo/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/odoo/.local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
