### ISSUE TITLE
backslash in message

### ISSUE THREAD

**Issue by ifedorov** [pika/pika#1253]
python 3.5
pika==1.1.0
message in rmq 
`"a[href=\"http://google.com\"]"`

into on_message_callback  it come back without backslash
```

print(repr(msg))
"a[href="http://google.com"]"
```

**Comment by lukebakken** [comment]
Pika treats message bodies as bytes. I suspect that you don't understand how backslashes are interpreted by `repr` or `print`.

If you think this is a real bug in Pika, provide code to reproduce it.
