### ISSUE TITLE
The `blocked_connection_timeout` is not always applied

### ISSUE THREAD

**Issue by arseni-mourzenko** [pika/pika#1257]
It seems there is a regression in pika 1.* (the test was done using pika 1.1.0).

Previously (in versions 0.*), when `blocked_connection_timeout` was specified in the connection parameters, a call to `pika.BlockingConnection` was indeed timing out after the number of specified seconds. This is not the case any longer.

In order to reproduce the issue:

1. Deploy a AMQP server such as RabbitMQ on a virtual machine.
1. Connect to the server by running the Python script below. It should connect and output to the console that it took a few tens of milliseconds to connect.
1. Pause the virtual machine (don't shut it down or delete it; just pause).
1. Run the script again.

The script would show that it took ten seconds (plus a few milliseconds) to abort the connection:

> Connection timed out after 10019 ms.

This is unexpected: the value of `blocked_connection_timeout` being 1 (see the script below), it should timeout when one second is elapsed, and not waiting for `socket_timeout`/`stack_timeout`.

If you run the script a few more times (while still keeping the virtual machine paused), you may notice that the timeout would drop to a duration varying from 600 ms. to three seconds, and once it drops, it doesn't seem to reach ten seconds any longer. In order to get it up to ten seconds, resume the virtual machine, run the script so it connects successfully, then pause the virtual machine.

If logs are enabled, this is what is shown (timestamp is important):

> 01:31:46 INFO:Pika version 1.1.0 connecting to ('10.0.0.5', 5671)  
> 01:31:56 ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: timeout("TCP connection attempt timed out: [...]  
> pika.exceptions.AMQPConnectionError  
> Connection timed out after 10020 ms.

It seems like, indeed, the timeout is at TCP connection level, and `blocked_connection_timeout` was plainly ignored. When the script is ran again, the logs look like this:

> 01:33:45 INFO:Pika version 1.1.0 connecting to ('10.0.0.5', 5671)  
> 01:33:47 ERROR:Socket failed to connect: <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.0.0.2', 56096)>; error=113 (No route to host)
01:33:47 ERROR:TCP Connection attempt failed: OSError(113, 'No route to host');  
> pika.exceptions.AMQPConnectionError  
> Connection timed out after 2024 ms.

Would it be possible to honor the value specified in `blocked_connection_timeout`?

## Test script

```python
import logging
import pika
import time

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s:%(message)s",
    datefmt="%H:%M:%S"
)

parameters = pika.ConnectionParameters(
    host="...", # Replace it with the name of the virtual machine.
    port=5671,
    heartbeat=1,
    socket_timeout=10,
    stack_timeout=10,
    blocked_connection_timeout=1,
    connection_attempts=1,
    retry_delay=0
)

start = time.time() * 1000

try:
    connection = pika.BlockingConnection(parameters)
    duration = int(time.time() * 1000 - start)
    print("Connected in {} ms.".format(duration))
except:
    duration = int(time.time() * 1000 - start)
    print("Connection timed out after {} ms.".format(duration))
```

**Comment by lukebakken** [comment]
This is a **_perfect_** issue report, thank you! I'll get to work on it this week.

**Comment by lukebakken** [comment]
Here is how I tested what you report.

* Used [this code](https://gist.github.com/lukebakken/eff5f4497f8f176edd2a3909bf7aa141).
* Using Pika 0.13.1, I ran RabbitMQ, and then ran `kill -STOP $PID` on the `beam.smp` process pid.
* Ran `python ./repro_0.13.1.py`. The connection is established, but the AMQP handshake _never times out_.
* Using the `master` branch of Pika (which is 1.1.0, basically), the connection is established _and_ the AMQP handshake does time out, eventually.

Reading the code, I don't believe `blocked_connection_timeout` is intended for what you believe it to be - [docs](https://github.com/pika/pika/blob/305c4f14bff6fe2478b73859cac321ac8ae8914a/pika/adapters/blocking_connection.py#L290-L310). It appears that this timeout is only intended in response to `Connection.Blocked` from the server. @vitaly-krugl may be able to shed more light on this.

The event of a paused virtual machine (or paused process) is rare and I see that Pika does time out eventually in that case, so I don't think there's anything to fix here. Thanks.

**Comment by vitaly-krugl** [comment]
Luke's interpretation is correct.

**Comment by lukebakken** [comment]
Thanks @vitaly-krugl I appreciate the double-check

**Comment by Dhruva0707** [comment]
if you create a queue for the channel and use: 
for message in channel.consume():

in this case Arseni gave, an exception should be returned right? That is not so in my case
