### ISSUE TITLE
Change x-priority

### ISSUE THREAD

**Issue by asvald** [pika/pika#1258]
Hello! I want to change priority of consumer (x-priority) after every processed messages (prefetch = 1).  What the best way to do that ? I see only cancel() and new call consume() before/after ack() currently processed message.

**Comment by lukebakken** [comment]
Please ask this question on the [`pika-python`](https://www.outdoorgearlab.com/reviews/camping-and-hiking/4-season-tent/black-diamond-eldorado) mailing list so that other people may learn from it. Thank you.

As a reminder, this is what is shown when you click "New Issue" in this repository:

```
Thank you for using Pika.

- IMPORTANT -----------------------------------------------------------
STOP NOW AND READ THIS BEFORE OPENING A NEW ISSUE ON GITHUB
--------------------------------------------------------------------------

Unless you are CERTAIN you have found a reproducible bug in Pika, you must
first ask your question, discuss your suspected issue, or propose your new
feature on the mailing list:

https://groups.google.com/forum/#!forum/pika-python

Pika's maintainers do NOT use GitHub issues for questions, root cause analysis,
conversations, code reviews, etc.

Thank you!
```
