### ISSUE TITLE
encoding of int data type depends on its value

### ISSUE THREAD

**Issue by howff** [pika/pika#1261]
The encoding of integers into either 32-bit or 64-bit seems to depend on the current value of the int. This makes it inconsistent for subsequent readers which might be expecting a fixed size (32 or 64 bits). Can data.py allow a specification of data type when encoding?
I note there are other issues still open about inconsistencies with data types #599 #601

**Comment by lukebakken** [comment]
Thanks for using Pika. This library is maintained by volunteers during their spare time so we can't make any promises about prioritizing this issue. We would be happy to review a pull request addressing these issues.

**Comment by seenureddy** [comment]
@lukebakken Are you working on this issue?

**Comment by lukebakken** [comment]
No I have been busy with the .NET client for several weeks now.

**Comment by lukebakken** [comment]
> The encoding of integers into either 32-bit or 64-bit seems to depend on the current value of the int. This makes it inconsistent for subsequent readers which might be expecting a fixed size (32 or 64 bits).

The protocol does have a data type specifier that prefixes the value. Please see the fix in #1345
