### ISSUE TITLE
Connection Creation sometimes hang forever without any exception.

### ISSUE THREAD

**Issue by avolution** [pika/pika#1269]
Sometimes it work, sometimes not.
On fail there is no output or so .. the process hangs forever

My ConnectionParameters are:

`
connection = pika.BlockingConnection(
    pika.ConnectionParameters(host='localhost',
                              credentials=credentials,

                              connection_attempts=10,
                              retry_delay=1,

                              heartbeat=60,

                              blocked_connection_timeout=5,
                              socket_timeout=5,
                              stack_timeout=5,

                              )
)
`

My Connection-Quality is kind of bad, because I am using a port forward to the rabbitmq Server. Pika should be able to handle that.

----

using pika version 1.1.0

**Comment by Nabu-thinker-ru** [comment]
I suspect i have the same problem. Is there any workarounds?

**Comment by avolution** [comment]
@Nabu-thinker-ru 
Don't use the BlockingConnection Client 
Use 

https://pika.readthedocs.io/en/stable/examples/asynchronous_consumer_example.html 
https://pika.readthedocs.io/en/stable/examples/asynchronous_publisher_example.html

The Async Client is working well

**Comment by lukebakken** [comment]
@avolution thank you for following up.
