### ISSUE TITLE
Re-queue at the tail of the queue

### ISSUE THREAD

**Issue by khaitqhust** [pika/pika#1272]
Hi there, 

According to the RabbitMQ document:

> Messages can be returned to the queue using AMQP methods that feature a requeue parameter (basic.recover, basic.reject and basic.nack), or due to > a channel closing while holding unacknowledged messages. Any of these scenarios caused messages to be requeued at the back of the queue for RabbitMQ releases earlier than 2.7.0. From RabbitMQ release 2.7.0, messages are always held in the queue in publication order, even in the presence of requeueing or channel closure.

> When a message is requeued, it will be placed to its original position in its queue, if possible. If not (due to concurrent deliveries and acknowledgements from other consumers when multiple consumers share a queue), the message will be requeued to a position closer to queue head.

But, I want to re-queue message at the tail of the queue. How i can do this?
I am using RabbitMQ 3.8, pika 0.12.0

Thank you!

**Comment by lukebakken** [comment]
Hello and thanks for using Pika.

Please do not use GitHub for questions. The reason is that other people will probably not learn from the answers you receive. This project does not use GitHub for discussions.

Since you are asking a RabbitMQ-specific question, ask on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by lukebakken** [comment]
When you opened [this issue](https://github.com/pika/pika/issues/1271), you saw the following text explaining that you should first ask on the mailing list. When a project provides instructions, please follow them -

```
Thank you for using Pika.

- IMPORTANT -----------------------------------------------------------
STOP NOW AND READ THIS BEFORE OPENING A NEW ISSUE ON GITHUB
--------------------------------------------------------------------------

Unless you are CERTAIN you have found a reproducible bug in Pika, you must
first ask your question, discuss your suspected issue, or propose your new
feature on the mailing list:

https://groups.google.com/forum/#!forum/pika-python

Pika's maintainers do NOT use GitHub issues for questions, root cause analysis,
conversations, code reviews, etc.

Thank you!
```
