### ISSUE TITLE
Pika stripping comments inside strings

### ISSUE THREAD

**Issue by chowey** [pika/pika#1279]
This shows up in [es-module-shim](https://cdn.pika.dev/-/es-module-shims@v0.4.7-iVxJEhO4aDmWgEVhkYjN/dist=es2019/es-module-shims.js), line 2343:

```js
    const sourceMappingIndex = resolvedSource.lastIndexOf('
```

Compare to the [source file](https://github.com/guybedford/es-module-shims/blob/0.4.7/src/es-module-shims.js#L120):

```js
    const sourceMappingIndex = resolvedSource.lastIndexOf('//# sourceMappingURL=');
```

Everything after the "comment" is stripped from the pika build, even though the "comment" is inside a string.

**Comment by lukebakken** [comment]
I believe you want one of these repositories - https://github.com/pikapkg

**Comment by chowey** [comment]
My bad.
