### ISSUE TITLE
How to pass custom parameters to consumer callback?

### ISSUE THREAD

**Issue by rajeevbaalwan** [pika/pika#1283]
I have found this doc for basic_consume

>queue (str) – The queue to consume from. Use the empty string to specify the most recent server-named queue for this channel
on_message_callback (callable) –The function to call when consuming with the signature on_message_callback(channel, method, properties, body), where channel: pika.Channel method: pika.spec.Basic.Deliver properties: pika.spec.BasicProperties body: bytes
auto_ack (bool) – if set to True, automatic acknowledgement mode will be used (see http://www.rabbitmq.com/confirms.html). This corresponds with the ‘no_ack’ parameter in the basic.consume AMQP 0.9.1 method
exclusive (bool) – Don’t allow other consumers on the queue
consumer_tag (str) – Specify your own consumer tag
arguments (dict) – Custom key/value pair arguments for the consumer
callback (callable) – callback(pika.frame.Method) for method Basic.ConsumeOk.

But how can i pass this parameter:
>arguments (dict) – Custom key/value pair arguments for the consumer

and read the same in consumer callback ?

**Comment by lukebakken** [comment]
Please use the google group to ask questions in the future:

https://groups.google.com/g/pika-python

Use the `functools` library to add arguments in this manner:

https://github.com/pika/pika/blob/master/examples/basic_consumer_threaded.py#L70-L71
