### ISSUE TITLE
Use of catch_warnings/filterwarnings can cause exceptions to be raised in other threads

### ISSUE THREAD

**Issue by asinha94** [pika/pika#1285]
While encoding an integer, all warning are filtered so that they will raise exceptions if they occur. [The context-manager is not thread-safe](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings) and any warning raised in any other thread at the same time will be raised as an exception. My team has run into this a few times while pika is under heavy load. Offending code here https://github.com/pika/pika/blob/a3ae3e5aae3fd546e9ae73bff0175f5d61a9d39a/pika/data.py#L135-L146

Reading the #888 where it was introduced, it seems to be done to maintain backwards compatibility with Python 2.6, which uses the deprecated `__int__()` method. I'm not 100% sure on where the `DeprecationWarning` is even raised since `value` is an `int` (is it when `b'I'` is packed since it's a non-integer? If thats the case can't the `b'l'` also throw?)

Since Python 2.6 isn't supported anymore I think that can be removed and the code reverted back to 
https://github.com/pika/pika/blob/fca3c48c74c546915f829f1a211a30413e44bfbc/pika/data.py#L121-L127

**Comment by asinha94** [comment]
If there are no other consequences for removing the `DeprecationWarning` I can submit a PR for this, or it could be combined with #1265

**Comment by lukebakken** [comment]
Please submit a PR for this issue (with tests, if appropriate). If you have time to address #1265 in another PR that would be great.

**Comment by lukebakken** [comment]
Fixed by #1290
