### ISSUE TITLE
asynchronous_publisher_example.py do take in account confirms with multiple parameter

### ISSUE THREAD

**Issue by pat1** [pika/pika#1289]
I publish to a rabbitmq broker setting a callback for confirm delivery:
channel.confirm_delivery(ack_nack_callback=self.on_delivery_confirmation)

Rabbitmq broker use the multiple parameter when confirm publish:
https://www.rabbitmq.com/confirms.html#consumer-acks-multiple-parameter

How I can check this field in on_delivery_confirmation callback ?
Seem to me the  asynchronous_publisher_example.py is broken about this 
https://github.com/pika/pika/blob/a3ae3e5aae3fd546e9ae73bff0175f5d61a9d39a/examples/asynchronous_publisher_example.py#L243
The example do not check the multiple field and the list of _deliveries messages is wrong.

**Comment by lukebakken** [comment]
We would welcome improvements to the example code. Please see the following:

https://groups.google.com/forum/#!msg/rabbitmq-users/-bmUoo0-gMk/tfB7RrlmBQAJ

**Comment by pat1** [comment]
I use this implementation:
https://github.com/r-map/rmap/blob/b422d6b643d4bd972d0d8260b536701b8a5374be/python/rmap/rmap_core.py#L1801

as example I can suggest this class:
https://github.com/r-map/rmap/blob/b422d6b643d4bd972d0d8260b536701b8a5374be/python/rmap/rmap_core.py#L1628
can run in thread with ack
method run to start ; stop to stop (terminate if in thread)
message can be read from queue and execute "pipefunction" for consume and async ack also by queue ...
 This work for me like the Shovel Plugin in RabbitMQ with optional messages elaboration in the middle.
