### ISSUE TITLE
channel, basic_publish never return (twisted_connection)

### ISSUE THREAD

**Issue by sekogan** [pika/pika#1298]
We use a single RabbitMQ server with clients connecting to it from about 250 machines. The network is fairly stable but once in a while some connectivity issues do happen. Most of the clients reconnect to the broker but some of them (like 1-2) occasionally hang forever.

Made a minimal script that reproduces one of the causes of the issue (please find it down below). The script emulates broken connection by calling `connection.transport.abortConnection()` but it is also possible to reproduce the issue by inserting firewall rules denying packets to/from the broker.

The script contains three cases in which methods `basic_consume`, `channel` and `basic_publish` are called respectively. The problem is that the `channel` and `basic_publish` methods never return control if the connection is broken while they are running. `basic_consume` is taken as an example of a different behavior: it raises a `ConnectionAborted` exception if the connection is lost. This inconsistency seems weird.

To be fair, in all three cases the `TwistedProtocolConnection.closed` deferred is fired. Previously, we didn't notice the issue because we used a strategy of terminating the client process if the connection is lost. Now we are trying to reconnect to the broker and started to see the issue.

We are using pika 1.1.0 and twisted 19.10.0.

Debug-level logs:
[case_1.log](https://github.com/pika/pika/files/5849152/case_1.log)
[case_2.log](https://github.com/pika/pika/files/5849153/case_2.log)
[case_3.log](https://github.com/pika/pika/files/5849154/case_3.log)

```py
from twisted.internet import defer, protocol, task
import twisted.internet.error
import pika
import pika.adapters.twisted_connection
from settings import *  # imports RABBITMQ_*, QUEUE_NAME


@defer.inlineCallbacks
def main(reactor):
    client_creator = protocol.ClientCreator(
        reactor,
        pika.adapters.twisted_connection.TwistedProtocolConnection,
        pika.ConnectionParameters(
            virtual_host=RABBITMQ_VIRTUAL_HOST,
            credentials=pika.PlainCredentials(*RABBITMQ_CREDS),
        ),
    )

    connection = yield client_creator.connectTCP(RABBITMQ_HOST, RABBITMQ_PORT)
    yield connection.ready

    case = 1
    if case == 1:  # OK case
        channel = yield connection.channel()
        yield channel.queue_declare(queue=QUEUE_NAME)
        deferred = channel.basic_consume(queue=QUEUE_NAME)
    elif case == 2:  # Troublesome case
        deferred = connection.channel()
    elif case == 3:  # Troublesome case
        channel = yield connection.channel()
        yield channel.confirm_delivery()
        yield channel.queue_declare(queue=QUEUE_NAME)
        deferred = channel.basic_publish(
            exchange="", routing_key=QUEUE_NAME, body="hello"
        )

    connection.transport.abortConnection()  # Emulate lost connection

    try:
        yield deferred  # <- waits forever here in cases 2 and 3,
        # raises twisted.internet.error.ConnectionAborted in case 1, as expected
        assert False
    except twisted.internet.error.ConnectionAborted:
        pass


if __name__ == "__main__":
    task.react(main)
```

**Comment by michaelklishin** [comment]
@sekogan thank you for your contributions. Would you like to address the first case as well?

**Comment by sekogan** [comment]
@michaelklishin The first case was an example of "good" behavior, so there is no need to fix it.
As far as I'm concerned, the issue can be closed.

**Comment by michaelklishin** [comment]
OK, great. Thanks again for contributing :)
