### ISSUE TITLE
Changelog not updated for 1.2.0 release on ReadTheDocs

### ISSUE THREAD

**Issue by timabbott** [pika/pika#1307]
Hi!  I was upgrading to the latest 1.2.0 release on pypi and wanted to read the changelog, but I notice it's not updated on ReadTheDocs yet:

https://pika.readthedocs.io/en/stable/version_history.html

I notice that https://github.com/pika/pika/blob/master/docs/version_history.rst has been updated; maybe the ReadTheDocs build failed or something?

**Comment by michaelklishin** [comment]
@lukebakken @gmr how can I update ReadTheDocs?

**Comment by gmr** [comment]
I'll login today and see how to get people access. The build is breaking when it runs.

**Comment by gmr** [comment]
I'll need other ReadTheDocs usernames to add as maintainers. Currently @lukebakken and I are the only maintainers.

The build was failing due to being set for Python 2 and missing Pathlib. I've updated the project to build with Python 3.

**Comment by gmr** [comment]
Confirmed the builds are fixed and manually triggered 1.2.0, stable, and latest. Any future builds should automatically be triggered and updated, barring any issues with the build itself.

**Comment by lukebakken** [comment]
Thanks a lot @gmr!
