### ISSUE TITLE
pika.exceptions.StreamLostError

### ISSUE THREAD

**Issue by futur3gho5t** [pika/pika#1309]
Hello ,could somebody tell me please how to resolve this problem: pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')

I use my consumer thread class:

class CrawlThread(threading.Thread):

    def __init__(self, lang, data_queue):
        threading.Thread.__init__(self)
        self.lang = lang
        self.data_queue = data_queue
        parameters = pika.ConnectionParameters(host='localhost')
        rabbit_conn = pika.BlockingConnection(parameters)
        self.channel = rabbit_conn.channel()
        self.channel.queue_declare(queue=SENDING_QUEUE, durable=True)
        self.channel.basic_qos(prefetch_count=1)
        self.channel.basic_consume(SENDING_QUEUE, on_message_callback=self.callback)
        threading.Thread(target=self.channel.basic_consume('task_queue', on_message_callback=self.callback))

    def callback(self, ch, method, properties, body):
        url = body.decode()
        print(f'{thread_name(self.getName())} Received ::{url}')
        ch.basic_ack(delivery_tag=method.delivery_tag)
        result_data = crawl_util.start_crawl(url=url, lang=self.lang)
        self.data_queue.put(result_data)

    def run(self):
        while True:
            self.channel.start_consuming()

in callback function i make some logic that take a few time.how to save the connection?
Thanks

**Comment by michaelklishin** [comment]
All this tells us is that RabbitMQ or an intermediary (proxy, load balancer) has closed the connection. There is a broad range of possible reasons.
