### ISSUE TITLE
pika.exceptions.AMQPConnectionError 

### ISSUE THREAD

**Issue by sogand145** [pika/pika#1318]
when I want to connect to rabbitmq by Pika in django project, I get this error:
```python
File "/code/auth-service/utils/consumers.py", line 15, in <module>
     connection = pika.BlockingConnection(parameters)
   File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
     raise self._reap_last_connection_workflow_error(error)
 pika.exceptions.AMQPConnectionError
```

my code is:
```python
connection = pika.BlockingConnection(pika.ConnectionParameters(host='rabbitmq'))
```

all my projects run by docker-compose.yml file
I appreciate for any help to solving this problem

**Comment by ThallyssonKlein** [comment]
Your application is starting up before rabbitmq is available. I'm also experiencing the same problem. There is an alternative to wait for a specific host and port to run the application but I couldn't apply that to rabbit.

**Comment by mojtabajahannia** [comment]
maybe need to start rabbitmq.
in linux:
`sudo systemctl start rabbitmq-server`
`sudo systemctl enable rabbitmq-server`

**Comment by pra-dan** [comment]
On MAC, providing `localhost` leads to this error; instead explicitly providing `127.0.0.1` works as
```python3
connection = pika.BlockingConnection(pika.ConnectionParameters('127.0.0.1'))
```

**Comment by lukebakken** [comment]
Sorry, I was unsubscribed from this repository and have missed new issues from the past year. If this issue still requires attention, please add a comment. Thank you.

**Comment by PrantaChakraborty** [comment]
hey @lukebakken Today I faced the same issue.

**Comment by jesmaelnezhad** [comment]
I had this problem, and in my case, the problem was that there is a time gap between RabbitMQ start and when it's ready to accept connections. So my problem was simply solved by waiting 30 seconds before trying to connect (I was connecting from a container that would start right after RabbitMQ's container).

**Comment by AhmadrezaNia** [comment]
Hi @lukebakken. I have a rabbit MQ server on a Windows PC, working on Docker. I mange to publish and subscribe messages from another PC to that server. However, I use the exact code on my raspberry pi for publishing and subscribing and get the same error: 
Traceback (most recent call last):
  File "/home/ahmadreza1/Desktop/FL_New/Client_1.py", line 169, in <module>
    connection = pika.BlockingConnection(parameters)
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/blocking_connection.py", line 360, in init
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python3.9/dist-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError


here is my code for connecting to Rabbit MQ server :
credentials = pika.PlainCredentials('user', 'pass')

parameters = pika.ConnectionParameters(host ='server IP',
                                                  port = 5672, virtual_host = 'Test', 
                                                  credentials=credentials)

connection = pika.BlockingConnection(parameters)

channel = connection.channel()

**Comment by muhammad-faizan-122** [comment]
I was facing same issue, by following [RabbitMQ installation guideline](https://www.rabbitmq.com/docs/install-homebrew) resolved that issue.

**Comment by Ghxst** [comment]
If you arrive here from google (like I initially did), make sure you check inbound rules on your firewall of the box RabbitMQ is running on and double check there's a rule for the ports you want to connect over 😅 .
