### ISSUE TITLE
How to consume many subject using multiprocess

### ISSUE THREAD

**Issue by roycefan** [pika/pika#1319]
I want to consume three subject using multiprocess, 

main.py  
    
       #first
        consumer_thread1= threading.Thread(target=orderConsumer.run_dispatch1())
        consumer_thread1.start()    //   it will block here .
       
       #second
        consumer_thread2 = threading.Thread(target=orderConsumer.run_dispatch2())
        consumer_thread2.start()

run_dispatch2
              connection = pika.SelectConnection(parameters=self.parameters,
                                           on_open_callback=self.on_open)
               connection.ioloop.start()

run_dispatch2....

**Comment by lukebakken** [comment]
Sorry, I was unsubscribed from this repository and have missed new issues from the past year. I will investigate this before the next release, thank you!

**Comment by lukebakken** [comment]
Since this issue is stale, I will assume you have found a solution. If not, please leave a comment.
