### ISSUE TITLE
reconnecting might better start the loop. proposed minimal fix.

### ISSUE THREAD

**Issue by alexbodn** [pika/pika#1321]
hello friends,

studying this example, i came to the conclusion there might be an error.
in case of an unintended connection drop, a loop restart seems more fit to be issued, and not a stop thereof.

https://github.com/pika/pika/blob/444ea0482eb604e16a6beaeb960cc5755096d286/examples/asynchronous_publisher_example.py#L105

**Comment by lukebakken** [comment]
Sorry, I was unsubscribed from this repository and have missed new issues from the past year. I will investigate this before the next release, thank you!

**Comment by lukebakken** [comment]
Part of #1363

**Comment by lukebakken** [comment]
[This code](https://github.com/pika/pika/blob/main/examples/asynchronous_publisher_example.py#L315-L330) will re-start the connection because `self._stopping` is still `False`.
