### ISSUE TITLE
Big heartbeat don't work

### ISSUE THREAD

**Issue by hontiky** [pika/pika#1326]
Could someone help me? 

I need to write the app which could save the connection between broker and consumer even for 2 hours. I need this because we have the API, which is use after message is read and it's response time could take more then hour. 

I read about `heartbeat`, set it to 7200 seconds but for some reason it don't help. If processing of the message took < 2000 everything was ok.

I read info in #1097 that broker still could broke connection even with big heartbeat. 

Could somebody help? Which parameters should I use to disable heartbeats at all or set it to 7200 seconds? Do I need to configure broker somehow?

UPD: I using docker with rabbitmq broker, could be this a problem?

**Comment by olii** [comment]
AMQP heartbeat is an application-level heartbeat to ensure that there is an open TCP connection between your application and a broker. You can set any reasonable interval but you have to make sure that you poll the connection from time to time so the broker doesn't close it.

You should be good with any value of heartbeat if you manage to call https://pika.readthedocs.io/en/stable/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingConnection.process_data_events from time to time (with an interval no longer than `heartbeat /2`. I assume you use a blocking connection.

With recent RabbitMQ, there is a timeout for an unacked message to be acked (defaults to 30 minutes): https://www.rabbitmq.com/consumers.html#acknowledgement-timeout

Given your use-case of processing time over 2 hours you either:
1) change the default unacked timeout at the broker side, or
2) ack the message and start processing it after.

**Comment by lukebakken** [comment]
> ack the message and start processing it after.

This is a good solution. You can place the message on an "in progress" queue while you perform work. You should not adjust the heartbeat parameters.
