### ISSUE TITLE
error(104, 'Connection reset by peer') immediately(on the same second) after the blocking call 

### ISSUE THREAD

**Issue by i-sach** [pika/pika#1330]
Hello,
Need help. I am seeing the "ConnectionClosed" exceptions as below atleast twice a day.
I am using pika 0.13.1

  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2120, in basic_publish
    mandatory, immediate)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2207, in publish
    self._flush_output()
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
ConnectionClosed: (-1, "error(104, 'Connection reset by peer')")

The data i am trying send is under 1000 string length characters and on the same second i get the exception when the "BlockingCall" takes place. The connection parameters are just localhost as the servername. The subscriber is also on the same machine but a different process and At the same time in rabbitmqLog no entry is seen or no missed heartbeats.

Please suggest

Thanks in Advance

**Comment by dabbler0606** [comment]
It may be that the connection has been idle for too long and was disconnected. When the client sends the message again, it will report an error

Connection reset by peer

you can catch ConnectionClosed exception and retry

**Comment by lukebakken** [comment]
Sorry, I was unsubscribed from this repository and have missed new issues from the past few months. I am assuming this issue is resolved. If not, let me know.

**Comment by kashishnaqvi10** [comment]
I am also getting this error, I have tried several fixes such has using heartbeat and blockingConnection timeout but nothing helped

**Comment by lukebakken** [comment]
@kashishnaqvi10 if you'd like assistance, please do the following:
* Start a new discussion here - https://github.com/pika/pika/discussions
* Include a link to a git repository with the following in it:
  * **COMPLETE** code that I can run that shows what you have tried
  * Log files from RabbitMQ during your tests
