### ISSUE TITLE
Update license in Trove Classifier

### ISSUE THREAD

**Issue by svramusi** [pika/pika#1340]
Currently, the trove classifier states the license is `BSD License` but the main page in GitHub says the license is `BSD-3-Clause License`. Could you please use the correct license identifier according to https://spdx.org/licenses/BSD-3-Clause.html in the trove classifier (assuming thats the correct license)? I would like to use pylic to validate that we're using 3-Clause where appropriate.

**Comment by lukebakken** [comment]
@svramusi please review #1362. Thanks! Sorry it took so long, I mistakenly turned off notifications for this repository.

**Comment by lukebakken** [comment]
Reverted by https://github.com/pika/pika/commit/4f789b90fa1b3a269b8e33d0ac42249472ffca51

Guess what, #1362 broke publishing to PyPi.

I have to use one of the license specifiers listed here:

https://pypi.org/classifiers/

@svramusi I suggest you follow up with the PyPi people, or comment here:

https://github.com/pypa/trove-classifiers/issues/17
