### ISSUE TITLE
Remove dependency on "mock", the backport of Python3.4's unittest.mock to earlier Python versions

### ISSUE THREAD

**Issue by libnoon** [pika/pika#1357]
The "mock" package is a backport of Python 3.4's unittest.mock. Now
that we only support Python 3.4+, this dependency can be removed.

In order to package pika properly on modern Fedora-based distributions (incl. CentOS, RHEL),
we have to get rid of the "mock" dependency.
See https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by libnoon** [comment]
I propose this pull request:
https://github.com/pika/pika/pull/1356

**Comment by lukebakken** [comment]
Fixed by #1356
