### ISSUE TITLE
How to reconnect connection?

### ISSUE THREAD

**Issue by piaoyuankui** [pika/pika#136]
I am struggle with reconnection mechanization of pika on a application that need long connection between rabbitmq.
currently, once rabbitmq  shutdown for some reason, pika client have no way to recognize it, and close itself silently.

When try to figure out how connection handle the socket IO, I find out connection may close when reading no data.

```
def _handle_read(self):
    # reading data
    ...

    # We received no data, so disconnect
    if not data:
        log.debug('Calling disconnect')
        return self._adapter_disconnect()
```

What I suggest to do is, not disconnect the connection but notify the connection about server is not available.

```
def _handle_read(self):
    # reading data
    ...

    # We received no data, so disconnect
    if not data:
        pika.log.debug('Reading no data.')
        self.event_state &= ~READ
        self.ioloop.update_handler(self.socket.fileno(), self.event_state)

        self._on_connection_closed(None, True)
        return
```

Please help me to figure out this, Do I miss-understanding some of the source code?

**Comment by ecerulm** [comment]
pika.exceptions.AMQPConnectionError for those that land here from google while searching for "pika reconnect"

**Comment by vitaly-krugl** [comment]
If you need to reconnect, I believe that the most robust way is to create a new adapter instance (BlockingConnection, SelectConnection, etc.) versus calling the old adapter instance's `connect()` method. Using `connect()` for reconnecting relies on internal member variables being properly re-initialized, which relies on some duplicate initialization logic that can easily get out of sync with that in the constructor.

My preference would be to get rid of the public `connect()` method altogether from all of the adapters, which would eliminate extra code paths to test and maintain.
