### ISSUE TITLE
Improve release process a bit

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#1375]
Some good protips here:

https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/

Automatic versioning would be nice.

**Comment by seenureddy** [comment]
@lukebakken Add me to this issue.

**Comment by lukebakken** [comment]
Fixed by https://github.com/pika/pika/commit/fb002a08ce48476466e5b2e4b0a82094307acbc8
