### ISSUE TITLE
Update fallback SSL/TLS protocol version

### ISSUE THREAD

**Issue by Zerpet** [pika/pika#1385]
In the connection module, the method `URLParameters._set_url_ssl_options()` tries to set the secure protocol version to `ssl.PROTOCOL_TLS` and falls back to `ssl.PROTOCOL_TLSv1` if the first is not available (since it was introduced in 3.6 and this client supports 3.4+).

https://github.com/pika/pika/blob/c34c411874f049f2048aa5133ea20f87c95fa223/pika/connection.py#L905-L912

This has the following issues:
- The usage of `ssl.PROTOCOL_TLS` is [deprecated in 3.10](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS) in favour of ` ssl.PROTOCOL_TLS_CLIENT`
- The fallback sets an unsecure protocol

I propose the following changes:
1. Try to set [ssl.PROTOCOL_TLS_CLIENT](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT)
2. Fall back to [ssl.PROTOCOL_TLSv1_2](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLSv1_2)

Those changes would address the usage of deprecated `ssl.PROTOCOL_TLS`, and would fall back to a secure protocol by default. The constant `ssl.PROTOCOL_TLSv1_2` was introduced in Python 3.4, therefore it is safe to assume this constant will be there for supported Python versions.

**Comment by lukebakken** [comment]
Good find!

**Comment by Zerpet** [comment]
CodeQL found it for me :smile: https://github.com/pika/pika/security/code-scanning/2
