### ISSUE TITLE
Open to funding?

### ISSUE THREAD

**Issue by lorenzwalthert** [pika/pika#1391]
At work, we extensively use pika and benefit from it. Great job. We'd like to support the ongoing development financially, but could not figure out a way to do so. Would you consider giving your user this option, e.g. through GitHub Sponsors or Tidelift?

**Comment by lukebakken** [comment]
Hi Lorenz,

That is a very generous offer. Pika was originally written by Gavin Roy (@gmr). Over the years significant contributions have come from users like @vitaly-krugl. Currently the RabbitMQ team at VMware maintains this library. We're fortunate to be able to work on open-source software and get paid for it.

I'm going to ask for the official word on this, but if you use RabbitMQ purchasing official support from VMware is probably the best way to ensure we're able to keep working on Pika (https://www.rabbitmq.com/#support)

**Comment by lukebakken** [comment]
Yep, paying for RabbitMQ support is the best way to fund Pika. Thanks!
