### ISSUE TITLE
isssue with steam and updates

### ISSUE THREAD

**Issue by jcole3737** [pika/pika#1420]
Not sure if anyone else has this issue but after installing the most recent updates my steam refused to open i clicked on the steam icon and it flashed the box that said it was checking for steam updates then the box goes away and steam does not open no matter how long I wait. I tried rebooting my pc twice and no resolution then I rebooted a third time but this time I rebooted into a older version of Pika the generic one below the updated version and that resolves the issue I really like this distro and hope to keep it if this is a bug with one of the most recent updates hopefully it is fixed other than that no issues thus far thanks for the Awesome OS. 

Thank you for using Pika.

- IMPORTANT -----------------------------------------------------------
STOP NOW AND READ THIS BEFORE OPENING A NEW ISSUE ON GITHUB
--------------------------------------------------------------------------

Unless you are CERTAIN you have found a reproducible bug in Pika, you must
first ask your question, discuss your suspected issue, or propose your new
feature on the mailing list:

https://groups.google.com/forum/#!forum/pika-python

Pika's maintainers do NOT use GitHub issues for questions, root cause analysis,
conversations, code reviews, etc.

Thank you!

**Comment by Zerpet** [comment]
Not sure what steam has to do with an AMQP client. You probably came to the wrong repository.
