### ISSUE TITLE
ERR NOAUTH Authentication required.

### ISSUE THREAD

**Issue by Gxiaodiao** [pika/pika#1446]
Using the golang dependency "github.com/go-redis/redis/v9" prompts ERR NOAUTH Authentication required, but redis does not use this problem, as follows:

`
package main

import (
	"context"
	"github.com/go-redis/redis/v9"
	"time"
)

func main() {

	rdb := redis.NewClient(&redis.Options{
		Addr:     "192.168.254.12:9221",
		Password: "pika99", // no password set
		DB:       0,        // use default DB
	})

	//rdb := redis.NewClient(&redis.Options{
	//	Addr:     "10.1.250.157:6379",
	//	Password: "google00", // no password set
	//	DB:       0,          // use default DB
	//})
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_, err := rdb.Ping(ctx).Result()
	if err != nil {
		println(err.Error())
	}
}

`
Help to check, thank you

**Comment by lukebakken** [comment]
You are using the wrong GitHub repository. Please start a discussion here:

https://github.com/redis/go-redis/discussions
