### ISSUE TITLE
Add Python `3.12` to GitHub Actions

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#1470]
Depends on #1469 because `nose2` still uses the `imp` module.

**Comment by henning-schild** [comment]
python 3.12 missing in the official support matrix is currently blocking a few package bumps in gentoo linux https://bugs.gentoo.org/929480

I tried to send a mail to the list, but the list is not open to the public.

**Comment by lukebakken** [comment]
> I tried to send a mail to the list, but the list is not open to the public.

Yes, this list is open to the public, you must join it first:
https://groups.google.com/g/pika-python

If someone wants to speed up testing with Python 3.12, they can convert the tests to `pytest`. I will get around to it when I have time, but for right now I'm busy working on RabbitMQ issues / support for people who pay for support contracts.

**Comment by lukebakken** [comment]
https://github.com/pika/pika/pull/1474

**Comment by henning-schild** [comment]
> > I tried to send a mail to the list, but the list is not open to the public.
> 
> Yes, this list is open to the public, you must join it first: https://groups.google.com/g/pika-python

Not sure which button to press, all it does is lure me into getting a google account. So open for google account holder but seemingly not "the public".

**Comment by lukebakken** [comment]
@henning-schild going forward, open a discussion here.
