### ISSUE TITLE
SkyPVP

### ISSUE THREAD

**Issue by MoiMiz** [pika/pika#1475]
Dear Pika server, 

I wanted to report that in SkyPVP there is a bug where a player won't be registered into the 'warzone', where pvp is enabled, if they crouch and stand on the edge of the block closest to spawn.

**Comment by lukebakken** [comment]
@MoiMiz this project is an AMQP 0.9.1 client library. You have the wrong project.

**Comment by MoiMiz** [comment]
Ok sorry my bad
