### ISSUE TITLE
Type Hint Issue with arguments parameter in queue_declare method of BlockingChannel Class - (expected "DeclareOk | None"  [arg-type])

### ISSUE THREAD

**Issue by rodrigo1t** [pika/pika#1482]
I'm encountering a type hint issue when using the `arguments` parameter in the `queue_declare` (`arguments={'x-message-ttl': 1000 * 60 * 60 * 24 * 90}`) method of the BlockingChannel class. The specific issue is related to the type of the arguments parameter.

Type Checking:
I'm using mypy with the --strict
`mypy main.py --strict`

Error Message:
`Argument "arguments" to "queue_declare" of "BlockingChannel" has incompatible type "dict[str, int]"; expected "DeclareOk | None"  [arg-type]`

### Code:

```
def __init_queue_service(self) -> None:
        queue_connection_string = os.environ['QUEUE_CONNECTION_STRING']
        queue_config: dict[str, Any] = {
            'host': queue_connection_string.split(':')[0],
            'port': int(queue_connection_string.split(':')[1]),
            'user': queue_connection_string.split(':')[2],
            'password': queue_connection_string.split(':')[3],
        }

        credentials = pika.PlainCredentials(
            queue_config['user'],
            queue_config['password'],
        )
        parameters = pika.ConnectionParameters(
            queue_config['host'],
            queue_config['port'],
            '/',
            credentials,
        )
        self.__queue_connection = pika.BlockingConnection(parameters)

        # Create queue if needed
        self.__queue_channel = self.__queue_connection.channel(

        )
        self.__queue_channel.queue_declare(
            queue=SYNC_QUEUE_NAME,
            durable=True,
            exclusive=False,
            auto_delete=False,
            arguments={'x-message-ttl': 1000 * 60 * 60 * 24 * 90},  # 90 days. <<<<<<
        )

```

Environment:
pika version: 1.3.2
Python version: 3.12.3
pika-stubs version: 0.1.3
mypy version: 1.11.0 
mypy-extensions version: 1.0.0

Additional Observation:
I was looking at the blocking_connection.pyi file, specifically the queue_declare method of the BlockingChannel class, and noticed that the type hint for the arguments parameter is set to Optional[spec.Queue.DeclareOk]. However, according to the [documentation](https://pika.readthedocs.io/en/stable/modules/adapters/blocking.html?highlight=queue_declare#pika.adapters.blocking_connection.BlockingChannel.queue_declare), the arguments parameter is described as a dict with key-value pairs.

**Comment by frost-nzcr4** [comment]
The problem is not in `pika` package, but in `pika-stubs` which you installed. It's outdated (version 0.1.3 from 10 June 2020). They have a bug in their stubs at https://github.com/hahow/pika-stubs/blob/master/pika-stubs/adapters/blocking_connection.pyi#L232

```python
        arguments: Optional[spec.Queue.DeclareOk] = ...,
```

**Comment by lukebakken** [comment]
@frost-nzcr4 thank you for looking into this. If someone wishes to add type annotations to this project, it would be appreciated.
