### ISSUE TITLE
Unable to pass user data to callbacks

### ISSUE THREAD

**Issue by tpot** [pika/pika#158]
Hello.  I'm trying to declare and bind multiple queues to an exchange asynchronously, but can't figure out a non-racy way to pass a parameter to the queue_declare callback.  )-:   A better way would be to have some way to pass user data to the callback functions as part of the API.  Can pika do this or Is there something basic I'm missing about the interface?

I ended up using functools.partial to do this, which only works with the git version, not 0.9.5 due to how it checks whether callbacks are callable or not.

import functools

channel.queue_declare(
  callback = functools.partial(on_queue_declare, user_data),
  queue = "whatever",
  auto_delete = True
)

def on_queue_declare(host, frame):
  # Do my funky thing

**Comment by art049** [comment]
That's still an issue

**Comment by lukebakken** [comment]
Passing user data would also address #898

**Comment by lukebakken** [comment]
Both `functools.partial` and a closure are good solutions to this issue.

**Comment by lukebakken** [comment]
Re-opening. I noticed that [this library](https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L398-L401) supports this feature. Pika should too.

**Comment by lukebakken** [comment]
@vitaly-krugl has suggested that `functools.partial` be the accepted way to do this [here](https://github.com/pika/pika/pull/941#issuecomment-363241531) and I agree. I have updated some of the code in `examples/` to demonstrate this.

**Comment by vitaly-krugl** [comment]
`lambda` is another way, in addition to `functools.partial`, to pass extra args to your own callback. Finally, in OOP, the callback will often be an instance method, with the instance already having the necessary context without additional args.
