### ISSUE TITLE
Creating a connection from a BlockingConnection hangs forever if the socket timeout has been set.

### ISSUE THREAD

**Issue by damzam** [pika/pika#208]
This will hang. It's broken code that we use in production.

> > > import pika
> > > connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
> > > connection.socket.settimeout(10000)
> > > channel = connection.channel()

**Comment by DawaTenzinNamgay12180008** [comment]
hello i don't any time out so how should i define
