### ISSUE TITLE
Using tornado.gen with pika can be a bit arduous

### ISSUE THREAD

**Issue by jonathanhogg** [pika/pika#228]
I've just started using pika and Tornado together in anger, and I'm very keen on using the `tornado.gen` style of writing asynchronous code. Unfortunately, doing this with pika is a bit more arduous than it could be due to the naming of the callback parameters.

Basically, `tornado.gen.Task` only works if the async function being called has a callback function parameter called `callback`. This is fairly arbitrary, but I can see their reasoning. Unfortunately, the pika functions tend to use different names for this parameter depending on the function, like `on_open_callback`. Happily, some work out-of-the-box, like `exchange_declare()`.

Put this down as a "nice to have", though.

**Comment by vitaly-krugl** [comment]
@jonathanhogg, thank you for your feedback. Some functions take multiple callback arguments, so they can't all be named "callback" (e.g., the connection's constructor). There hasn't been any activity on this issue for several years, so I am going to close it. If you have additional suggestions, please open a new issue. Thank you.
