### ISSUE TITLE
suspend on heartbeat

### ISSUE THREAD

**Issue by irodushka** [pika/pika#246]
I set heartbeat_interval property in pika.SelectConnection:

return pika.SelectConnection(pika.ConnectionParameters(host=conf.mq_host, heartbeat_interval=30), self.on_connected)

Then I start consuming messages, and I see that consumer suspends from time to time, process is freezed for approx 1000 ms. More details - my consumer gets messages, processes it and sends reply to another exchange. Average processing time is less than 1 ms, but sometimes it grows to approx 1000ms for one processing cycle only. These processing time peaks occures from time to time and it's interesting that they are very stable about 1000ms (1005, 1008, 1001, and never like 500 or 2000).
I turned on logging in pika and found such a messages (in the moment of "freezing" exactly):

----- here it looks like I recv a message:

pika.connection :  2012-12-27 16:43:08,122 : [DEBUG] : Frame: &lt;METHOD(['frame_type=1', 'channel_number=1', "method=&lt;Basic.Deliver(['consumer_tag=ctag1.0', 'redelivered=False', 'routing_key=request.update', 'delivery_tag=1726', 'exchange=com.micex.requests'])>"])>
pika.connection :  2012-12-27 16:43:08,123 : [DEBUG] : Frame: &lt;Header(['frame_type=2', 'channel_number=1', "properties=&lt;BasicProperties(['app_id=uby07oyqs58xdmpiig091eob'])>", 'body_size=320'])>
pika.connection :  2012-12-27 16:43:08,123 : [DEBUG] : Frame: &lt;Body(['frame_type=3', 'channel_number=1', 'fragment={"request.update":{"reqno":"4313","member":"vasya@superbroker","client_code":"superbroker.MXSE.1953201","status":{"seqnum":1,"is_active":false,"is_success":true,"ts":1356612188116,"message":{"code":"ok.exchange-accepted","params":[""]}}}}'])>
pika.channel :  2012-12-27 16:43:08,123 : [DEBUG] : Called with &lt;METHOD(['frame_type=1', 'channel_number=1', "method=&lt;Basic.Deliver(['consumer_tag=ctag1.0','redelivered=False', 'routing_key=request.update', 'delivery_tag=1726', 'exchange=com.micex.requests'])>"])>, &lt;Header(['frame_type=2', 'channel_number=1', "properties=&lt;BasicProperties(['app_id=uby07oyqs58xdmpiig091eob'])>", 'body_size=320'])>, u'{"request.update":{"reqno":"4313","member":"vasya@superbroker","client_code":"superbroker.MXSE.1953201","status":{"seqnum":1,"is_active":false,"is_success":true,"ts":1356612188116,"message":{"code":"ok.exchange-accepted","params":[""]}}}}'

--then I processed the message and was going to publish it to another exchange:

pika.connection :  2012-12-27 16:43:08,126 : [DEBUG] : Frame: &lt;METHOD(['frame_type=1', 'channel_number=2', "method=&lt;Basic.Publish(['ticket=0', 'mandatory=False', u'routing_key=superbroker.MXSE.1953201', 'immediate=False', u'exchange=com.micex.requests.log'])>"])>

--but here it looks like I got a heartbeat frame...

pika.heartbeat :  2012-12-27 16:43:08,126 : [DEBUG] : Received 1 heartbeat frames, sent 1

-- and going to send heartbeat reply

pika.heartbeat :  2012-12-27 16:43:08,126 : [DEBUG] : Sending heartbeat frame
pika.connection :  2012-12-27 16:43:08,126 : [DEBUG] : Frame: &lt;Heartbeat(['frame_type=8', 'channel_number=0'])>
pika.adapters.select_connection :  2012-12-27 16:43:08,126 : [DEBUG] : Calling &lt;bound method SelectConnection._handle_events of &lt;pika.adapters.select_connection.SelectConnection object at 0x1d89b10>>
pika.adapters.select_connection :  2012-12-27 16:43:08,127 : [DEBUG] : Will call &lt;bound method HeartbeatChecker.send_and_check of &lt;pika.heartbeat.HeartbeatChecker object at 0x1d89d10>> on or after 1356612218

-- !!!!!!!!!!!!!! See timestamps of prev and next messages 16:43:08,127->16:43:09,128
-- The following messages look like the continuation of my publish?..

pika.connection :  2012-12-27 16:43:09,128 : [DEBUG] : Frame: &lt;Header(['frame_type=2', 'channel_number=2', "properties=&lt;BasicProperties(['content_type=application/json'])>", 'body_size=468'])>
pika.adapters.select_connection :  2012-12-27 16:43:09,128 : [DEBUG] : Calling &lt;bound method SelectConnection._handle_events of &lt;pika.adapters.select_connection.SelectConnection object at 0x1d89b10>>
pika.connection :  2012-12-27 16:43:09,129 : [DEBUG] : Frame: &lt;Body(['frame_type=3', 'channel_number=2', 'fragment={"request.log.update": {"reqno": "4313", "member": "vasya@superbroker", "status": {"seqnum": 1, "is_success": true, "message": {"code": "ok.exchange-accepted", "params": [""]}, "is_active": false, "ts": 1356612188116}, "client_code": "superbroker.MXSE.1953201"}}'])&gt;

I started my publish at 16:43:08,126 and finished at 16:43:09,129. It's not impressing.
If I disable heartbeats I dont see any delays at all and everything works fine, but of cause I get problems with "dead" connections on server side.
I can only suppose that there is a collision somewhere in pika, so heartbeat processing interrupts and slows down the main ioloop.

My configuration - Linux RHEL6, Python 2.6.6, pika 0.9.8, RabbitMQ-server 3.0.1

(btw I broke my brain searching for the reason of  this 1000ms freezing and never thought it might be heartbeats)

Thanks

**Comment by base698** [comment]
when I try to set heartbeat on SelectConnection I get:  TypeError: __init__() got an unexpected keyword argument 'heartbeat_interval'

**Comment by base698** [comment]
I see nothing referencing heartbeat in the sourcecode for selectconnection either...

**Comment by vitaly-krugl** [comment]
@base698: see `pika.connection.ConnectionParameters`. The adapters take an optional `pika.connection.ConnectionParameters` instance as a constructor argument.

**Comment by hoverzheng** [comment]
Think you !
I solved it, I closed the connect twice, and modified it.
