### ISSUE TITLE
strange behavior of auto_delete property for an exchange point

### ISSUE THREAD

**Issue by ghost** [pika/pika#249]
I try to use auto_delete property for an exchange point.

I run a sender then I run a receiver. It works.

I stop the receiver. The sender continues to work. I use a timeout callback.

I wait for two seconds then I start the receiver. It doesn't handle messages from the sender.

I check the exchange list (RabbitMQ Management). The exchange was deleted. The sender doesn't know about it. It can't recreate the exchange point.  The connection and the channel are opened. I restart it. It works again.

It's my wrapper for pika. Code. It's a wrapper for SelectConnection.

receiver.py:

from rabbitmq import *

def handle_delivery(channel, method, properties, body):
    print 'delivery =', channel, method, properties, body

receiver = PikaReceiver(exchange = {'name' : 'monitor', 'type' : PikaObject.direct, 'auto_delete' : True},
                        queue = {'name' : 'monitor', 'auto_delete' : True},
                        routing_key = 'status',
                        handle_delivery = handle_delivery,
                        no_acknowledgement = True)

while True:
    pass

sender.py:

from rabbitmq import *
import uuid
import json

def init_callback(code, pika_obj):
    print 'init =', code, pika_obj.exchange_name

```
exchange_name = pika_obj.exchange_name

if isinstance(pika_obj, PikaSender):
    if exchange_name == 'monitor':
        send_status()
```

def handle_reject(method, properties, body):
    print 'reject =', method, properties, body

def send_status():
    info = {'id' : client_id}

```
print 'send_status'

sender.publish(body = json.dumps(info), routing_key = 'status', mandatory = True)

if sender.is_connection_open():
    sender.connection.add_timeout(3, send_status)
```

sender = PikaSender(exchange = {'name' : 'monitor', 'type' : PikaObject.direct, 'auto_delete' : True},
                    init_callback = init_callback,
                    handle_reject = handle_reject)

client_id = uuid.uuid4().get_hex()

while True:
    pass

Console:

[andrey@home-pc pika]$ ./sender.py 
init = 0 monitor
send_status
send_status
send_status
send_status
send_status

[andrey@home-pc pika]$ ./receiver.py 
delivery = <pika.channel.Channel object at 0x7f6a2f347b90> <Basic.Deliver(['consumer_tag=ctag0', 'redelivered=False', 'routing_key=status', 'delivery_tag=1', 'exchange=monitor'])> <BasicProperties([])> {"id": "34f1c57d35fd4fb29dca30983941e616"}
^CTraceback (most recent call last):
  File "./receiver.py", line 14, in <module>
    while True:
KeyboardInterrupt
[andrey@home-pc pika]$ ./receiver.py

No messages.

[root@home-pc pika]# rabbitmqctl list_exchanges
Listing exchanges ...
    direct
amq.direct  direct
amq.fanout  fanout
amq.headers headers
amq.match   headers
amq.rabbitmq.log    topic
amq.rabbitmq.trace  topic
amq.topic   topic
monitor direct
...done.

**Comment by samrudh** [comment]
In general, what is the callback for sender to know that exchange is deleted?
By callback, I mean asynchronous callback, and not some flag to be checked before publishing.
