### ISSUE TITLE
BlockingConnection not receiving messages after some time (~10-12 hours of running)

### ISSUE THREAD

**Issue by chuckhacker** [pika/pika#297]
My worker code is not much different than the RabbitMQ tutorial # 2 for Pika (http://www.rabbitmq.com/tutorials/tutorial-two-python.html). I have linked the Pastebin of my code (the real work is done in the OS process that I fire up in the callback function -- it blocks the callback thread for about 30-40 seconds until it's finished):
http://pastebin.com/hxubRien

Symptoms are that the worker is initially very responsive to new messages. As soon as I queue a new message in RabbitMQ, the worker responds immediately. Then after running the worker overnight for about 10 hours (without receiving messages during this duration), the worker stops responding to new messages. I add the messages to the queue, but they remain there unack'd.

Two things I did to eliminate the possibility of the worker hanging are 1.) ACK upon receipt rather than ACK upon job completion (yeah, this is counter to what the tutorial says) and 2.) defer processing to a separate OS process (the worker is a skeleton)

Do you have any suggestions for best practices or how I could diagnose this? It seems to be a flaw with Pika which is why I am reporting it here. I will attach a debugger with winpdb and try to investigate more.

**Comment by ntom** [comment]
I had exactly the same issue, again and again, I switched to using the async example form here, so far seems okay, will report back if no issues http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html
