### ISSUE TITLE
Maximum hearbeat_interval which can be set is 600s

### ISSUE THREAD

**Issue by maitreyavvm** [pika/pika#303]
HI there,

I am using pika 0.9.9 with RabbitMQ 3.0.3. Few of the consumers we have are long running, so I would want to have a long heartbeat_interval so that the connections are not removed from either side. But the network infrastructure will not allow long idle connections so I wanted to set the heartbeat interval to 3600s(assuming pika is single threaded and can analyze the heartbeat events only between requests). But when I check the Timeout value in the RMQ Management page, I see it set only to 600. 

Any number i try in the range of  (300-600) works but above 600, it somehow defaults to 600. I think I didnt have this problem with RMQ 2.8. I am using php-amqplib for other piece of code and it is able to set heartbeat_interval to 3600s with RabbitMQ 3.0.3. My usage of creating a conncetion is as follows:

connection = pika.BlockingConnection(pika.ConnectionParameters(host=self.server,port=self.port,heartbeat_interval=3600))

**Comment by carlhoerberg** [comment]
This is a really bad bug. Especially as BlockingConnection doesn't handle heartbeats in the background in a separate thread, something that at least should be documented.

All other official clients can override the server suggested heartbeat today, this is the first client i've seen that can't do it.

**Comment by vitaly-krugl** [comment]
UPDATE Setting a longer heartbeat should be possible now
