### ISSUE TITLE
IncompatibleProtocolError

### ISSUE THREAD

**Issue by wedaly** [pika/pika#317]
Hi,

I'm trying to use rabbitmq and pika on localhost for testing purposes, and I am receiving an IncompatibleProtocolError.

Here are the steps I'm following:

1) I start up rabbitmq-server, and when I run rabbitmqctl status I get:
Status of node rabbit@localhost ...
[{pid,390},
 {running_applications,
     [{rabbitmq_management_visualiser,"RabbitMQ Visualiser","3.0.4"},
      {rabbitmq_management,"RabbitMQ Management Console","3.0.4"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.0.4"},
      {rabbit,"RabbitMQ","3.0.4"},
      {os_mon,"CPO  CXC 138 46","2.2.10"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.0.4"},
      {webmachine,"webmachine","1.9.1-rmq3.0.4-git52e62bc"},
      {mochiweb,"MochiMedia Web Server","2.3.1-rmq3.0.4-gitd541e9a"},
      {xmerl,"XML parser","1.3.2"},
      {inets,"INETS  CXC 138 49","5.9.2"},
      {mnesia,"MNESIA  CXC 138 12","4.7.1"},
      {amqp_client,"RabbitMQ AMQP Client","3.0.4"},
      {sasl,"SASL  CXC 138 11","2.2.1"},
      {stdlib,"ERTS  CXC 138 10","1.18.3"},
      {kernel,"ERTS  CXC 138 10","2.15.3"}]},
 {os,{unix,darwin}},
 {erlang_version,
     "Erlang R15B03 (erts-5.9.3.1) [source] [64-bit] [smp:8:8] [async-threads:30] [hipe] [kernel-poll:true] [dtrace]\n"},
 {memory,
     [{total,35653280},
      {connection_procs,5696},
      {queue_procs,27576},
      {plugins,152984},
      {other_proc,9868108},
      {mnesia,62360},
      {mgmt_db,47384},
      {msg_index,22960},
      {other_ets,1239568},
      {binary,522528},
      {code,18264216},
      {atom,695185},
      {other_system,4744715}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,6523774566},
 {disk_free_limit,1000000000},
 {disk_free,199230787584},
 {file_descriptors,
     [{total_limit,156},{total_used,4},{sockets_limit,138},{sockets_used,1}]},
 {processes,[{limit,1048576},{used,196}]},
 {run_queue,0},
 {uptime,2667}]
...done.

2) I run the following code (RABBITMQ_USER='guest', RABBITMQ_PASS='guest', RABBIT_HOST='localhost')

credentials = pika.PlainCredentials(settings.RABBITMQ_USER,  
                                            settings.RABBITMQ_PASS)             

parameters = pika.ConnectionParameters(heartbeat_interval=5,  
                                               credentials=credentials,  
                                               host=settings.RABBIT_HOST)       

self.channel = None  
self.connection = pika.SelectConnection(parameters, self.on_connected)
# ....

self.connection.ioloop.start()

3) I get the following traceback:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/will/queue/consumer.py", line 237, in run
    self.connection.ioloop.start()
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/select_connection.py", line 108, in start
    self.poller.start()
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/select_connection.py", line 336, in start
    self.poll()
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/select_connection.py", line 351, in poll
    return self._handler(self.fileno, ERROR, error)
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/base_connection.py", line 315, in _handle_events
    self._handle_error(error)
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/base_connection.py", line 291, in _handle_error
    self._handle_disconnect()
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/base_connection.py", line 240, in _handle_disconnect
    self._adapter_disconnect()
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/base_connection.py", line 131, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/Users/will/python/lib/python2.7/site-packages/pika-0.9.13p0-py2.7.egg/pika/adapters/base_connection.py", line 143, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
IncompatibleProtocolError

Any idea what could be causing this?  I'm running Mac OS X Mountain Lion.  Any help would be greatly appreciated.

Thanks!
-- Will

**Comment by Ralithune** [comment]
I'm getting this error too.  Did this ever get figured out?

**Comment by vitaly-krugl** [comment]
I just ran @wedaly's multiprocessing code sample on Mac OS X El Capitan and Python 2.7.10 using pika from the current master branch without any exception. It ran until I closed the connection from the RabbitMQ Management GUI interface.

@Ralithune, are you also using the multiprocessing pattern as in @wedaly's example? Are multiple threads involved? Which platform, python version, and pika version? 

Take a look at DEBUG-level logs from pika. Pika logs a lot of info at DEBUG level, and you can usually figure out what's going on. Also, Wireshark is a great (and free) protocol analyzer that has AMQP support. Also, take a look at Connection code beginning with Connection.connect() to get a better understanding of the connection flow.

In the present (and former) SelectConnection implementation, `IncompatibleProtocolError`  means that the socket connection was disconnected somewhere after opening of the socket and before Connection.Start method from the server. At the moment, socket connection is established in the scope of the SelectConnection's constructor.

**Comment by raissanucci** [comment]
I'm getting the error when I try to create more than 900 child processes, each of them declaring a queue

**Comment by vitaly-krugl** [comment]
@raissanucci, you're probably overwhelming something - either your system's capacity to deal with some many processes or file descriptors or RabbitMQ's file descriptor capacity. You should also take a look at RabbitMQ server logs. Default RabbitMQ is preconfigured for a very small number of file descriptors. Also, your system might be configured for a small number of total file descriptors. 
Also, make sure that you're not reusing the same connection on multiple processes.

Those are the first places I would look.

See also the last paragraph in https://github.com/pika/pika/issues/317#issuecomment-192587913.

Finally, you probably don't want to be commenting in a closed issue. Your scenario with 900 processes is different from the issue reported here.  It's better to open a new one.

**Comment by Ralithune** [comment]
@vitaly-krugl I can go through my notes, but I don't think I took note of how this got fixed for me.  I think I remember it being something really dumb that I was doing, but I can't be sure.  In any event it apparently wasn't a big enough deal for me to remember it, so maybe it was something simple like blocked ports or bad credentials? Sorry I'm not more help.

**Comment by vaishalipavashe** [comment]
Hi,

I have "pika (0.10.0)" version installed and I am getting same error:

{code}
ERROR:pika.adapters.base_connection:Socket Error: 54
ERROR:pika.adapters.base_connection:Incompatible Protocol Versions
.
.
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 169, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
pika.exceptions.IncompatibleProtocolError
{code}

I am trying to use it with HP OneView RabbitMQ: http://h17007.www1.hpe.com/docs/enterprise/servers/oneviewhelp/oneviewRESTAPI/content/s_SCMB-python-fusion.html
