### ISSUE TITLE
UNEXPECTED_FRAME for BlockingConnection

### ISSUE THREAD

**Issue by fat-crocodile** [pika/pika#344]
Hi!

BlockingConnection._send_frame looks like this:

def _send_frame(self, frame_value):
....super(BlockingConnection, self)._send_frame(frame_value)
....self._frames_written_without_read += 1
....if self._frames_written_without_read == self.WRITE_TO_READ_RATIO:
........self._frames_written_without_read = 0
........self.process_data_events()

self._frames_written_without_read may become equal with self.WRITE_TO_READ_RATIO in the middle of the message A. 
if self.process_data_events() got some frames, it will call handlers. 
If handler will cause some messages sending (publish or ack), they would be sended in the middle of message A. 

and RabbitMQ server would return UNEXPECTED_FRAME

And It strange, but I got it not only on big messages, that contain more then 10 frames. I don't know, why :(

Ubuntu 12.4, pika 9.13.

Are there any reasons, to keep lines

....if self._frames_written_without_read == self.WRITE_TO_READ_RATIO:
........self._frames_written_without_read = 0
........self.process_data_events()

in _send_frame? May be move them in BlockingConnection._send_method, like this:

def _send_method(self, channel_number, method_frame, content=None):
....super(BlockingConnection, self)._send_method(channel_number, method_frame, content)
....if self._frames_written_without_read >= self.WRITE_TO_READ_RATIO:
........self._frames_written_without_read = 0
........self.process_data_events()

**Comment by gmr** [comment]
Closing due to lack of updates. 0.9.14 may have addressed, may have not. BlockingConnection sucks and needs to be rewritten from scratch or removed.
