### ISSUE TITLE
frame_error on basic_publish

### ISSUE THREAD

**Issue by wichert** [pika/pika#349]
I have code which does little more than publishing messages to a durable topic exchange:

``` python
channel.basic_publish(
            exchange=self.exchange,
            routing_key=routing_key,
            body=body,
            properties=pika.BasicProperties(delivery_mode=2))
```

This seems to result in frame_errors frequently. The rabbitmq server log says:

```
AMQP connection <0.2410.2> (running), channel 1 - error:
{amqp_error,frame_error,
            "type 3, first 16 octets = <<\"{\\\"uuid\\\": \\\"8d0c6f\">>: {invalid_frame_end_marker,\n                                                      115}",
            none}
```

This is using pika 0.9.13.

**Comment by fordnox** [comment]
Having same issue here with RabbitMQ 3.3.5 and pika 0.9.14 
Downgrading to pika 0.9.9 helped

**Comment by fake-name** [comment]
Why is this issue closed? I have recently encountered it using 0.9.14.

More critically, I am *specifically* acking after I publish, and the issue is still present:

		msgProps = pika.BasicProperties(correlation_id = props.correlation_id)
		ch.basic_publish(exchange='',
						 routing_key=props.reply_to,
						 properties=msgProps,
						 body=response)

		self.log.info("Message published. Acking.")

		# Ack has to be after the payload response has been published (and the requisite delay),
		# or pika will shit a brick.
		# see https://github.com/pika/pika/issues/349
		ch.basic_ack(delivery_tag = method.delivery_tag)


Like the others, downgrading to 0.9.9 fixes this issue.

**Comment by lenolib** [comment]
I am also having the same problems, running RabbitMQ 3.4.4 and pika 0.9.14
Seem to occur randomly when I send large messages.

**Comment by thomdixon** [comment]
Same problem with 0.9.14. I'll attempt the downgrade to 0.9.9 as others have done to see if that temporarily addresses the issue.

**Comment by fake-name** [comment]
This issue, and the complete lack of response have lead to me completely abandoning `pika` alltogether.

I'd recommended just using bare [amqp](https://pypi.python.org/pypi/amqp) until the dev's actually deign to respond.

**Comment by danielfaust** [comment]
Try txamqp, I think it's no longer mantained, and requires a little bit of tweaking, but it is fast and rock-solid.

**Comment by eandersson** [comment]
@Daniel you could also try rabbitpy or amqp-storm. Both should be rocksolid and are still maintained.

**Comment by jjmalina** [comment]
Does anyone have sample code that can reliably reproduce the issue? I'd be interested in taking a stab at writing a fix because I've been stuck on 0.9.9 for a while and want to use Tornado but 0.9.9's Tornado version is like 3 years old.

**Comment by thomdixon** [comment]
@jjmalina Running the code [from this repository](https://github.com/thomdixon/pika_issue_349) gives me the following output:

```
vagrant@localhost:/vagrant$ python main.py
PUBLISH: blah
CONSUME: blah
PUBLISH: test
PUBLISH: test2
CONSUME: test
PUBLISH: test
PUBLISH: test2
CONSUME: test2
CONSUME: test
PUBLISH: test
PUBLISH: test2
CONSUME: test2
PUBLISH: test
PUBLISH: test2
PUBLISH: test
PUBLISH: test2
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 50, in run
    self.consumer_channel.start_consuming()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 955, in start_consuming
    self.connection.process_data_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 243, in process_data_events
    raise exceptions.ConnectionClosed()
ConnectionClosed
```

and looking at `tail /var/log/rabbitmq/rabbit@localhost.log` gives:

```
accepting AMQP connection <0.420.0> ([::1]:54685 -> [::1]:5672)

=ERROR REPORT==== 2-Apr-2015::10:27:15 ===
AMQP connection <0.420.0> (running), channel 2 - error:
{amqp_error,unexpected_frame,
            "expected content body, got non content body frame instead",
            'basic.publish'}

=INFO REPORT==== 2-Apr-2015::10:27:15 ===
closing AMQP connection <0.420.0> ([::1]:54685 -> [::1]:5672)
```

Does this help?

**Comment by eandersson** [comment]
@thomdixon Are you running one pika connection per thread?

**Comment by thomdixon** [comment]
@eandersson One connection with two channels per process (using multiprocessing, as opposed to threads).

**Comment by vitaly-krugl** [comment]
@eandersson, you asked the perfect question. This is user error: the code provided by @thomdixon at https://github.com/thomdixon/pika_issue_349 corrupts the data stream by attempting to use the same socket connection from two processes. When you create a multiprocessing.Process, you get a fork of the parent process that clones the parent's memory and file descriptors, including pika.Connection's socket file descriptor. As the result, the two processes (parent and forked) end up sharing the exact same socket connection. Subsequently, publishing from one process and creating a consumer from another process results in corruption of the data stream on the single sahred TCP/IP connection.

**Comment by thomdixon** [comment]
@vitaly-krugl I've updated the repository to no longer use `multiprocessing` at all. One process, one thread, one connection, two channels. The following still reproduces the problem:

```
vagrant@localhost:/vagrant$ python main.py &
[1] 8174
vagrant@localhost:/vagrant$ ./rabbitmqadmin publish exchange=issue349 routing_key=test.issue349 payload="blah"
CONSUME: blah
PUBLISH: test
PUBLISH: test2
CONSUME: test
PUBLISH: test
PUBLISH: test2
CONSUME: test2
CONSUME: test
PUBLISH: test
PUBLISH: test2
CONSUME: test2
PUBLISH: test
PUBLISH: test2
PUBLISH: test
PUBLISH: test2
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    consumer.run()
  File "main.py", line 49, in run
    self.consumer_channel.start_consuming()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 955, in start_consuming
    Message published
self.connection.process_data_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 243, in process_data_events
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
[1]+  Exit 1                  python main.py
vagrant@localhost:/vagrant$ tail /var/log/rabbitmq/
rabbit@localhost.log       rabbit@localhost-sasl.log  shutdown_err               shutdown_log               startup_err                startup_log
vagrant@localhost:/vagrant$ tail /var/log/rabbitmq/
rabbit@localhost.log       rabbit@localhost-sasl.log  shutdown_err               shutdown_log               startup_err                startup_log
vagrant@localhost:/vagrant$ tail /var/log/rabbitmq/rabbit@localhost.log
accepting AMQP connection <0.392.0> ([::1]:54697 -> [::1]:5672)

=ERROR REPORT==== 2-Apr-2015::12:41:32 ===
AMQP connection <0.392.0> (running), channel 2 - error:
{amqp_error,unexpected_frame,
            "expected content body, got non content body frame instead",
            'basic.publish'}

=INFO REPORT==== 2-Apr-2015::12:41:32 ===
closing AMQP connection <0.392.0> ([::1]:54697 -> [::1]:5672)
```

**Comment by vitaly-krugl** [comment]
@thomdixon, thanks for updating the test. I will try it a bit later on my system.

**Comment by vitaly-krugl** [comment]
@thomdixon, I tested your updated single-process https://github.com/thomdixon/pika_issue_349 on my MacBookPro with pika 0.9.14 and was able to reproduce the failure. However, when I installed pika master, I was no longer able to reproduce the issue.

This issue was most likely already addressed by PR #509 in response to issue #507.

**Comment by thomdixon** [comment]
@vitaly-krugl Thank you for taking the time to test. I guess we'll update from 0.9.9 to 0.9.15 when it comes out to skip this issue.

**Comment by vitaly-krugl** [comment]
@thomdixon, I would like to see many of those PRs validated, merged, and released soon, as our code is impacted by a number of those stability issues in 0.9.14.
