### ISSUE TITLE
BlockingConnection does not utilise retry_timeout or connection_attempts parameters

### ISSUE THREAD

**Issue by markunsworth** [pika/pika#354]
When using a `ConnectionParameters` object and setting the connection_attempts and retry_delay parameters, the BlockingConnection does not attempt to reconnect if a connection could not be established.

It looks like the `BlockingConnection` doesn't make use of the `connect()` method in the `connection.Connection` base class as it has an override implemented.

https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L200

Should this really be the case? Has it been implemented this way for a reason that I don't see?

**Comment by vitaly-krugl** [comment]
This should be addressed in Pika 0.10.0.
