### ISSUE TITLE
SOL_TCP vs IPPROTO_TCP

### ISSUE THREAD

**Issue by nehald** [pika/pika#370]
I'm trying to use pika with jython 2.7 (yea.. I know) and get the following error.
Jython 2.7b1 (default:ac42d59644e9, Feb 9 2013, 15:24:52) 
[OpenJDK 64-Bit Server VM (Sun Microsystems Inc.)] on java1.6.0_27
Type "help", "copyright", "credits" or "license" for more information.

> > > import pika
> > > connection = pika.BlockingConnection()
> > > Traceback (most recent call last):
> > > ..
> > > ..
> > >  File "/opt/Lib/site-packages/pika-0.9.13-py2.7.egg/pika/adapters/base_connection.py", line 153, in _create_and_connect_to_socket
> > > self.socket.setsockopt(socket.SOL_TCP, socket.TCP_NODELAY, 1)
> > > AttributeError: 'module' object has no attribute 'SOL_TCP'

Could we replace socket.SOL_TCP  with socket.IPPROTO_TCP (which I believe is a little more standard) ?

Thanks
Nehal

**Comment by jimbaker** [comment]
Although commenting on closed bugs may be a bad idea, it seems better in this case to provide some completeness. So with that in mind, I just opened a bug in Jython for the missing socket.SOL_TCP support (which I got some useful details about by reviewing this specific issue.) This does not change the fact that it makes more sense to use socket.IPPROTO_TCP.

Please note that we completely revamped socket support as of Jython 2.7.0, with it now being based on Netty. So far it's looking pretty good, but like any rewrites there is the possibility of regressions. Feel free to open bugs as they come up at http://bugs.jython.org.
