### ISSUE TITLE
AttributeError are suppressed in callback functions

### ISSUE THREAD

**Issue by abranches** [pika/pika#373]
I found that in some situations a strange behaviour occurs when AttributeExceptions are raised in the callback functions.

What exactly happens is that if a consumer starts consuming from an already existing and non empty queue, and in the callback we raise an AttributeException, that exception seems to be supressed somehow.

Here's a simple example:
**receiver.py:**
```
#!/usr/bin/env python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
channel = connection.channel()
channel.queue_declare(queue='hello')

print ' [*] Waiting for messages. To exit press CTRL+C'

def callback(ch, method, properties, body):
    print " [x] Received %r" % (body,)
    raise AttributeError("my attribute error")
    print "end callback"

channel.basic_consume(callback,
                      queue='hello')
                      #no_ack=True)

channel.start_consuming()
```

**sender.py:**
```
#!/usr/bin/env python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
channel = connection.channel()

channel.queue_declare(queue='hello')

channel.basic_publish(exchange='',
                      routing_key='hello',
                      body='Hello World!')
print " [x] Sent 'Hello World!'"
connection.close()
```

**Steps to reproduce it:**

1. Run sender.py:
sends hello message.

2. Run receiver.py and keep it alive:
gets the message in queue but it raises nothing. It should have raised AttributeException (or ConnectionClosed really).

3. Run sender.py again:
receiver gets the new message and now it raises exceptions.ConnectionClosed(), which is the expected behaviour.

I could also ask, why is the AttributeException "replaced" by ConnectionClosed  in BlockingConnection.process_data_events()? This creates really awkward and hard to debug situations if there's any kind of typo in the callback function (that's what happen to me).

I went digging a little at the pika source code, but couldn't find anything that could cause this..

Thanks,
Pedro

**Comment by vitaly-krugl** [comment]
Addressed in @gmr's recent commit to pika master.
