### ISSUE TITLE
Different behaviors on different platforms when dealing with closed socket

### ISSUE THREAD

**Issue by huyphan** [pika/pika#391]
I experienced the different behaviors of pika on my Centos 5.7 and Ubuntu 12.04 boxes when dealing with closed socket from RabbitMQ.

I'm using this script https://gist.github.com/huyphan/6361962 which is a modified version of a pika sample script. Basically it sends a message to RabbitMQ every 7 seconds. What I wanted to test is to see if pika is able to reconnect if I restarted RabbitMQ broker in between that 7 seconds. 

It turned out that the script works fine on Ubuntu (i.e. it was able to detect connection closed, reconnect to RabbitMQ and send the message), but was failed to do any part of that on Centos.

By checking the epoll events, I noticed that after RabbitMQ was restarted, if my script tried to send a message to the broker (with the old socket), epoll returned different events on two OS. For Ubuntu, the event code is 29 (which is 0x10 | ERROR | WRITE), while on Centos it's 25 (0x10 | ERROR | READ).

Looking closer at the source code at `base_connection.py`

```python
def _handle_events(self, fd, events, error=None, write_only=False):
        """Handle IO/Event loop events, processing them.

        :param int fd: The file descriptor for the events
        :param int events: Events from the IO/Event loop
        :param int error: Was an error specified
        :param bool write_only: Only handle write events

        """
        if not fd:
            LOGGER.error('Received events on closed socket: %d', fd)
            return

        if events & self.WRITE:
            self._handle_write()
            self._manage_event_state()

        if not write_only and (events & self.READ):
            self._handle_read()

        if events & self.ERROR:
            LOGGER.error('Error event %r, %r', events, error)
            self._handle_error(error)

def _handle_error(self, error_value):
        """Internal error handling method. Here we expect a socket.error
        coming in and will handle different socket errors differently.

        :param int|object error_value: The inbound error

        """
        import traceback
        traceback.print_stack()
        if 'timed out' in str(error_value):
            raise socket.timeout
        error_code = self._get_error_code(error_value)
        if not error_code:
            LOGGER.critical("Tried to handle an error where no error existed")
            return

        # Ok errors, just continue what we were doing before
        if error_code in self.ERRORS_TO_IGNORE:
            LOGGER.debug("Ignoring %s", error_code)
            return

        # Socket is closed, so lets just go to our handle_close method
        elif error_code in (errno.EBADF, errno.ECONNABORTED):
            LOGGER.error("Socket is closed")

        elif self.params.ssl and isinstance(error_value, ssl.SSLError):

            if error_value.args[0] == ssl.SSL_ERROR_WANT_READ:
                self.event_state = self.READ
            elif error_value.args[0] == ssl.SSL_ERROR_WANT_WRITE:
                self.event_state = self.WRITE
            else:
                LOGGER.error("SSL Socket error on fd %d: %r",
                             self.socket.fileno(), error_value)
        else:
            # Haven't run into this one yet, log it.
            LOGGER.error("Socket Error on fd %d: %s",
                         self.socket.fileno(), error_code)

        # Disconnect from our IOLoop and let Connection know what's up
        self._handle_disconnect()
```

`_handle_event` function was called with `write_only = True`, that means on Ubuntu, it would call `_handle_write`, and since the socket was closed, `_handle_error` was passed a `socket.error` object for `error` param, that lead to the line `self._handle_disconnect()`.

However on Centos, as there's only the ERROR and READ flag in the event code, `_handle_event` called `_handle_error` directly without `error` param, that made pika thrown out "Tried to handle an error where no error existed" and never reconnect to the broker.

I'm not sure if this issue can be sorted out from pika or it's actually related to RabbitMQ itself, however my Java client (on which I did a similar test) works just fine on both platforms, so I guess there's something we can do here. 

FYI, I was testing on RabbitMQ 3.1.2, same issue happened with version 3.1.3 and 3.1.5.

**Comment by vitaly-krugl** [comment]
Many error-handling improvements were made in release 0.10.0 and additional ones in pika master. If this is still an issue with the latest pika master, please open a new issue with all the necessary info (how to reproduce, platform, python version, pika version/commit, traceback, DEBUG-level logs, etc.)
