### ISSUE TITLE
got non method frame instead

### ISSUE THREAD

**Issue by mfyang** [pika/pika#392]
When try to publish tens of thousands docs to rabbit-mq via pika,  I got the following err msg.  

WARNING:pika.adapters.blocking_connection:Disconnected from RabbitMQ at ww-mq-platform.wisewindow.com:5672 (505): UNEXPECTED_FRAME - expected method frame, got non method frame instead

related code I am using is 

```python
file_name = sys.argv[1]
f = open(file_name)
lines = f.readlines()
f.close()

credentials = pika.PlainCredentials(username, passwd)
params = pika.ConnectionParameters(host=host, credentials=credentials)
conn = pika.BlockingConnection(params)
channel = conn.channel()

for line in lines:
    try:
        channel.basic_publish(body=line, exchange=exchange, routing_key=key)
    except:
        print '-------failed:', line
        raise

time.sleep(2)
conn.close()
```

**Comment by vitaly-krugl** [comment]
Thank for reporting. BlockingConnection was rewritten for the 0.10.0 release. I am not aware of this issue following the rewrite. Please open a new issue if this still occurs with Pika 0.10.0.
