### ISSUE TITLE
ConnectionClosed raised if the callback function raises AttributeError

### ISSUE THREAD

**Issue by Dan-stahr** [pika/pika#403]
The process_data_events in  blocking_connection.py is defined as follows : 

    def process_data_events(self):
        """Will make sure that data events are processed. Your app can
        block on this method.

        """
        try:
            if self._handle_read():
                self._socket_timeouts = 0
        except AttributeError:
            raise exceptions.ConnectionClosed()
        except socket.timeout:
            self._handle_timeout()

The ```_handle_read()``` method calls - somewhere deep - a callback specified by the pika user. However, if this piece of custom code throws AttributeError, pika still consider this error as ConnectionClosed. It's very annoying to debug AttributeErrors in such callbacks.

Therefore, it'd be nice to at least place the original exception as a cause of this ConnectionClosed error. The least hacky way would be (in my opinion) catching the error more specificall or wrapping the original error in another one, e.g. CallbackError.

**Comment by thomdixon** [comment]
@gmr Ran into this today. I recommend passing `sys.exc_info()[2]` as the third argument to `raise` so the traceback more accurately reflects the source of the error until your more permanent solution is in place.

**Comment by vitaly-krugl** [comment]
@gmr, this is fixed in master via e7b6d73aa2a38b7e2d4ac57e111bec9f9d518e08
