### ISSUE TITLE
Duplicate consumer tag exception when pausing and resuming consumption

### ISSUE THREAD

**Issue by purpleP** [pika/pika#425]
Here is some of my code.

 def connect(self):
        self.connection = pika.SelectConnection(pika.ConnectionParameters(
            host=AbstractReceiver.host), on_open_callback=self.on_connection_open)

    def on_message_receive(self, channel, method, header, body):
        AbstractReceiver.on_message_receive(self, body)
        channel.basic_ack(delivery_tag=method.delivery_tag)

    def on_connection_open(self, connection):
        connection.channel(on_open_callback=self.on_channel_open)
        # connection.add_timeout(1, self.on_timeout)

    def start_connection(self):
        self.connect()
        self.consuming_thread = ConsumingThread(self.connection)
        self.consuming_thread.daemon = True
        self.consuming_thread.start()

    def pause_consumption(self):
        self.log.info("Trying to pause consumption")
        self.channel.basic_cancel(callback=self.on_canceled, consumer_tag=self.consumer_tag)

    def resume_consumption(self):
        self.start_consumption()

    def start_consumption(self):
        self.consumer_tag = self.channel.basic_consume(self.on_message_receive, queue=self.queue_name)

**Comment by vitaly-krugl** [comment]
@purpleP, I see that there are threads involved in your example. Pika connections are not thread-safe, so you may not access a connection or any of its channels from multiple threads.

**Comment by vitaly-krugl** [comment]
In released versions of pika, connections are not thread-safe. See https://github.com/pika/pika/blob/master/docs/faq.rst.
