### ISSUE TITLE
pika.adapters.base_connection:Socket Error on fd... causes silent failure of basic_publish in blocking connection

### ISSUE THREAD

**Issue by joekarl** [pika/pika#439]
We've actually seen this error a handful of times (always intermittently, can't reproduce). 

It appears that when the socket goes away in the middle of a publish, pika recognizes it, but never throws an exception, so the publish appears to complete successfully when in actuality it was never written to the socket because it was closed. 

The errors we see are:

    [Thu Feb 13 17:32:35 2014] [error] ERROR:pika.adapters.base_connection:Socket Error on fd 34: 104
    [Thu Feb 13 17:32:35 2014] [error] WARNING:pika.adapters.base_connection:Socket closed when connection was open
    [Thu Feb 13 17:32:35 2014] [error] CRITICAL:pika.connection:Attempted to send frame when closed
    [Thu Feb 13 17:32:35 2014] [error] CRITICAL:pika.connection:Attempted to send frame when closed

Relevant code: https://github.com/pika/pika/blob/master/pika/adapters/base_connection.py#L284

Possible fixes would be: 

* do something (throw an error?) when this socket error occurs
* throw an error when one attempts to send a frame when the connection is closed (right now it just spits out a CRITICAL log error, but nothing that can be captured)

Thoughts?

**Comment by gmr** [comment]
I changed the logging to an exception. It shouldn't happen, but it's better to let you deal with the fallout instead of ignore it.
