### ISSUE TITLE
IOLoop is taking 1 second to stop in SelectConnection

### ISSUE THREAD

**Issue by sjiitr** [pika/pika#467]
I had installed rabbitmq-server on my local machine (Ubuntu 12.04) using apt-get command which was version 2.7.1 . Everything was working fine.

Then I upgraded it to version 3.3.1 using debian package.

I am using SelectConnection publisher example given in the docs with a little modification that is, it calls self.stop() instead of self.schedule_next_message() after publishing first message and what I found is, IOLoop is taking around 1 sec to stop after channel.close() and connection.close() which was not happening earlier.

Please help me.

Thank you

**Comment by gmr** [comment]
This should be addressed, sorry for the very long time to update
