### ISSUE TITLE
BlockingConnection basic_publish delays exchange not found error until next channel operation

### ISSUE THREAD

**Issue by leth** [pika/pika#474]
If you try to publish a message to an exchange which does not exist, the blocking connection channel will not raise an exception until the next channel operation is attempted.

A workaround seems to be to call `process_data_events()` on the connection after the channel publish call.

**Comment by vitaly-krugl** [comment]
@leth, that's the nature of BlockingConnection. If you're not executing code in BlockingConnection, then it's not processing input either. If you're using RabbitMQ that supports Publisher Acknowledgements, then you can enable it on a given channel via `channel.confirm_delivery()`, and you should then get the "exchange not found" error before `basic_publish` returns.

**Comment by vitaly-krugl** [comment]
Works as intended. Let's close.

**Comment by vitaly-krugl** [comment]
Please see my earlier comments. This feature works as intended in BlockingConnection. SelectConnection and other asynchronous adapters can be more responsive if used appropriately in an I/O-bound applications.
