### ISSUE TITLE
can I get blocked connection notifications with pika?

### ISSUE THREAD

**Issue by knktc** [pika/pika#476]
I use pika to publish and consume tasks. In my case, the publishers are fast but the consumers are really slow. That makes my ram hit the high watermark, and rabbitmq flow control blocked the publisher's connection.
I don't know how to use pika to get blocked connection notifications? If I can get the notifications, I can pause the publishers' work. 
I tried to find this feature in pika's docs, but failed...
Thank you!

**Comment by gmr** [comment]
Added methods that more explicitly allow the registration of callbacks for these frames. Sorry for the delay in response.
