### ISSUE TITLE
Could not connect remote RabbitMQ Server

### ISSUE THREAD

**Issue by Daemoneyes** [pika/pika#483]
I installed a rabbitmq server on one of my virtual machine,the ip address is like 192.168.199.140.All the firewall have been shutdown so I can connect to the rabbitmq by touching 192.168.199.140:5672 (Log trace in vm).
I try to connect the rabbitmq server through pika.On vm itself it works fine but on my host computer,it doesn't work.
The code looks like:

```
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
import pika
cre=pika.PlainCredentials("ucd","ucd")
para=pika.ConnectionParameters("192.168.199.140",5672,"ucd",cre)
conn=pika.BlockingConnection()
```

The logger gives me info like:

```
DEBUG:Added: {'callback': <bound method  BlockConnection._on_connection_error    of  <pika.adapters.blocking_connection.BlockingConnection object at 0x00000000035D5E10>>, 'only': None, 'one_shot': False, 'arguments': None}
```

DEBUG:Added: {'callback': <bound method BlockingConnection._on_connection_start of <pika.adapters.blocking_connection.BlockingConnection object at 0x00000000035D5E10>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}

```
INFO:Connecting to ::1:5672
ERROR:Connection to ::1:5672 failed: timeout
INFO:Connecting to 127.0.0.1:5672
ERROR:Connection to 127.0.0.1:5672 failed: timeout
```

So why I connect 192.168.199.140 but the pika parse 127.0.0.1? I've checked my host on windows,there is no record on that.

**Comment by ilias1995** [comment]
i have the same problem.
log:
Traceback (most recent call last):
  File "manual_payment_processing.py", line 70, in send_pay
    connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 130, in __init__
    super(BlockingConnection, self).__init__(parameters, None, False)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/usr/local/lib/python3.6/site-packages/pika/connection.py", line 596, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
    error = self._adapter_connect()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 301, in _adapter_connect
    raise exceptions.AMQPConnectionError(error)
pika.exceptions.AMQPConnectionError: Connection to ::1:5672 failed: [Errno 99] Address not available

code:
connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))

can some one help me?

**Comment by eandersson** [comment]
> i have the same problem.
> log:
> Traceback (most recent call last):
> File "manual_payment_processing.py", line 70, in send_pay
> connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
> File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 130, in **init**
> super(BlockingConnection, self).**init**(parameters, None, False)
> File "/usr/local/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 72, in **init**
> on_close_callback)
> File "/usr/local/lib/python3.6/site-packages/pika/connection.py", line 596, in **init**
> self.connect()
> File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 230, in connect
> error = self._adapter_connect()
> File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 301, in _adapter_connect
> raise exceptions.AMQPConnectionError(error)
> pika.exceptions.AMQPConnectionError: Connection to ::1:5672 failed: [Errno 99] Address not available
> 
> code:
> connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
> 
> can some one help me?

Try changing localhost to 127.0.0.1, maybe RabbitMQ isn't listening to your ipv6 loopback?

**Comment by lukebakken** [comment]
> maybe RabbitMQ isn't listening to your ipv6 loopback?

`localhost` isn't correctly set up in `/etc/hosts` or in some other part of that person's system. They also filed #1151 with the same question.

Changing `localhost` to `127.0.0.1` should work.
