### ISSUE TITLE
It's not possible to schedule work below 1 sec

### ISSUE THREAD

**Issue by bra-fsn** [pika/pika#493]
Using the async producer example (http://pika.readthedocs.org/en/latest/examples/asynchronous_publisher_example.html), I've noticed that the minimum resolution is 1 second (specified as TIMEOUT = 1 in SelectPoller).
I think it would be good to either:
- lower that to 0.1 or 0.01 (eats a little more CPU)
- make it overrideable easily
- make it adapt to the lowest specified add_timeout call

**Comment by gmr** [comment]
Thanks for the issue.

**Comment by vitaly-krugl** [comment]
@bra-fsn and @xintron, this issue should also be resolved natively in SelectConnection once PR #549 is resolved and merged.
