### ISSUE TITLE
channel.flow set to False: callback is not called

### ISSUE THREAD

**Issue by senseysensor** [pika/pika#495]
Here is piece of my code. When I pass ```False```, callback never gets called. On ```True``` everything works good.

```python
 def set_flow(self, flow):
    # ....
    channel.flow(self.flow_done, flow)
    self._waiting_for_flow_reply.acquire()    # <-- so here I wait...
    # ....

# and below:
 def flow_done(self, state):
        """ Flow callback """
        self._logger.info('Flow state: %s', 'ON' if state else 'OFF')
        self._waiting_for_flow_reply.release()    # <-- here I release the lock...
```

before everything worked good. Not sure what could change, but I didn't touch the code for a long time. Pika is 0.9.14 from repo, I updated it before. RabbitMQ 3.3.4, Erlang R15B01, debian 7. SelectConnection. Probably only the rabbit server could be updated, but not major version. No warnings / errors in pika logger. Any ideas?

**Comment by gmr** [comment]
Nothing should have changed that impacted that code, perhaps something on the RabbitMQ side? Flow is only partially supported. Closing due to age, no real idea what's going on here or the use case for Channel.Flow these days.
