### ISSUE TITLE
Heartbeat failure does not close the socket

### ISSUE THREAD

**Issue by kherrala** [pika/pika#502]
I discovered this behaviour after hours of tracking why my application seems to spawn multiple connections on poor connectivity. When heartbeat._close_connection() is executed it never calls adapter_disconnect() on connection. This also means that socket is not unregistered from IOLoop and never closed.

Easiest fix seems to be to add this call in heartbeat.py:
self._connection._adapter_disconnect()

In my opinion the code should be refactored so that Heartbeat gets a callback to run in constructor and all the shutdown logic is inside Connection-class.

**Comment by gmr** [comment]
ThANKS FOR THE PR
