### ISSUE TITLE
After ConnectionClosed exception, connection.is_open and channel.is_open should be False, but are both True

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#518]
Occurs on linux (Amazon linux) as well as MacOS Yosemite and Mavericks with pika 0.9.14. Used to work fine with https://github.com/pika/pika/archive/24c3f1d6bdab3d609721dd721b9ac87771906789.zip.
1. Connect to RabbitMQ (any version) via BlockingConnection.
   1.1. Save `channel = connection.channel()`
2. Publish a message on the connection
3. Let the heartbeat expire without sending/receiving anything (no I/O on the connection during this time)
4. Attempt to Publish a message on the connection: connection raises ConnectionClosed exception as expected.

PROBLEM: After ConnectionClosed exception, `channel.is_open` returns True and `channel.connection.is_open` also returns True; however, `channel.connection.socket is None`. After ConnectionClosed exception, one would expect both `channel.connection.is_open` and `channel.is_open` to return False to reflect the fact that connection is closed.

My code checks `channel.is_open` and `channel.connection.is_open` to determine when it's time to reconnect. Because of this bug, the code is mislead into thinking that the connection is still open and doesn't reconnect. Subsequently, when the code attempts to use the connection to publish a message, pika raises: "AttributeError: `NoneType' object has no attribute 'sendall'`

My code reconnected just fine with https://github.com/pika/pika/archive/24c3f1d6bdab3d609721dd721b9ac87771906789.zip (0.9.14 p0 dev, I think), but started breaking once we upgraded to the official release 0.9.14.

```
  File "/Users/vkruglikov/nta/nupic/nupic/support/decorators.py", line 214, in retryWrap
    result = func(*args, **kwargs)
  File "/Users/vkruglikov/nta/products/htmengine/htmengine/utils/message_bus_connector.py", line 313, in publish
    immediate=False):
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 553, in basic_publish
    (properties, body))
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 1141, in _rpc
    self._wait_on_response(method_frame))
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 1159, in _send_method
    self.connection.send_method(self.channel_number, method_frame, content)
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 274, in send_method
    self._send_method(channel_number, method_frame, content)
  File "build/bdist.macosx-10.10-intel/egg/pika/connection.py", line 1519, in _send_method
    content[1][start:end]))
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 417, in _send_frame
    super(BlockingConnection, self)._send_frame(frame_value)
  File "build/bdist.macosx-10.10-intel/egg/pika/connection.py", line 1490, in _send_frame
    self._flush_outbound()
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 377, in _flush_outbound
    if self._handle_write():
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/base_connection.py", line 365, in _handle_write
    return self._handle_error(error)
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/base_connection.py", line 302, in _handle_error
    self._handle_disconnect()
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/base_connection.py", line 248, in _handle_disconnect
    self._adapter_disconnect()
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 318, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "build/bdist.macosx-10.10-intel/egg/pika/adapters/blocking_connection.py", line 371, in _check_state_on_disconnect
    raise exceptions.ConnectionClosed()
ConnectionClosed
```

```
(Pdb) self._channel.connection.is_open
True
(Pdb) self._channel.is_open
True
(Pdb) self._channel.connection.socket
(Pdb) repr(self._channel.connection.socket)
'None'
```

When attempting to use the connection after ConnectionClosed, but still channel.is_open and channel.connection.is_open both returning True (e.g., `channel.basic_publish()`, `channel.cose()` or `cannel.connection.close()`), you get `AttributeError: 'NoneType' object has no attribute 'sendall'`:

```
/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/adapters/blocking_connection.pyc in _send_method(self, method_frame, content, wait)
   1157         prev_received_response = self._received_response
   1158         self._received_response = False
-> 1159         self.connection.send_method(self.channel_number, method_frame, content)
   1160         while wait and not self._received_response:
   1161             try:

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/adapters/blocking_connection.pyc in send_method(self, channel_number, method_frame, content)
    272 
    273         """
--> 274         self._send_method(channel_number, method_frame, content)
    275 
    276     def sleep(self, duration):

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/connection.pyc in _send_method(self, channel_number, method_frame, content)
   1501 
   1502         """
-> 1503         self._send_frame(frame.Method(channel_number, method_frame))
   1504 
   1505         # If it's not a tuple of Header, str|unicode then return

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/adapters/blocking_connection.pyc in _send_frame(self, frame_value)
    415 
    416         """
--> 417         super(BlockingConnection, self)._send_frame(frame_value)
    418         self._frames_written_without_read += 1
    419         if self._frames_written_without_read >= self.WRITE_TO_READ_RATIO:

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/connection.pyc in _send_frame(self, frame_value)
   1488         self.frames_sent += 1
   1489         self.outbound_buffer.append(marshaled_frame)
-> 1490         self._flush_outbound()
   1491         if self.params.backpressure_detection:
   1492             self._detect_backpressure()

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/adapters/blocking_connection.pyc in _flush_outbound(self)
    375         if self.outbound_buffer:
    376             try:
--> 377                 if self._handle_write():
    378                     self._socket_timeouts = 0
    379             except socket.timeout:

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika-0.9.14-py2.7.egg/pika/adapters/base_connection.pyc in _handle_write(self)
    358             frame = self.outbound_buffer.popleft()
    359             try:
--> 360                 self.socket.sendall(frame)
    361                 bytes_written = len(frame)
    362             except socket.timeout:

AttributeError: 'NoneType' object has no attribute 'sendall'
```

**Comment by vitaly-krugl** [comment]
As of c7a72cdd4f5f7e1d692bf42943c9f3810f6bb1b7, it's partially-fixed: `connection.is_open` now correctly reports False`, but channel.is_open still reports False

**Comment by vitaly-krugl** [comment]
Possibly fixed by PR #685 or before it. Need to implement an acceptance test that reproduces the scenario using tiny heartbeat timeout and verifies that both connection.is_open and channel.is_open return False.

**Comment by lukebakken** [comment]
@vitaly-krugl could you provide the code you were using to reproduce this? I assume it must have disabled heartbeats, correct?

**Comment by vitaly-krugl** [comment]
This was happening in proprietary code of my former employer. If I recall correctly, the code would perform some blocking operation that on occasion caused the RabbitMQ server's heartbeat timeout logic to drop the connection. Here are two test cases that I can think of:

1. The natural way
1.1 Using BlockingConnection, create a connection and channel with a non-zero heartbeat
1.2 `time.sleep` long enough to cause RabbitMQ server to drop the connection
1.3 Attempt to publish a message and verify that pika `ConnectionClosed` exception was raised.
1.4 Verify that connection.is_open and channel.is_open are both False and connection.is_closed and channel.is_closed are both True

**Comment by lukebakken** [comment]
Thanks! I have verified #1 using the attached code, and you can see in the transcript that this issue is fixed.

[producer.py.txt](https://github.com/pika/pika/files/1683701/producer.py.txt)

[transcript.txt](https://github.com/pika/pika/files/1683702/transcript.txt)

**Comment by vitaly-krugl** [comment]
Thanks @lukebakken. It would be awesome to have a test, so that if this ever breaks again we would catch it immediately. `#2` could be handy for it :).
