### ISSUE TITLE
Exception due to closed connection when sending frames

### ISSUE THREAD

**Issue by ayounes** [pika/pika#520]
I am using pika version 0.9.8.

I am sending messages every 20ms to RMQ using pika.  When I send a message I using this api:

data_connection = pika.BlockingConnection(pika.ConnectionParameters(host=RMQ, credentials = cred))

then inside the for loop I do some computation and data gleaning which takes about 20ms before calling

 data_channel.basic_publish(exchange='',
                                       routing_key=queue_name,
                                       body=msg,
                                       properties=pika.BasicProperties(delivery_mode = 2,) # make message persistent
                                       )

I have several of these programs writing to different queues. The one I am having problems with  sends messages that are larger than the rest len(msg) yields on average 1328, msg is json.  

  I see the following errors:

2015-01-07 13:49:23,779 18586 Attempted to send frame when closed
2015-01-07 13:49:23,779 18586 Attempted to send frame when closed
2015-01-07 13:49:23,780 18586 Attempted to send frame when closed
2015-01-07 13:49:23,780 18586 Closing connection (200): Normal shutdown
2015-01-07 13:49:23,780 18587 sample_task_worker: task processing and query time=3.42
2015-01-07 13:49:23,780 18586 Added: {'callback': <bound method BlockingConnection._on_connection_closed of <pika.adapters.blocking_connection.BlockingConnection object at 0x24204d0>>, 'only': N
2015-01-07 13:49:23,781 18586 Regular Sample Thread 3: 'NoneType' object has no attribute 'send'
2015-01-07 13:49:23,781 18586 Regular Sample Thread 3: Unexpected thread crash
2015-01-07 13:49:23,781 18586 Regular Sample Thread 3: Restarting thread after 10 seconds

Admittedly I have another thread also writing to the same queue, but I also see this issue happen when just this thread is running alone.

Any thoughts?

**Comment by gmr** [comment]
Are you doing one connection per thread? And are you blocking in any way? (long running queries, time.sleep, etc)

**Comment by ayounes** [comment]
I have one connection per thread, each thread uses the same style call I mentioned above, and the queries and processing time between calls to RMQ are about 20ms, so they are short.  The problem is intermittent, it does not happen all the time, but it happens frequently enough that it affects the throughput of the thread I mentioned.  

I am looking into reducing the message size to something smaller however, that is not the ideal solution I am looking for.

**Comment by gmr** [comment]
Since you're using BlockingConnection and an old version, I'm not sure how well you will fare. You might want to try [rabbitpy](https://pypi.python.org/pypi/rabbitpy) as it provides both thread-safety and a more pythonic way of interacting with RabbitMQ for non-asynchornous and threaded clients.

**Comment by ayounes** [comment]
I stand corrected, i did  pip list and I am running pika (0.9.13).

Anyway, I will try rabbitpy and let you know.  Hopefully it won't be a huge code change.

Thanks...Amro

**Comment by ayounes** [comment]
I made three changes in my code that seem to have alleviated the issue. It only occurs rarely when I first start the program but it does not seem to happen again.  Need to soak the code to make sure.

1.  Upgrade from 0.9.13 to 0.9.14
2. Reduced the average size of my messages.  Rather than send everything I need every time, I make sure that for that type of data, only the fields that will be used on the other end are sent.
3.  Imeplemented this after the basic_publish() call in my loop:


       last_process_event_call = 0  
       while(some_condition):
                <....snipped...>
                data_connection.basic_publish(<...snipped...>)
                if (time.time() - last_process_event_call) > 6:
                    data_connection.process_data_events()
                    last_process_event_call = time.time()

**Comment by gmr** [comment]
Thanks for the update
