### ISSUE TITLE
Multiple hosts in connection parameters

### ISSUE THREAD

**Issue by rmb938** [pika/pika#528]
Can you please add a way to give multiple hosts in the connection parameters. If my pika client is connected to a rabbitmq cluster it should be able to failover to the next node in the cluster. The current system does not allow for this functionality.

**Comment by rmb938** [comment]
It also seems like the callback for connection.add_timeout is not always called

**Comment by gmr** [comment]
Would be nice to support the address array support similar to how the Java client does this. Thanks for the suggestion.

**Comment by gmr** [comment]
Re "If x-cancel-on-ha-failover is given to a consumer and add_on_cancel_callback is set. The callback is not called on failover"

Which version of pika and RabbitMQ are you using? Which connection adapter?

**Comment by rmb938** [comment]
0.9.14 pika with the Select connection adapter

3.4.3 RabbitMQ

**Comment by gmr** [comment]
That should be working. My understanding of the HA part of the functionality is:

- A cluster exists with at least 2 nodes
- A mirrored queue that is declared on node 1 and mirrored to node 2
- A consumer exists on node 2 that passed ``{x-cancel-on-ha-failover: True}`` when issuing the ``Basic.Consume`` for said queue
- node 1 is shutdown, causing the owner of the queue to migrate to node 2
- Consumer on node 2 is sent a ``Basic.Cancel`` this happens, causing any of the cancellation callbacks to fire.

Is that your understanding as well?

**Comment by rmb938** [comment]
That is my understanding and testing it now I was actually doing something completely wrong so there isn't an issue.

**Comment by pmphnd** [comment]
Having multiple hosts in connection would be extremely useful for failover (in case loadbalancer is not an option). Looking forward.

**Comment by vitaly-krugl** [comment]
@rmb938, does the broker node close the connection following the consumer cancellations?

I don't think that it would be a good idea for pika to silently reconnect, because certain resources and operations on them are meaningful only on the channel/connection from which they were obtained. For example, it would not be meaningful to use a new channel to Ack a message that was received on a closed channel/connection.

**Comment by rmb938** [comment]
I think it just cancels the consumer I don't think it actually closes the connection or channel.

**Comment by vitaly-krugl** [comment]
Per https://www.rabbitmq.com/ha.html:
> they can consume with the argument x-cancel-on-ha-failover set to true. Their consuming will then be cancelled on failover and a consumer cancellation notification sent. It is then the consumer's responsibility to reissue basic.consume to start consuming again.

This talks about simply reissuing basic.consume to get going again, not reconnecting.  If the connection isn't dropped in this case, when would pika when use of multiple hosts in connection parameters? I think it would make sense only when the connection is dropped?

**Comment by rmb938** [comment]
Well the cancel on ha failover is called when the queue you're consuming on moves to another node due to failover. So if you have a cluster of node A,B and C and your client is connected to C but the queue is "living" on A, if node A fails the queue will get moved to B or C. When that happens node C will tell the client that the queue has failed over. 

However if the client is connected to C and that node fails it now has to manually reconnect to another node. The Java client will just try and connect to the next server in the list,reopen the connections (not the channels) and call the consumer cancel event to let the programmer to decide what to do at that point.

Since pika doesn't do this natively I just keep my own list of servers and when a consumer throws a connection exception I just have it try and open a connection to a server that is next in my list. So this feature is not really a large priority but it would be nice to keep in line on the way the official java client does things.

**Comment by vitaly-krugl** [comment]
@rmb938, makes sense. Thanks for the explanation!

**Comment by awasilyev** [comment]
@rmb938, could you please share your code for reconnecting to the list of rabbitmq hosts?

**Comment by rmb938** [comment]
Yea no problem. The code the it is part of is specific to my system so if the bellow code is not enough to figure it out please let me know.

```python
while not self.stopped:
            if self.connection is not None:
                self.logger.debug("Restarting IO Loop")
                if not self.connection.is_closed and not self.connection.is_closing:
                    self.connection.close()
            try:
                if self.connection is None:
                    self.connection = self.connect()
                else:
                    self.connection = self.connect(True)
            except AMQPConnectionError as e:
                self.logger.error("Rabbitmq Connection error " + e.message)
                continue
            if self.queue.startswith("amq."):
                self.queue = ""
            self.connection.ioloop.start()


def connect(self, reconnect=False):
        self.logger.debug("Creating connection")
        connection = self.rabbitmq.asyncconnection(self.on_connection_open, reconnect)
        connection.add_on_open_error_callback(self.on_connection_open_error)
        self.logger.debug("Connection created")
        return connection


def asyncconnection(self, callback, reconnect=False):
        if reconnect:
            self.paramIndex += 1
            if self.paramIndex >= len(self.connectionParams):
                self.paramIndex = 0
        connection = pika.SelectConnection(parameters=self.connectionParams[self.paramIndex],
                                           on_open_callback=callback, stop_ioloop_on_close=False)
        return connection
```
connectionParams in asyncconnection is a list of pika.ConnectionParameters

**Comment by koorgoo** [comment]
Seems to be an old feature request...
With growing acceptance of fault tolerance requirement nowadays it is highly desired to help a developer with its implementation. 
Vote up.

**Comment by luiscoms** [comment]
+1

**Comment by jonathanwminer** [comment]
+1

**Comment by pchristos** [comment]
+1

**Comment by avihoo** [comment]
+1

**Comment by luiscoms** [comment]
How can I use multiple hosts on `SelectConnection`?


Like:
```python
pika.SelectConnection(configs, self.on_connection_open)
```

**Comment by vitaly-krugl** [comment]
This feature is presently  only in pika's master branch for now and is
targeting pika v1.0.0 release (no ETA yet). For SelectConnection and other
non-blocking adapters, you would access it via the create_connection()
class method documented in
pika.adapters.base_connection.BaseConnection.create_connection() in pika's
master branch.

**Comment by lokeshh** [comment]
@vitaly-krugl I did like you said. Following is my configuration:

```
        conns = []
        credentials = pika.PlainCredentials(self.username, self.password)
        ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        ssl_context.verify_mode = ssl.CERT_REQUIRED
        ssl_context.load_cert_chain(certfile="cert.pem", keyfile="key.pem")
        ssl_context.load_verify_locations(cafile="cacert.pem")
        for node_with_port in self.nodes.split(','):
            node = node_with_port.split(':')[0]
            parameters = pika.ConnectionParameters(
                ssl_options=pika.SSLOptions(ssl_context),
                credentials=credentials,
                host=node,
                port=5671
            )
            conns.append(parameters)

        LOGGER.info('Connecting to rabbit')

        connection = pika.SelectConnection.create_connection(conns, self.on_connection_open)
```
The above code works but when I do `self._connection.ioloop.start()` I get following error:

```
AttributeError: 'AMQPConnectionWorkflow' object has no attribute 'ioloop'

```

**Comment by lukebakken** [comment]
@lokeshh did you call `connection.connect()` first? Please see example code [here](https://github.com/pika/pika/blob/master/examples/asynchronous_consumer_example.py#L363-L369)

**Comment by lokeshh** [comment]
@lukebakken Thank you. Sorry reading this late. I think this should work. I didn't get a chance to test it though as I switched to blocking connection.

**Comment by sathishbabu96** [comment]
@lukebakken I tried the way you mentioned here

> @lokeshh did you call `connection.connect()` first? Please see example code [here](https://github.com/pika/pika/blob/master/examples/asynchronous_consumer_example.py#L363-L369)

I am getting the following error:

`AttributeError: 'AMQPConnectionWorkflow' object has no attribute 'connect'`

**Comment by lukebakken** [comment]
@sathishbabu96 please don't reply to a closed issue. Post your question, as well as the code you are using, to the [`pika-python`](https://groups.google.com/forum/?pli=1#!forum/pika-python) mailing list. A single `AttributeError` only tells me that you have done something wrong in your code but I really don't have time to guess what that might be. Thank you.

**Comment by sathishbabu96** [comment]
@lukebakken Thanks for the quick reply. I will post my query to the mailing list.
