### ISSUE TITLE
SelectConnection passes reason_code=0 to on_close_callback upon failed socket connection

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#534]
SelectConnection passes `reason_code=0` to `on_close_callback` (that was registered via SelectConnection constructor) upon failed socket connection. This creates a problem for discerning between a user-initiated close vs. a socket connection failure.

`BaseConnection._handle_disconnect` has no method frame to pass to `self._on_connection_closed`, so `on_close_callback` ends up being emitted with `reason_code=0, reason_text='Not specified'`, which doesn't make sense for an error condition like lost socket connection.

**Comment by gmr** [comment]
@vitaly-krugl is this still the case with the updates to SelectConnection?

**Comment by vitaly-krugl** [comment]
@gmr: Yes, it seems to be still the case; see https://github.com/pika/pika/blob/3125c79b1b71e4e605e7a129c4d309b3edbb796f/pika/adapters/base_connection.py#L270-L274: it calls `self._on_connection_closed(None, True)`; and `_on_connection_closed(...)` calls `self._on_disconnect(reply_code, reply_text)`, but nothing in this case set up `self.closing`, so `reply_code` and `reply_text` are zero and some default reply_text.

**Comment by vitaly-krugl** [comment]
Fixed by PR #685
