### ISSUE TITLE
BlockingConnection publishing spotty

### ISSUE THREAD

**Issue by rmb938** [pika/pika#539]
Every now and then when I try and publish to a queue using the BlockingConnection the message never gets sent to rabbitmq. Doing a trace on rabbitmq does not show the message and it seems to only happen when the exchange field in basic_publish is an empty string.

I am using pika 0.9.14

**Comment by rmb938** [comment]
Actually seems like it was my fault. Was mixing channels from the SelectConnection

**Comment by vitaly-krugl** [comment]
@rmb938, there are a couple of reasons for this that I can think of:
1. When the exchange is an empty string, the broker will attempt to deliver the message to a queue with the queue name specified by the routing_key parameter that you passed to basic_publish. If a queue with that name (and on the same vhost) doesn't exist at the time of basic_publish, then the message would not be delivered.
2. In some testing that I was doing last night on using BlockingConnection to send a large number (e.g., 50000) of messages with very large message bodies (e.g., 100KB per message body), I discovered that messages were not being delivered upon return from basic_publish, and instead still remained in the BlockingConnection's outbound_buffer list. When you're experiencing this, try calling the `close()` method of the BlockingConnection instance that was used to send the missing messages and see if those messages show up.

Please reply here with your findings.

Best,
Vitaly
