### ISSUE TITLE
No Way To Check if BlockingConnection Generator Has Items

### ISSUE THREAD

**Issue by markcf** [pika/pika#544]
It would be good if there was a function for the BlockingConnection.consume Generator to check if it has items before calling consume, this way a program could avoid being blocked in the function if there are no items in rabbit.

I'll gladly write a pull request for this, but I'd like to check if there's a reason to not have this behaviour first.

I'm imagining something like this:

```
def getWaitingMessages(self):
    return len(self._generator_messages)
```

**Comment by vitaly-krugl** [comment]
Hi @markcf, are you thinking that you would call something like `getWaitingMessageCount()` and if it returned non-zero N you would then start a `consume()` loop and let it run only for N iterations and then break out to avoid blocking in the generator while waiting for the next messages to arrive? If so, you might end up with a poorly behaved polling-style application in terms of CPU consumption. You might be better off with something like the Twisted Connection or see if pika BlockingConnection is compatible with Gevent.

**Comment by markcf** [comment]
Hello,
That's essentially what I'm thinking.

Normally I'd agree with you and use an event driven system. 

For this specific project, performance isn't a huge concern. Especially since the messages in Rabbit tend to be a bit larger, so the time spent polling an in memory list is minimal compared to the time spent processing them.

 The priorities of this system are high reliability and easy maintenance. Polling avoids a lot of potential pitfalls (timing bugs come to mind) and is much simpler to debug if something does come up. In addition, it makes log messages easier to understand and makes the system generally simpler. 

For this project both options were evaluated, and polling came out on top.

I understand this is not the general case, and if the general opinion is that such a feature shouldn't be included in order to discourage polling based systems that is reasonable.

**Comment by gmr** [comment]
Merged your PR.
