### ISSUE TITLE
connect port 21, it won't raise timeout

### ISSUE THREAD

**Issue by yqnetwork** [pika/pika#551]
try:
    self.__connection = pika.BlockingConnection(pika.ConnectionParameters(
            host=self.__mq_host, port=21, virtual_host=self.__mq_virtual_host,
            credentials = credentials))
except Exception, ex:
    ....

When pika.ConnectionParameters port is set 21, 22, I test  this port by accident, I find it will not raise 
a timeout exception. The other ports work normally, raise a timeout exception. I know the 21
port is for ftp.But I think it's unnormal .

**Comment by gmr** [comment]
Could it be that something is listening on Port 21 and Pika's waiting for a response? Pika expects an AMQP server on the other side and doesn't try and detect improper protocols or put a timer on how long it should take to negotiate an AMQP connection.
