### ISSUE TITLE
SelectConnection gives WARNING "Unknown state on disconnect: 6" on connection.close()

### ISSUE THREAD

**Issue by robochat** [pika/pika#562]
When I shutdown my process by calling connection.close(), I always see a WARNING message in my logs

       WARNING -  ... -  Unknown state on disconnect: 6

I have tracked this down to the BaseConnection._adapter_disconnect() method (actually BaseConnection,_check_state_on_disconnect()) and found that connection_state = 6 means CONNECTION_CLOSING. This makes sense since BaseConnection._adapter_disconnect() is getting called *before* the Connection._on_disconnect() method which sets the connection_state as CONNECTION_CLOSED. 

It almost seems like in Connection._on_connection_closed() we should be disconnecting the adapter *after* we run Connection._on_disconnect() ie.

        # Invoke a method frame neutral close
        self._on_disconnect(self.closing[0], self.closing[1])

        # If this did not come from the connection adapter, close the socket
        if not from_adapter:
            self._adapter_disconnect()

But there are probably issues with swapping the order of the calls that I'm not aware of.

**Comment by vitaly-krugl** [comment]
@robochat, this change in Master should have addressed this issues: https://github.com/pika/pika/commit/294904ee13d34abcea23527e87dd48c991542760#diff-1a5308d8b684fdafac1f89e376e8933dR161

**Comment by robochat** [comment]
If I understand correctly, the key line is in base_connection._check_state_on_disconnect(self)
    elif not self.is_closed and not self.is_closing:
Yes, I think that should be enough. I will try to test it soon. Together with your change to the passing of (reply_code, reply_text) values: https://github.com/pika/pika/pull/537, we could start getting the proper shutdown messages now.
Thanks

**Comment by vitaly-krugl** [comment]
@robochat: yes, your understanding is correct. Please post the result of your testing. Thanks!

**Comment by vitaly-krugl** [comment]
@robochat, would you mind re-testing against master and closing the issue?. This should have been addressed as noted above.

Thanks,
Vitaly

**Comment by vitaly-krugl** [comment]
Fixed via https://github.com/pika/pika/commit/294904ee13d34abcea23527e87dd48c991542760#diff-1a5308d8b684fdafac1f89e376e8933dR161
