### ISSUE TITLE
BaseConnection._handle_ioloop_stop() would crash due to missing SelectConnectin.ioloop.stop

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#566]
This issue concerns PR #555: this triggers a bug in `BaseConnection._handle_ioloop_stop()` when it attempts to call `self.ioloop.stop()` here https://github.com/pika/pika/commit/e03c7adbb609f91e7523057a33c05817f096acad#diff-1a5308d8b684fdafac1f89e376e8933dR209

If confirmed, then in addition to the fix, it would be great to have a test for this code path.

**Comment by vitaly-krugl** [comment]
CC @wjps

**Comment by wjps** [comment]
Do you have a test case? Or do you just think there might be an issue?

ioloop.stop() is pushed through to the same method on the poller.

**Comment by vitaly-krugl** [comment]
@wjps, oops, sorry about that. I missed the `def __getattr__` in `IOLoop`. Closing the issue.
