### ISSUE TITLE
Memory leak: BlockingChannel._replies list grows forever

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#576]
RPC replies get added to `BlockingChannel._replies`, but never get purged, so it grows perpetually. Here is what it looks like after several calls to basic_publish and confirm_delivery:

```
In [130]: ch._replies
Out[130]: 
['Confirm.SelectOk',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Confirm.SelectOk',
 'Basic.Ack',
 'Confirm.SelectOk',
 'Basic.Ack',
 'Confirm.SelectOk',
 'Confirm.SelectOk',
 'Confirm.SelectOk',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack',
 'Basic.Ack']
```

**Comment by gmr** [comment]
Are you doing any processing of data events? You have to let the poor adapter breath, it will not unless you tell it to or let it catch up with itself.

**Comment by vitaly-krugl** [comment]
@gmr, I was using BlockingConnection, which should process data events on its own.

**Comment by gmr** [comment]
In principle I agree, but in a single thread with no background IO management, it can't with a big performance trade-off (which I was fine with, but users were not)

**Comment by vitaly-krugl** [comment]
`process_data_events()` gets called all over the place in BlockingConnection/BlockingChannel code and I leave `_force_data_events_override` at default (None), so it should not interfere with event processing in `_rpc()`, either:
```
        if force_data_events and self._force_data_events_override is not False:
            self.connection.process_data_events()
```

**Comment by vitaly-krugl** [comment]
I really don't see any code in the implementation that could possibly purge anything from the `BlockingChannel._replies` list.

**Comment by vitaly-krugl** [comment]
No longer an issue in the new SelectConnection-based implementation of BlockingConnection.
