### ISSUE TITLE
Sending large messages fails silently

### ISSUE THREAD

**Issue by paulinus** [pika/pika#582]
Sending a 200KB message with the following code does not raise any error, but message does not get to server. Messages smaller than 130KB work fine.
```
import pika

message_length = 200000
message = 'x' * message_length

parameters = pika.ConnectionParameters(XXX)
connection = pika.BlockingConnection(parameters)
channel = connection.channel()
channel.basic_publish(exchange='XXX', routing_key='XXX', body=message)
channel.close()
```

I've tried sending with another library to see check if the problem was the server. Sending it with this code works, so i'm assuming that server can handle that message size.
```
import amqp

c = amqp.connection.Connection(XXX)
ch = amqp.channel.Channel(c)
message = amqp.basic_message.Message('x'*200000)
ch.basic_publish(message, exchange=XXX, routing_key=XXX)
```

Can someone reproduce the error?
Thanks!
pau

**Comment by vitaly-krugl** [comment]
@paulinus, I don't see this problem in master at c7a72cdd4f5f7e1d692bf42943c9f3810f6bb1b7.

**Comment by paulinus** [comment]
You are right. The problem is solved in current master. Thanks @vitaly-krugl !
