### ISSUE TITLE
When channel.queue_bind fails to find the exchange... is the Connection is corrupted?

### ISSUE THREAD

**Issue by tonyennis** [pika/pika#583]
I wrote the code below to be a test consumer.  When I run the producer code first, it creates the exchange and the code below works fine.  However, if I run this code before the exchange is created, queue_bind() fails. This is unsurprising.  10 seconds later, we try again. And it fails again, but this time the exception is blank. Now something is wrong.  I started moving the code inside the ++/-- into the `try` block one line at a time, bottom to top. Once the `connection` line is moved in, the code works fine.

It would see that the failed bind to the exchange is corrupting/damaging the connection instance.

    def ermagerd():

        # ++
        connection = pika.BlockingConnection(pika.ConnectionParameters(config.poller['RABBIT_SERVER']))
        channel = connection.channel()
        result = channel.queue_declare(durable=False, exclusive=True)
        queue_name = result.method.queue
        # --

        waiting = True
        while waiting:
            print("Waiting is %s" % str(waiting))
            try:
                channel.queue_bind(queue=queue_name, exchange=config.poller['EXCHANGE'], routing_key=config.poller['ROUTING_KEY'])
                waiting = False    # yay!
                print("Successfully bound to the %s exchange" % config.poller['EXCHANGE'])
            except BaseException as e:
                print("Waiting for the exchange")
                print(str(e))
                time.sleep(10)

        channel.basic_consume(callback, queue=queue_name, no_ack=True)
        channel.start_consuming()

**Comment by vitaly-krugl** [comment]
@tonyennis, AMQP signals errors (exchange not found in your case) by closing the channel and including the error code and text message in the Channel.Close method. So, it's normal for the channel to close under these circumstances, but not the connection.

You need to provide additional information to help debug this, including a small **fully-functional** script that reproduces the issue, pika logs, and complete tracebacks for both exceptions. Also, describe your runtime environment, pika version, and anything else that might be helpful.

**Comment by tonyennis** [comment]
What's the best way to provide the info? Dump it into this page?

**Comment by vitaly-krugl** [comment]
I just added more info in my comment. And yes, dump the relevant info into a comment or the body of the issue.

**Comment by tonyennis** [comment]
I am incorrect. It is indeed the channel that's the issue.  Thanks for the help.  If it turns out to be more subtle, I'll open another issue and include full information.
