### ISSUE TITLE
UnboundLocalError: local variable 'read' referenced before assignment (Python 3) in SelectPoller.poll

### ISSUE THREAD

**Issue by ztane** [pika/pika#596]
There is a critical flaw in the [`poll`](https://github.com/pika/pika/blob/master/pika/adapters/select_connection.py#L320) function of `SelectPoller`.

If an `EINTR` exit occurs (and it **will** occur sooner or later), the `read, write, error` tuple is not assigned at all; neither would there be any exception being thrown, and the code crashes below with `UnboundLocalError: local variable 'read' referenced before assignment`.

Possibly at least each of these names should be assigned to an empty iterable by default, thus

    read = write = error = ()
    try:
         ....

It is to be noted that all Linux / Glibc-using Python versions prior to Python 3.5 are vulnerable to EINTR; in Python 3.5> Python ought to handle the EINTR instead.

**Comment by ztane** [comment]
Ironically this bug was introduced by @wjps [in an effort to make the SelectPoller to actually work](https://github.com/pika/pika/commit/7f91a684f4b8548ab18d9f2a3cd0d5f49fb60e3d#diff-69e7c8c211c62cdb127e8ab3324ce7c6R317)

**Comment by vitaly-krugl** [comment]
Good catch! This actually applies to the `poll` methods in **all** of the pollers. That section of code in all of the `poll` methods should either be written in a loop or it should allow all exceptions to be raised and then have a decorator to retry on EINTR. As a loop, it would look something like this:

```
    while True:
        try:
            read, write, error = select.select(self._fd_events[READ],
                                               self._fd_events[WRITE],
                                               self._fd_events[ERROR],
                                               self.get_next_deadline())
        except select.error as error:
            if error.errno == errno.EINTR:
                continue
            else:
                raise


CC @wjps

**Comment by vitaly-krugl** [comment]
And, come to think of it, `BaseConnection._handle_read` and `BaseConnection._handle_write` also need a loop like that around their `socket.recv` and `socket.send` calls.

CC @ztane @wjps

**Comment by vitaly-krugl** [comment]
PR #604 should fix this issue

**Comment by ztane** [comment]
604 is still buggy, needs fix :D

**Comment by vitaly-krugl** [comment]
Updated PR #604 to address @ztane's code review feedback.
