### ISSUE TITLE
basestring does not exist in python 3

### ISSUE THREAD

**Issue by beruic** [pika/pika#605]
in connection.py on line 211 we have:

    if not isinstance(host, basestring):

but basestring does not exist in python 3, so this throws a NameError.

**Comment by vitaly-krugl** [comment]
@beruic, is this in theory or during actual use of `connection.py` from master? The reason that I ask is that `connection.py` imports `basestring` from `pika.compat`, which redefines `basestring` here https://github.com/pika/pika/blob/9f7f24331c15ad8775d97b750f05322129b5c632/pika/compat.py#L14 for python 3.x as `basestring = (str,) `

**Comment by beruic** [comment]
This is during actual use. This is suficient to trigger it:

    #!/usr/bin/env python3

    import pika

    if __name__ == '__main__':

        parameters = pika.ConnectionParameters("localhost")
        

I'm on Ubuntu 15.04 using python 3.4.

**Comment by vitaly-krugl** [comment]
@beruic, would you mind helping debug why `basestring` from `pika.compat` is not having the desired effect?

**Comment by beruic** [comment]
Tell me what to do.

**Comment by vitaly-krugl** [comment]
@beruic, please add a comment with a complete traceback from this failure.

**Comment by beruic** [comment]
Running the above script, the output is:

    beruic@Skrumpbuntu:~$ ./test.py
    Traceback (most recent call last):
      File "./test.py", line 7, in <module>
        parameters = pika.ConnectionParameters("localhost")
      File "/usr/local/lib/python3.4/dist-packages/pika/connection.py", line 361, in __init__
        if host and self._validate_host(host):
      File "/usr/local/lib/python3.4/dist-packages/pika/connection.py", line 207, in _validate_host
        if not isinstance(host, basestring):
    NameError: name 'basestring' is not defined

**Comment by vitaly-krugl** [comment]
Do you have an import in your `pika/pika/connection.py` that is exactly like this the following?

```
from pika.compat import basestring, url_unquote, dictkeys
```

**Comment by vitaly-krugl** [comment]
@beruic, I suspect that the pika package that you're using is not pika from the tip of master that recently got python 3.x support. You're probably executing an older version of pika, perhaps inadvertently. When I need to uninstall an old package, I run the `pip uninstall <package name>` command multiple times until pip tells me that it can't find the package. This gets rid of it from multiple places, such as the user installation and system installation that I wasn't even aware existed, etc. Once I get rid of all of them, then I go ahead and install the new one. This avoids conflicts.

**Comment by everilae** [comment]
@beruic could you check what version of pika you are using, or describe how you installed it.

One way to check would be
```python
    >>> import pika
    >>> help(pika)
```

and look for *VERSION*. I second @vitaly-krugl that prolly you have an old version of pika which lacks PY3 support.

**Comment by beruic** [comment]
The pika package I get throgh pip is version 0.9.14. I installed it in a virtualenv through pycharm. I'll try with the latest version.

**Comment by beruic** [comment]
The issue is the version. It works with the newest version.

**Comment by vitaly-krugl** [comment]
@beruic, please close this issue. Python 3.x support is a new feature for the next release.

**Comment by Dmitry-N-Medvedev** [comment]
pika version: pika==**0.10.0**
python --version: **Python 3.5.1**

both are used from virtual environment.

the error persists:

```
Traceback (most recent call last):
  File "/home/dmitry/Documents/projects/cmi-services/tests/common/rmq/infra/test_rmq_infra.py", line 42, in test_recreate
    infra.recreate()
  File "/home/dmitry/Documents/projects/cmi-services/common/rmq/infra/__init__.py", line 141, in recreate
    self._connection = self.connect()
  File "/home/dmitry/Documents/projects/cmi-services/common/rmq/infra/__init__.py", line 96, in connect
    pika.ConnectionParameters(self.connectionParameters),
  File "/home/dmitry/Documents/projects/cmi-services/venv/lib/python3.5/site-packages/pika/connection.py", line 652, in __init__
    self.host = host
  File "/home/dmitry/Documents/projects/cmi-services/venv/lib/python3.5/site-packages/pika/connection.py", line 392, in host
    (value,))
TypeError: host must be a str or unicode str, but got <ConnectionParameters host=127.0.0.1 port=5672 virtual_host=cmi ssl=False>
```

**Comment by gmr** [comment]
@Dmitry-N-Medvedev your error is unrelated and is due to this:
```python
rmq/infra/__init__.py", line 96, in connect
    pika.ConnectionParameters(self.connectionParameters)
```
It appears that self.connectionParameters is already an instance of ``pika.ConnectionParameters``.

Pika 0.10.0 works fine with Python 3.5.1 (I use it heavily in production with this combination).
