### ISSUE TITLE
Implement acceptance tests for TwistedConnection adapter

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#616]
There are presently no acceptance tests for TwistedConnection adapter.

Here is an example of a basic test script from [python unittest framework](https://docs.python.org/2/library/unittest.html); the test method names need to begin with "test_" to be recognized by the framework; you can have helper/private methods with names that don't begin with "test_"; it's desirable to use test method names that are descriptive of what's being tested (long names are okay in these tests).

```
import unittest

class TestStringMethods(unittest.TestCase):

  def test_upper(self):
      self.assertEqual('foo'.upper(), 'FOO')

  def test_isupper(self):
      self.assertTrue('FOO'.isupper())
      self.assertFalse('Foo'.isupper())

  def test_split(self):
      s = 'hello world'
      self.assertEqual(s.split(), ['hello', 'world'])
      # check that s.split fails when the separator is not a string
      with self.assertRaises(TypeError):
          s.split(2)

if __name__ == '__main__':
    unittest.main()
```

Definitely use unittest's specialized `self.assert*` methods rather than python's builtin `assert`. Unittest's specialized assertion methods output useful info when assertions fail.

The framework instantiates a fresh instance of the test class for each test method. Don't define a constructor in your test class; if you need to initialize something common for each test method, then override the [def setUp(self)](https://docs.python.org/2/library/unittest.html#unittest.TestCase.setUp) framework "fixture" method and do it there.

There is a lot of flexibility for structuring these tests: you can have a dedicated test class for each test method (as in https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py) or multiple test methods per test class (as in the above example). It's up to you.

The Twisted adapter to be tested is in https://github.com/pika/pika/blob/master/pika/adapters/twisted_connection.py. There are actually two adapters there: `TwistedConnection` and `TwistedProtocolConnection`. Ideally, both need to be tested, but practically just start with the one that you're most comfortable with. You would create tests for `TwistedConnection` in `pika/tests/acceptance/twisted_connection_test.py` and similarly for `TwistedProtocolConnection` in  `pika/tests/acceptance/twisted_protocol_connection_test.py`.

At the beginning of each test method, register a test timeout timer of 10 seconds with twisted ioloop that invokes a method in your test class that in turn calls `self.fail('test timed out')`. In the unittest framework, the `setUp` "fixture" is a handy way to do it for each test method if you will have multiple test methods in a single test class. `setUp` instance method gets called by the framework just before each test method. For example:

```
class _TwistedTestCaseBase(unittest.unittest.TestCase):
    def setUp(self):
        """This method is called by unittest framework on a fresh test class instance just before calling
        a test method; a fresh test class instance is constructed by the framework for each test method
        """
        #1. register a 10-second test timeout timer with twisted ioloop that will call _on_test_timed_out;
        #     this should be the same ioloop that will be used by the test code.
        #2. call self.addCleanup to schedule cancellation of the test timeout timer; the cleanup
        #     callback will be called by the unittest framework after the test method exits.

    def _on_test_timed_out(self):
        self.fail('test timed out: %r' % (self,))


class TestTwistedConnection(_TwistedTestCaseBase):
    ... your test method(s) here
```

Each test is a granular basic usage workflow; e.g.,
1. test method `test_connect_and_close`: initiate the connection sequence, wait for the expected callback (or equivalent) that indicates successful connection establishment; if you get the "connection closed" or "connection error" callback while waiting for connection to complete, you need to fail the test by calling `self.fail('some useful message')`; after connection establishment completes successfully, initiate connection close and wait for the corresponding connection-closed callback; once you get the "connection closed" callback, then do what's needed in twisted to allow the ioloop to unblock so that the test method may return.
2. test method `test_open_channel_and_close`: similarly to `test_connect_and_close`, create connection and open channel; verify that the expected callbacks (or equivalent) were called and fail if an unexpected callback happens first; close the channel and verify the expected callback. Allow the test method to return.
3. test method `test_publish`: open connection and channel; create a queue (use self.addCleanup to register a callback that deletes that queue); publish a message (exchante='', routing_key='queue name'); read the message back and verify the body and other attributes of the message; using `basic_get` is probably the simplest way to read the message in this test method.
4. test method `test_basic_consume`: open connection and channel; create  queue;  publish a message; use `basic_consume` to consume the message; verify message body and other attributes.

https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py is an example of an acceptance test suite for the pika blocking adapter. You can find comparable test methods there and perhaps borrow the code for message validation, etc. Note the use of `self.addCleanup` immediately after creation of resources to schedule their destruction and the use of uuid to avoid collisions, especially when tests are executed in parallel. The `self.addCleanup` callbacks are called by the test framework after the test method exits. `self.addCleanup` is also very handy for scheduling things to be unregistered at the end of each test method's execution: for example, this would be handy for canceling the test timeout timer.

**Comment by vitaly-krugl** [comment]
Is there a Twisted user in the community that could take on this task?

**Comment by lukebakken** [comment]
Thanks for noticing this open issue @abompard
