### ISSUE TITLE
Attempt to gracefully close the SelectConnection after ioloop.stop() causes an exception

### ISSUE THREAD

**Issue by mpolk** [pika/pika#620]
I am writing a multithreaded daemon, which consumes the messages from the RabbitMQ server in asynchronous way. It uses a SelectConnection opened in the child thread to get and process the messages. When the time comes to go down, the main thread should somehow signal to the message processing thread about  this. At this time the message consuming thread is being inside its IOLoop. AFAIK the only thread-safe (more or less) way to interrupt an IOLoop is to call its stop() method. So the main thread does this:
```python
self.mqConn.ioloop.stop()
```
 after which there are two options:

1) Simply terminate the consuming thread immediately after it leaves IOLoop. My daemon feels good in this case, but the RabbitMQ complains:
```
=WARNING REPORT==== 30-Jun-2015::14:34:38 ===
closing AMQP connection <0.11146.9> (127.0.0.1:35725 -> 127.0.0.1:5672):
connection_closed_abruptly
```
Probably it is not *very* bad, but it would be better to avoid this. So I try the next options:

2) I copy-paste all this wonderful spaghetti initialization/termination code from the ["Asynchronous Consumer Example"](http://pika.readthedocs.org/en/0.9.14/examples/asynchronous_consumer_example.html).

Then I use the following sequence to enter IOLoop and to exit from it:
```python
self.mqConn.ioloop.start()
self.mqChannel.basic_cancel(callback=self.onCancelled, consumer_tag=self.mqConsumerTag)
self.mqConn.ioloop.start()
```
in hope that `basic_cancel` will help to terminate the connection gracefully. But the execution does not even reach all these wonderful callbacks. I get an exception directly in the `basic_cancel` call:

```
Exception in thread TelephonyMonitor:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/mpolk/stat-daemon/TelephonyMonitor.py", line 34, in run
    self.mqChannel.basic_cancel(callback=self.onCancelled, consumer_tag=self.mqConsumerTag)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 180, in basic_cancel
    {'consumer_tag': consumer_tag})] if nowait is False else [])
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 1046, in _rpc
    self._send_method(method_frame)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 1057, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1503, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1490, in _send_frame
    self._flush_outbound()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 73, in _flush_outbound
    self.ioloop.poller._manage_event_state()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 390, in _manage_event_state
    self.event_state)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 183, in update_handler
    self.poller.update_handler(fileno, events)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 427, in update_handler
    self._poll.modify(fileno, self.events)
IOError: [Errno 2] No such file or directory
```

What is especially insulting that the example code itself runs on my system well and terminates gracefully. However it uses a plain KeyboardInterrupt exception to interrupt its IOLoop and does not call ioloop.stop(). I believe this is a main reason why it does not suffer from my problems. Unfortunately I cannot do this way because of the multithreadness of my program.

**Comment by gmr** [comment]
Pika is not thread safe. Your best bet is to run a IOLoop per thread and never let any context of pika cross threads.

**Comment by mpolk** [comment]
Yes I know. But does not it mean that:
1) since ioloop.start() blocks the calling thread
2) and since any other thread should not even touch this ioloop,
therefore, any pika consumer should live forever?

I understand, some ways to stop this eternal consuming still exist:

1) for example, send "Terminate!" message from the parent to the specially arranged exchange, so that RabbitMQ will return it to the consuming thread, it will obey and terminate

2) apply "kill -9" to entire process with all it threads, consumers and ioloops

3) unplug the server from the outlet

4)...

Any of this methods will probably stop the consumer, but fixing ioloop.stop() seems to be a better way. This call is obviously designed to serve this purpose, and some recent attempts to make it work may be found [right in this repository](https://github.com/pika/pika/issues/548).

**Comment by vitaly-krugl** [comment]
@mpolk, SelectConnection's `ioloop.stop` is thread-safe as of pika v0.10.0. Please verify.

**Comment by mpolk** [comment]
Thank you, I will try it.

2016-01-13 0:26 GMT+02:00 vitaly-krugl <notifications@github.com>:

> @mpolk <https://github.com/mpolk>, SelectConnection's ioloop.stop is
> thread-safe as of pika v0.10.0. Please verify.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pika/pika/issues/620#issuecomment-171079997>.
>



-- 
С уважением,
Дм.Степаненко, сист.админ. "Сателлит Сервис"
ICQ: 112689047 тел.: +38(050)47-32-118

**Comment by vitaly-krugl** [comment]
Per my earlier comment, SelectConnection's ioloop.stop is thread-safe as of pika v0.10.0, so closing the issue. Thank you for reporting.
