### ISSUE TITLE
BlockingConnection ignores heartbeat_interval?

### ISSUE THREAD

**Issue by edmcman** [pika/pika#622]
When I run:

    #!/usr/bin/env python
    import pika
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost', heartbeat_interval=0))
    channel = connection.channel

I see:

    DEBUG:pika.connection:Creating a HeartbeatChecker: 580

It's like the heartbeat_interval is just ignored.

**Comment by gmr** [comment]
What version are you running? You might want to try pika from master. We're about to tag 0.10.0dev0 as a pre-release for pypi.

**Comment by edmcman** [comment]
I just installed from pip... 0.9.14

**Comment by gmr** [comment]
K.. yeah I'd try pika master -- BlockingConnection has been rewritten to be less *buggy* than 0.9.14.

**Comment by edmcman** [comment]
Ok, will try it now

**Comment by edmcman** [comment]
Seems to work, thanks.  I did notice that specifying a heartbeat_interval higher than the server's recommended value results in the server's value being used.  Is this correct?  (Doesn't effect me either way -- I just thought it was odd)
