### ISSUE TITLE
Many messages were not published after the program exit 

### ISSUE THREAD

**Issue by pfreixes** [pika/pika#623]
Next snippet shows one example used to test other stuff not related with this issue, but I came across with some issue because of that. Using the next script not all messages are at last published.

```python
import pika

# publish one message in each queue, the order doesn't matter
connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()
for i in range(0, 1000):
    channel.basic_publish('test.concurrence',
                          'test.{}'.format(i),
                          "%1.5f" % time.time(),
                          pika.BasicProperties(content_type='text/plain', delivery_mode=1))
```

It just publishes 1K messages and finishes the program. When I ran this code and I tried to find out if all messages were delivery to each queue - where each queue is bound to the exchange using the topic test.#num_queue - I realized that not all messages where published. Next snippet shows the command used to check that:

```bash
$ python publisher.py
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
37
$ ./purge.sh
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
1000
$ python publisher.py
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
17
```
The number of queues that have no a message were randomly, and that point let me thought that it would be a bug in Pika.

Then I changed the previous code and I added a kind of synchronization method where it tries to get the process alive for an amount time using the sleep command. Next snippet shows this change:

```python
import pika
import time

# publish one message in each queue, the order doesn't matter
connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
channel = connection.channel()
for i in range(0, 1000):
    channel.basic_publish('test.concurrence',
                          'test.{}'.format(i),
                          "%1.5f" % time.time(),
                          pika.BasicProperties(content_type='text/plain', delivery_mode=1))

time.sleep(10)
```
 
After that I ran the code again, the queues were purged properly, and all messages were published rightly as you can see into the next output command:

```bash
$ python publisher.py
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
0
$ ./purge.sh
$ python publisher.py
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
0
```

**Comment by vitaly-krugl** [comment]
@pfreixes, you're probably using the official 0.9.14 release. You can work around it by forcing the flushing of output buffers via a synchronous command such as a passive queue declare. This problem should be fixed in pika master, which will be part of pika 0.10.0. Please try it from pika master.

**Comment by pfreixes** [comment]
In fact I got the master yesterday and this is the version used  where I got this issue

```bash
$ pip freeze
pika===0.10.0p0
```

**Comment by vitaly-krugl** [comment]
@pfreixes: Thanks for the info; I will look into it later today.

**Comment by vitaly-krugl** [comment]
@pfreixes, here is what must be happening, and it's not a bug in pika: When you publish a bunch of messages without publisher acknowledgements, they get queued up in the socket buffer; after the app exits, the operating system (kernel) continues to deliver the content of the socket buffer to the destination (RabbitMQ broker); it will take some time to flush the socket buffer.

Try calling `channel.close()` instead of `time.sleep(10)`; the `channel.close()` call will synchronously flush the socket buffer and complete when Channel.CloseOK is received from the broker.

**Comment by pfreixes** [comment]
@vitaly-krugl it helps a lot. Thanks.

**Comment by gmr** [comment]
Also know that using time.sleep in your code with Pika will result in the python interpreter stopping and no actions taking place at all.

**Comment by pfreixes** [comment]
@gmr obviously Python interpreter do almost nothing when the sleep is called but I disagree with one thing, that I was looking for using this sleep was trigger the timeouts related with the buffers beyond the user land. 

Think for example with the tcp_nodelay [1] option or other optmitzations that could leave some packages still to be sent. 

In fact there is no reason to think that the close, without make the `channel.close()`, should get the same behaviour. W

[1]

**Comment by gmr** [comment]
Well, Channel.Close is a synchronous RPC call to the RabbitMQ server while Basic.Publish is not. You'll not return from Channel.Close until RabbitMQ has received all of the publish frames. My point is time.sleep will prevent Pika's async underpinnings from doing anything to make sure your messages get anywhere.

**Comment by pfreixes** [comment]
Ahhh I thought that publish was syncron as well, that was my mistake. I will try to remember that for future uses.

**Comment by gmr** [comment]
You can make it sync for a cost (performance penalty) by enabling publisher confirmations or using transactions.

**Comment by vitaly-krugl** [comment]
Gavin, to be true to the blocking nomenclature, the new BlockingConnection/BlockingChannel implementation always flushes `Connection.outbound_buffer` to the socket before returning control from any of the sending methods. In @pfreixes's case, many of the messages were still in the kernel's socket buffer and should eventually reach RabbitMQ broker, even if the app exited immediately after stuffing them all into the socket.

@pfreixes, if you block somewhere in your code outside of pika (or call time.sleep(x), which is equivalent), then things like heartbeat processing will not happen in BlockingConnection and RabbitMQ will eventually drop your connection (depending on heartbeat settings). If you need to call `time.sleep(x)`, you may call `BlockingConnection.sleep(x)` instead to permit pika to process heartbeats, etc. And there is also `BlockingConnection.process_data_events(...)` that you may call periodically, if needed.

**Comment by vitaly-krugl** [comment]
For example, if you execute the following script, all 100,000 messages will eventually show up in the queue "test" (assuming it exists). However, I personally prefer to gracefully close the channel/connection.

```
from pika import BlockingConnection


def main():
  ch = BlockingConnection().channel()

  for i in xrange(100000):
    ch.basic_publish("", routing_key="test", body="message-%s" % (i,))


if __name__ == "__main__":
  main()
```

**Comment by gmr** [comment]
I meant sync with RabbitMQ via AMQP, not sync with the socket.

**Comment by vitaly-krugl** [comment]
Got it, thanks for the clarification.

**Comment by pfreixes** [comment]
@gmr I was thinking at socket level about async and sync, not in use transactions or confirmation delivery at amqp protocol level.

@vitaly-krugl obvsiously the code was only a test and the sleep was putted there to reach some kind of flush, and the most important it worked for that test. 

The point here is that I used te script made by @vitaly-krugl and I ran the same test, and it appears to have the same issue, when the channel is not closed explicitly the messages already sent aren't the 1K messages that we should expect. Have a look to that script just a bit modified to fit into my test environment

```python
 from pika import BlockingConnection


def main():
  ch = BlockingConnection().channel()

  for i in xrange(1000):
    ch.basic_publish("test.concurrence", routing_key="test.{}".format(i+1), body="message-%s" % (i+1,))


if __name__ == "__main__":
  main()
```

And here different executions of this test

```bash
$ python publisher_2.py
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
221
$ ./purge.sh
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
1000
$ ./rabbitmqadmin.py list queues name messages | grep "test." | grep " 0 " | wc -l
503
```

May be I'm missing something but the point here is the buffers are not already flushed or something like that.

**Comment by vitaly-krugl** [comment]
@pfreixes, the side-effects that you're seeing are normal for how the operating system supports TCP/IP sockets. Immediately after `python publisher_2.py` completes, some of the messages are still in the kernel's socket buffer, so RabbitMQ hasn't received them all yet, and it most likely explains why you see 221 instead of 0. When you call `./purge.sh`, it purges only what's in the queues at this instant, but the remaining messages from kernel's socket buffer continue to be delivered to RabbitMQ, which most likely explains your 503 result above.

Try waiting a few seconds after calling `python publisher_2.py`. Start calling `./rabbitmqadmin.py`, etc. after several seconds elapsed. If you still don't get the expected results, please try to debug the issue. If you still need help with it, please create a **complete** simple-as-possible test that reproduces the problem that you're seeing and attach the test to this github issue.

**Comment by pfreixes** [comment]
@vitaly-krugl and  @gmr finnally I've found out the issue, this is a kind of side effect because of rabbitmq. I dont know if it is a really bug but the behavior is a bit weird.

When the channel is not properly closed by the client, Rabbitmq might drop the last packages sent by the snippet used in these tests. I realized now about that because, first I can confirm that all tcp packets are already sent by the client until the last FIN tcp package and lowering the number of messages to send until 200 hundred I saw that the messages that always can be missed are the last ones. For example:

```bash
| test.189 | 0        |
| test.190 | 0        |
| test.191 | 0        |
| test.192 | 0        |
| test.193 | 0        |
| test.194 | 0        |
| test.195 | 0        |
| test.196 | 0        |
| test.197 | 0        |
| test.198 | 0        |
| test.199 | 0        |
| test.200 | 0        |
``` 
Remember that the script send each message in a ordred way, starting from 1 until N - where for this lasts tests I used 200. Threfore only the last messages are affected.

This is a random behavior, and it explains why the `sleep` worked to remove this side-effect. Rabbitmq looks to publish the messages in a kind of burst way, and when the time elapsed between the last messages and the disconnection of the client - without the properly `close` - the chances to get this side-effect are inversely proportional.

IMHO the destructor of the channel could deal with those situations where the user has not close the channel "by hand".

**Comment by vitaly-krugl** [comment]
@pfreixes, thanks for the info. This sounds like it could be an issue in RabbitMQ. Would you mind posting it on rabbitmq-users google group?

**Comment by pfreixes** [comment]
@vitaly-krugl done, even you should consider to make the close of the channel by the destructor to avoid this behavior.

**Comment by pfreixes** [comment]
@vitaly-krugl Just to give more information and close it at last. Rabbitmq guys says that the only way to make sure that the tcp buffers are properly read is using the properly channel close, follow this thread [1].

Therefore the close of the channel operation have to be considered to put it into the destructor to avoid this side-effect.

[1] https://groups.google.com/forum/#!topic/rabbitmq-users/7lMUnkS1ssU

**Comment by gmr** [comment]
There's no guaranteed way to make class destructors (object.__del__) work properly. The invocation of them is up to the interpreter's gc and relying on them would make pika more opinionated than it should be (imo). FWIW [gmr/rabbitpy](https://github.com/gmr/rabbitpy) is more opinionated on these things and when you use the context manager, will shutdown the channel and connection for you.

http://stackoverflow.com/questions/6104535/i-dont-understand-this-python-del-behaviour has a good answer describing what I'm referring to re object.__del__

**Comment by pfreixes** [comment]
As I can read, I did not realize about this situation before you explained it, leaving aside the none deterministic use of the `__del__`,  the main issue can be overcome just using weak references. Expained also in the same stackoverfow thread [1] by the author of the question.

[1] http://eli.thegreenplace.net/2009/06/12/safely-using-destructors-in-python/

**Comment by vitaly-krugl** [comment]
Thanks for your follow-up @pfreixes!
