### ISSUE TITLE
Release the next major version

### ISSUE THREAD

**Issue by dellis23** [pika/pika#625]
When's the next major version release planned?  We were having a lot of problems with some of the issues reported at high concurrency, and updating to 0.10.0b1 seemed to fix it all.  This is less of a complaint and more of a "hey, that's awesome, everyone should get this by default!"

**Comment by gmr** [comment]
0.10.0b1 is on pypi as a pre-release and barring any major issues with this or subsequent pre-releases, 0.10.0 will be released on July 27th.
