### ISSUE TITLE
Socket Error handling problematic

### ISSUE THREAD

**Issue by billbr** [pika/pika#631]
We have a complex application that keeps failing due to unhandled socket errors. I have been able to build a simple case to reproduce the issue. I have used the sample select consumer and select publisher from the readthedocs examples. The ExamplePublisher has been modified to read a queue and publish any message that shows up. I have set the heartbeat interval to 10 seconds and then wait 20+ seconds between publishes. This creates a socket closure.  Pika processes the error and cleans up the connection (destroying my timeout scheduled for connection restart).  

Here are the log messages from the critical part:
INFO       2015-07-23 08:25:35,727 pika_publisher                 enable_delivery_confirmations        258 : Issuing Confirm.Select RPC command
DEBUG      2015-07-23 08:25:35,733 pika.channel                   _rpc                                 1036: Adding in on_synchronous_complete callback
DEBUG      2015-07-23 08:25:35,734 pika.callback                  add                                  152 : Incremented callback reference counter: {'callback': <bound method Channel._on_synchronous_complete of <pika.channel.Channel object at 0x7ff72ac6fad0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 5}
DEBUG      2015-07-23 08:25:35,734 pika.channel                   _rpc                                 1041: Adding passed in callback
DEBUG      2015-07-23 08:25:35,735 pika.callback                  add                                  152 : Incremented callback reference counter: {'callback': <bound method Channel._on_selectok of <pika.channel.Channel object at 0x7ff72ac6fad0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 5}
DEBUG      2015-07-23 08:25:35,737 pika.adapters.select_connection poll                                 477 : Calling <bound method SelectConnection._handle_events of <pika.adapters.select_connection.SelectConnection object at 0x7ff72ac6f5d0>>

=== pika sees socket is closed here when trying to send a frame ===
ERROR      2015-07-23 08:25:35,738 pika.adapters.base_connection  _handle_error                        279 : Socket Error on fd 5: 32

WARNING    2015-07-23 08:25:35,739 pika.adapters.base_connection  _check_state_on_disconnect           145 : Socket closed when connection was open
DEBUG      2015-07-23 08:25:35,741 pika.callback                  add                                  161 : Added: {'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x7ff72ac6f5d0>>, 'only': None, 'one_shot': True, 'arguments': None, 'calls': 1}
WARNING    2015-07-23 08:25:35,742 pika.connection                _on_disconnect                       1284: Disconnected from RabbitMQ at 15.244.209.6:8080 (0): Not specified
DEBUG      2015-07-23 08:25:35,743 pika.callback                  process                              217 : Processing 0:_on_connection_closed
DEBUG      2015-07-23 08:25:35,744 pika.callback                  process                              231 : Calling <bound method ExamplePublisher.on_connection_closed of <ExamplePublisher(test_publisher, started 140699551250176)>> for "0:_on_connection_closed"
WARNING    2015-07-23 08:25:35,757 pika_publisher                 on_connection_closed                 104 : Connection closed, reopening in 5 seconds: (0) Not specified
ERROR      2015-07-23 08:25:35,758 pika.adapters.base_connection  _handle_events                       305 : Error event 29, None
CRITICAL   2015-07-23 08:25:35,758 pika.adapters.base_connection  _handle_error                        255 : Tried to handle an error where no error existed

There are two issues here:
1. Pika does not cleanly handle the socket issues or provide a simple mechanism to recover from them.
2. Pika fails to carry the necessary metadata to handle the error in the _handle_events/_handle_error methods to correctly reflect what error actually occurred.

At this point we are having to wrap large amounts of error handling around pika to handle these conditions that should be invisible to us.

Suggested approach to a fix:
Anytime the socket gets closes for any reason (not just a few), have a parameter that says "attempt to autostart the socket" and a registed callback for the error code to get a boolean from the publisher indicating whether or not to try to recover and continue.

If I get some more time, I will try to suggest a patch/fix that has been tested.

**Comment by vitaly-krugl** [comment]
@billbr, this should be addressed by PR #685
