### ISSUE TITLE
Data packing of 'long' integers in python 3 does not work

### ISSUE THREAD

**Issue by bbuchanan-bcs** [pika/pika#640]
In Python 3, the data packing does not correctly handle int types larger than 32 bit. https://github.com/pika/pika/blob/master/pika/data.py#L118

This code will never trigger on Python 3 unless a user explicitly imports are uses pika.compat.long (https://github.com/pika/pika/blob/master/pika/compat.py#L59)  to wrap all 64 bit integers. The unit tests are passing because that is exactly what the unit tests do :)

I would recommend using bounds checking to determine the size of the integer if it is an 'int' type and pack accordingly. A decent example is the pika-python3 libraries solution, https://github.com/renshawbay/pika-python3/blob/python3/pika/data.py#L50

**Comment by vitaly-krugl** [comment]
CC @ztane

**Comment by everilae** [comment]
Have not made a pull req as of yet, but would https://github.com/everilae/pika/blob/datafixes/pika/data.py#L124 address the issue? The whole branch would require some major eyeballing, since it rewrites a lot of data handling, but is based on the current master of pika/pika pretty much.

**Comment by gmr** [comment]
For the next **major** version of pika (1.0.0), we'll be moving to (pamqp)[https://github.com/gmr/pamqp] which impacts much of this (#645).

That being said, this should be fixed for the 0.10 branch with as few changes as possible.

It'd also be code to get a unit test in that covers the failing case.

**Comment by lukebakken** [comment]
Resolved by #888
