### ISSUE TITLE
How to use delay message

### ISSUE THREAD

**Issue by singpenguin** [pika/pika#643]
RabbitMQ Delayed Message Plugin
https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/

How to use delay message in pika? Is there some example?

Thanks

**Comment by gmr** [comment]
You'd use [``Channel.bash_publish``](http://pika.readthedocs.org/en/0.10.0/modules/channel.html#pika.channel.Channel.basic_publish) and set the values in the [headers ``property``](http://pika.readthedocs.org/en/0.10.0/modules/channel.html#pika.channel.Channel.basic_publish) as they demonstrated in the [readme](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/#usage)

```python
channel.basic_publish(exchange='test',
                      routing_key='test',
                      body='Hello World!',
                      properties=pika.BasicProperties(content_type='text/plain',
                                                      delivery_mode=1,
                                                      headers={'x-delay': 5000}))
```
