### ISSUE TITLE
No any error information in case of unexpected interrupt connection

### ISSUE THREAD

**Issue by morden2k** [pika/pika#648]
Hi guys,

I do not have any information about any errors in pika if connection closed unexpectedly with error (I mean network connection). Connection closes like we do not have any errors:

1) connect to rabbit mq (SelectConnection)
2) unplug Ethernet

Result of pika.SelectConnection::on_close_callback :

    reply_code = 0
    reply_text = 'Not specified'

Like ALL IS OK. May be I did not noticed but I did not find any information in documetation how to detect error information on case of unexpected close (e.g. callbacks, veriables)

Is it posible to have any information why connection closed unexpectedly? How I see by source code (may be I something lost) on these cases you cleanup any information about last errors, closes socket and reset all befere call of callback :( If this is not posible will this posible in future? 

    BaseConnection:

        def _on_connection_closed(self, method_frame, from_adapter=False):

            if method_frame and self._is_connection_close_frame(method_frame):
                self.closing = (method_frame.method.reply_code,
                                method_frame.method.reply_text)

            if self.heartbeat:
                self.heartbeat.stop()

            # after this no any info about socket error
            # since: "self.socket = None" on _adapter_disconnect
            # without any saving of last error information :(((((((((((((
            #
            if not from_adapter:
                self._adapter_disconnect()  

            self._on_disconnect(self.closing[0], self.closing[1])

How I see by logger, you have like this:  "WARNING:pika.adapters.base_connection:Socket closed when connection was open" but no any callbacks or variables where I can get this error information without parsing of logger output.

**Comment by gmr** [comment]
When you have a handler for on_close_callback, when it's closed closed due to a socket error, you will get 0 like you saw. If you're closed by RabbitMQ, you'll get the info you send. 

It seems like it should be reasonable to add the socket exception message in the reply_text variable in the callback though.

**Comment by morden2k** [comment]
Sorry I do not understand you. You just write what I write. What do you mean on "add the socket exception message in the reply_text variable in the callback though."? As I said is reply_text is 'Not specified' and reply_code=0. Yes, I know that on_close_callback uses for process close codes from RabbitMQ, not socket. But I did not find how to retrive any error information about closing with error.

For example, in WinAPI we have function GetLastError which allow to get last error code in last call. And it is not depends in which level error occurred. It just return last error and allow to know what is going on on call. E.g. when you open sharing file this is can be FS level problem, this is can be CIFS level problem and this is can be socket level problem since you uses network for open file. In any case you will have error information.

But how I see (as I said may be I missed something) in pika it is not possible to know reason what is going on unexpected close with error. No any errors, no any exceptions :-( I just can detect error using my additional internal variable like “this is manual close” (if false) and set is true if this is was manual/expected close. But this is do not resolve problem – I do not have reason what is wrong. What I found that is you just display warning "WARNING:pika.adapters.base_connection:Socket closed when connection was open". But hooking and analyze logger this is idiocy. This is only one way to know error which I know on current moment.

Do you really not return or not save in variable any error information in library (in case if this is not RabitMQ level)? I just want to know this answer. And answer to question - if no will and when this possible in future? And also if no - could you propose workaround for retrieve error info (I do not specialist in python, I just uses it for make some control/testing scripts for my services)?

If you do not want to have/process some error codes (or raise exceptions for for this situation) in your lib, some string will enough for me like get_last_error_string as minimum (“Socket closed when connection was open” which you displays in log).

**Comment by morden2k** [comment]
P.S. IMHO 'Socket closed when connection was open' is not correct message when you unplug ethernet or have crash of app on outside endpoint. How I remember must be like "Connection reset by peer" or something this which usualy uses in sockets on this case (when TCP RSP packet received without FIN-ACK). You can retrieve this string and error code from socket library. I did not work with sockets in python but I'm sure (more than confident) that socket library allow to retrive error information and error codes.

**Comment by gst** [comment]
I agree with @morden2k 

I actually ran into a similar situation when testing pika : 

first of all we have to :  `sudo iptables -D INPUT -p tcp --destination-port amqp  -j DROP`

then doing a pika.BlockingConnection() results in a ConnectionClosed() instance be raised.

First problem is that no message is associated/attributed with this ConnectionClosed instance, so my first attempt to log it gave me nothing valuable : 

```
try:
    pika.BlockingConnection()
except Exception as exc:
    print(exc)  # nothing / empty string
```

So I had then to log the exception class to know which kind of exception it was.

But pika itself correctly reports the good problem (timeout) : 

```
2015-10-08 15:42:25,567 - pika.adapters.base_connection - INFO - Connecting to 127.0.0.1:5672
2015-10-08 15:42:25,818 - pika.adapters.base_connection - ERROR - Connection to 127.0.0.1:5672 failed: timeout
2015-10-08 15:42:25,820 - pika.connection - WARNING - Could not connect, 0 attempts left
```

but on my side I so get the ConnectionClosed instance with no / empty message.

```
2015-10-08 15:42:25,822 - myapp - ERROR - BlockingConnection() failed: ConnectionClosed:
```

would it be possible : 

1) to get another exception class in this case, say ConnectionTimedout ?
2) also would it be possible for any of the pika exceptions instances to have a not empty message associated to each of them ?

**Comment by gst** [comment]
douh..

> first of all we have to : sudo iptables -D INPUT -p tcp --destination-port amqp -j DROP

s/-D/-A/

copied the bad line from my history ;)

**Comment by vitaly-krugl** [comment]
PR #685 should address this issue.
