### ISSUE TITLE
Exception : pika.exceptions.ConnectionClosed when BlockingConnection is called

### ISSUE THREAD

**Issue by KartikKannapur** [pika/pika#650]
I was using RabbitMQ's [first tutorial](https://www.rabbitmq.com/tutorials/tutorial-one-python.html) for reference & when I tried to run 

    connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))

as mentioned in the tutorial, it threw the following error

    >>> connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Python27\lib\site-packages\pika\adapters\blocking_connection.py", line 339, in __init__ self._process_io_for_connection_setup()
    File "C:\Python27\lib\site-packages\pika\adapters\blocking_connection.py", line 374, in_process_io_for_connection_setup
        self._open_error_result.is_ready)
    File "C:\Python27\lib\site-packages\pika\adapters\blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
    pika.exceptions.ConnectionClosed

I tried the same thing on both Windows(64-bit) & Linux(64-bit), and it threw the same error.

**Comment by gmr** [comment]
That means that the connection to your RabbitMQ server was closed -- you should make sure RabbitMQ is running and accepting connections.

**Comment by KartikKannapur** [comment]
Thanks @gmr Will check on that.

**Comment by jackeisenbach** [comment]
Hi gmr, 

Could you please specify steps on how to start up the RabbitMQ server. It's not in the tutorial. Thanks!

**Comment by vitaly-krugl** [comment]
@jackeisenbach: see the official RabbitMQ documentation at https://www.rabbitmq.com/.  There is also a google group for RabbitMQ users that is very active: https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by RONNCC** [comment]
@KartikKannapur @gmr 

Can you elaborate on how to check from the pika side if a connection is ok?
e.g.. I have 

        if self.connection.is_closed:
            #reconnect
            self.connection = pika.BlockingConnection(connectionParams)
            self.channel = self.connection.channel()

before my send (a basic publish), and that doesn't seem to be enough as I still get ConnectionClosed errors sporadically

**Comment by antime** [comment]
When I use haproxy to connection the rabbitmq ,I got the same error aarter running script. But without haproxy ,It is run well.

**Comment by vitaly-krugl** [comment]
@antime, this issue is closed. If you are still experiencing an issue that you think is caused by pika, please open a new issue, and provide a full description of your issue, including python version, os and version, description of network topology, DEBUG-level pika logs demonstrating the issue from beginning, and network AMQP logs (use WireShark to collect AMQP logs in AMQP mode)

**Comment by fannyhub** [comment]
@antime and for anyone who has this problem - make sure you have your rabbitmq-server installed correctly. I have noticed I had some problem with my installation and was getting the problem mentioned above

**Comment by devpmn** [comment]
I am getting the same error.
I have my RabbitMQ Server running on AWS EC2
I am getting this same error on this line:

`connection = pika.BlockingConnection(pika.ConnectionParameters('xx.xx.xx.xx',5672,'/',credentials)) 
`where xx.xx.xx.xx : public ip address of my instance

Pls tell me,  if I am using the correct parameters. What should be the IP address , virtual hostname.
I have checked  the credentials , the user that I am using exists and it has the rights to access '/' virtual host

**Comment by vitaly-krugl** [comment]
@devpmn, this issue is closed. ConnectionClosed may occur for different reasons. The RabbitMQ Users goole group would be a more appropriate place to ask for help.
