### ISSUE TITLE
Connection blocked events do not get processed when calling `consume()`

### ISSUE THREAD

**Issue by replay** [pika/pika#653]
If RabbitMQ is below a resource limit when I connect, the BlockingConnection can end up in a hanging state if I first publish a message and then directly go into `consume()`, even when using the `inactivity_timeout` parameter.

As far as I can see the problem seems to be that when `consume()` sends the `basic_consume` message it waits for the `OK` from Rabbit and does not call the defined `on_blocked_connection_callback` before entering the actual consumption loop. Obviously I could wait for a second after publishing my message and then call `process_data_events()` before entering `consume()`, but that's not a solution. 

How to reproduce:

- Make sure you have a RabbitMQ which is already below resource limits. For example by setting `disk_free_limit` to some really high value.

- This callback gets called as long as the `time.sleep(1)` is there and the sleep is longer than it takes for the `blocked_connection` event to arrive. If you remove the sleep, then it just hangs and the callback does not get called because it's waiting for Rabbit's `OK` message before entering the consumption loop:

        import time
        import pika

        connection_parameters = pika.ConnectionParameters(
            host='192.168.1.101',
            port=5672,
            credentials=pika.PlainCredentials('guest', 'guest'),
        )

        conn = pika.BlockingConnection(connection_parameters)

        def callback(method):
            print('connection blocked!')

        conn.add_on_connection_blocked_callback(callback)

        chan = conn.channel()

        chan.basic_publish(
            exchange='test_exchange',
            routing_key='key',
            body='test'
        )

        time.sleep(1)

        conn.process_data_events()

        for msg in chan.consume(queue='somequeue', inactivity_timeout=1):
            print(msg)

A possible solution might be to also make this `_flush_output` handle the `connection_blocked` event: https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L1522

**Comment by vitaly-krugl** [comment]
@replay, thanks for the report.

I'm thinking out-loud here, please read on and bear with me ... 

I am going to provide some background that will help me, you, and others think about possible solutions.

One of the pesky problems with the previous generations of BlockingConnection were issues related to reentrancy and unexpected callbacks; these have lead to instability in both BlockingConnection and user code. E.g., call publish; before the publish returns, you get a consumer callback; you call publish again (the first publish call hasn't even returned yet); you get another consume callback before the second publish returns (the first publish hasn't returned either), and so on. This would lead to bad things such as `RuntimeError: maximum recursion depth exceeded` or execution of user code in ways that the programmer didn't anticipate from a blocking type of interface (it's BlockingConnection, after all); when using a blocking interface, you expect to not have to deal with the "callback hell" that you would normally associate with asynchronous interfaces.

The new generation of BlockingConnection addresses the above-mentioned reentrancy-related issues among others (e.g., performance). However, it is now apparent that it didn't anticipate the type of issue that you are reporting. It's a bit of a slippery slope when a synchronous (blocking) API has to confront asynchronous events.

If this may result in callbacks/reentrancy (possibly nested, too) in the midst of **any** blocking API call, then it **defeats the simplicity and robustness of using a synchronous interface, and it becomes even more complex than the  environments of asynchronous interfaces**, such as SelectConnection or TwistedConnection: at least in those environments your code never gets reentered while it's in the midst of an API call and is allowed to run to completion of the current event without any reentrancy whatsoever.

@replay, what do your app(s) need to do upon `on_blocked_connection_callback`? Would they need to raise an exception to interrupt the current blocking call? Would they need to make pika API calls on the same connection or channel as the active blocking call, and which ones? Would they need to set a timer in the connection?

Furthermore, I would expect this problem to not be limited to the `consume()` method. For example, what would happen when a connection is blocked and you placed the channel in delivery-confirmation mode (`BlockingChannel.confirm_delivery()`) and then tried to publish a message. Would the code also hang as it did with `consume()`? (or any other blocking API that waits for some form of confirmation (`ok`) from the broker, for that matter). @replay, would you mind trying it out with publish (and some others?) and report your findings here?

**Comment by replay** [comment]
Thanks for all the thoughts, this makes much more sense now.

What we are trying to achieve is very similar to the RPC Client in the example in the RabbitMQ documentation (https://www.rabbitmq.com/tutorials/tutorial-six-python.html). The main difference is that we want to let the user choose whether he wants to use synchronous or asynchronous interface, in the case of the synchronous interface I'd need to use `.consume()` instead of relying on the callback while continuously calling `process_data_events()` like they do in the example. 
So that's where the problem happens, the RPC Client publishes a job into the exchange, then calls `process_data_events()` once, and then uses `.consume()` to wait for the reply.
My plan was to just raise an exception in `on_blocked_connection_callback` so the user of the RPC Client can deal with it.

I understand your arguments that a user could potentially end up in an endless recursion when he does certain things inside the callback. Do you think it would be a possible solution for the `BlockingConnection` adapter to setup it's own internal callback for the `ConnectionBlocked` and `ConnectionUnblocked` events, and then in this internal callback it just sets some flag like `self.blocked = True`. Then the `chan.consume()` method could raise some exception to the user saying that this connection got blocked, which would be consistent with the expectation of a synchronous interface. 

I'll test the `confirm_delivery()` and then report back here.

**Comment by replay** [comment]
@vitaly-krugl you were right, `chan.confirm_delivery()` hangs exactly the same way as `chan.consume()` does because it's waiting for the `OK` message.

**Comment by vitaly-krugl** [comment]
@replay, thank you for the test results and the clarification of your use-case.

I was also thinking along the lines that exceptions for signaling such things as blocked/unblocked connections might be cleaner than callbacks in a synchronous interface. This might necessitate API changes. Here are some additional things to consider in the design:

1. Existing code that uses pika expects the callback and doesn't expect the new exception(s), so it would break; this could be easily addressed by an opt-in via a new optional arg in the BlockingConnection constructor that defaults to the old behavior.
2. If an API call gets interrupted by such an exception (e.g., ConnectionBlocked, ConnectionUnblocked, ConnectionTimerExpired, etc.), then how would the user continue after the interruption?
  * Considering that the API call probably already sent some frame(s) to the broker and was waiting for the reply from broker. Would the channel and connection be compromised (in a bad state) after this? Would the user have to retry the call? What if this was something "destructive", such as `basic_get` or `basic_publish`? 
  * To handle it gracefully, the API might need to change to return a "promise" from each API method that the user could wait on for completion and result. This way, if the call is interrupted by one of those transient conditions, the user could handle the exception and resume waiting on the "promise".

I think that in the near term, it might be more practical to allow the connection-blocked/unblocked (and some others, such as timer?) callbacks to flow through at any time, but with severe (documented) restrictions on what the user code may do with the source BlockingConnection/Channel from such callbacks.

**Comment by replay** [comment]
All your points make sense, especially that it's important to take care that we do not modify the interface and raise unexpected Exceptions.

As a near term solution, which would require documentation explaining the restrictions, what do you think about this? I also added a test which fails without the patch due to time out, but succeeds with the patch. This does not include anything like returning promises from the API yet:
https://github.com/pika/pika/compare/master...NetAccessCorp:master

**Comment by replay** [comment]
@vitaly-krugl I have pushed an updated and improved version: https://github.com/pika/pika/compare/master...NetAccessCorp:blocked_event_callback

Currently I'm still not satisfied with the way the Timeouts work in my branch, because in the case of the timeouts it's still an issue to resume to the waiting state after a Timeout exception has been raised, so please just ignore this part for now. In fact i'm not sure if it makes sense to use exceptions for timeouts at all, because their case is quite different and will always require reentry at the point where the exception has been raised.

Regarding your two points to consider:

1. With this patch, the state of connections and channels gets cleaned up on `ConnectionBlockedException`, so the channel and connections are not left in an inconsistent state. Since RabbitMQ simply ignores frames that have been sent on a blocked connection it should be safe to just clean the state up on client side. 
The limitations are similar as for the `add_timeout` method where the docs say:
`NOTE: the timer callbacks are dispatched only in the scope of specially-designated methods: see BlockingConnection.process_data_events and BlockingChannel.start_consuming.`
2. In the case of `basic_publish` the only way to be sure that the msg has been delivered is by turning `confirm_delivery` on, so that's the same as it is now. In the case of `basic_get` RabbitMQ won't send another msg if the connection is blocked, so it's not destructive. This should also make the promises unnecessary.

This is some test code:

    import pika
    import random

    connection_parameters = pika.ConnectionParameters(
            host='127.0.0.1',
            port=5672,
            credentials=pika.PlainCredentials('guest', 'guest'),
    )

    conn = pika.BlockingConnection(connection_parameters, exception_on_event=True)
    chan = conn.channel()
    chan.confirm_delivery()

    while True:
        try:
            print("publishing")
            chan.basic_publish(
                exchange='test_exchange',
                routing_key='key',
                body=str(random.random()),
            )
            conn.sleep(1)
            chan.basic_get(
                queue='test_queue'
            )
        except pika.exceptions.ConnectionBlockedEvent:
            print("blocked")
            while True:
                try:
                    print("sleeping")
                    conn.sleep(3)
                except pika.exceptions.ConnectionUnblockedEvent:
                    print("unblocked")
                    break

When I Block/Unblock this connection, while the script is running, I see that it correctly detects and handles the events.

I'd be happy to hear your thoughts on this.

**Comment by vitaly-krugl** [comment]
@replay: Sorry that I have not been able to give this any attention lately. I am quite a bit swamped for another few days. Thanks for your patience.

**Comment by vitaly-krugl** [comment]
@replay, I've been swamped, but I have not forgotten. Please take a look at PR #701. It implements a feature that enables users to configure a Connection.Blocked timeout such that the connection gets torn down whenever connection remains blocked for the given timeout seconds, resulting in `ConnectionClosed` exception in `BlockingConnection`.

Also, see https://github.com/vitaly-krugl/pika/blob/blocked-handling/pika/adapters/blocking_connection.py#L277-L309 for an explanation of the recursion/reentrancy protection in `BlockingConnection` implementation and additional insights into handling of Connection.Blocked and Connection.Unblocked.
