### ISSUE TITLE
Request to add asyncio adapter

### ISSUE THREAD

**Issue by zloidemon** [pika/pika#654]
Would you like add asyncio adapter?

**Comment by krishna-kashyap** [comment]
+1

**Comment by gmr** [comment]
Yes

**Comment by krishna-kashyap** [comment]
If there is a interface, set of methods to be implemented in a adapter so as to be able to plug it in Pika, I can try writing the adapter for asyncio. From source code it wasn't all that evident (I compared multiple of the adapters to see if there are common methods which are being implemented)

**Comment by leifurhauks** [comment]
Are there concrete plans to be adding support for asyncio, or is it currently just an an item on the wishlist?

**Comment by leifurhauks** [comment]
Would it be mostly just a matter of implementing those methods from `pika.connection.Connection` that `raise NotImplementedError`?

For example, for [`add_timeout(self, deadline, callback_method)`](https://github.com/pika/pika/blob/master/pika/connection.py#L704), it looks to me like it would just need to pass the parameters to the [`call_later`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.call_later) method on the asyncio event loop.

Like @krishna-kashyap , I might be able to contribute if someone is prepared to review PRs for this.

**Comment by zloidemon** [comment]
Hey, when are you planing to release it?

**Comment by TheDodd** [comment]
+1 this would be super awesome!

**Comment by appetito** [comment]
Hi!
Here is preview version of asyncio adapter - just clone of Twisted adapter
https://github.com/appetito/pika

It is not tested well but seems working, you cat try.

**Comment by vitaly-krugl** [comment]
Awesome, @appetito! If it matches the interface of SelectConnection/TornadoConnection/LibevConnection, then you can easily add it to the async adapter acceptance test suite via `async_test_base.AsyncAdapters`.

**Comment by povilasb** [comment]
+1

**Comment by mosquito** [comment]
Hi there I will PR #768 now it works.

**Comment by vbogretsov** [comment]
+1

**Comment by kotyara1005** [comment]
+1

**Comment by pquentin** [comment]
For reference, PR #805 improves #768.

**Comment by mosquito** [comment]
Actually you should try to use [aio-pika](https://github.com/mosquito/aio-pika)

**Comment by lukebakken** [comment]
Resolved by #805
