### ISSUE TITLE
BlockingConnection and connection times out + connection_attempts

### ISSUE THREAD

**Issue by gst** [pika/pika#655]
I've been playing with BlockingConnection recently.

Have found the following : 

If the server isn't *available* (as with `sudo iptables -A INPUT -p tcp --destination-port amqp  -j DROP`) here is what we can see:

```
pika.adapters.base_connection - INFO - Connecting to 127.0.0.1:5672
pika.adapters.base_connection - ERROR - Connection to 127.0.0.1:5672 failed: timeout
```

the socket.connect method raise a socket.error which is catched by `SelectConnection._create_and_connect_to_socket()` and then the error is returned by that function, higher in the stack the error is finally given to `self._values = (self._value_class(*args, **kwargs),)` within `CallbackManager.process()`

but what we get as exception is `ConnectionClosed()` (this is raised from within `BlockingConnection._flush_output` (called from _process_io_for_connection_setup)).

Now, if I set a `connection_attemps > 1` to the BlockingConnection parameters then I get well the socket.error timeout exception..

Shouldn't we also get it for connection_attemps == 1 (which is actually the default) ? 

this would be more consistant.

**Comment by gst** [comment]
> Now, if I set a connection_attemps > 1 to the BlockingConnection parameters then I get well the socket.error timeout exception..

well.. what I get is exactly `AMQPConnectionError` (but with the socket timeout error text as argument so it's ok for me).

**Comment by gst** [comment]
Have maybe a patch.. PR should arrive..

**Comment by gst** [comment]
In this regards, I find that it should be usefull / good to have a *connect_timeout* parameter, so to be used instead of socket_timeout **only** in the `_create_and_connect_to_socket()`.. once the connection is established then the socket_timeout would applied.. what do you think ?

**Comment by base698** [comment]
I think this is what I'm seeing in this question:  http://stackoverflow.com/questions/33739147/never-ending-message-loop-same-message-redelivered-in-python-rabbitmq-consumer   Any work arounds?

**Comment by vitaly-krugl** [comment]
@base698, http://stackoverflow.com/questions/33739147/never-ending-message-loop-same-message-redelivered-in-python-rabbitmq-consumer appears to be a different issue, related to RabbitMQ's heartbeat timeouts.  I posted an answer to that question on Stackoverflow.

**Comment by base698** [comment]
I can't see anything on that page you posted about heartbeats in python.  I'm using SelectConnection and can't find anything related to timeouts.  Printing dir(_connection) shows something called heartbeat but it's not a method.  I see references online about heatbeat and heartbeat_interval neither are params allowed for select connection.

**Comment by vitaly-krugl** [comment]
@base698: I added a couple of comments to clarify the heartbeat situation in the above-referenced Stackoverflow post as user1778420. The issue discussed in the above-referenced Stackoverflow post is related to heartbeats, which is different from the issue logged here by @gst.
