### ISSUE TITLE
Can't reuse channel ?

### ISSUE THREAD

**Issue by Zephor5** [pika/pika#669]
Sorry to bother, but **can I reuse the channel automatically？**
I'm using the channel to publish, and the connection hold by a connection pool ([mypika](https://github.com/Zephor5/mypika/blob/master/mypika.py)), So I can reuse those connections, but if I don't `close` the channel and put the connection back, the other query for `channel` will create another one other than the one was created before.
I don't want to create a channel each time I acquire one. Should I setup a channel pool or there's something else I can do.
    This should be a question on stackexchange...but I think I can get better answer here.

**Comment by gmr** [comment]
Why are you creating a new channel every time? Why not pool the channels as well, or an object for Connection+Channel?

Channels are really just an RPC feedback mechanism so you get exceptions and such for your commands when they fail. Should be no harm in holding them in your pool. They should be the primary thing APIs interact with instead of connections.

**Comment by Zephor5** [comment]
@gmr Thx a lot to wake me up.
Here I have another question that I can't use one channel to get the message published by that channel.
The method `basic_publish` just flush data and return, the publisher don't care if the publish is success ?

**Comment by gmr** [comment]
Correct, you can use transactions, mandatory publishing, or publisher confirmations to get that kind of information. RabbitMQ.com is a good resource for such info.

**Comment by taoqf** [comment]
I use two connections, one for consuming, and the other one for publishing
I do not reuse the channel,, so when i want to publish a message ,i create a channel, when i get the replay, i close the channel.
But i find the channel will close when it is not be using for some minutes.so when i need publish again, it will throw a `pika.exceptions.ConnectionClosed` error.
What is the best way to use pika? i am new to it.

**Comment by vitaly-krugl** [comment]
@taoqf, for questions, a better option is to post on the rabbitmq-users google group.

**Comment by taoqf** [comment]
Should i connect and disconnect from rabbitmq each time i want publish?

**Comment by vitaly-krugl** [comment]
Instead of posting questions in a closed issue, try here: https://groups.google.com/forum/#!forum/rabbitmq-users
