### ISSUE TITLE
queue_declare behavior with nowait=True has changed

### ISSUE THREAD

**Issue by awelzel** [pika/pika#688]
Hey @vitaly-krugl,

as I mentioned elsewhere, ```nowait``` functionality for ```queue_declare``` and others appears to be broken after 1e0b0f395b58c7dbfdbd53e875bee2197432225d. Tested with ```TornadoConnection```.

See the attached example code which simply connects to the broker and declares the given queue. With 1e0b0f395b58c7dbfdbd53e875bee2197432225d applied, a ```ValueError``` is raised:

```
(py3env) awelzel@tinky:$ python examples/nowait.py other_queue      
ERROR:pika.callback:Calling <bound method Channel._on_openok of <pika.channel.Channel object at 0x7fb1b4af5320>> for "1:Channel.OpenOk" failed
Traceback (most recent call last):
  File "/home/awelzel/python/pika/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/home/awelzel/python/pika/pika/channel.py", line 1058, in _on_openok
    self._on_openok_callback(self)
  File "examples/nowait.py", line 27, in channel_open
    nowait=True
  File "/home/awelzel/python/pika/pika/channel.py", line 703, in queue_declare
    replies)
  File "/home/awelzel/python/pika/pika/channel.py", line 1129, in _rpc
    raise ValueError('A populated callback must be accompanied by '
```

After reverting above commit, no exception happens and the queue is created on the broker.

Here's a unit test that will fail with current master.
```
diff --git a/tests/unit/channel_tests.py b/tests/unit/channel_tests.py
index 57c5178..042c35f 100644
--- a/tests/unit/channel_tests.py
+++ b/tests/unit/channel_tests.py
@@ -765,6 +765,15 @@ class ChannelTests(unittest.TestCase):
         self.obj._set_state(self.obj.OPEN)
         self.assertRaises(ValueError, self.obj.queue_delete, 'callback', 'foo')
 
+    @mock.patch('pika.spec.Queue.Declare')
+    @mock.patch('pika.channel.Channel._send_method')
+    def test_queue_declare_nowait_send_method(self, send_method, unused):
+        self.obj._set_state(self.obj.OPEN)
+        mock_callback = mock.Mock()
+        self.obj.queue_declare(mock_callback, 'foo', nowait=True)
+        send_method.assert_called_with(spec.Queue.Declare(0, 'foo',
+                                                          nowait=True))
+
     @mock.patch('pika.spec.Queue.Delete')
     @mock.patch('pika.channel.Channel._rpc')
     def test_queue_delete_rpc_request(self, rpc, unused):
```

Thoughts?

[nowait.txt](https://github.com/pika/pika/files/82519/nowait.txt)

**Comment by vitaly-krugl** [comment]
@awelzel, the use case in `test_queue_declare_nowait_send_method` above is invalid, because it's invalid to pass a completion callback with an asynchronous request: it's impossible for this callback to ever be called with `nowait=True`, so calling it this way is an error.

**Comment by awelzel** [comment]
@vitaly-krugl , ok, makes sense. Your commit changed this behavior though: Before it, it was possible to pass in a ```callback``` together with ```nowait=True``` - it was simply ignored.

But, I agree. It makes sense to bail out when passing in a callback and having ```nowait=True``` as this combination is invalid.

There are two unfortunate things:
 - ```callback``` for ```queue_declare()``` is a required parameter, so you have to pass ```None``` explicitly. Similar for ```queue_bind()```.
 - the exception message isn't very indicative about the issue.```A populated callback must be accompanied by populated acceptable_replies``` certainly doesn't point to "you should pass None for nowait=True". Could check before calling ```_rpc()```? Thoughts?

Anyways, maybe just nitpicking ;)

**Comment by vitaly-krugl** [comment]
@awelzel: Thanks for thinking about it and your feedback. Good point about the message in the exception. The parameter check in `_rpc()` also catches internal bugs. What would be a good place for a more user-friendly check?

**Comment by awelzel** [comment]
@vitaly-krugl , I thought that simply putting into ```queue_declare()```

```
if nowait and callback is not None:
   raise ValueError('Unexpected callback for nowait=True')
```
would be enough. And note it in the Changelog?

However, given that it applies to more method with ```nowait``` and a ```callback```, maybe ```_validate_channel_and_callback()``` should be extended with above condition and taking ```nowait=False``` as default, then modifying callers as appropriate?

**Comment by vitaly-krugl** [comment]
@awelzel, I took another look. I think I can simply change the current cryptic message "A populated callback must be accompanied ..." to something more meaningful.

**Comment by vitaly-krugl** [comment]
@awelzel - would this work https://github.com/pika/pika/pull/690/files#diff-831cec7ce02158498fb9bb8d1fd55451R1128 ?

**Comment by vitaly-krugl** [comment]
@awelzel, can this issue be closed?

**Comment by awelzel** [comment]
Yes, thanks!

**Comment by vitaly-krugl** [comment]
Please close.
