### ISSUE TITLE
How to disable pika debug message

### ISSUE THREAD

**Issue by xiaopeng163** [pika/pika#692]
Hi 

I use pika in my project, when i set my project's log level to DEBUG, it gives me many pika debug messages which i does not want, I only want my own debug messages, how to disable pika's debug message output

```
2016-01-13 14:44:02,403.403 3514 DEBUG pika.channel _on_synchronous_complete 994 [-] 0 blocked frames
2016-01-13 14:44:02,403.403 3514 DEBUG pika.callback process 231 [-] Calling <function single_argument at 0x7f2b9c359c08> for "1:Basic.QosOk"
```

**Comment by vitaly-krugl** [comment]
Please post the source code that you use for setting your project log level to DEBUG

**Comment by xiaopeng163** [comment]
part of my code:

```
import logging
import traceback
import pika

LOG = logging.getLogger(__name__)


class Publisher(object):
    def __init__(self, host='localhost', port=5672, userid='guest', password='guest'):

        self.parameters = pika.ConnectionParameters(
            host=host, port=port,
            credentials=pika.PlainCredentials(userid, password))

        self._connection = None
        self._channel = None

    def connect(self):
        """This method connects to RabbitMQ, returning the connection handle.

        :rtype: pika.BlockingConnection

        """
        LOG.debug('Connecting to rabbitmq server')
        try:
            # Open a connection to RabbitMQ on localhost using all default parameters
            self._connection = pika.BlockingConnection(self.parameters)

            # Open the channel
            self._channel = self._connection.channel()
            return True
        except Exception as e:
            LOG.error(e)
            LOG.debug(traceback.format_exc())
            return False
```

**Comment by vitaly-krugl** [comment]
Regarding

> when I set the level to DEBUG, i will get message like this

How do you set the level to DEBUG?

**Comment by xiaopeng163** [comment]
```python
    _EARLY_LOG_HANDLER = logging.StreamHandler(sys.stderr)
    log = logging.getLogger()
    log.addHandler(_EARLY_LOG_HANDLER)
    if level is not None:
        log.setLevel(level)
```

**Comment by xiaopeng163** [comment]
anyone know that?

**Comment by awelzel** [comment]
@xiaopeng163 ,

IIRC, pika nicely adheres to Python logging, so you may use either of the following:
```
# reduce log level
logging.getLogger("pika").setLevel(logging.WARNING)

# or, disable propagation
logging.getLogger("pika").propagate = False
```

The first one reduces the log level of the logger used by pika to ```WARNING```. The second one disables propagation of log messages to the root logger. You should probably use the first one as it will still show ```error``` and ```critical/fatal``` logs from pika.

The python logging docs are very helpful:
https://docs.python.org/2/library/logging.html

HTH,
   Arne

**Comment by vitaly-krugl** [comment]
In my own debugging, if I want to see just my own app's DEBUG logs, I set the log level of my own app's log context root to DEBUG, instead of turning off everyone else's. For example, if my app creates loggers like this: `logging.getLogger("taurus.engine")`, `logging.GetLogger("taurus.collector")`, etc., and I want to see my app's own DEBUG-level logging output, I simply change the log level for my own app and leave everyone else's alone like this: `logging.getLogger("taurus").setLevel(logging.DEBUG)`

**Comment by awelzel** [comment]
@vitaly-krugl ,

> [...]I simply change the log level for my own app and leave everyone else's alone like this: logging.getLogger("taurus").setLevel(logging.DEBUG)

...and you attach a handler to the ```taurus``` logger, not the ```root``` logger? Otherwise I don't understand it ;)

**Comment by vitaly-krugl** [comment]
@awelzel: I use `logging.config.fileConfig` with `disable_existing_loggers=False`, as in this code: https://github.com/numenta/numenta-apps/blob/83bddd39ad36d0b102ca8f68c087717d470b5cc0/nta.utils/nta/utils/logging_support_raw.py#L286, where the root defaults to INFO per https://github.com/numenta/numenta-apps/blob/master/nta.utils/conf/logging.conf.

In trying to come up with a simpler example, I wonder if the following would work for setting must my own logger to DEBUG, while keeping everyone else's at INFO, for example:

```
logging.basicConfig(level=logging.INFO)  # set everyone to INFO
logging.getLogger("taurus").setLevel(logging.DEBUG)  # set just my own level to DEBUG
```

**Comment by awelzel** [comment]
> Okay, here is an actual example via 2.7.10 python shell; observe that other_logger.debug(...) doesn't produce anything, as intended.

@vitaly-krugl Thanks, indeed this works. Double checked the docs and it makes sense. cool!

https://docs.python.org/2/howto/logging.html#logging-flow

**Comment by vitaly-krugl** [comment]
@xiaopeng163, I think this resolves your question. If it does, please close the issue.

**Comment by xiaopeng163** [comment]
@vitaly-krugl yes, thanks!
