### ISSUE TITLE
Possible problem with message_count

### ISSUE THREAD

**Issue by mattboston** [pika/pika#693]
I'm using the following code to check the size of a queue.  Does this tell me both the number of ready and unack'd messages?  Or only the ready ones?  We're looking to get a total count of all messages including the unack'd ones.

servername = "mq001"
params = pika.ConnectionParameters(
    host=servername,
    port=port,
    virtual_host=virtual_host,
    credentials=pika.PlainCredentials(username,password),
)
connection = pika.BlockingConnection(params)
channel = connection.channel()
status = channel.queue_declare(queue=queue_name, durable=True)
count = status.method.message_count

**Comment by mattboston** [comment]
Just to add a little clarity, we're using this code to decide when it's safe to power off our dev message queue servers at the end of the day, but the code said the queues were clear and powered off the server when there might have been unack'd messages

**Comment by vitaly-krugl** [comment]
The rabbitmq-users group is a much better place to search and ask question like this one, since pika merely returns these values from the broker. See https://groups.google.com/forum/#!searchin/rabbitmq-users/message-count/rabbitmq-users/AM23w2CDxsw/y9I4LrM4U2MJ
