### ISSUE TITLE
Proposal: Split out adapters

### ISSUE THREAD

**Issue by gmr** [pika/pika#695]
I've been toying with the idea of splitting out most of the pika connection adapters to their own packages and splitting up things in their own repos with the pika core library being a wrapper for sub-projects. As a rough example the projects would be structured as so:

- pika
 - requires pika-blocking, pika-select
- pika-blocking
  - requires pika-core
- pika-select
  - requires pika-core
- pika-asyncore
  - requires pika-core
- pika-libev
  - requires pika-core, pyev
- pika-tornado
  - requires pika-core, tornado
- pika-twisted
  - requires pika-core, twisted

This would allow us to have individual maintainers for each of the adapters with commit access to the repos and would allow us to have the project continue to grow without having so much stomping on the main codebase for adapter specific fixes.

I'm looking for feedback/thoughts on this concept. If we move forward on it, I'll be working to break things up and restructure the repos once the actionable PRs are merged and 0.11 is released.

**Comment by vitaly-krugl** [comment]
A split like this will bring on the typical version compatibility management/coordination issues. As a contributor, I found the current structure to be more efficient for making changes that affect the core and one or more adapters. Although, I understand that the current situation may be overwhelming for a single maintainer.

**Comment by vitaly-krugl** [comment]
The split might also cause loss of a common interface in adapters where this is possible and practical (e.g., SelectConnection, TornadoConnection, LibevConnection).

Also, we are presently able to have a common acceptance test suite for the above-mentioned async adapters, but might not be able to do that after the split.
