### ISSUE TITLE
Using one connection and multiple channels to receive and send messages

### ISSUE THREAD

**Issue by yangyuliang1981** [pika/pika#699]
In my scene, the node should have both functions of send and receive messages.
But the number of the node is larger than 10000, so we don't want to create too many connections in each node. If we create two connections in each node, then there will be more than 20000 connections in rabbitmq, it's terrible.

The pika official document said the connection is not thread safe.
And I failed to use one connection ( with Blocking connection adapter) and two channels which are in different thread to send and receive messages at the same time. 

If there are two connections to send and receive messages dividely, it works fine.

Is there any suggestions to fix this issue? 
Using one connection to realize sending and receiving message in one computer.

**Comment by vitaly-krugl** [comment]
@yangyuliang1981, as you discovered, a single connection in pika is not thread safe. Depending on your use cases, you may add your own mutual exclusion around calls into BlockingConnection/BlockingChannel to make it thread-safe, but it might be inefficient.

If your code is I/O-bound, then one efficient way would be to switch to an asynchronous programming framework without threads, using one of the other adapters in pika, such as SelectConnection, TornadoConnection, TwistedConnection.
 
Options outside of pika that I have familiarity with:

1. rabbitpy documentation describes thread-safe access with channel per thread: https://rabbitpy.readthedocs.org/en/latest/threads.html. I don't have experience with rabbitpy; it's authored by pika's maintainer @gmr.
2. haigha (https://github.com/agoragames/haigha) used with gevent engine ("green threads"; cooperative multitasking). haigha with gevent engine worked well for me in a product that I worked on a few years ago. This model is well suited for I/O bound apps.

**Comment by yangyuliang1981** [comment]
@vitaly-krugl 
Thanks a lot for your help.
Now our project is on requirements phase, I'll forward a response when we get a final solution in 2016.

**Comment by vitaly-krugl** [comment]
@yangyuliang1981, please come back and share your response when you're ready. I will close the issue for now.

**Comment by fscnick** [comment]
If I use `add_callback_threadsafe()` to send messages to another channel, is that OK?

**Comment by fscnick** [comment]
@lukebakken Here is the snippet of the concept. If the source channel  (`self.chan_src`) consumes a message from queue, it would create a thread to handle the message. Emit the callback at the end of thread.

```python
def thread_task( pika_manager, method_frame, msg):
    logging.info("In thread. msg: %s", msg)
    res = int(msg) + 1
    pika_manager.add_threadsafe_callback(method_frame, method_frame, str(res))

class PikaManager(object):
     ...
    def on_message(self, channel, method_frame, header_frame, body):
        logging.info("Get msg %s", body)
        t = threading.Thread(
            target = functools.partial(thread_task, self, method_frame, body))
        t.start()

    def send_result(self, method_frame, msg):
        self.chan_dst.basic_publish(exchange='', routing_key='dst', body=msg)
        logging.info("Send result.")

        if not NO_ACK:
            self.chan_src.basic_ack(delivery_tag=method_frame.delivery_tag)
            logging.info("Send ack.")
        
    def add_threadsafe_callback(self, cb, method_frame, msg):
        self.conn.add_callback_threadsafe(
            functools.partial(self.send_result, method_frame, msg)
        )
```

Test 100000 messages with `NO_ACK` is `True`.
Test 80000 messages with `NO_ACK` is `False`.

The entire example is [here](https://github.com/fscnick/pika_add_threadsafe). Feel free to use it, if nothing goes wrong. 

I'm a python rookie. If I made something stupid, kindly let me know.
