### ISSUE TITLE
SSL rehandshakes

### ISSUE THREAD

**Issue by deadtrickster** [pika/pika#703]
More question than issue probably.

From this code https://github.com/pika/pika/blob/master/pika/adapters/base_connection.py#L304
I have a feeling that ssl rehandshakes aren't supported (i.e. after want_read/write connection is closed anyway). Am I right? How this affects experience? 

Thank you

**Comment by vitaly-krugl** [comment]
The SSL functionality could probably use some attention and definitely needs tests. Care to contribute?

**Comment by deadtrickster** [comment]
@vitaly-krugl 
Well I'm not that good with Python, also having this wide adoption the last thing I want is to break stuff.
I came up with this question while researching for my client implementation in Common Lisp. I just wanted to make sure I'm doing everything right. I wrote SSL layer and I ran test for 24 hrs without rehandshake. So actually the first question here is how to properly trigger rehandshake manually.

**Comment by vitaly-krugl** [comment]
https://github.com/openwebos/libpalmsocket may be a good algorithmic reference for re-handshakes, etc. I rewrote libpalmsocket a while back, adding support for SSL renegotiation, certificates, and workarounds for a number of OpenSSL bugs.

**Comment by vitaly-krugl** [comment]
@deadtrickster, I posted on the RabbitMQ users group about RabbitMQ-triggered renegotiations here https://groups.google.com/forum/#!topic/rabbitmq-users/g7LkNe9sKDw.

At this time, we don't have any reason to believe that RabbitMQ would automatically trigger SSL/TLS Renegotiation.

I am going to close this issue for now. If you gain any further specific insights about how this might be triggered, please post them here, and we may reopen this issue. Thx.
