### ISSUE TITLE
There is only one basic_get callback allowed.

### ISSUE THREAD

**Issue by dschep** [pika/pika#709]
The implementation of `basic_get()` doesn't work if called more than once (before the callback is executed). It seems to only have 1 slot for callbacks [here](https://github.com/pika/pika/blob/0114fc45e7173a9520a4cb0f51ea96b4e9eeafa2/pika/channel.py#L281) as opposed to a list (or otherwise linking it to the specific request). This is, IMO, unexpected behavior. At the very least, it should be clearly documented. Here's a simple test case. Note, the failure scenario has to be quit by hand.

```
$ python2 testpika.py 1
message body
$ python2 testpika.py 2
message body
Basic.GetOk received with no active callback
```

Here's the source for `testpika.py`:
```
#!/usr/bin/env python2

import logging
import sys

import pika


def on_open(connection):
    connection.channel(on_channel_open)


def on_queue_setup(method_frame):
    global channel, num_messages
    props = pika.BasicProperties(content_type='text/plain', delivery_mode=1)
    for i in range(num_messages):
        channel.basic_publish('', 'test', 'message body', props)

    for i in range(num_messages):
        channel.basic_get(on_basic_get, 'test', no_ack=True)

msg_count = 0
def on_basic_get(self, method, properties, body):
    global num_messages, msg_count

    print body

    msg_count += 1
    if msg_count == num_messages:
        connection.close()


def on_channel_open(new_channel):
    global channel
    channel = new_channel

    channel.queue_declare(on_queue_setup, 'test')

num_messages = int(sys.argv[1])

logging.getLogger('pika').addHandler(logging.StreamHandler())
parameters = pika.URLParameters('amqp://guest:guest@localhost:5672/%2F')
channel = None
connection = pika.SelectConnection(parameters=parameters,
                                   on_open_callback=on_open)

try:
    connection.ioloop.start()

except KeyboardInterrupt:
    connection.close()
```

**Comment by jamestbrown** [comment]
:+1:

**Comment by vitaly-krugl** [comment]
Thanks for reporting. It definitely doesn't sound right. So that I may understand this better, which usage scenario are you anticipating for the multiple outstanding Basic.Get requests versus using the typically more efficient Basic.Consume?

**Comment by dschep** [comment]
I agree that typically `basic_consume` should be used, I was using `basic_get` to keep my HTTP service stateless and just pop 1 message off the queue on HTTP GET(in hindsight, `basic_qos` + only ACKing when the message is fetched via HTTP would work better). Regardless, I'd expect `basic_get` functionality should be callable more than once or unless it's document that it can't.

**Comment by vitaly-krugl** [comment]
Thanks @dschep, I agree that either documentation or functionality needs to be addressed. Just wanted to get a better handle on the usage scenario.
