### ISSUE TITLE
String SSL certificates

### ISSUE THREAD

**Issue by jbpineiro** [pika/pika#721]
It is possible use pika ssl_options with string variables as certificates instead of path to file certificates?.
I see that pika use ssl module of python and found that: http://stackoverflow.com/questions/12336239/how-to-open-ssl-socket-using-certificate-stored-in-string-variables-in-python.
It is possible change pika code to use other ssl module like M2Crypto, TLS Lite, pyOpenSSL or something else that allow use string certificates?

**Comment by vitaly-krugl** [comment]
@jbpineiro, there are no plans at this time to add support for other SSL modules. Please describe your environment, including why you're unable to make it work with file paths.

**Comment by Giri-Chintala** [comment]
@vitaly-krugl i have use-case with similar requirements. 

We are using AWS Lambda to put/get messages from RabbitMQ. Our security policy restricts us saving Certificates to disk on EC2 where Lambda is hosted. So, we are thinking about store certificates in S3 and retrieve certs in Lambda Function and pass cert as string in ssl_options.

**Comment by vitaly-krugl** [comment]
It looks like the python community is working to add support for in-memory certs and cert chains, but it likely won't be backported to 2.x; reference https://bugs.python.org/issue16487

**Comment by vitaly-krugl** [comment]
@Giri-Chintala: so, your security policy for AWS Lambda won't even allow you to create temp files?

**Comment by vitaly-krugl** [comment]
Hmmm..., I wonder if you can work around this limitation via Filesystem in User Space (FUSE). E.g., https://pypi.python.org/pypi/fusepy/. This way, the certs could be stored entirely in memory, but accessed via the file API just like ordinary files.

**Comment by Giri-Chintala** [comment]
@vitaly-krugl i will try FUSE. Thanks for great suggestions!

**Comment by vitaly-krugl** [comment]
@Giri-Chintala, please update us here on your experience with working around the issue via FUSE or anything else. If you can get it to work, then a recipe would be most appreciated for the benefit of the other community members. Thank you.

**Comment by Giri-Chintala** [comment]
@vitaly-krugl  
i tried using fuse in my local, but unfortunately i am unable to use in my AWS Lambda as i don't get root access.
https://www.stavros.io/posts/python-fuse-filesystem/

**Comment by vitaly-krugl** [comment]
@Giri-Chintala:  regarding

> i tried using fuse in my local, but unfortunately i am unable to use in my AWS Lambda as i don't get root access

Do you mean that you would need root permissions to set this up?

**Comment by vitaly-krugl** [comment]
I am afraid that the current implementation of pika and built-in ssl module don't support string certs. Builtin SSL module appears as if it will support string certs on Python 3.6 or 3.7. And, as has been mentioned, there are other SSL options, such as pyopenssl.

One thing you may try is to fork pika and modify it to use pyopenssl or similar instead of the builtin SSL library.

By the way, you never mentioned which version of python you're using.
