### ISSUE TITLE
Slow throughput when threading producer/consumer

### ISSUE THREAD

**Issue by pgreaney** [pika/pika#723]
I have a setup with 50 producers and 50 consumers running to a single queue in rabbitMQ. I am only able to get a maximum of about 800 messages/second using the example async producer/consumer when running "Hello, World!" through. Does anyone know why this might be? The only thing I've changed in this script is my IP address to connect to for attachment purposes

[BenchmarkPyConsumer.txt](https://github.com/pika/pika/files/184545/BenchmarkPyConsumer.txt)
[BenchmarkPyProducer.txt](https://github.com/pika/pika/files/184546/BenchmarkPyProducer.txt)
[BenchmarkPython.txt](https://github.com/pika/pika/files/184544/BenchmarkPython.txt)

**Comment by vitaly-krugl** [comment]
@pgreaney, assuming your thorughput computation logic works properly, there are likely a few things that are specific to your implementation that are slowing things down. Here are some to consider

1. The dreaded cpython global interpreter lock (A.K.A. GIL)
2. Context switches from having so many threads
3. delivery_mode=2: this is persistent mode, which likely requires RabbitMQ to do more work
4. immediate=True; not sure whether this slows things down, but it might.

I have in the past performed performance benchmarking using a single publisher thread (no consumer, and I think with default delivery_mode), achieving much higher throughput (8,000 per second or so? running everything on a 3 year-old development MacBookPro). See https://github.com/vitaly-krugl/amqp-perf. NOTE I haven't used that tool in a while, so use at own risk 😃 .

Another aspect that's troublesome in your benchmark code (although no bearing on throughput) is that the publisher code runs an infinite loop that incessantly publishes messages. There are a couple of problems, especially if this type of logic were to be used in production code:

1. It doesn't behave like an I/O bound application for which the async adapters were intended, and can overwhelm the program's memory if networking cannot keep up.
2. The released 0.10.0 pika had a commit that allowed code like your publishing loop to make some progress, actually attempting to sending the data to the non-blocking socket without relying on ioloop to write to the socket when it detects that the socket is writeable. Unfortunately, that PR introduced some bugs, and we had to revert the part of the PR that attempted to send data in the context of the publisher. Thus, this type of loop won't work with the next release of pika.

**Comment by vitaly-krugl** [comment]
Just noticed that the benchmark publisher declares the queue as non-durable (`_channel.queue_declare(self.on_queue_declareok, queue_name)`), so not sure whether `delivery_mode=2` will have any impact at all; the message certainly won't get stored if the queue is non-durable; I don't remember whether RabbitMQ would complain (i.e., raise error) if you tried to send persistent messages to a non-durable queue (certainly sounds inconsitent). FYI.

**Comment by vitaly-krugl** [comment]
@pgreaney, it looks like the performance issue is somewhere on your side. I outlined some potential causes in https://github.com/pika/pika/issues/723#issuecomment-212298726. 

Here is a chart of a pika.BlockingConnection-based consumer and producer running concurrently from two processes and achieving throughputs of about 8K messages per second.

pika.BlockingConnection in pika v 0.10.0 and current pika master branch is implemented as a layer on top of pika.SelectConnection.

Both clients (using pika from master branch) and RabbitMQ 3.6.0 were running on the same machine (MacBookPro) for minimal latency.

The channels were created as follows:

```
import pika
conn = pika.BlockingConnection()
ch = conn.channel()
```

Here is the chart with 8K messages/sec publisher and consumer throughputs: 
![screen shot 2016-04-23 at 5 03 33 pm](https://cloud.githubusercontent.com/assets/1441066/14764701/c62a0c8c-0976-11e6-95d5-c1133d00e0a5.png)

**Comment by vitaly-krugl** [comment]
And here is a chart with acks. The BlockingConnection-based consumer is ack'ing, which slows down the draining of the queue due to BlockingConnection's synchronous characteristics. In this case, I would expect a SelectConnection consumer to do better. But, the performance is still pretty decent for a pure python synchronous implementation. 
![screen shot 2016-04-23 at 5 43 28 pm](https://cloud.githubusercontent.com/assets/1441066/14764830/562c9ff8-097b-11e6-951a-61de42750b2b.png)
