### ISSUE TITLE
How to schedule my message sending process with SelectConnection.

### ISSUE THREAD

**Issue by yangyuliang1981** [pika/pika#731]
As a fresher, I don't know how to schedule my message sending process with SelectConnection.

I think the SelectConnection is a loop, so I think it need a thread.
The module will be in another thread.
Then how can I schedule my messaging sending process?

The official example used **add_timeout **function to schedule the message sending.
Then there must be a message queue, when the queue is empty, should the loop still circling?

**Comment by yangyuliang1981** [comment]
Using the latest code from github, it works ok, while the code from pypi is not work.
The former fix some bugs with connection close.
Done!

**Comment by vitaly-krugl** [comment]
See http://pika.readthedocs.org/en/latest/faq.html regarding pika and thread-safety
