### ISSUE TITLE
Problem connecting after connection refused.

### ISSUE THREAD

**Issue by holljen** [pika/pika#732]
While trying to make our applications pika connection more robust (one that tries to reconnect whenever the connection goes down) I hit a snag. Reconnecting after a connection fails works fine as long as rabbitmq is running again before the connect call. However, if rabbitmq is down and a connection refused is received the next connect call fails with:
`[E 160413 14:09:46 base_connection:335] Socket Error: 104
[E 160413 14:09:46 base_connection:168] Incompatible Protocol Versions`

I can reproduce this problem using the example code found here:
http://pika.readthedocs.org/en/latest/examples/tornado_consumer.html

Alter connect() (yeah I know this is a dirty hack...): 

```
        LOGGER.info('Connecting to %s', self._url)
         params = pika.ConnectionParameters(host='localhost', port=13372,
                                            virtual_host='/' )
         while 1:
             try:
                 conn = TornadoConnection(params,  on_open_callback=self.on_connection_open)
             except Exception as e:
                 logging.exception( "Bad stuff going on" )
                 time.sleep(1)
             else:
                 break
 
         return conn
```
 

To trigger the problem:
1. Stop rabbitmq
2. Start script
3. Start rabbitmq

Output:
```
ERROR      2016-04-13 15:09:25,499 root                           connect                              59  : Bad stuff going on
Traceback (most recent call last):
  File "pika_test.py", line 57, in connect
    conn = TornadoConnection(params,  on_open_callback=self.on_connection_open)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/tornado_connection.py", line 54, in __init__
    stop_ioloop_on_close)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 80, in __init__
    on_close_callback)
  File "/usr/local/lib/python3.4/dist-packages/pika/connection.py", line 613, in __init__
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/pika/connection.py", line 756, in connect
    error)
  File "/usr/local/lib/python3.4/dist-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/usr/local/lib/python3.4/dist-packages/pika/connection.py", line 1265, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: Connection to 127.0.0.1:13372 failed: [Errno 111] Connection refused
INFO       2016-04-13 15:09:26,501 pika.adapters.base_connection  _create_and_connect_to_socket        212 : Connecting to 127.0.0.1:13372
ERROR      2016-04-13 15:09:26,502 pika.adapters.base_connection  _handle_error                        335 : Socket Error: 104
ERROR      2016-04-13 15:09:26,502 pika.adapters.base_connection  _check_state_on_disconnect           168 : Incompatible Protocol Versions
WARNING    2016-04-13 15:09:26,502 pika.adapters.base_connection  _handle_ioloop_stop                  299 : Connection is closed but not stopping IOLoop
ERROR      2016-04-13 15:09:26,502 tornado.application            handle_callback_exception            629 : Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 384, in _handle_read
    data = self.socket.recv(self._buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 407, in _handle_read
    return self._handle_error(error)
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 338, in _handle_error
    self._handle_disconnect()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 288, in _handle_disconnect
    self._adapter_disconnect()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/tornado_connection.py", line 73, in _adapter_disconnect
    super(TornadoConnection, self)._adapter_disconnect()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 154, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/usr/local/lib/python3.4/dist-packages/pika/adapters/base_connection.py", line 169, in _check_state_on_disconnect
    raise exceptions.IncompatibleProtocolError
pika.exceptions.IncompatibleProtocolError

```

**Comment by gmr** [comment]
First off, don't use time.sleep with Tornado (or any IOLoop based implementation) -- you'd be better off scheduling a callback on the IOLoop (See http://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop.add_timeout)

I'd say the main bug you're reporting here is that ``pika.exceptions.IncompatibleProtocolError`` is being raised because the state is never being cleared when disconnected.  I'll take a look and see what's up there. You should be getting ``AMQPConnectionError`` each time.

What version of pika are you using?

**Comment by holljen** [comment]
Version 0.10.0.

And you're quite right about the time.sleep() it was just a quick way of triggering the problem with the example code :) Our own code uses timeouts and exhibits the same behaviour.

The pika.exceptions.IncompatibleProtocolError is being raised when rabbitmq is back up again.

**Comment by gmr** [comment]
| The pika.exceptions.IncompatibleProtocolError is being raised when rabbitmq is back up again.

That does help confirm the theory of the connection state not being reset on disconnect. I'll take a look and try and get a fix in soon.

**Comment by vitaly-krugl** [comment]
@gmr, this would likely be fixed when this and similar TODOs in connection.py are addressed: https://github.com/pika/pika/blob/5dc90ad8bce20687009d9e9ed358c84c4666d3f1/pika/connection.py#L1186

I was planning to work on this shortly.

**Comment by vitaly-krugl** [comment]
@holljen, a number of connection error handling inconsistencies have already been addressed in pika master. Are you getting the same results with current pika from the master branch?

**Comment by vitaly-krugl** [comment]
@holljen and @gmr: based on the logs, it looks like the user code is attempting to reconnect directly from the "on connection error" callback. If this is true (and it appears incredibly likely that it is), then it would explain why the state is not cleaned up yet at the time of the call;  see https://github.com/pika/pika/blob/5dc90ad8bce20687009d9e9ed358c84c4666d3f1/pika/connection.py#L1187-L1190.

**Comment by vitaly-krugl** [comment]
Also, my personal preference is not to re-connect an existing failed connection instance, but rather to instantiate a new connection instance after connection failure. Reconnecting an existing connection relies on a second code path for initializing connection state and connecting, which is likely not sufficiently tested, and on occasion gets out of sync with the main code path. Discarding the old connection instance and creating a new one should be more stable long-term.

**Comment by holljen** [comment]
@vitaly-krugl What exactly do you mean by a new connection instance? If you look a the example code above I create a new TornadoConnection for every connection retry which I considered to be a new connection instance, but I might be mistaken.

**Comment by vitaly-krugl** [comment]
@holljen: sorry, maybe my mistake in interpreting the logs and tracebacks. I see that `pika.Connection._on_connection_error()` gets called, which means that your code doesn't supply an "on connection error" callback to the connection constructor, so the default just raises `exceptions.AMQPConnectionError`. 

If your code doesn't re-connect the existing connection object (but creates a new connection object instead), then @gmr's theory
> That does help confirm the theory of the connection state not being reset on disconnect

might not apply here, since that would only come into play if you tried to re-connect an existing connection object (via its `connect()`) method.

Pika performs an opinionated analysis of the failure and translates it into exceptions that are guesses as to the cause of connection failure. For example, if the connection is lost while the connection is in the `CONNECTION_PROTOCOL` state, pika assumes that the broker dropped the connection because the protocol version supplied in the initial handshake message by the client is not acceptable by the broker, so pika maps the error to the `IncompatibleProtocolError` exception.

**Comment by vitaly-krugl** [comment]
To summarize the potential differences in behavior: In your case, since you don't pass the "on connection error" callback to the tornado adapter's constructor, if `socket.connect()` fails, you will get the `AMQPConnectionError` exception from the default `pika.Connection._on_connection_error` handler. On the other hand, if `socket.connect()` succeeds, then the pika connection transitions to the `CONNECTION_PROTOCOL` state; in this state, `pika.Connection` sends `frame.ProtocolHeader()` to the broker, and expects to receive `Connection.Start` from broker. If connection is lost before `Connection.Start` is received, then the released pika would raise `IncompatibleProtocolError`.

Note that with the latest changes in pika master branch, pika's async adapters communicate connection errors to the application via callbacks instead of exceptions in most cases.

**Comment by vitaly-krugl** [comment]
If rabbitmq comes up in a bad state (low on resources, or something else wrong with networking), then you might experience a problem like this when trying to connection again even when using a new connection object. Did you check rabbitmq logs? Also, WireShark now has support for AMQP and I've used it in the past to debug connectivity problems quite effectively.

**Comment by holljen** [comment]
I'm having success with pika master. Error is similar, but at least I can catch the exception now and retry the connect. I'll do some more testing and come back with the results.

I noticed however, that master is backwards incompatible with 0.10.0. The type parameter to Channel.exchange_declare was changed into exchange_type. Is this intentional?

**Comment by vitaly-krugl** [comment]
Thanks for the update. Regarding exchange `type` arg, this was a deprecated parameter (bad idea to name args and other variables using builtin names) that finally got removed; see https://github.com/pika/pika/blob/master/docs/version_history.rst

**Comment by holljen** [comment]
With master I get both a on_open_error AND a connection_closed callback when this connection issue occurs. (Now using my production code). 

Other than that it seems to me that the difference between master and 0.10 is that an exception was being raised somewhere where I couldn't get at it while in Master the callbacks are called as expected.

```
[I 160414 09:19:54 pikaclient:78] Starting PIKA connection
[I 160414 09:19:54 base_connection:216] Connecting to 127.0.0.1:13372
[E 160414 09:19:54 base_connection:348] Socket Error: 104
[I 160414 09:19:54 connection:1891] Disconnected from RabbitMQ at localhost:13372 (-1): ConnectionResetError(104, 'Connection reset by peer')
[W 160414 09:19:54 base_connection:309] Connection is closed but not stopping IOLoop
[E 160414 09:19:54 connection:1919] Incompatible Protocol Versions
[E 160414 09:19:54 connection:1954] Connection setup failed due to The protocol returned by the server is not supported: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
[W 160414 09:19:54 pikaclient:122] Pika open failed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
[W 160414 09:19:54 pikaclient:175] PIKA Connection closed unexpectedly. Reply (-1) ConnectionResetError(104, 'Connection reset by peer')
```

**Comment by vitaly-krugl** [comment]
Because I/O operations performed by async adapters are typically performed in the context of the ioloop, the exceptions were problematic, so we started favoring the callbacks over exceptions. 

The second callback provides more detailed info.

**Comment by vitaly-krugl** [comment]
Is it okay to close this issue?

**Comment by holljen** [comment]
I guess so. Thanks for already fixing this issue and rapid response! :+1:
