### ISSUE TITLE
BlockingConnection gets closed unexpectedly

### ISSUE THREAD

**Issue by bb-work** [pika/pika#734]
I'm using pika 0.10.0

I have code which opens a connection for publishing some data that comes in on a different channel.  It works great until there's a lull on the other channel, at which point the connection gets closed, and I get a ConnectionClosed() exception when I try to publish.  I've tried adding a heartbeat with different interval values, which had no effect.

Relevant code:

class RabbitPublish(object):
    def __init__(self, username='xxxx', password='xxxx', host='xxxx', port=xxxx,
                 exchange_name='xx', logger=logHelper("log.txt"),
                 virtual_host='xx', **kwargs):

        self.logger = logger

        self.exchange = exchange_name
        credentials = pika.credentials.PlainCredentials(username, password)
        self.parameters = pika.ConnectionParameters(host, port, virtual_host, credentials, heartbeat_interval=HEART_BEAT)

    def connect(self):
        self.connection = pika.BlockingConnection(self.parameters)
        self.channel = self.connection.channel()
        self.channel.exchange_declare(exchange=self.exchange, type='fanout', durable=True, passive=False)
        self.logger.info('connecting to {}'.format(self.exchange))

    def publish(self, body, prop_params=dict(content_type='text/plain')):

        if prop_params:
            properties = pika.BasicProperties(**prop_params)
        else:
            properties = None

        self.channel.basic_publish(exchange=self.exchange, routing_key='', body=body, properties=properties)

**Comment by vitaly-krugl** [comment]
Hi @bb-work, BlockingConnection implementation is synchronous and runs entirely only in your thread when you make a call to the connection or channel. It has no background thread. So, if the time between I/O calls into your pika connection/channel exceeds the connection heartbeat timeout, RabbitMQ broker will close your connection. Rabbit's default connection timeout used to be 580 seconds, but they dropped it down to 60 seconds in recent versions.

If this is the problem, then you can work around it by increasing the heartbeat timeout. You can change the default heartbeat timeout in your RabbitMQ configuration. You should also be able to increase the connection heartbeat timeout or completely disable it from the client side via pika.ConnectionParameters, but there is a caveat that you need to be aware of: The presently-released versions of pika (on PyPi) don't allow you to increase the heartbeat timeout (it picks the lowest of the two values: the one proposed by RabbitMQ during connection setup and what's provided by the user in pika ConnectionParameters). The version in pika master changed this to pick the max of the two.

So, from the client side, you should be able to disable the heartbeat timeout via ConnectionParameters by setting the value to 0 (please post here if this doesn't work), or you can use the version of pika from Master to specify a higher timeout value (in seconds) that would meet your requirements.

**Comment by vitaly-krugl** [comment]
@bb-work, besides the suggestions in my previous comment, you should also check the RabbitMQ logs to help diagnose the issue. I am going to close this issue for now. If you have further insights related to it, please post them here, and we may reopen it if needed.
