### ISSUE TITLE
__enter__ / __exit__ methods on Connection/Channel

### ISSUE THREAD

**Issue by pfhayes** [pika/pika#736]
Would these be beneficial, or are they omitted intentionally? Happy to make a PR myself that introduces this functionality

**Comment by vitaly-krugl** [comment]
Connection and Channel classes are at the asynchronous (non-blocking) core of pika. The context manager methods don't make sense in async API. They are more appropriate for the blocking API. See `__enter__/__exit__` in the `BlockingConnection` class.

**Comment by pfhayes** [comment]
great that's what I was looking for - thanks!

**Comment by pfhayes** [comment]
I notice that the BlockingChannel does not have an __enter__/__exit__ - would that be an appropriate addition vs. closing the BlockingChannel manually?

**Comment by vitaly-krugl** [comment]
@pfhayes, PEP-343 on BlockingChannel sounds reasonable to me. @gmr?

We're hoping to cut a new release in the near future, so this change might not get merged until after the release.

PR #629 added PEP-343 in BlockingConnection. See that PR for test examples. Pika's channels have an additional caveat: if attempting to close a channel that's already closed, the channel raises `ChannelClosed` exception. So, you will need to take this into account in both implementation and tests.
