### ISSUE TITLE
Implement acceptance and unit tests for SSL/TLS connectivity

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#744]
This includes the following tasks:
1. Configure RabbitMQ server in the CI build to accept the desired SSL/TLS connections (see #742 for a basic example)
   1. Travis/Linux
   2. Travis/OS X
   3. AppVeyor/windows
2. Unit tests (with mocked-out connection) of ssl-specific code paths, including the WANT_READ in `BaseConnection._handle_read`.
3. Acceptance tests
   1. Connection with server-only cert verification
   2. Connection with mutual cert verification
   3. sending/receiving several very large messages, with verification of content
   4. sending/receiving many small messages, with verification of content

**Comment by hasB4K** [comment]
Because of #765, the tests should me also made on Centos :)

**Comment by vitaly-krugl** [comment]
@hasB4K, it appears that #765 was due to openssl eliminating the weak crypto. See https://github.com/pika/pika/issues/765#issuecomment-247906951.

**Comment by vitaly-krugl** [comment]
@lukebakken, I would like to fix/clean up SSL support in pika. Could you please help by enabling RabbitMQ to accept SSL connections in addition to plaintext on all Travis-CI and AppVeyor builds? Also provide rudimentary documentation where the client test code can find the necessary artifacts (e.g., public cert).

See https://github.com/pika/pika/blob/master/docs/examples/tls_mutual_authentication.rst and https://github.com/pika/pika/blob/master/docs/examples/tls_server_uathentication.rst for examples.

**Comment by lukebakken** [comment]
We can fix [this `TODO`](https://github.com/pika/pika/blob/master/pika/adapters/base_connection.py?utf8=%E2%9C%93#L405-L408) once SSL tests are in place.

**Comment by lukebakken** [comment]
This has effectively been in place for a while now ever since TLS/SSL was enabled on Travis, and @vitaly-krugl did the big refactor of connection workflow.

**Comment by vitaly-krugl** [comment]
@lukebakken  - but don't we want to have TLS/SSL test automation in place? I think we need it. In the past, such things got broken periodically because there were not tests. Having an open ticket for it is a good way to make sure it doesn't fall through the cracks.

**Comment by lukebakken** [comment]
It is in place, first the test suite is run without TLS, then TLS is enabled on all connections. RabbitMQ is set up to accept TLS listeners on port 5671:

https://github.com/pika/pika/blob/master/.travis.yml#L55-L61
https://github.com/pika/pika/blob/master/.travis.yml#L45
https://github.com/pika/pika/blob/master/testdata/rabbitmq.conf.in

**Comment by vitaly-krugl** [comment]
@lukebakken , thanks for the clarification. I remember a while back you had to disable TLS tests (in one of the environments, perhaps?) due to an issue with getting RabbitMQ server to install properly for TLS there or something like that.

**Comment by lukebakken** [comment]
Something like that! Or maybe a Travis issue?
