### ISSUE TITLE
Crash on massive sending

### ISSUE THREAD

**Issue by Silver90** [pika/pika#747]
Hi all, I've a rabbitmq instance on Vagrant installed with docker, and a script (written for Python3.4 and Pika last version) that send messages in loop to the server.

When I send about 500 messages, the server stay open but close the connection created by the script, and the script crash with this traceback

```
=INFO REPORT==== 3-May-2016::08:15:14 ===
accepting AMQP connection <0.1151.0> (172.18.0.1:50055 -> 172.18.0.2:5672)

=ERROR REPORT==== 3-May-2016::08:18:05 ===
closing AMQP connection <0.671.0> (172.18.0.3:57626 -> 172.18.0.2:5672):
writer,send_failed,{error,timeout}}
Traceback (most recent call last):
 File "code/server.py", line 199, in <module>
   channel.start_consuming()
 File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
   self.connection.process_data_events(time_limit=None)
 File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 647, in process_data_events
   self._flush_output(common_terminator)
 File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 426, in _flush_output
   raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
ololog exited with code 1

=WARNING REPORT==== 3-May-2016::08:19:01 ===
closing AMQP connection <0.1151.0> (172.18.0.1:50055 -> 172.18.0.2:5672):
client unexpectedly closed TCP connection
```

If I use the same rabbitmq+docker version without Vagrant, the problem doesn't occour. Should I consider a library problem?

**Comment by vitaly-krugl** [comment]
It would be interesting to know why RabbitMQ decided to close AMQP connection. It might be some sort of networking issue when Vagrant is in the picture

Several things would help:

1. Version of rabbitmq, pika, and relevant OS
2. Simplified python script using `BlockingConnection` that reproduces the problem on your rabbit+docker+vagrand configuration
3. Debug logs from pika: `import logging; logging.basicConfig(level=logging.DEBUG)` before creating `BlockingConnection`.

**Comment by Silver90** [comment]
Ok I followed the steps that you have requested:

- Rabbitmq 3.6.1, ubuntu 14.04.4, pika 0.10.0
- Now use BlockingConnection

And this is the result of logging:
```
=ERROR REPORT==== 4-May-2016::09:03:06 ===
closing AMQP connection <0.395.0> (172.18.0.3:49855 -> 172.18.0.4:5672):{writer,send_failed,{error,timeout}}

ERROR:pika.adapters.base_connection:Error event 25, None
CRITICAL:pika.adapters.base_connection:Tried to handle an error where no error existed
DEBUG:pika.heartbeat:Received 2 heartbeat frames, sent 2
DEBUG:pika.heartbeat:Sending heartbeat frame
ERROR:pika.adapters.base_connection:Socket Error: 104
DEBUG:pika.heartbeat:Removing timeout for next heartbeat interval
WARNING:pika.adapters.base_connection:Socket closed when connection was open
DEBUG:pika.callback:Added: {'only': None, 'calls': 1, 'arguments': None, 'one_shot': True, 'callback': <bound method SelectConnection._on_connection_start of <pika.adapters.select_connection.SelectConnection object at 0x7f2251e84dd8>>}
WARNING:pika.connection:Disconnected from RabbitMQ at olorabbitmq:5672 (0): Not specified
DEBUG:pika.callback:Processing 0:_on_connection_closed
DEBUG:pika.callback:Calling <bound method _CallbackResult.set_value_once of <pika.adapters.blocking_connection._CallbackResult object at 0x7f224f67dcc8>> for "0:_on_connection_closed"
CRITICAL:pika.adapters.blocking_connection:Connection close detected
Traceback (most recent call last):
File "code/server.py", line 201, in <module>
channel.start_consuming()
File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
self.connection.process_data_events(time_limit=None)
File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 647, in process_data_events
self._flush_output(common_terminator)
File "/usr/local/lib/python3.4/site-packages/pika/adapters/blocking_connection.py", line 426, in _flush_output
raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
```

**Comment by vitaly-krugl** [comment]
Please attach a simple script using BlockingConnection that reproduces the lost connection.

From what the pika logs show, it appears that pika simply detected a lost socket connection. Pika in the master branch has had a number of improvements to connection error handling, so you might want to repeat your experiment.

It could be an error somewhere else in your stack that causes the connection to drop. Take a careful look through rabbitmq logs.

**Comment by vitaly-krugl** [comment]
@Silver90 Is it okay to close this issue?

**Comment by Silver90** [comment]
Yes, sorry if I answered late. I have partially solved by setting heartbeat to 0 (Consumer), restart always on docker-compose file and set message durable (from client). 
However, this problem occurs only if I use vagrant in ubuntu does not happen.

**Comment by vitaly-krugl** [comment]
Thanks for the update. Closing...
