### ISSUE TITLE
Please add (beta) release containing fix for `nowait` blocking channel rpc

### ISSUE THREAD

**Issue by reallistic** [pika/pika#758]
Please add release with this commit:
https://github.com/pika/pika/commit/9598b4391647ca0a9e0e48dbe87d66aa116dae50#diff-831cec7ce02158498fb9bb8d1fd55451R1288

**Comment by reallistic** [comment]
The latest code still has some bugs so I am closing this.

**Comment by vitaly-krugl** [comment]
@reallistic, could you please be more specific about "The latest code still has some bugs"? Are you referring to #759?
