### ISSUE TITLE
Some synchronous channel methods allow nowait but require callback

### ISSUE THREAD

**Issue by reallistic** [pika/pika#759]
This is true for `Channel.queue_bind` and `Channel.queue_declare`.

**Comment by lukebakken** [comment]
Using `nowait=True, callback=None` as parameters is the correct way to enable `nowait` without a callback.

**Comment by vitaly-krugl** [comment]
@lukebakken, there is no reference to the PR that fixes this issue. Did you close it by accident? Thx.

**Comment by lukebakken** [comment]
> Did you close it by accident?

No because it appears that Pika is working by design. Using `nowait=True, callback=None` as parameters is the correct way to enable `nowait` without a callback method.
