### ISSUE TITLE
BlockingChannel.consume yields either a 3-tuple or None

### ISSUE THREAD

**Issue by Serafean** [pika/pika#760]
When using the consumer generator (as from example) with inactivity_timeout set;
if the inactivity timeout triggers, the entire for cycle fails.

for method_frame, header_frame, body in __channel.consume(queue=configuration.rabbitQueue, inactivity_timeout=5):
   do_stuff(method_frame)

Will raise :
TypeError: 'NoneType' object is not iterable
if the timeout is triggered.

suggestion : in blocking_connection.py:1811
 -  yield None
 + yield (None, None, None)

Or fix documentation to include "raises TypeError on timeout"

**Comment by vitaly-krugl** [comment]
@Serafean, thanks for the feedback. I added the `inactivity_timeout` feature and, in retrospect, I think that I would now prefer `yield (None, None, None)` in this case. However, the current behavior is already in an official release and likely already in use, so I would hate to break those apps.

Another option would be to add a second example to the method's docstring:

```
for msg in channel.consume('queue', inactivity_timeout=5):
    if msg is None:
        print "timeout"
        continue

    method, properties, body = msg
    print body
    channel.basic_ack(method.delivery_tag)
```

@gmr, could you please chime in with your decision on above two options? Thx.

**Comment by Serafean** [comment]
IMHO not only adding the example, but also modifying the existing one to discourage the assumption that consume() always yields a 3-tuple.

**Comment by dunk** [comment]
This just bit me. Yes, it is in some production code which is a pity because clearly the correct way to do this is to `yield (None, None, None)`. +1 for making that the default (at some point)

**Comment by vitaly-krugl** [comment]
Yeah, I would like to clean this up; waiting for guidance from @gmr.

**Comment by dunk** [comment]
While it might require changes in all clients it's only going to be a change that everyone wants to do - i.e. to remove that mandatory special-casing code.

**Comment by vitaly-krugl** [comment]
Anyone wish to submit a PR for `yield (None, None, None)`, including updated tests and documentation?

**Comment by vitaly-krugl** [comment]
Technically, since pika is < v1.0, it should be reasonable to make breaking improvements like this, and I think we did a little of that in the previous release cycle.

**Comment by mathieulongtin** [comment]
Instead of special casing the iterator, why not just stop the consumer when it times out?

The above code would become:
```
while True:
    for method, properties, body in channel.consume('queue', inactivity_timeout=5):
        print body
        channel.basic_ack(method.delivery_tag)
    print "got inactivity timeout"
```

**Comment by LPiner** [comment]
+1 @mathieulongtin 

Raising an exception for this is just strange.

**Comment by lukebakken** [comment]
@mathieulongtin - I decided that returning `(None, None, None)` would be less surprising behavior to users based on [this comment](https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L1809-L1815).
