### ISSUE TITLE
publish confirm, missing ack or nack

### ISSUE THREAD

**Issue by hduzh** [pika/pika#761]
I put http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_publisher_example.html and http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html combined in one thread. But there is a strange problem:
trace:rabbit_server.py(281),pika_delivering_debug,cur_delivery_num=1078,delivering_msgs_len=2,delivering_msgs=[541, 599]
as you see, some msg acks or nacks are lost.
I also registered return_callback, but msg 541, 599 aren't returned.
Any ideas? thank you.

**Comment by vitaly-krugl** [comment]
@hduzh, have you made any progress resolving this? Please update this issue. Thx.

**Comment by lukebakken** [comment]
When reporting an issue, please try to be as descriptive as possible which helps Pika developers resolve issues quickly.

* Include the operating system, broker version (RabbitMQ version), Python version
* Include the full set of working code necessary to reproduce the issue
* Include a clear statement of what you expect to see and what you saw
* If you include a stack trace, include it as a text file attachment, not in-line in the issue

If you can provide the above information, please do so and re-open this issue. Thank you!
