### ISSUE TITLE
Issue with exiting when using the Example (async) Consumer in a Process

### ISSUE THREAD

**Issue by pazzo83** [pika/pika#763]
Hello,

I am having an issue gracefully exiting when I wrap a pika consumer inside of a python process (using multiprocessing).  The idea here is I'd like to spin up several rabbit mq connections, each to a specific process.

My issue is that when I try to handle a KeyboardInterrupt, and I call the consumer's "stop()" method, I get the following error:

```
AttributeError: 'ExampleConsumer' object has no attribute '_channel'
```

It seems both the _channel attribute and the _connection attribute disappear by the time it enters the "except" part of my try/except for handling the KeyboardInterrupt.  I have verified that they are created when "run()" is called.

Here is a basically the code in question.  First, my process:

```
class RabbitConsumer(multiprocessing.Process):
    def __init__(self, bot_id, exchange, callback_func, rabbit_user, rabbit_pw, rabbit_host,
                 rabbit_port, *args, **kwargs):
        super(RabbitConsumer, self).__init__(*args, **kwargs)
        self.ec = ExampleConsumer(bot_id, exchange, callback_func, rabbit_user, rabbit_pw, rabbit_host, rabbit_port)

    def run(self):
        try:
            self.ec.run()

        except KeyboardInterrupt:
            self.ec.stop()

    def terminate(self):
        self.ec.stop()
        super(RabbitConsumer, self).terminate()
```

ExampleConsumer is essentially the one from the docs unchanged with the exception of some minor things in the **init**
Note that the stacktrace from the exception is coming from the "self.ec.stop()" in the process's "terminate" method, so the KeyboardInterrupt is being picked up from the code below.

I start my wrapper processes this way:

```
for proc in self.consumers:
            proc.start()
        try:
            for proc in self.consumers:
                proc.join()
        except KeyboardInterrupt:
            for proc in self.consumers:
                proc.terminate()
                proc.join(1)
```

Any idea what is happening here?

Thanks!

**Comment by lukebakken** [comment]
Please provide a *complete* set of code that the Pika team can use to reproduce and diagnose this issue. We do not have the time to guess and try to re-create it. If you do so, attach the code to this issue in a text file and re-open it. Thanks!
