### ISSUE TITLE
connection created by BlockingConnection() close blocked

### ISSUE THREAD

**Issue by mnoky** [pika/pika#764]
I'm encountering a situation where channel.close() blocks forever. This is very similar to issue #661 and #147, but I have a succinct test case to consistently reproduce this. Here's the key: the issue only happens once the disk space threshold has been reached for the RabbitMQ server.

Using: pika 0.10.0, RabbitMQ 3.5.6-1, python 2.7.11 on Ubuntu 14.04

First, simulate a "disk full" condition for RabbitMQ. Edit the RabbitMQ config file `/etc/rabbitmq/rabbit.config` and add set the `disk_free_limit` param to something high, e.g.:
```
{disk_free_limit, 9000000000000}
```

Next, use the test code provided in issue #147. It will hang on `connection.close()`. If you terminate the program, the following stack trace will be produced:
```
Traceback (most recent call last):
  File "qtest.py", line 14, in <module>
    channel.close()
  File "/usr/local/python2env/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1343, in close
    self._flush_output(close_ok_result.is_ready)
  File "/usr/local/python2env/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/usr/local/python2env/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/python2env/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 590, in poll
    events = self._poll.poll(self.get_next_deadline())
KeyboardInterrupt
```

I've seen this problem happen in other pika calls as well, such as `channel.queue_declare()`. The same hang happens and terminating the program produces a similar stack trace: 
```
Traceback (most recent call last):
  File "myprogram.py", line 167, in <module>
    main()
  File "myprogram.py", line 162, in main
    run()
  File "myprogram.py", line 120, in run
    channel.queue_declare(queue=queue_name, durable=True)
  File "/usr/local/pythonenv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "/usr/local/pythonenv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/usr/local/pythonenv/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/pythonenv/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 590, in poll
    events = self._poll.poll(self.get_next_deadline())
```

This is particularly bad in my case because the consumer process first calls `channel.queue_declare()` to make sure the queue exists before consuming. However, when the "disk full" situation happens, the consumer application cannot even start because of that blocking problem!

**Comment by osteenbergen** [comment]
I have the same issue but using a different test method. Running netcat (``nc -k -l 5672``) and pointing pika to it results in a hanging process during connection. Stack trace is the same.

Setting timeouts doesn't work as the connection is established, but the server doesn't respond.

**Comment by vitaly-krugl** [comment]
cc @gmr 

@mnoky, you haven't provided any debug-level logs of your session, so it's hard to surmise exactly what is happening. Most likely, your connection is subject to being blocked by RabbitMQ that is signaled to the client via connection.blocked, which is RabbitMQ's extension to AMQP protocol; see https://www.rabbitmq.com/connection-blocked.html.

You can often gain valuable insight by enabling DEBUG-level logging before starting the connection and observing the log. Personally, I really like the free WireShark protocol analyzer from www.wireshark.org, as it now supports AMQP.

I added a feature to `ConnectionParamters` via the `blocked_connection_timeout` argument that might/should help if you're talking to a real RabbitMQ server (it won't help in the fake `nc -k -l 5672` case); see  https://github.com/pika/pika/blob/5dc90ad8bce20687009d9e9ed358c84c4666d3f1/pika/connection.py#L571

Note that the `blocked_connection_timeout` arg is not in the released version of Pika, so you would need to get Pika from master to try it.

Please post how it went. If `blocked_connection_timeout` didn't work for you, please collect AMQP protocol information from your session via WireShark and post a gist link here. I am going to close the issue for now, but can re-open if needed.

**Comment by mnoky** [comment]
Thanks Vitaly. I tried out Pika from the master and set `blocked_connection_timeout`. It worked like a charm! Debug messages indicate that the server does indeed send back a reason why the operation failed:

```
WARNING:pika.connection:Received <METHOD(['channel_number=0', 'frame_type=1', "method=<Connection.Blocked(['reason=low on disk'])>"])> from broker
```

One followup question: Is an official new release due anytime soon?

**Comment by vitaly-krugl** [comment]
I am glad that `blocked_connection_timeout` in master branch worked for you. Thanks for following up.

Regarding:
> One followup question: Is an official new release due anytime soon?

@gmr has been pretty busy, but I hope some cycles will free up soon for an official release.

**Comment by mnoky** [comment]
Do you have a sense if the master branch is fairly stable? If so, it might be worthwhile for us to use that. Thanks again!

**Comment by vitaly-krugl** [comment]
@mnoky, I can't speak for myself, as I am not a major user at this moment, although I continue to pitch in. However, here is a recent post on google groups that is quite positive: https://groups.google.com/forum/#!topic/pika-python/RRt3zBeDhQU. Perhaps you can follow up there?
