### ISSUE TITLE
Pika can connect to RabbitMq with tls/ssl on ubuntu, but not work on Centos?

### ISSUE THREAD

**Issue by fengyiyingdong** [pika/pika#765]
The same code can work on Ubuntu, not work on Centos! Firewall already closed!

Ubuntu 16.04, python version 3.5.2. 

Centos 7,python version 3.5.2.

Ubuntu and centos are the newly installed in virtualbox! 

On centos, client can connect to server with no ssl, but if connect to server with ssl, it will be fail!

Can you help me? Thanks very much!

This the code:

```
 #!/usr/bin/env python3.5
    import pika
    import ssl
    
    ssl_options = {    
        "ca_certs":"/root/ca/private/ca.crt",
        "certfile": "/root/ca/rbq/client.crt",
        "keyfile": "/root/ca/rbq/client.key",
        "cert_reqs": ssl.CERT_REQUIRED,
        "ssl_version":ssl.PROTOCOL_TLSv1_2
    }
    credentials = pika.PlainCredentials('ttttt', '123456')
    parameters = pika.ConnectionParameters(host='192.168.1.164',
                                           port=5671,
                                           virtual_host='/',
                                           heartbeat_interval = 0,
                                           credentials=credentials,
                                           ssl = True,
                                           ssl_options = ssl_options)
    connection = pika.BlockingConnection(parameters)
    connection.close()
```

This the error msg:

`Traceback (most recent call last):
      File "./rb.py", line 20, in <module>
        connection = pika.BlockingConnection(parameters)
      File "/usr/local/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
        self._process_io_for_connection_setup()
      File "/usr/local/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
        self._open_error_result.is_ready)
      File "/usr/local/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
        raise exceptions.ConnectionClosed()
    pika.exceptions.ConnectionClosed`

This rabbitmq server log:

```
 [root@master1 rabbitmq]# tail rabbit@master1.log 
    SSL: certify: ssl_alert.erl:93:Fatal error: decrypt error
    
    =INFO REPORT==== 22-Aug-2016::12:50:48 ===
    accepting AMQP connection <0.22118.20> (192.168.1.131:48526 -> 192.168.1.164:5671)
    
    =INFO REPORT==== 22-Aug-2016::12:50:48 ===
    closing AMQP connection <0.22118.20> (192.168.1.131:48526 -> 192.168.1.164:5671)
    
    =ERROR REPORT==== 22-Aug-2016::12:54:04 ===
    SSL: certify: ssl_alert.erl:93:Fatal error: decrypt error
```

**Comment by vitaly-krugl** [comment]
@fengyiyingdong, does the information in pull request #742 help with your issue?

**Comment by fengyiyingdong** [comment]
Thanks!  My problem have 

My server certificate (the one in ca/server/server.crt) uses md5WithRSAEncryption as the signature algorithm. That is going to be a problem. [](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Using_OpenSSL.html)  states that "Verification of signatures using the MD5 hash algorithm is disabled in Red Hat Enterprise Linux 7 due to insufficient strength of this algorithm. Always use strong algorithms such as SHA256."

It is likely that the openssl in Ubuntu is going to drop support for md5 signature algorithms some day as well, so you would better update the certificate.

**Comment by vitaly-krugl** [comment]
@fengyiyingdong, thank you for the update.

**Comment by prashantvidja** [comment]
@fengyiyingdong 
I have generated cert with tls_gen but not working for me.
https://github.com/michaelklishin/tls-gen
Could you please tell me how you have created the certificate?
Thanks
