### ISSUE TITLE
Using binary correlation ID gives UnicodeDecodeError in Python 3

### ISSUE THREAD

**Issue by arthur-tacca** [pika/pika#769]
Passing binary data as the correlation ID gives a UnicodeDecodeError on the recipient side (unless that binary data happens to be bytes of a UTF-8 encoded string). Here is a minimal example to reproduce:

https://gist.github.com/arthur-tacca/d3d05bdf5640807a46deda95a131d5bf

It both publishes to a queue and reads from the queue within the same process, but obviously this normally happens in separate client and server processes. You would also normally include a `reply_to` queue in the message properties. Neither of these affect the bug.

There is a small chance that you will need to run it multiple times to get the error, but it fails for me every time. Here is the end of the stack trace:

```
  File "/home/arthur/env3/lib/python3.5/site-packages/pika/connection.py", line 1343, in _on_data_available
    consumed_count, frame_value = self._read_frame()
  File "/home/arthur/env3/lib/python3.5/site-packages/pika/connection.py", line 1435, in _read_frame
    return frame.decode_frame(self._frame_buffer)
  File "/home/arthur/env3/lib/python3.5/site-packages/pika/frame.py", line 250, in decode_frame
    out = properties.decode(frame_data[12:])
  File "/home/arthur/env3/lib/python3.5/site-packages/pika/spec.py", line 2119, in decode
    self.correlation_id, offset = data.decode_short_string(encoded, offset)
  File "/home/arthur/env3/lib/python3.5/site-packages/pika/data.py", line 65, in decode_short_string
    value = encoded[offset:offset + length].decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 3: invalid start byte
```

It seems to me there are two possibilities here. Which is correct depends on other RabbitMQ clients, not just pika. My suspicion is that the first is true.
- The correlation ID can be arbitrary binary data. In this case, the bug is that the recipient attempts to decode it; instead it should be returning the raw bytes, and leave it up to the application to decide whether to interpret it as UTF8 bytes with `.decode()` or as something else. Additionally, on the sending side, objects of type `str` (in Python 3) or `unicode` (in Python 2) should not be accepted; again, it is up to the application to encode such strings as UTF8 bytes (or some other encoding) if it so wishes.
- Alternatively, the correlation ID is defined to be a unicode string (which is transmitted using UTF8 encoding on the wire, but no application should ever know or care about this). In this case, `bytes` objects should not accepted in the sender code. (For backwards compatibility, `str` should probably be accepted in Python 2 but only if it only includes ASCII characters.)

This was tested using pika 0.10.0, with both Python 3.4 (on Windows) and Python 3.5 (on Ubuntu). Looking at the Python 2 code in `data.py`, in the `decode_short_string` function, it looks like strings are never decoded from UTF8. (There is a statement `value = bytes(value)` wrapped in a `try` / `except UnicodeEncodeError` block, but I think `value` is a `str` object, and in Python 2 `bytes` is a synonym for `str`, so this statement does nothing. This may explain the comment above that says "No idea what this does and why".)

On another note, when there is some error in the expected format of a message header, surely pika should acknowledge it before raising an exception? Otherwise the message will stay in the queue forever, even if the consumer attempts to consume the message again (often in an infinite loop).

**Comment by lukebakken** [comment]
Thank you very much for the code to reproduce this issue.

> On another note, when there is some error in the expected format of a message header, surely pika should acknowledge it before raising an exception?

Doing so could result in a lost message, so we won't be changing that behavior.

I'm investigating the decode issue now.

**Comment by lukebakken** [comment]
Here is how the RabbitMQ Java client [writes a `shortstr`](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ValueWriter.java#L43-L56) and [reads a `shortstr`](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ValueReader.java#L61-L70). It appears that the data is assumed to be UTF-8.

I will investigate an implementation that defaults to UTF-8 encoding with the option of plain 'ol bytes.

**Comment by lukebakken** [comment]
@arthur-tacca - the PR isn't ideal, but it solves the issue you raise. Thank you again for providing the report and code.

**Comment by everilae** [comment]
About "It appears that the data is assumed to be UTF-8", that's how the AMQP spec defines short-strings in 4.2.5.3  Strings.
