### ISSUE TITLE
_PollerBase.add_timeout needs to write to _w_interrupt.

### ISSUE THREAD

**Issue by hodgestar** [pika/pika#771]
Currently at https://github.com/pika/pika/blob/master/pika/adapters/select_connection.py#L300 a new timeout is added. If the select loop is already sleeping for longer than the timeout, it will continue to sleep. The ``add_timeout`` function needs to write a byte to the interrupt socket pair to wake up the select loop.

**Comment by vitaly-krugl** [comment]
@hodgestar, a pika connection is not thread-safe, so nothing should be calling add_timeout when the the select loop is sleeping. See

* http://pika.readthedocs.io/en/latest/faq.html

**Comment by hodgestar** [comment]
Thank you for the link to the documentation, but I have already read it. As described in the docs you link to, I have a connection per thread and would like to notify the connection in the thread that it needs to wake up so that it can publish an event. Pika already handles this case when stopping a connection in a thread.

**Comment by vitaly-krugl** [comment]
In order to support making `add_timeout` thread-safe, simply writing to `_w_interrupt` would not suffice. The event loop (at least the timer management) would need to be made thread-safe, too.

**Comment by vitaly-krugl** [comment]
That said, I think that this is a good example of something that may be worthwhile to have in BlockingConnection: http://www.tornadoweb.org/en/stable/ioloop.html#callbacks-and-timeouts. The callback itself could then make other calls to the pika connection safely.

**Comment by hodgestar** [comment]
Correct.

**Comment by vitaly-krugl** [comment]
@hodgestar, please feel free to open a new issue regarding `add_callback`. And if you're inclined to submit a pull request, including tests, for review, that would be welcome, too.

**Comment by vitaly-krugl** [comment]
@hodgestar: That said, I think that a thread-safe `add_callback` in Tornado is a good example of something that may be worthwhile to have in BlockingConnection: http://www.tornadoweb.org/en/stable/ioloop.html#callbacks-and-timeouts. The callback itself could then make other calls to the pika connection safely.

**Comment by vitaly-krugl** [comment]
@hodgestar, please feel free to open a new issue regarding `add_callback`. And if you're inclined to submit a pull request, including tests, for review, that would be welcome, too.
