### ISSUE TITLE
Correct/recommended message payload type in python2/3

### ISSUE THREAD

**Issue by senseysensor** [pika/pika#773]
Sorry for posting question here, but have no idea about better place for this,

migrating project to python 3 I try to figure what is best / recommended type of message payload? For the moment I want to keep compatibility with 2nd python version. I haven't found anything concrete in the documentation, seems I can either forcibly encode all places in the code to pass bytes or in opposite decode to pass payload at text. Even if this doesn't matter and both will work, I suppose there should be some best practices. Thanks for your advices.

ps - before there was some option to open channel with force binary option, but now there is no this option. So I am not sure about all this, great if you give some hints in documentation.

**Comment by vitaly-krugl** [comment]
Hi @senseysensor, please post on https://groups.google.com/forum/#!forum/rabbitmq-users or https://groups.google.com/forum/#!forum/pika-python. Thanks!
