### ISSUE TITLE
ConnectionClosed exception when connecting to remote RabbitMQ server on EC2

### ISSUE THREAD

**Issue by kirang89** [pika/pika#774]
I've been trying to connect to a remote RabbitMQ instance on EC2, but I keep getting the `pika.exceptions.ConnectionClosed` exception. Here's the sample code I used: 

```
import pika

def main():
    c = pika.PlainCredentials('testuser', 'testuser')
    params = pika.ConnectionParameters(host="<public ip>", port=5672, virtual_host="/", credentials=c)
    connection = pika.BlockingConnection(params)

    channel = connection.channel()
    channel.queue_declare(queue='words')

    channel.basic_publish('test_exchange', routing_key='words', body='hello')
    connection.close()
```

It works fine when connecting to a local RabbitMQ instance. Just to dismiss any issue related to the remote setup, I tried using another client like haigha to connect, and it worked just fine. 

I'm not sure what the exception is about. Any help would be appreciated. Thanks!

**Comment by lukebakken** [comment]
There should be more information provided by `ConnectionClosed` like error code. If you can provide more information, please re-open this issue. Thank you.
