### ISSUE TITLE
Queue not being bound quickly

### ISSUE THREAD

**Issue by anthok** [pika/pika#777]
We are using pika with multiple queues and asynchronously consuming them with over 2000 messages in total. The problem is that when trying to declare_and_bind() a new a queue, the queue will be created after a short delay but it will then take over 2 minutes for it to actually be bound, resulting in lost messages.

Any ideas?

Thanks guys

**Comment by vitaly-krugl** [comment]
That would make all the pika tests that declare and bind a queue take forever to complete, but they don't take that long. 

A good place to start is:

1. Create a tiny, focused code sample that reproduces your issue
2. Examine the server logs
3. Examine AMQP traffic using the free WireShark protocol analyzer
4. Examine pika's debug-level logs.

**Comment by vitaly-krugl** [comment]
Your app is not using a connection (or its channels) from multiple threads, is it?

**Comment by anthok** [comment]
The problem doesn't start happening until there is over 2000 messages in total. We are just using the async consumer to process multiple queues.

**Comment by anthok** [comment]
We ended up redoing our queuing system and it all works great now. Thanks for the help!
