### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dzen** [pika/pika#782]
Hi ! Is there any release scheduled ?

Is there any roadmap to look for, or any blocking bugs ?
Thank you.

**Comment by danslapman** [comment]
Really need blocked_connection_timeout support!

**Comment by hassonofer** [comment]
Can anyone please comment on this

**Comment by dacox** [comment]
I am also curious about this - I see there have been some bug fixes and was wondering if there is a reason that no new release has been uploaded to PyPi.

**Comment by ecederstrand** [comment]
Ping? We're hitting #659 and would be glad for a minor release :-)

**Comment by gmr** [comment]
I've got some time set aside this weekend to review things with a goal to get a pre-release of the next version out.

**Comment by eldhart** [comment]
Also looking forward to a new release, glad to see I'm not alone :)

**Comment by bobintornado** [comment]
pointing to master branch in my requirements.txt already and can't get my stuff working without `socket_timeout`. (my network is just a bit slow)

**Comment by lukebakken** [comment]
We are working on `0.11.0`. Thanks for your interest in Pika.
