### ISSUE TITLE
Cannot connect over ssl

### ISSUE THREAD

**Issue by gitstn** [pika/pika#783]
Hi

I posted this over rabbitmq-users mailing list as well, posting it here to get if this is something pika specific.

I am using python pika, the issue I am seeing is that on the localhost where I am running the broker, I can connect over ssl using url amqps://user:pass@localhost/%2F or even amqps://user:pass@brokerhost/%2F, but if I try the same from a different host using the url amqps://user:pass@brokerhost/%2F, the exact same python script throws following exception

Traceback (most recent call last):

  File "pikarcv.py", line 8, in <module>

    connection = pika.BlockingConnection(parameters)

  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 339, in __init__

    self._process_io_for_connection_setup()

  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup

    self._open_error_result.is_ready)

  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output

    raise exceptions.ConnectionClosed()

pika.exceptions.ConnectionClosed

and on the broker, I get following errors logged

=CRASH REPORT==== 23-Nov-2016::04:49:00 ===

  crasher:

    initial call: tls_connection:init/1

    pid: <0.14901.0>

    registered_name: []

    exception exit: {function_clause,

                        [{tls_v1,enum_to_oid,

                             [28],

                             [{file,"tls_v1.erl"},{line,404}]},

                         {ssl_handshake,

                             '-dec_hello_extensions/2-blc$^1/1-0-',1,

                             [{file,"ssl_handshake.erl"},{line,1657}]},

                         {ssl_handshake,

                             '-dec_hello_extensions/2-blc$^1/1-0-',1,

                             [{file,"ssl_handshake.erl"},{line,1657}]},

                         {ssl_handshake,dec_hello_extensions,2,

                             [{file,"ssl_handshake.erl"},{line,1657}]},

                         {tls_handshake,decode_handshake,3,

                             [{file,"tls_handshake.erl"},{line,182}]},

                         {tls_handshake,get_tls_handshake_aux,3,

                             [{file,"tls_handshake.erl"},{line,153}]},

                         {tls_connection,next_state,4,

                             [{file,"tls_connection.erl"},{line,454}]},

                         {gen_fsm,handle_msg,7,

                             [{file,"gen_fsm.erl"},{line,505}]}]}

      in function  gen_fsm:terminate/7 (gen_fsm.erl, line 622)

    ancestors: [tls_connection_sup,ssl_sup,<0.150.0>]

    messages: []

    links: [<0.153.0>]

    dictionary: [{ssl_manager,ssl_manager}]

    trap_exit: true

    status: running

    heap_size: 2586

    stack_size: 27

    reductions: 824

  neighbours:

=SUPERVISOR REPORT==== 23-Nov-2016::04:49:00 ===

     Supervisor: {local,tls_connection_sup}

     Context:    child_terminated

     Reason:     {function_clause,

                     [{tls_v1,enum_to_oid,

                          [28],

                          [{file,"tls_v1.erl"},{line,404}]},

                      {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,

                          [{file,"ssl_handshake.erl"},{line,1657}]},

                      {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,

                          [{file,"ssl_handshake.erl"},{line,1657}]},

                      {ssl_handshake,dec_hello_extensions,2,

                          [{file,"ssl_handshake.erl"},{line,1657}]},

                      {tls_handshake,decode_handshake,3,

                          [{file,"tls_handshake.erl"},{line,182}]},

                      {tls_handshake,get_tls_handshake_aux,3,

                          [{file,"tls_handshake.erl"},{line,153}]},

                      {tls_connection,next_state,4,

                          [{file,"tls_connection.erl"},{line,454}]},

                      {gen_fsm,handle_msg,7,

                          [{file,"gen_fsm.erl"},{line,505}]}]}

     Offender:   [{pid,<0.14901.0>},

                  {name,undefined},

                  {mfargs,{tls_connection,start_link,undefined}},

                  {restart_type,temporary},

                  {shutdown,4000},

                  {child_type,worker}]

=CRASH REPORT==== 23-Nov-2016::04:49:00 ===

  crasher:

    initial call: rabbit_reader:init/4

    pid: <0.14904.0>

    registered_name: []

    exception exit: {{function_clause,

                         [{tls_v1,enum_to_oid,

                              [28],

                              [{file,"tls_v1.erl"},{line,404}]},

                          {ssl_handshake,

                              '-dec_hello_extensions/2-blc$^1/1-0-',1,

                              [{file,"ssl_handshake.erl"},{line,1657}]},

                          {ssl_handshake,

                              '-dec_hello_extensions/2-blc$^1/1-0-',1,

                              [{file,"ssl_handshake.erl"},{line,1657}]},

                          {ssl_handshake,dec_hello_extensions,2,

                              [{file,"ssl_handshake.erl"},{line,1657}]},

                          {tls_handshake,decode_handshake,3,

                              [{file,"tls_handshake.erl"},{line,182}]},

                          {tls_handshake,get_tls_handshake_aux,3,

                              [{file,"tls_handshake.erl"},{line,153}]},

                          {tls_connection,next_state,4,

                              [{file,"tls_connection.erl"},{line,454}]},

                          {gen_fsm,handle_msg,7,

                              [{file,"gen_fsm.erl"},{line,505}]}]},

                     {gen_fsm,sync_send_all_state_event,

                         [<0.14901.0>,{start,5000},infinity]}}

      in function  gen_fsm:sync_send_all_state_event/3 (gen_fsm.erl, line 240)

      in call from ssl_connection:sync_send_all_state_event/2 (ssl_connection.erl, line 1630)

      in call from ssl_connection:handshake/2 (ssl_connection.erl, line 96)

      in call from ranch_ssl:accept_ack/2 (src/ranch_ssl.erl, line 118)

      in call from rabbit_net:accept_ack/2 (src/rabbit_net.erl, line 261)

      in call from rabbit_reader:init/4 (src/rabbit_reader.erl, line 230)

    ancestors: [<0.14902.0>,<0.289.0>,<0.288.0>,<0.287.0>,rabbit_sup,

                  <0.160.0>]

    messages: []

    links: [<0.14902.0>]

    dictionary: []

    trap_exit: false

    status: running

    heap_size: 1598

    stack_size: 27

    reductions: 223

  neighbours:

=SUPERVISOR REPORT==== 23-Nov-2016::04:49:00 ===

     Supervisor: {<0.14902.0>,rabbit_connection_sup}

     Context:    child_terminated

     Reason:     {{function_clause,

                      [{tls_v1,enum_to_oid,

                           [28],

                           [{file,"tls_v1.erl"},{line,404}]},

                       {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',

                           1,

                           [{file,"ssl_handshake.erl"},{line,1657}]},

                       {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',

                           1,

                           [{file,"ssl_handshake.erl"},{line,1657}]},

                       {ssl_handshake,dec_hello_extensions,2,

                           [{file,"ssl_handshake.erl"},{line,1657}]},

                       {tls_handshake,decode_handshake,3,

                           [{file,"tls_handshake.erl"},{line,182}]},

                       {tls_handshake,get_tls_handshake_aux,3,

                           [{file,"tls_handshake.erl"},{line,153}]},

                       {tls_connection,next_state,4,

                           [{file,"tls_connection.erl"},{line,454}]},

                       {gen_fsm,handle_msg,7,

                           [{file,"gen_fsm.erl"},{line,505}]}]},

                  {gen_fsm,sync_send_all_state_event,

                      [<0.14901.0>,{start,5000},infinity]}}

     Offender:   [{pid,<0.14904.0>},

                  {name,reader},

                  {mfargs,

                      {rabbit_reader,start_link,

                          [<0.14903.0>,

                           {acceptor,{0,0,0,0,0,0,0,0},5671},

                           {sslsocket,

                               {gen_tcp,#Port<0.24951>,tls_connection},

                               <0.14901.0>}]}},

                  {restart_type,intrinsic},

                  {shutdown,30000},

                  {child_type,worker}]

=SUPERVISOR REPORT==== 23-Nov-2016::04:49:00 ===

     Supervisor: {<0.14902.0>,rabbit_connection_sup}

     Context:    shutdown

     Reason:     reached_max_restart_intensity

     Offender:   [{pid,<0.14904.0>},

                  {name,reader},

                  {mfargs,

                      {rabbit_reader,start_link,

                          [<0.14903.0>,

                           {acceptor,{0,0,0,0,0,0,0,0},5671},

                           {sslsocket,

                               {gen_tcp,#Port<0.24951>,tls_connection},

                               <0.14901.0>}]}},

                  {restart_type,intrinsic},

                  {shutdown,30000},

                  {child_type,worker}]

I can't make head or tail out of this error. Appreciate any help here...

Thanks,

**Comment by vitaly-krugl** [comment]
Do these examples help? https://github.com/pika/pika/pull/742/files

**Comment by MicrowaveX** [comment]
Hi,

i tried with this example (docs/examples/tls_server_uathentication.rst) above, but I also stuck with pika just quitting with the exception

Traceback (most recent call last):
  File "tls_example.py", line 13, in <module>
    conn = pika.BlockingConnection(cp)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 339, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed

I just had to add port=5671 in the pika.ConnectionParameters, otherwise it tried to connect on 5672 which is my plain port.

i've tried with python2 and python3 - same. 
Also i tried out "openssl s_client -connect localhost:5671" which works fine. 
Looking on the server with "netstat -apn | grep :5671" I can see that pika is opening the connection and leaves it then in the CLOSE_WAIT state when crashing.

Does anybody have an idea? I'm trying since 4 hours and no progress :(

Thank you!

**Comment by lukebakken** [comment]
The `tls_v1,enum_to_oid` issue is a known issue. Please see this issue for more context and a resolution: ruby-amqp/bunny#303
