### ISSUE TITLE
The action of channel.queue_bind is not looking correct with header exchange

### ISSUE THREAD

**Issue by yangyuliang1981** [pika/pika#793]
In my case, I use header exchange to bind the queue using queue arguments, not routing_key.
But the code of channel.queue_bind will bind both the arguments and the routing key at the same time.
It not looks correct.

In Rabbit MQ UI web, I can set the routing key or queue arguments individually.
And this is what I really want.

`
    def queue_bind(self, callback, queue, exchange,
                   routing_key=None,
                   nowait=False,
                   arguments=None):
        """Bind the queue to the specified exchange

        :param callable callback: The callback to call on Queue.BindOk;
            MUST be None when nowait=True.
        :param queue: The queue to bind to the exchange
        :type queue: str or unicode
        :param exchange: The source exchange to bind to
        :type exchange: str or unicode
        :param routing_key: The routing key to bind on
        :type routing_key: str or unicode
        :param bool nowait: Do not wait for a Queue.BindOk
        :param dict arguments: Custom key/value pair arguments for the binding

        """
        self._validate_channel_and_callback(callback)
        replies = [spec.Queue.BindOk] if nowait is False else []
        if routing_key is None:
            routing_key = queue
        return self._rpc(spec.Queue.Bind(0, queue, exchange, routing_key,
                                         nowait, arguments or dict()),
                         callback, replies)`

**Comment by lukebakken** [comment]
Please provide a PR that includes tests and reference this issue if you'd like this change implemented. It would be breaking change to the Pika API so we would have to take that into consideration.
