### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'basic_publish'

### ISSUE THREAD

**Issue by ghost** [pika/pika#796]
HI~
when rabbitmq not start up, i try connect to rabbitmq, then show this :   

WARNING 2017-02-02 08:03:59 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:03:59 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:04 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
WARNING 2017-02-02 08:04:04 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:04:04 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:09 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
WARNING 2017-02-02 08:04:09 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:04:09 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:14 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
WARNING 2017-02-02 08:04:14 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:04:14 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:19 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
WARNING 2017-02-02 08:04:19 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:04:19 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:24 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
WARNING 2017-02-02 08:04:24 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:04:24 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:29 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
WARNING 2017-02-02 08:04:29 API _create_and_connect_to_socket  231 : Connection to 172.16.179.111:5672 failed: [Errno 111] Connection refused
WARNING 2017-02-02 08:04:29 API on_connection_error  89  : Connect Failed, reopening
INFO    2017-02-02 08:04:34 API _create_and_connect_to_socket  216 : Connecting to 172.16.179.111:5672
ERROR   2017-02-02 08:04:34 API _handle_read  442 : Read empty data, calling disconnect
WARNING 2017-02-02 08:04:34 API _handle_ioloop_stop  323 : Connection is closed but not stopping IOLoop
WARNING 2017-02-02 08:04:34 API on_connection_error  89  : Connect Failed, reopening

**Comment by lukebakken** [comment]
When reporting an issue, please try to be as descriptive as possible which helps Pika developers resolve issues quickly.

* Include the operating system, broker version (RabbitMQ version), Python version
* Include code to reproduce the issue
* Include a clear statement of what you *expect* to see and what you *saw*
* If you include a stack trace, include it as a text file attachment, *not* in-line in the issue

If you can provide the above information, please do so and re-open this issue.

In this case, I do not see `AttributeError: 'NoneType' object has no attribute 'basic_publish'` in the stack trace.
