### ISSUE TITLE
Pika fails to send large message on some Python build on Windows

### ISSUE THREAD

**Issue by Ignalion** [pika/pika#797]
Generally, vanilla Python seems to use winsock2 errorcodes for winsock1 one.
If you look into errnomodule.c file, you can see:
```
#ifdef EWOULDBLOCK
    inscode(d, ds, de, "EWOULDBLOCK", EWOULDBLOCK, "Operation would block");
#else
#ifdef WSAEWOULDBLOCK
    inscode(d, ds, de, "EWOULDBLOCK", WSAEWOULDBLOCK, "Operation would block");
#endif
#endif
```

This processed only if EWOULDBLOCK is set, or, if you please, if errno.h is included.
errno.h is included only if set HAVE_ERRNO_H in Python.h, like this
```
#ifdef HAVE_ERRNO_H
#include <errno.h>
#endif
```

and this variable can be set in pyconfig.h file.

The thing is, if Python is builded w\o this set, then EWOULDBLOCK and WSAEWOULDBLOCK will be different numbers on Windows (140 and 10035 respectively).
In this case when you're trying to send large message to RabbitMQ (larger than socket buffer) then WSAEWOULDBLOCK error code would be returned.
But pika seems to process only EWOULBLOCK in _handle_write function in base_connection.py file:
```
        except _SOCKET_ERROR as error:
            if error.errno in (errno.EAGAIN, errno.EWOULDBLOCK):
                LOGGER.debug("Would block, requeuing frame")
                self.outbound_buffer.appendleft(frame)
```

Thus, this would lead to error sending message however it should not.

I think, it would be reasonable to add WSA socket errornumbers as well at least for this case (generally, they are used in many places in pika)

**Comment by lukebakken** [comment]
We should review how [Twisted deals with this issue](https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/tcp.py#L46-L78)

**Comment by lukebakken** [comment]
@Ignalion - could you please provide a code example or steps on how to reproduce this? Is it simply sufficient to send a large message using Pika on Windows?

**Comment by lukebakken** [comment]
I installed Python 3.6.3 on Windows 8.1 using chocolatey, which uses the official installer. In an interactive session, I do not see differences between `errno` values, which leads me to believe that Python is built with `HAVE_ERRNO_H` defined:

```
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win
Type "help", "copyright", "credits" or "license" for more information.
>>> import errno
>>> errno.EWOULDBLOCK
10035
>>> errno.WSAEWOULDBLOCK
10035
>>> errno.WSAECONNRESET
10054
>>> errno.ECONNRESET
10054
>>> errno.WSAECONNABORTED
10053
>>> errno.ECONNABORTED
10053
>>> errno.WSAEWOULDBLOCK
10035
>>> errno.EWOULDBLOCK
10035
>>>
```
