### ISSUE TITLE
Connection does not start.

### ISSUE THREAD

**Issue by redlolgeerf** [pika/pika#798]
I'm using TornadoConnection adapter to connect to rabbitmq like this:

	credentials = pika.PlainCredentials(settings.RABBIT_MQ_LOGIN, settings.RABBIT_MQ_PASSW)
	connection_params = pika.ConnectionParameters(
		host=settings.RABBIT_MQ_HOST,
		port=settings.RABBIT_MQ_PORT,
		virtual_host="/",
		credentials=credentials,
		heartbeat_interval=580
	)

	event = locks.Event()

	def _on_open_callback(conn):
		event.set()
	def _on_open_error_callback(unused_connection, reason=None):
		event.set()

	connection = pika.adapters.TornadoConnection(
		parameters=connection_params,
		on_open_callback=_on_open_callback,
		on_open_error_callback=_on_open_error_callback,
		stop_ioloop_on_close=False
	)

	yield event.wait()

but event is never set.

Looking at my rabbitmq logs I find this:

 =INFO REPORT==== 28-Feb-2017::13:57:32 ===
accepting AMQP connection <0.21714.0> (127.0.0.1:55780 -> 127.0.0.1:5672)

=ERROR REPORT==== 28-Feb-2017::13:57:42 ===
closing AMQP connection <0.21714.0> (127.0.0.1:55780 -> 127.0.0.1:5672):
{handshake_timeout,frame_header}

pika version 0.10.0
rabbitmq version 3.5.7

My guess is that, pika does not receive any frame from rabbitmq server, but I have no clue, what causes it.

**Comment by lukebakken** [comment]
Closing as this is a very old version of RabbitMQ. If this can be reproduced using the latest version (`3.6.10`), please re-open.
