### ISSUE TITLE
channel.consume(...) generator does not detect closed channel

### ISSUE THREAD

**Issue by hexadite-grishak** [pika/pika#799]
If, for whatever reason, the channel is closed, the `consume` method will simply wait until the timeout and return `None`.  So, for example, the following code will run forever:
```python
for res in channel.consume('some_queue', inactivity_timeout=2):
    if not res:
        continue
    method, properties, body = res
    do_something_with(method, properties, body)
```
I would expect that if the channel closes the call to `channel.consume(...)` will raise a `ChannelClosed` exception.
The solution here is to check the property `channel.is_closed` and act accordingly if `is_closed` returns `True`. But that seems like something that should be abstracted-away library.

**Comment by lukebakken** [comment]
@hexadite-grishak - I believe pull request #886 addressed this issue. If not, please re-open this issue. Thanks!
