### ISSUE TITLE
How can I stop consuming once Queue is empty

### ISSUE THREAD

**Issue by mengalong** [pika/pika#801]
HI,
I use pika.BlockingConnection to consuming messages from rabbitmq.
My publisher produces variable number of messages on known schedules,
So I'm thinking about start Consumers to on schedule and stop once Queue is empty.
I am wondering how to meet this requirement。

Thanks very much.

**Comment by vitaly-krugl** [comment]
Thank you for the question. I am going to close this issue since the RabbitMQ Google Group is the more appropriate forum for asking questions. See https://groups.google.com/forum/#!forum/rabbitmq-users
