### ISSUE TITLE
Ping rabbitmq server

### ISSUE THREAD

**Issue by szepeviktor** [pika/pika#804]
Hello!

Could you help me to monitor the local rabbitmq server preferably without autentication but not causing authentication failure? Or with a username and password but now knowing anything (queues) about the server.

I've seen only authenticated examples in the docs and here https://www.rabbitmq.com/tutorials/tutorial-one-python.html
Thank you!

**Comment by vitaly-krugl** [comment]
@szepeviktor, please re-post your question on the rabbimtmq-users group https://groups.google.com/forum/#!forum/rabbitmq-users, which is a better forum for asking questions.

**Comment by szepeviktor** [comment]
@vitaly-krugl Thank you!

The short answer is
```bash
http://127.0.0.1:15672/api/aliveness-test/%2F
```

**Comment by vitaly-krugl** [comment]
@szepeviktor, thank you for sharing the answer.

**Comment by szepeviktor** [comment]
The sad new is there is no usable response without authentication.

I am interested in the AMQP answer also as this is an HTTP management port.

**Comment by vitaly-krugl** [comment]
Let's see what rabbimtmq-users group  has to say about your questions.

**Comment by donho** [comment]
Hi @szepeviktor I have the same need. Did you get the answer? Could you post the solution here please?

**Comment by lukebakken** [comment]
https://www.rabbitmq.com/monitoring.html
