### ISSUE TITLE
 exceptions.ConnectionClosed() issue

### ISSUE THREAD

**Issue by ThreeWalnuts** [pika/pika#808]
I create a listener to keep receiving messages from a queue.
There are lots of messages in the queue.  After a while, it's very strange that pika automatically disconnects to the rabbitMQ server. See the following exception:
Traceback (most recent call last):
  File "/root/waa-slack-bot/waa_response_listener_test.py", line 197, in receive_waa_response_from_Q
    channel.start_consuming()
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 647, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 426, in _flush_output
    raise exceptions.ConnectionClosed()

What should I do?
I have set the heartbeat_interval=0 in the ConnectionParameters, but I still encounter above errors.
Anyone encounters this before? My pika version is 0.10. 0

**Comment by vitaly-krugl** [comment]
Hi, have you checked server logs? Look for heartbeat timeout errors. What's the max time that your app takes to process a message? As in max time between calls into the channel to retrieve the next message?

**Comment by vitaly-krugl** [comment]
If server logs don't help, Wireshark now includes support for the AMQP protocol and is great for tracking down comms issues.

Another possibility is threading: is your app multi-threaded? A given Connection instance in Pika is not thread-safe, and using it from more than one thread will corrupt the data path at some point, leading to closed connections.

**Comment by ThreeWalnuts** [comment]
@vitaly-krugl , Yes, my app is multi-threaded, two threads, one thread is used to push messages into a queue. The other is used to receive messages from another queue. From the beginning, I used only one connection for both threads. Later, I changed my app to use different connections respectively. But no matter which pattern, I still get above errors. 
What should I do next? I'm stuck here now.

**Comment by vitaly-krugl** [comment]
Try the other things I suggested above

> Hi, have you checked server logs? Look for heartbeat timeout errors. What's the max time that your app takes to process a message? As in max time between calls into the channel to retrieve the next message?

> If server logs don't help, Wireshark now includes support for the AMQP protocol and is great for tracking down comms issues.

**Comment by lukebakken** [comment]
There is not enough information to debug this issue. If you are able to provide code that reliably reproduces this issue, please do so and re-open this issue. Thanks.
