### ISSUE TITLE
SSL hostname verification

### ISSUE THREAD

**Issue by arossert** [pika/pika#811]
I'm using pika to communicate with RabbitMQ over SSL.

I have enabled SSL on the server and configured the connection with:
```
'ssl_options': {
    'ca_certs': RABBITMQ_APPSERV_CA_CERT,
    'cert_reqs': ssl.CERT_REQUIRED
}
```
The certificate is validated but the hostname in the certificate is not.
How can enable the hostname verification?

**Comment by lukebakken** [comment]
Please follow issue #464. At this time, you must implement your own verification.
