### ISSUE TITLE
blocked_connection_timeout unexpected ?

### ISSUE THREAD

**Issue by km3945** [pika/pika#812]
pika (0.10.0)

TypeError: __init__() got an unexpected keyword argument 'heartbeat'
TypeError: __init__() got an unexpected keyword argument 'blocked_connection_timeout'

```
MQ_PARAMETERS = pika.ConnectionParameters(
    host='127.0.0.1',
    port=5672,
    virtual_host="/",
    credentials=credentials,
    connection_attempts=2,
    heartbeat=580,
    blocked_connection_timeout=300)
connection = pika.BlockingConnection(MQ_PARAMETERS)

**Comment by vitaly-krugl** [comment]
Those parameters are in master, but have not been officially released. This is what you have in the release 0.10.0: https://github.com/pika/pika/blob/0.10.0/pika/connection.py#L304-L339
