### ISSUE TITLE
BlockingChannel.basic_publish() succeeds even after interface is disabled

### ISSUE THREAD

**Issue by dsoprea** [pika/pika#821]
I'm trying to test reconnect under `BlockingConnection`, and I can't get it to fail. Setting heartbeats doesn't matter.

What do I do?

**Comment by lukebakken** [comment]
One option is to stop and restart your broker. If you'd like to discuss this further, I suggest the [`rabbitmq-users` mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users). Thanks!
