### ISSUE TITLE
Pika Blocking Connection timeout at 180 sec max

### ISSUE THREAD

**Issue by amulyas** [pika/pika#824]
we are using Pika blocking connection adapter, we do not have idle timeout set in our stack, but still its timing out at 180 sec max, here is the sample code, we tried to introduce heartbeat but that is not helping at all ... this is very critical and any help is greatly appreciated 

params = pika.URLParameters(url)
params.socket_timeout = 300
params.heartbeat_interval = 20
params.blocked_connection_timeout = 300
connection = pika.BlockingConnection(params)
channel = connection.channel()
channel.queue_declare(queue='hello')
channel.basic_publish(exchange='', routing_key='hello', body='Hello')
print "Sent 'Hello World!'"
print "sleeping "
time.sleep(280)

def callback(ch, method, properties, body):
  print "  Received %r" % (body)
channel.start_consuming()
channel.basic_consume(callback,
    queue='hello',
    no_ack=True)
connection.close()

**Comment by markunsworth** [comment]
You should direct usage questions at the google group, this is just for bugs.

https://groups.google.com/forum/#!forum/pika-python

**Comment by vitaly-krugl** [comment]
Good point @markunsworth. I am going to close this issue. @amulyas, please post your question on the rabbitmq-users google group.

**Comment by amulyas** [comment]
I think its bug in heartbeat with Blocking connection but I will post on google groups
