### ISSUE TITLE
Multithreading is not working

### ISSUE THREAD

**Issue by mounikakuchana** [pika/pika#828]
Hi
I have a rabbitmq with single queue.I tried to connect to it to get all the messages in the queue.
I am able to get the messages from queue without using multithreading and single thread connection.
I want to create multiple threads for my connection such a way that
1st thread reads 1st message of queue
2nd thread reads 2nd messages of queue
......
x thread reads x message from queue
and all the threads need to run at the same time how can I do this

the code which I tried is as follows for multithreading
**code**:
import time, threading, pika

class Threaded_worker(threading.Thread):
    def callback(self, ch, method, properties, body):
        print (' [x] received %r' % (body,))
        time.sleep(1)
        ch.basic_ack(delivery_tag = method.delivery_tag)

    def __init__(self):
        threading.Thread.__init__(self)
        self.pika_conn_params = pika.ConnectionParameters(
            host='x.x.x.x', port=5672,
            credentials=pika.credentials.PlainCredentials('xxx', 'xxx'),
        )
        self.connection = pika.BlockingConnection(self.pika_conn_params)
        self.channel = self.connection.channel()
        self.queue = self.channel.queue_declare(
            queue='xxx', durable=True,
            exclusive=False, auto_delete=False
        )
        self.channel.basic_qos(prefetch_count=1)

        threading.Thread(target=self.channel.basic_consume(self.callback, queue='xxx'))

    def run(self):
        print ('start consuming')
        self.channel.start_consuming()

for _ in range(3):
    print ('launch thread')
    td = Threaded_worker()
    td.start()

when I try to execute this it is launching three threads 
three thread are reading same messages from queue
can some one help me with this issue

Thanks

**Comment by vitaly-krugl** [comment]
@mounikakuchana, a single pika connection is not thread-safe, per documentation. As such, each thread must have its own pika connection.

**Comment by nanvel** [comment]
https://www.rabbitmq.com/tutorials/amqp-concepts.html
> For applications that use multiple threads/processes for processing, it is very common to open a new channel per thread/process and not share channels between them.
It sounds like open one connection and have a channel per thread.
