### ISSUE TITLE
KeyError when creating channel on closed connection

### ISSUE THREAD

**Issue by mvallebr** [pika/pika#835]
I have the following piece of code:

```python
    def sendEvent(self, event):
        self._logger.info("RabbitMQProducer.sendEvent called with input: {0}".format(str(event)))

        def publish():
            self._connection.channel().basic_publish(exchange=self._exchange,
                                                     routing_key=self._getRoutingKey(event),
                                                     body=json.dumps(event))

        try:
            publish()
        except ConnectionClosed:
            self._connect()
            publish()
```

My application receives messages from a queue and then executes this code to publish to a different queue. 

When the application stays some time without receiving a message, `self._connection` seems to enter on a "disconnected" state, maybe the physical connection is really lost. I would expect `ConnectionClosed` exception to be raised at this point, but it's not actually what happens:

```
  File "/bb/mbigh/mbig3929/evsuggested/src/news/evsuggested/rabbitmq_producer.py", line 37, in sendEvent
    publish()
  File "/bb/mbigh/mbig3929/evsuggested/src/news/evsuggested/rabbitmq_producer.py", line 32, in publish
    self._connection.channel().basic_publish(exchange=self._exchange,
  File "/opt/bb/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 689, in channel
    channel_number=channel_number)
  File "/opt/bb/lib/python2.7/site-packages/pika/connection.py", line 711, in channel
    return self._channels[channel_number]
KeyError: 6
```

It seems it fails at channel constructor, for some weird reason. 
As you can see from the stacktrace, I am using blocking connection.

It seems like lots of other issues, like https://github.com/pika/pika/issues/809 . 
It really seems like a bug. Am I failing to detect something? I am using pika 0.10.0.

**Comment by vitaly-krugl** [comment]
@mvallebr, is your app using threads?

**Comment by vitaly-krugl** [comment]
I get a ConnectionClosed exception with Pika 0.10.0 with the following simple snippet of code executed in IPython:
```
In [7]: from pika import BlockingConnection

In [8]: import time

In [9]: c = BlockingConnection()

In [10]: time.sleep(180) # default late-version rabbitmq heartbeat interval is 60 sec

In [11]: c.channel()
---------------------------------------------------------------------------
ConnectionClosed                          Traceback (most recent call last)
<ipython-input-11-f95cd61fefe3> in <module>()
----> 1 c.channel()

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika/adapters/blocking_connection.pyc in channel(self, channel_number)
    696 
    697             # Drive I/O until Channel.Open-ok
--> 698             channel._flush_output(opened_args.is_ready)
    699 
    700 

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika/adapters/blocking_connection.pyc in _flush_output(self, *waiters)
   1172         self._connection._flush_output(
   1173             self._channel_closed_by_broker_result.is_ready,
-> 1174             *waiters)
   1175 
   1176         if self._channel_closed_by_broker_result:

/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika/adapters/blocking_connection.pyc in _flush_output(self, *waiters)
    424                     # an error
    425                     LOGGER.critical('Connection close detected')
--> 426                     raise exceptions.ConnectionClosed()
    427                 else:
    428                     LOGGER.info('Connection closed; result=%r', result)

ConnectionClosed: 
```

**Comment by vitaly-krugl** [comment]
Please provide minimal, self-contained code that reproduces your issue reliably, as well as any additional information necessary for reproducing it.

**Comment by mvallebr** [comment]
I am not using threads, it's a single threaded application. I have, however, 2 instances of Blocking connection, 1 to consume (I consume using channel.consume() method which returns a generator) and 1 to publish to a different exchange. 

I will try to create an example project, publish on github and post the link here. The problem is - the error happens just after some time, it will be hard to reproduce on purpose. I will try though.

**Comment by vitaly-krugl** [comment]
Examining the client-side debug-level logs and also the RabbitMQ logs should give you a clue about the event that triggers the issue.

**Comment by lukebakken** [comment]
@mvallebr - please feel free to re-open this issue if you are able to provide code that reliably reproduces your issue with pika and RabbitMQ logs included. Thanks!

**Comment by mvallebr** [comment]
Luke, I think we found the problem and instead we would like to provide you a pull request, I am just trying to get permission from my company first.

**Comment by lukebakken** [comment]
Thanks! Link it to this issue and re-open.
