### ISSUE TITLE
How do I close logs?

### ISSUE THREAD

**Issue by Panda-Master** [pika/pika#837]
Hi,

Recently, I'm using the scrapy and pika, but the pika logs interfere with the scrapy logs. How do I close the pika logs?

**Comment by LukaAndrojna** [comment]
import logging
logging.getLogger('pika').setLevel(logging.WARNING)

**Comment by lukebakken** [comment]
Thanks @LukaAndrojna 

@Panda-Master - Pika uses Python's standard `logging` module, so you can also find information [in the docs](https://docs.python.org/2/howto/logging.html) and by searching online.
