### ISSUE TITLE
Produce a new release

### ISSUE THREAD

**Issue by rmk135** [pika/pika#838]
Hello guys,

New release of this library is wanted! At least I do need ``blocked_connection_timeout`` option really badly :)

Does anybody work on this? When new release could be expected?

Thanks,
Roman

**Comment by rmk135** [comment]
Hello @dumbbell, @gmr, @tonyg, @vitaly-krugl,

Can I, please, ask you to pay some attention on this issue?

Thanks,
Roman

**Comment by michaelklishin** [comment]
@rmk135 hi Roman. We are aware of community interest in a new release.

This library is undergoing a transition from one extremely busy maintainer to a group of "just" busy ones. It takes a while to make sure everyone agrees on what needs to be done before we can produce a release. Please be patient.

The best thing the community can do to help is to go through pull requests, try them out and review them.

**Comment by rmk135** [comment]
Hello @michaelklishin ,

Thanks in advance for giving some understanding on what's going on. However, I need to ask if you see any light in the end of the tunnel and have any kind of target date, when this release could be seen on PyPi?

I'm really sorry for disturbing you, guys, but I need to know this because it affects my business.

Roman

**Comment by rmk135** [comment]
Thanks, guys

Will wait until you will release it.
