### ISSUE TITLE
start_consuming() keeps running even after channel closed by exception

### ISSUE THREAD

**Issue by streamliner18** [pika/pika#841]
I'm encountering this problem when a channel exception caused the channel to close in the middle of a `start_consuming` loop, there is no way to know it as neither did `start_consuming` return, nor was an exception thrown. It basically kept looping as if it was normal, despite the entire channel is gone.

_My use case necessitates BlockingConnection; hence I can't find an alternative._

Here's the code to reproduce that. Trigger the problem by randomly writing something with a `logs.something` key to `egress` exchange. The callback will cause the broker to shutdown my channel, as the exchange I publish to is invalid.

```python
from pika import BlockingConnection, ConnectionParameters


def callback(channel, methods, props, body):
    channel.basic_publish(
        'exchange_not_exist',
        routing_key='123',
        body='Nope this is wrong'
    )


def main():
    conn = BlockingConnection(
        ConnectionParameters('localhost')
    )
    ch = conn.channel()
    ch.exchange_declare('egress', exchange_type='topic', durable=True)
    q = ch.queue_declare(exclusive=True).method.queue
    ch.queue_bind(q, 'egress', 'logs.#')
    ch.basic_consume(callback, q, True)
    print('Starts consuming.')
    ch.start_consuming()
    print('I\'m done.')


if __name__ == '__main__':
    main()
```

**Comment by lukebakken** [comment]
I can't reproduce this using RabbitMQ `3.6.10`, Arch Linux, python `2.7.13` and `3.6.2`. You don't specify your environment or provide server logs, both of which would be helpful.

I added a couple `print` statements to your code:

```python
from pika import BlockingConnection, ConnectionParameters


def callback(channel, methods, props, body):
    print("callback start")
    channel.basic_publish(
        'exchange_not_exist',
        routing_key='123',
        body='Nope this is wrong'
    )
    print("callback exit")


def main():
    conn = BlockingConnection(
        ConnectionParameters('localhost')
    )
    ch = conn.channel()
    ch.exchange_declare('egress', exchange_type='topic', durable=True)
    q = ch.queue_declare(exclusive=True).method.queue
    ch.queue_bind(q, 'egress', 'logs.#')
    ch.basic_consume(callback, q, True)
    print("Starts consuming.")
    ch.start_consuming()
    print("I'm done.")


if __name__ == '__main__':
    main()
```

Output:

```sh
$ python ~/Projects/issues/pika/gh-841/repro.py 
Starts consuming.
callback start
callback exit
```

**Comment by streamliner18** [comment]
But you just reproduced the problem!

After your publishing call, the broker should raise an exception stating that a channel exception occurred (due to the nonexistent queue), and closes the channel. You can verify from the management console that the channel and all of its associated consumer tags are **gone**. **However**,

- No exception raised from the callback (which seems to be expected)
- `start_consuming` did not raise an exception, but its channel is dead
- `start_consuming` did not return, despite this in the documentation:

> `BlockingChannel.start_consuming()`
> Processes I/O events and dispatches timers and basic_consume callbacks **until all consumers are cancelled**.

In fact all the consumers are cancelled. But the function weren't returning.

Fyi, my platform is python (miniconda3) 3.6, pika latest, macOS 10.12.2. I retested this on my linux box (same python and pika, Ubuntu 16.04 x64), same problem. Both using a docker version of `rabbitmq:3.6.10` with manually enabled management plugin.

**Comment by lukebakken** [comment]
Thank you for the additional information. I understand what you were first reporting now and will take a look at it.

**Comment by radzhome** [comment]
I think my issue is related to this one - https://github.com/pika/pika/issues/885  . I see start_consuming() doesn't raise an exception even though basic_cancel was called anymore. This seems to be fine in pika 0.10 though.

**Comment by lukebakken** [comment]
@streamliner18 I am re-visiting this issue. I am seeing this behavior in `0.10.0` as well as the latest code. Not sure why at this point.

**Comment by radzhome** [comment]
I have no issues with 0.10.0 and my code sample, let me try latest build and see if its resolved. If not I'll give you an updated code sample.

**Comment by HosseinlGholami** [comment]
same problem  !
first run it inside a thread :
______________________________________________________________________________
import threading 
import ctypes 
import time 
import pika

class rbmq(threading.Thread): 
  
    # Thread class with a _stop() method.  
    # The thread itself has to check 
    # regularly for the stopped() condition. 
  
    def __init__(self,Slug,ChannelNum,Parameter,prefetch_count,QueueName,CalbackFunc,*args, **kwargs): 
        super(rbmq, self).__init__(*args, **kwargs) 
        self.slug=Slug
        self.parameters=Parameter
        self.pckh=prefetch_count
        self.queuename=QueueName
        self.channelnum=ChannelNum
        self.callbackfunc=CalbackFunc
    
    def run(self): 
        # target function of the thread class 
        try: 
            print("thread strart")
            connection = pika.BlockingConnection(self.parameters)
            channel = connection.channel(1)
            channel.basic_qos(prefetch_count=self.pckh)
            channel.basic_consume(queue=self.queuename,
                          on_message_callback=self.callbackfunc,
                          consumer_tag=self.slug)
            print( self.slug ,' [*] Waiting for messages.')
            channel.start_consuming()
            print("thread end")
        finally: 
            channel.stop_consuming()
            channel.close()
            connection.close()
            print('theread stop') 
           
    def get_id(self): 
        # returns id of the respective thread 
        if hasattr(self, '_thread_id'): 
            return self._thread_id
        for id, thread in threading._active.items(): 
            if thread is self: 
                return id
   
    def stop(self): 
        thread_id = self.get_id() 
        res = ctypes.pythonapi.PyThreadState_SetAsyncExc(thread_id, 
              ctypes.py_object(SystemExit)) 
        if res > 1: 
            ctypes.pythonapi.PyThreadState_SetAsyncExc(thread_id, 0) 
            print('Exception raise failure') 
       


def Packet_Handeler_callback(ch, method, properties, body):
     print("Received"+body.decode("utf-8") +" from :" +method.consumer_tag)
     time.sleep(3)
     ch.basic_ack(delivery_tag = method.delivery_tag)
     
# as main :
credentials = pika.PlainCredentials('hgh', 'guest')
parameters = pika.ConnectionParameters('localhost',5672,'/',credentials)
t1 = rbmq(Slug='kjk',ChannelNum=5959,Parameter=parameters,
          prefetch_count=2,
          QueueName='classic_queue_2',
          CalbackFunc=Packet_Handeler_callback
          )
t1.start()

____________________________________________________________________________________________________
____________________________________________________________________________________________________
then in other program im trying to stop it  , and its wont stop !
______________________________________________________________________________________________________
_____________________________________________________________________________________________________
import pika


credentials = pika.PlainCredentials('hgh', 'guest')
parameters = pika.ConnectionParameters('localhost',5672,'/',credentials)

connection = pika.BlockingConnection(parameters)
channel = connection.channel(5959)
channel.basic_cancel("kjk")
channel.stop_consuming("kjk")
connection.close()
________________________________________________________________________________________________

**Comment by HosseinlGholami** [comment]
first run basic_consume inside a thread :
______________________________________________________________________________

import threading 
import ctypes 
import time 
import pika

class rbmq(threading.Thread): 
    # Thread class with a _stop() method.  
    # The thread itself has to check 
    # regularly for the stopped() condition. 
  
    def __init__(self,Slug,ChannelNum,Parameter,prefetch_count,QueueName,CalbackFunc,*args, **kwargs): 
        super(rbmq, self).__init__(*args, **kwargs) 
        self.slug=Slug
        self.parameters=Parameter
        self.pckh=prefetch_count
        self.queuename=QueueName
        self.channelnum=ChannelNum
        self.callbackfunc=CalbackFunc
    
    def run(self): 
        # target function of the thread class 
        try: 
            print("thread strart")
            connection = pika.BlockingConnection(self.parameters)
            channel = connection.channel(1)
            channel.basic_qos(prefetch_count=self.pckh)
            channel.basic_consume(queue=self.queuename,
                          on_message_callback=self.callbackfunc,
                          consumer_tag=self.slug)
            print( self.slug ,' [*] Waiting for messages.')
            channel.start_consuming()
            print("thread end")
        finally: 
            channel.stop_consuming()
            channel.close()
            connection.close()
            print('theread stop') 
           
    def get_id(self): 
        # returns id of the respective thread 
        if hasattr(self, '_thread_id'): 
            return self._thread_id
        for id, thread in threading._active.items(): 
            if thread is self: 
                return id
   
    def stop(self): 
        thread_id = self.get_id() 
        res = ctypes.pythonapi.PyThreadState_SetAsyncExc(thread_id, 
              ctypes.py_object(SystemExit)) 
        if res > 1: 
            ctypes.pythonapi.PyThreadState_SetAsyncExc(thread_id, 0) 
            print('Exception raise failure') 
       


def Packet_Handeler_callback(ch, method, properties, body):
     print("Received"+body.decode("utf-8") +" from :" +method.consumer_tag)
     time.sleep(3)
     ch.basic_ack(delivery_tag = method.delivery_tag)
     
# as main :
credentials = pika.PlainCredentials('hgh', 'guest')
parameters = pika.ConnectionParameters('localhost',5672,'/',credentials)
t1 = rbmq(Slug='kjk',ChannelNum=5959,Parameter=parameters,
          prefetch_count=2,
          QueueName='classic_queue_2',
          CalbackFunc=Packet_Handeler_callback
          )
t1.start()

____________________________________________________________________________________________________
____________________________________________________________________________________________________
then in other program im trying to stop it  , and its wont stop !
______________________________________________________________________________________________________
_____________________________________________________________________________________________________

import pika
credentials = pika.PlainCredentials('hgh', 'guest')
parameters = pika.ConnectionParameters('localhost',5672,'/',credentials)

connection = pika.BlockingConnection(parameters)
channel = connection.channel(5959)
channel.basic_cancel("kjk")
channel.stop_consuming("kjk")
connection.close()
________________________________________________________________________________________________
