### ISSUE TITLE
Support automatic connection recovery

### ISSUE THREAD

**Issue by michaelklishin** [pika/pika#858]
À la [Bunny](http://rubybunny.info/articles/error_handling.html), [Java client](http://rabbitmq.com/api-guide.html) and so on.

Pika should copy what other clients do (the steps are quite similar, although there are small differences due to client library APIs not being identical) instead of rolling its own.
It remains to be seen to what extent Pika's multi-I/O library design will complicate this.

**Comment by hairyhum** [comment]
It does not look like this client should necessary have that kind of feature. Effectively for non-blocking connections the `synchronous_publisher_example.html` example is demonstrating a reasonable approach to reconnections and promotes better code quality by separating consumer and producer to make recoverable connection.

Blocking connection can be recovered in exception handling style (similar to php client). For example:
```python
while True:
    connection = pika.BlockingConnection(parameters)

    channel = connection.channel()
    channel.basic_consume(on_message, 'queue')

    try:
        channel.start_consuming()
    except pika.exceptions.ConnectionClosed:
        LOGGER.info('Connection closed. Recovering')
        continue
    except KeyboardInterrupt:
        channel.stop_consuming()

    connection.close()
    break
```

**Comment by vitaly-krugl** [comment]
I agree with @hairyhum's assessment that explicit reconnection by user promotes better code quality. It helps ensure that apps don't miss these important transitions, just as exceptions in OO programming (versus return values in non-OO) help make sure that errors are not ignored.

Related to a specific connection instance, apps will have channels that should no longer work. If the channels are "restored" automatically, then it leads to terrible side-effects - for example, a message received on a specific channel number may only be ACK'ed on that channel. If you automatically "restore" a channel after automatically reopening a connection, then the app will get unexpected errors when ACKing messages that were received on the original channel before reconnection.

**Comment by michaelklishin** [comment]
Fair enough. There are now doc examples that demonstrate recovery.
