### ISSUE TITLE
Python int type does not fit into struct 'i' format

### ISSUE THREAD

**Issue by lanzz** [pika/pika#861]
https://github.com/pika/pika/blob/master/pika/data.py#L118-L123

I'm getting a "struct.error: 'i' format requires -2147483648 <= number <= 2147483647" where my value is 2592000000. That value fits into a Python int, which is `long` and on our platform is 64-bit wide, while struct 'i' format is defined as strictly 32-bit. I can work around that by explicitly casting to `long`, but it is a bug in pika nonetheless.

**Comment by lukebakken** [comment]
* What version of Pika are you using?
* What version of Python are you using?
* What operating system and version are you using?

This is probably the same issue as #640

**Comment by lanzz** [comment]
pika v0.10.0
Python 2.7.6
Ubuntu 14.04.4

It is similar to #640, but is not specific to Python 3; rather it is caused by the assumption that the `int` type will be 32-bit, which is not true on 64-bit platforms.

**Comment by lukebakken** [comment]
Thank you for the additional information.

**Comment by lukebakken** [comment]
@lanzz can you provide code to reproduce this or instructions on how to reproduce? Thanks.

**Comment by lanzz** [comment]
This should be enough to trigger it on a 64-bit platform (assumes you already have a channel open):

```python
channel.queue_declare('queue_name', arguments={'x-message-ttl': 2592000000})
```

This is a 30-day TTL, might seem a lot but in our use cases we route failed tasks to a separate queue where we can inspect and requeue them manually if needed.

**Comment by gmr** [comment]
Seems like the only way to make this work implicitly (which goes against the zen of Python) would be to have if condition blocks in the marshaling code, which will require refactoring the codegen.py.

https://github.com/pika/pika/blob/master/utils/codegen.py#L129

I can't say I agree with the sentiment but understand where it's coming from.

**Comment by lanzz** [comment]
The code I initially highlighted should be fairly easy to change to do the right thing:
https://github.com/pika/pika/blob/master/pika/data.py#L118-L123

Right now it chooses the output size based on the input Python _type_, which does not align with reality. It should explicitly check if the input value will fit into 32 bits and choose 64-bit output if it doesn't, regardless of the Python type. Alternatively, it could always choose to encode integers as 64-bit values I guess. Arguably, it should also raise a `ValueError` if given a value that doesn't fit in 64 bits (as a cursory glance seems to indicate 64-bit integers are the largest integer type supported in AMQP).

**Comment by michaelklishin** [comment]
This problem is generally present in every (or at least many) client in a dynamically typed language. amq-protocol used by Ruby clients serialises numbers as longs for this reason IIRC.
