### ISSUE TITLE
Pika Socket Timeout should support >= 0 for connection

### ISSUE THREAD

**Issue by huntercatalan** [pika/pika#863]
Pika enforces that socket_timeout > 0 in pika version 0.11.0 in connection.py line 479. Although this is probably a good idea, I have a use-case where I would like the socket to never timeout. I can put a large number in there, but that is unnecessary as this spec is not enforced by other AMPQ clients nor anywhere in the AMPQ spec. tocket_timeout >= 0 should work. tx

**Comment by lukebakken** [comment]
A PR with the requested change would be welcome. Thanks!

**Comment by lukebakken** [comment]
@huntercatalan - please refer to the [`settimeout`](https://docs.python.org/2/library/socket.html#socket.socket.settimeout) documentation. Passing `0` has the same effect as putting the socket into non-blocking mode (i.e, no timeouts). You would have to use `None` to actually disable timeouts.
