### ISSUE TITLE
Using None instead of ConnectionParameters._DEFAULT

### ISSUE THREAD

**Issue by apisarek** [pika/pika#872]
I'm wondering why the default parameter in `ConnectionParameters` constructor is defined internally class `_DEFAULT`. If I want to write generic constructor and avoid exponentially big number of possibilities* I have to use externally the `ConnectionParameters._DEFAULT`.  It violates the docstring: `Designates default parameter value; internal use`.

*since Python doesn't have macros (a way to write and execute code dynamically) for each parameter of `ConnectionParameters` I have two options: calling the constructor with or without the certain parameter. The number of `if`s will equal `2^number_of_parameters_in_constructor`

**Comment by lukebakken** [comment]
Hi @apisarek -

This behavior has existed for 2 years and ensures that sane defaults are used for new connections. I'm not exactly sure what issue you're running into so providing example code showing that would be very helpful.

I will close this issue now but please feel free to re-open it if you can provide code showing your use case.

**Comment by apisarek** [comment]
Let's assume that `_DEFAULT` is not for internal use. Then we can write something like this
```
def get_connection_parameters(
        host: str,
        port: Optional[int] = None,
        credentials: Optional[PlainCredentials] = None
) -> ConnectionParameters:
    default = ConnectionParameters._DEFAULT
    parameters = {
        'host': host,
        'port': port or default,
        'credentials': credentials or default
    }
    return ConnectionParameters(**parameters)
```

Now let's assume that we want to be good engineers and don't look into places that we were told explicitly not to look: `Designates default parameter value; internal use`. Then our previous example must turn into:
```
def get_connection_parameters(
        host: str,
        port: Optional[int] = None,
        credentials: Optional[PlainCredentials] = None,
) -> ConnectionParameters:
    parameters = {}
    if port is None and credentials is None:
        parameters = {
            'host': host,
        }
    elif port is None and credentials is not None:
        parameters = {
            'host': host,
            'credentials': credentials
        }
    elif port is not None and credentials is None:
        parameters = {
            'host': host,
            'port': port,
        }
    elif port is not None and credentials is not None:
        parameters = {
            'host': host,
            'port': port,
            'credentials': credentials
        }
    return ConnectionParameters(**parameters)
```
I haven't reduced boolean expressions on purpose so you can get the idea better. Now `port` and `credentials` are optional, so there are 4 options. If the function had let's say 10 optional parameters then we would get 1024 conditional branches.

And as we can see in:
```
    def __init__(self,  # pylint: disable=R0913,R0914,R0912
                 host=_DEFAULT,
                 port=_DEFAULT,
                 virtual_host=_DEFAULT,
                 credentials=_DEFAULT,
                 channel_max=_DEFAULT,
                 frame_max=_DEFAULT,
                 heartbeat=_DEFAULT,
                 ssl=_DEFAULT,
                 ssl_options=_DEFAULT,
                 connection_attempts=_DEFAULT,
                 retry_delay=_DEFAULT,
                 socket_timeout=_DEFAULT,
                 locale=_DEFAULT,
                 backpressure_detection=_DEFAULT,
                 blocked_connection_timeout=_DEFAULT,
                 client_properties=_DEFAULT,
                 **kwargs):
```
there are 16 optional arguments, which gives us 2^16 = 65536 conditional branches. If you are paid per LOC then it's really good idea to spend time!
