### ISSUE TITLE
How to check is a connection ok?

### ISSUE THREAD

**Issue by zhangzx7054** [pika/pika#877]
I tried to use channel.is_open and connetcion.is_open to get the connection's and channel's status, but failed.
The return value is always True, even though I stopped rabbitmq server.
Here is my test code.
```
import pika 
import time

 credit = pika.PlainCredentials(username='cloud', password='cloud')
 connection = pika.BlockingConnection(pika.ConnectionParameters(host='10.32.1.12', credentials=credit))
 channel = connection.channel()

while True:
     connect_close = connection.is_closed
     connect_open = connection.is_open
     channel_close = channel.is_closed
     channel_open = channel.is_open
     print("connection is_closed ", connect_close)
     print("connection is_open ", connect_open)
     print("channel is_closed ", channel_close)
     print("channel is_open ", channel_open)
     print("")
     time.sleep(5)
```

Here is the print log. When rabbitmq server stops, the print log is still the same as below.
![bvvzmq](https://user-images.githubusercontent.com/6235662/30780702-d3d0e9bc-a143-11e7-8adf-7520745c9463.jpg)

**Comment by lukebakken** [comment]
Hello @zhangzx7054 -

Since you are using a `BlockingConnection`, heartbeats will only be processed if you actually do something with the channel. You can see this behavior with the following code:

```
import logging
import pika 
import time

logging.basicConfig(level=logging.DEBUG)
# logging.basicConfig(level=logging.INFO)

creds = pika.PlainCredentials(username='guest', password='guest')
params = pika.ConnectionParameters(host='localhost', credentials=creds,
                                   heartbeat_interval=10, blocked_connection_timeout=10)
connection = pika.BlockingConnection(params)
channel = connection.channel()

while True:
     print(time.strftime('%c', time.localtime()))
     channel.basic_publish('', 'my-alphabet-queue', 'abc')
     connect_close = connection.is_closed
     connect_open = connection.is_open
     channel_close = channel.is_closed
     channel_open = channel.is_open
     print("connection is_closed ", connect_close)
     print("connection is_open ", connect_open)
     print("channel is_closed ", channel_close)
     print("channel is_open ", channel_open)
     print("")
     time.sleep(5)
```

If you use one of the asynchronous adapters for your client code, you will also see the heartbeat mechanism detect lost connections. Please refer to the [example code](https://github.com/pika/pika/blob/master/examples/asynchronous_consumer_example.py).

**Comment by austinnichols101** [comment]
@lukebakken Is there a way to directly trigger a heartbeat `send_and_check` with a  BlockingConnection?  

My current workaround to **"do something with the channel"** is to check for the existence of an exchange, but I would prefer to simply force a heartbeat to show RMQ that my process is still alive. 

`self._channel.exchange_declare(exchange=self.EXCHANGE, passive=True)`

**Comment by vitaly-krugl** [comment]
If you periodically call `BlockingConnection.process_data_events` or `BlockingConnection.sleep()` it will attempt to send a heartbeat when it's time, and should raise `ConnectionClosed` when it fails to send on a closed TCP/IP stream.

In practice, you have to be prepared any time for a dropped connection (RabbitMQ issue, network issue, etc.). Checking a connection just before sending something is not guarantee that connection won't be lost while your're sending, so you need to anticipate re-connection and retries. For example, see [_RETRY_ON_AMQP_ERROR decorator and _ChannelManager wrapper of AMQP client](https://github.com/numenta/numenta-apps/blob/46fff2aec40c1a4d122f575ec0e3edeac0456068/nta.utils/nta/utils/message_bus_connector.py)
