### ISSUE TITLE
IOError: [Errno 4] (Interrupted system call) in Pica

### ISSUE THREAD

**Issue by pehrsoderman** [pika/pika#879]
OS: Ubuntu 16.04.03
Pica version: 0.10.0-1
Python version: 2.7.12

I am seeing cases of IOError: [Errno 4] (Interrupted system call) in Pica under load. A typical traceback looks like this: 

```
IOError: [Errno 4] Interrupted system call
(3 additional frame(s) were not displayed)
...
  File "pika/adapters/blocking_connection.py", line 1935, in basic_get
    self._basic_getempty_result.is_ready)
  File "pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "pika/adapters/select_connection.py", line 590, in poll
    events = self._poll.poll(self.get_next_deadline())
```

The relevant lines in the code looks like this: 

```
            try:
                events = self._poll.poll(self.get_next_deadline())
                break
            except _SELECT_ERROR as error:
                if _get_select_errno(error) == errno.EINTR:
                    continue
                else:
                    raise
```

Without knowing the details of the implementation, it looks to me like a select() call being interrupted, and the code attempting to catch the EINTR somehow failing.

**Comment by shinji-s** [comment]
I think you have hit a bug that has been patched but not in the version of pika you are using.
See https://github.com/pika/pika/issues/664.

**Comment by lukebakken** [comment]
Hello, thank you for your report. Please upgrade to Pika `0.11.0` to see if that resolves your issue. If it does not, feel free to re-open this issue. Thanks!

**Comment by pehrsoderman** [comment]
Will try with 0.11.0 and see if it goes away!

**Comment by sevaivanov** [comment]
It does go away on 0.11.0, cheers 🐙
