### ISSUE TITLE
basic_cancel no longer stops basic_consume

### ISSUE THREAD

**Issue by radzhome** [pika/pika#885]
This was fine under pika-0.10.0 but no longer working with pika-0.11.0

My message loop looks something like:
```
            self._channel.basic_qos(prefetch_count=1)
            self._consumer_tag = self._channel.basic_consume(callback,
                                                             queue=self._queue,
                                                             consumer_tag=self._consumer_tag)
            self._channel.start_consuming()
```

Stop message loop runs this:

```
self._channel.basic_cancel(consumer_tag=self._consumer_tag)
```

I use a signal to run the stop message loop
```
    signal.signal(signal.SIGTERM, handle_shutdown)  # sig num 15, terminated
    signal.signal(signal.SIGQUIT, handle_shutdown)  # sig num 3, terminal quit
    signal.signal(signal.SIGINT, handle_shutdown)  # sig num 2, terminal interrupt
```

I know it runs the cancel even with pika 11 but the cancel doesn't seem to interrupt the message loop code anymore.

UPDATE:
This seems to only affect blocking the connection.

For now I am going back to pika 0.10 which resolves the issue

**Comment by radzhome** [comment]
UPDATE:

I was wrong, it is also a problem with select connection.

**Comment by lukebakken** [comment]
@radzhome could you please provide a complete code sample that I can run? Thanks. I am currently investigating #841 but I see the same behavior in `0.10.0` as the current code in that issue.
