### ISSUE TITLE
Question re. interrupting `BlockingChannel.consume` from another thread

### ISSUE THREAD

**Issue by Bogdanp** [pika/pika#892]
In [Dramatiq][dramatiq] I've got an architecture where consumers live on their own thread and call `BlockingChannel`'s `consume` method with an inactivity timeout of `1s` by default. Whenever a consumer gets a message from Rabbit, it puts it on a shared in-memory work queue where it is grabbed and processed by any of `n` worker threads. Once the worker thread is done processing the message, it gets put on an "acks" queue that belongs to the consumer. When the consumer hits the inactivity timeout it acks any pending messages off its queue and then waits for new messages from RMQ.

Acking from the worker threads is not an option since `BlockingChannel`s are not thread safe.

When you set a QoS value the fact that `consume` can't be interrupted from another thread really starts to hurt throughput, at which point you are forced to either:

1. use a tiny `inactivity_timeout` (<100ms), which "fixes" the throughput issue but is essentially a spinlock so it's inefficient,
2. switch to `SelectConnection` and implement your own interrupt, this is probably what any sane person would do, but the problem is you'd end up implementing a lot of stuff that `BlockingChannel` already implements, or
3. hack your own interrupt by hooking into implementation details of `BlockingChannel`.

The latter is what I ended up doing ([here][c1], [here][c2] and [here][c3]) and my interrupt implementation is working well, but I don't feel too good about depending on `BlockingConnection`'s implementation details so my "issue" is more of a question than anything: is there a better way I could be doing this and, if not, would this be a good addition to `BlockingConnection` (I'd be happy to contribute)? 

[dramatiq]: http://dramatiq.io/
[c1]: https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/rabbitmq.py#L359-L373
[c2]: https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/rabbitmq.py#L422-L435
[c3]: https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/rabbitmq.py#L439-L458

**Comment by lukebakken** [comment]
Hi Bogdan -

Sorry it has taken a while to review how you've modified Pika to suit your needs. If you would like to submit a pull request with proposed changes (like [this suggestion](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/brokers/rabbitmq.py#L362-L363)), I would be happy to review them.

Thanks! 🎄

**Comment by zjj** [comment]
we overload BlockingConnection _flush_output, with Rlock to fix this, but not sure if just flush_output with lock is enough for threading safe.

**Comment by vitaly-krugl** [comment]
Pika's BlockingConnection is not at all thread-safe (there is no panacea either). Also, cPython threading and Global Interpreter Lock (GIL) are dubious for performance and concurrency.

I am guessing that you're processing the messages in a separate thread because it takes too long to process each one and this is causing the default AMQP heartbeat to time out and the connection to be dropped.

A common technique that I recall from some other event frameworks is to enable callbacks to be requested from the event loop in a thread-safe manner. This would be a more generally useful and flexible mechanism to facilitate the sort of thing you're trying to do, I think.

Just for reference, I created a functional prototype of thread-safe connection sharing via BlockingConnection-style API in https://github.com/vitaly-krugl/pika/tree/threaded-connection/pika. This prototype runs the client stack on a separate thread, such that application clients can take as long as they wish to process messages and not worry about missed heartbeats.

**Comment by vitaly-krugl** [comment]
pull request #956 will enable you to accomplish this via new method `add_callback_threadsafe`.

**Comment by Bogdanp** [comment]
@vitaly-krugl great! I've scanned the PR, but I don't have the pika implementation in my head atm. I assume [this line](https://github.com/pika/pika/pull/956/files#diff-40dd0dca78d99b5a2a1315abbcd71b70R543) ensures the polling mechanism's loop is interrupted and the callback is run immediately in the connection's thread, correct? If so, that looks great! Hope it gets merged. :D

**Comment by vitaly-krugl** [comment]
You will be able to process your message on another thread, and then delegate the call to `channel.basic_ack` to your pika thread that is executing `BlockingChannel.consume` via `BlockingConnection.add_callback_threadsafe`. See [example](https://github.com/vitaly-krugl/pika/blob/2c2b2e6efd45ac26ccc00bf0bb2874efe4cabbce/pika/adapters/asyncio_connection.py#L55-L62)

**Comment by Bogdanp** [comment]
Yup, I got that from the PR. My question was more about whether or not the `select/poll/epoll/kqueue` calls would keep blocking until the idle timeout or if they would be interrupted and thereby the callback would run immediately. Looking at [this test](https://github.com/pika/pika/pull/956/files#diff-e6451a0543d3370605bcfe2c985f3e52R1716) it looks like they do get interrupted so that's great! Thanks!

**Comment by vitaly-krugl** [comment]
Yes, should be interrupted!

**Comment by vitaly-krugl** [comment]
To clarify, BlockingConnection implements reentrancy control to avoid runaway recursion involving callbacks. In particular, it would not get interrupted in the middle of sending a command or message to the broker until that request completes and control goes back to one of the event-loop drivers. On the other hand, it should get interrupted very quickly if simply waiting inside one of the event loop drivers `BlockingConnection. ..sleep() ... process_data_events() ...start_consuming() ...consume()`.
