### ISSUE TITLE
Count unacked message count

### ISSUE THREAD

**Issue by sachind-cuelogic** [pika/pika#896]
- How to count unacked message count 
- We can find ready message count in pika by using 
```
rabbitmq_queue = channel.queue_declare(queue=GoogleRequeue_Queue, 
                                                durable=True)
ready_queue_length = rabbitmq_queue.method.message_count
```
from this I can find ready message count from queue
- But how can I find unacked message count from queue using pika (python)

**Comment by lukebakken** [comment]
Hello -

Retrieving the unacked message count is not part of the AMQP specification. You can, however, query the RabbitMQ REST API to retrieve the count. This is not a feature that Pika will support.

More info here: https://stackoverflow.com/q/13721066
