### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by trenton42** [pika/pika#897]
Would it be possible to make a release? Our hosting provider's Linux version now has a `+` at the end, and the released version breaks (but this has already been fixed in master).

**Comment by trenton42** [comment]
In the mean time, I changed my requirements to `git+https://github.com/pika/pika.git@387cb322885cfcf54f9f14b63b03fac6c2ce0ca5#egg=pika` (pinned to the specific commit with the fix instead of `master` in case some breaking changes are committed)

**Comment by michaelklishin** [comment]
We are going to release 0.11.2 in a bit.

**Comment by trenton42** [comment]
@michaelklishin Thanks!

and Thanks @lukebakken for the version fix

**Comment by michaelklishin** [comment]
[Release announcement](https://groups.google.com/forum/#!topic/rabbitmq-users/6h4BmWlNJGY).
