### ISSUE TITLE
exchange name in exchange_declare callback

### ISSUE THREAD

**Issue by jdavid** [pika/pika#898]
Hi,

The callback passed to ``exchange_declare`` gets a ``pika.frame.Method`` object, but apparently it is not possible to get the exchange name from it.

This is similar to https://stackoverflow.com/questions/19500319/exchange-name-in-pika-exchange-declare-callback

Is it possible to add this feature?

Thanks!

**Comment by lukebakken** [comment]
@jdavid please check out issue #158 where a suggestion to pass arbitrary user data to callbacks is suggested.

**Comment by jdavid** [comment]
That would be cool. Right now I am using closures for the callbacks passed to ``exchange_declare``, ``queue_declare``, ``queue_bind`` and ``basic_consume``.

Guess we can close this issue as a dup.

**Comment by lukebakken** [comment]
This will be resolved by #158
