### ISSUE TITLE
"too many values to unpack" for BlockingChannel.Consume

### ISSUE THREAD

**Issue by bartverstrynge** [pika/pika#899]
Trying out a very simple example, where I can receive messages using 

`method_frame, header_frame, body = channel.basic_get(queue=_queueName)`

Now I would like this to become a blocking call, so I found consume, and try to use it as such:

`a, b, c = channel.consume(queue=_queueName, inactivity_timeout=1)`

This gives me a "too many values to unpack", as if the function isn't returning a tuple of 3 parts. I'm not a Python pro - but I'm just following the tutorial and something looks off here?

**Comment by lukebakken** [comment]
"just following the tutorial" - could you please link to the tutorial you are using? It may be out of date.

**Comment by bartverstrynge** [comment]
So what I did was follow http://pika.readthedocs.io/en/0.10.0/examples/blocking_basic_get.html and get a basic queue producer and consumer up and running, which works. I had my basic_get with a sleep of 10 seconds if it saw a None. To make consumption faster, I then looked at actual blocking calls with time-outs, and moved to the consume functionality, looking at http://pika.readthedocs.io/en/0.11.2/examples/blocking_consumer_generator.html combined with http://pika.readthedocs.io/en/0.11.0/modules/adapters/blocking.html which states

> inactivity_timeout (float) – if a number is given (in seconds), will cause the method to yield None after the given period of inactivity; this permits for pseudo-regular maintenance activities to be carried out by the user while waiting for messages to arrive. If None is given (default), then the method blocks until the next event arrives. NOTE that timing granularity is limited by the timer resolution of the underlying implementation. NEW in pika 0.10.0.

As such, I tried the code in my first post, which gives the error indicated.

**Comment by lukebakken** [comment]
@bartverstrynge - the value returned by `consume` is a generator, which means you must iterate over it and not try to unpack it as though the value is a tuple. This is why the example [here](http://pika.readthedocs.io/en/0.11.2/examples/blocking_consumer_generator.html) uses a `for` loop.

This code may make it a little clearer:

```python
import pika
import pprint

connection = pika.BlockingConnection()
channel = connection.channel()
result = channel.consume('test', inactivity_timeout=1)
pprint.pprint(result)
try:
    a, b, c = result
except ValueError as err:
    pprint.pprint(err)
    for val in result:
        pprint.pprint(val)
```

**Comment by bartverstrynge** [comment]
This makes a LOT of sense - thanks for your explanation. Sorry for this faulty ticket :)

**Comment by lukebakken** [comment]
It's no problem, I'm glad to help out. Frequently when I don't understand how an API is supposed to work I'll check out the test suite, too. Have a good weekend 😺
