### ISSUE TITLE
Pika hangs on windows.

### ISSUE THREAD

**Issue by fornof** [pika/pika#900]
I am having issues with pika hanging on windows. 
I am using windows 10 64 bit, Cygwin, Python27. 
when I try https://www.rabbitmq.com/tutorials/tutorial-one-python.html , send.py works. However when I try python receive.py , it just hangs, I put in print statements. Nothing prints out unless I comment out the def callback . Here is the  receive.py with comments: https://gist.github.com/fornof/8624c476f2adadd73c1200e1f119dd9d

Here is my pip freeze: https://gist.github.com/fornof/8624c476f2adadd73c1200e1f119dd9d#file-pip-freeze
Here is my python verbose debug result, it hangs on the last line and does not continue.  https://gist.github.com/fornof/8624c476f2adadd73c1200e1f119dd9d#file-python-v-d-receive-py
Any help would be appreciated.

**Comment by lukebakken** [comment]
Hello - thanks for providing code. Reading your description it's not exactly clear what works and what doesn't, because I'm not exactly sure what "comment out the def callback" means.

If you could provide two `receive.py` files - one working, and one not, that would be great.

Also, Pika is not tested using Cygwin. Could you try the native Python 2.7 build for Windows?

**Comment by fornof** [comment]
Hello , thanks for responding. 
 in receive.py  working: https://gist.github.com/fornof/8624c476f2adadd73c1200e1f119dd9d#file-receive-py-working , I commented out those lines and it works meaning it prints out lines. When those lines that are necessary are left uncommented, Pika/python hangs. 
the other receive.py is https://gist.github.com/fornof/8624c476f2adadd73c1200e1f119dd9d#file-receive-py and does not work (it hangs) 

I am running native python2.7 build for windows (located at c:\Python27) as I was doing earlier.

**Comment by lukebakken** [comment]
Thanks again for those files. I am unable to reproduce your issue using Python 2.7 on Windows 8.1 (the VM I have available). Here is what I tried:

* Installed RabbitMQ 3.7.0 on the VM
* Installed Python 2.7.14 from [here](https://www.python.org/downloads/release/python-2714/) using the MSI installer.
* Modified your code to connect using this URI: `amqp://guest:guest@127.0.0.1/%2F` (`%2F` is the default vhost `/` url-encoded)
* Set the `PATH` to include the values you see in the screenshot.
* Use `pip` to install `pika`
* Run the program. As you can see, it waits for messages until I enter `CTRL-C`:

![pika-gh-900-repro](https://user-images.githubusercontent.com/514926/33693205-546c1c7c-daa6-11e7-9e83-895078517077.png)

At this point I'm not sure what is the issue in your environment. I would make sure that you are using the `python` executable that you expect, or give it a try on a different Windows machine/VM.

Here is the exact code that I ran -  notice that I removed the comment from the `queue_declare` method call:

```python
print ('importing pika')
import pika
print "started"
connection = pika.BlockingConnection(pika.URLParameters('amqp://guest:guest@127.0.0.1/%2F'))

channel = connection.channel()
print "hey there"

channel.queue_declare(queue='hello')

def callback(ch, method, properties, body):
    print " [x] Received %r" % body

channel.basic_consume(callback, queue='hello', no_ack=True)

print ' [*] Waiting for messages. To exit press CTRL+C'
print "waiting"
channel.start_consuming()
print "done consuming"
```

**Comment by fornof** [comment]
Thank you so much for those steps and for your help. I tried all those steps and in CMD it works. when I tried running it in Cygwin, it still bombs. Cygwin is the issue. I learned something new about using cygwin today. I will transition my workflow to using CMD and powershell as pika runs great on those. 
Thanks again!

**Comment by lukebakken** [comment]
Oh, OK, that's what wasn't clear. When I asked about Cygwin, I thought you were using *both* the Cygwin `bash` shell and Cygwin-installed Python. Yes, if you mix Windows-native Python with the Cygwin `bash` shell I'm sure weird things happen.
