### ISSUE TITLE
how could I check "queue" already exist in exchange or in virtual host?

### ISSUE THREAD

**Issue by nooperpudd** [pika/pika#914]
it's there any api to check queue exist or channel.basic_publish(exchange="",
                              routing_key=properties.reply_to,body="")

or routing_key exist?

```

> 'A non-string value was supplied for self.routing_key'
> AssertionError: A non-string value was supplied for self.routing_key

**Comment by lukebakken** [comment]
> 'A non-string value was supplied for self.routing_key'

This means that the value of `properties.reply_to` was not a string, which is required.

You don't check to see if a queue exists - just declare it and if it doesn't exist it will be created.

**Comment by mglowinski93** [comment]
@lukebakken 
What is actually impact of `basic_publishing` something to not existing `routing_key`?
I do not get any error from pika.

I do not want to define this queue, since it's an RPC consumer.
It might happen that producer closed this queue on timeout.

**Comment by mglowinski93** [comment]
@lukebakken 

> in the future, rather than commenting on an old, closed issue, please start a new discussion:

sure, i will. I simply didn't want to mess-up with similar topic in different issue.


> You won't. If RabbitMQ can't route a message, it is dropped. However, you should be using the [mandatory flag](https://github.com/pika/pika/blob/2135a24ca849e78addcdfec3ed701da2d7521e25/docs/examples/blocking_publish_mandatory.rst) if you need to know a message wasn't routed.

Thank you, that is what i needed to know.
