### ISSUE TITLE
Override of socket.socketpair may break some application code

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#916]
cc @lukebakken 

PR #908 overrides socket.socketpair. This assignment will break application code that has its own check and workaround for missing socket.socketpair, particularly when the application needs to create a socket pair with parameters not supported by this limited implementation. See https://github.com/pika/pika/pull/908/files#r160840234

This is why we originally contained that limited socketpair logic inside the internal method `_get_interrupt_pair` and didn't set attributes in the `socket` module.

**Comment by lukebakken** [comment]
OK, I'll take the implementation and make it internal to `pika`. Thanks for the heads-up.
