### ISSUE TITLE
Pika not working with SSL on recent version of RabbitMQ

### ISSUE THREAD

**Issue by hvico** [pika/pika#922]
Hello,

I tried to implement the provided SSL example for RabbitMQ:

[Link](https://pika.readthedocs.io/en/latest/examples/tls_mutual_authentication.html)

Client code:

#!/usr/bin/env python
import pika
import ssl
import logging

logging.basicConfig(level=logging.INFO)

cp = pika.ConnectionParameters('Mac-Pro-host', 5672, '/',
    ssl=True,
    ssl_options=dict(
        ssl_version=ssl.PROTOCOL_TLSv1,
        ca_certs="/somepath/testca/cacert.pem",
        keyfile="/somepath/localclient/key.pem",
        certfile="/somepath/localclient/cert.pem",
        cert_reqs=ssl.CERT_REQUIRED))

conn = pika.BlockingConnection(cp)
ch = conn.channel()

ch.queue_declare(queue='testssl')

ch.basic_publish(exchange='',
                      routing_key='testssl',
                      body='Hello World!')
print(" [x] Sent 'Hello World!'")
connection.close()

I could not make it work, I always get this error:

`
INFO:pika.adapters.base_connection:Connecting to 10.0.1.12:5672 with SSL
WARNING:pika.adapters.base_connection:Connection to 10.0.1.12:5672 failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
WARNING:pika.connection:Could not connect, 0 attempts left
ERROR:pika.adapters.blocking_connection:Connection open failed - u'Connection to 10.0.1.12:5672 failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)'
Traceback (most recent call last):
  File "./sendSSL.py", line 17, in <module>
    conn = pika.BlockingConnection(cp)
  File "build/bdist.macosx-10.13-intel/egg/pika/adapters/blocking_connection.py", line 374, in __init__
  File "build/bdist.macosx-10.13-intel/egg/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
  File "build/bdist.macosx-10.13-intel/egg/pika/adapters/blocking_connection.py", line 468, in _flush_output
pika.exceptions.ConnectionClosed: Connection to 10.0.1.12:5672 failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
`

I tried different options in ssl_version param: ssl.PROTOCOL_TLSv1, ssl.PROTOCOL_TLSv1_1, ssl.PROTOCOL_TLSv1_2, ssl.PROTOCOL_TLS. Everytime I get the same Wrong Version error.

My RabbitMQ server environment: RabbitMQ 3.7.2 (installed via HomeBrew) running at MacOS High Sierra 10.13.2. Tried to downgrade to RabbitMQ 3.6.14, same error.

The client runs from Windows (tried using both Python 2.7.14 and 3.6) and openssl 1.0.2n and I got the same error.

I also tried to run the client from the MacOS server itself (creating a client cert for it), it has Python 2.7.10. Got the same exact error (WRONG_VERSION_NUMBER).

**Comment by lukebakken** [comment]
You are connecting to port `5672` which is the default, non-TLS/SSL port for RabbitMQ. I can reproduce this error by connecting to that port. Be sure that you are connecting to the TLS/SSL port of your RabbitMQ server. If you are using the configuration from that example, the port is `5671`

**Comment by hvico** [comment]
Thanks lukebakken, you're absolutely right, it was as simple as that! I now see I checked the connection using openssl -s_client on port 5671 which gave me an OK message. Thank you very much.
