### ISSUE TITLE
Allow the use of TLS SNI

### ISSUE THREAD

**Issue by gbartl** [pika/pika#929]
The python SSL library allows the specification of a server_hostname parameter as part of the SSLContext.wrap_socket function. Setting this parameters to a server address enables the TLS SNI extension. At the moment pika does not expose this particular SSL parameter to the user due to it using the similar ssl.wrap_socket function. 

Enabling TLS SNI is required to connect to rabbitmq using TLS when rabbit is deployed on OPENSHIFT.

**Comment by lukebakken** [comment]
We would be happy to accept a pull request with this change. Thanks!

**Comment by lukebakken** [comment]
Resolved by #932
