### ISSUE TITLE
Connection drops when handling tasks with a long duration

### ISSUE THREAD

**Issue by GWSzeto** [pika/pika#930]
I'm starting to get the same error as #418 even when I adjust the heartbeat connection parameter.
My tasks take usually around 5 mins, but even then, when I set the heartbeat to both 0 and some very large number (ie: 60000)

My code Is essentially identical to the issue I mentioned above and the error I receive is this:
`Traceback (most recent call last):
  File "instagram_worker.py", line 43, in <module>
    channel.start_consuming()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 716, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 518, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1403, in _dispatch_events
    evt.body)
  File "instagram_worker.py", line 37, in dataHandler
    channel.basic_ack(delivery_tag=method.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1988, in basic_ack
    self._flush_output()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "error(104, 'Connection reset by peer')")`

**Comment by vitaly-krugl** [comment]
See comment https://github.com/pika/pika/issues/892#issuecomment-356783950

**Comment by vitaly-krugl** [comment]
And which version of Pika are you using?

**Comment by GWSzeto** [comment]
I'm using version 0.11.2

And after reading your comment from the other issue, I just wanted to clarify if it is like this example from the pika Doumentation http://pika.readthedocs.io/en/0.10.0/examples/connecting_async.html

**Comment by gmr** [comment]
Since it's async, are you letting the IO Loop process events while you're doing work or are you blocking the whole time?

You might want to implement something like this in a tight inner loop when processing a big message on an async stack: 
http://rejected.readthedocs.io/en/3.19.5/api_consumer.html#rejected.consumer.Consumer.yield_to_ioloop

**Comment by GWSzeto** [comment]
Since I am fairly new to this, correct me if I am wrong, but from what I understand, the IO Loop is what handles taking in tasks and publishing them into the event loop

If what I said above is true, then I have my publisher and my worker in 2 separate files, where I just ran the publisher once and published all the tasks to the queue and had it stop completely.

Then I had my worker go and consume from the queue after

**Comment by gmr** [comment]
AMQP is a bi-directional RPC protocol. Blocking communication with the server in single threaded/processing apps is less than ideal and can create unpredictable results.

Sorry I see you're using BlockingConnection but linked to the async example.

If you have a for loop in your code when processing a message, I'd suggest you invoke this on each iteration:

http://pika.readthedocs.io/en/0.11.2/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingConnection.process_data_events

**Comment by GWSzeto** [comment]
I'm going to post my code here just in case it's something external to pika,

`from google.cloud import bigquery
import pandas as pd
import pika
import re
import json
from unidecode import unidecode
from time import sleep

client = bigquery.Client(project="some_project")
params = pika.ConnectionParameters(host='localhost', heartbeat=600000)
connection = pika.BlockingConnection(params)
channel = connection.channel()
channel.queue_declare(queue="some_queue", durable=True)

def dataHandler(channel, method, properties, body):
    body = json.loads(body)
    csvURL = body["csvURL"]
    tablename = body["tablename"]
    print("recieved csv batch for %s" % tablename)

    df = pd.read_csv(csvURL, encoding="utf-8")
    print("read in the csv")
    columns = list(df)
    ascii_only_name = [unidecode(name) for name in columns]
    cleaned_column_names = [re.sub("[^a-zA-Z0-9_ ]", "", name) for name in ascii_only_name]
    underscored_names = [name.replace(" ", "_") for name in cleaned_column_names]
    valid_gbq_tablename = "test." + tablename
    df.columns = underscored_names

    # try:
    df.to_gbq(valid_gbq_tablename, "some_project", if_exists="append", verbose=True, chunksize=10000)
    # print("Finished Exporting")
    # except Exception as error:
    #     print("unable to export due to: ")
    #     print(error)
    #     print()
    channel.basic_ack(delivery_tag=method.delivery_tag)


channel.basic_qos(prefetch_count=1)
channel.basic_consume(dataHandler, queue="some_queue")
try:
    channel.start_consuming()
except KeyboardInterrupt:
    channel.stop_consuming()
channel.close()`

**Comment by gmr** [comment]
Try something like this:

```python
import re
import json
import threading

from google.cloud import bigquery
import pandas as pd
import pika
from unidecode import unidecode


def process_export(url, tablename):
    df = pd.read_csv(csvURL, encoding="utf-8")
    print("read in the csv")
    columns = list(df)
    ascii_only_name = [unidecode(name) for name in columns]
    cleaned_column_names = [re.sub("[^a-zA-Z0-9_ ]", "", name) for name in ascii_only_name]
    underscored_names = [name.replace(" ", "_") for name in cleaned_column_names]
    valid_gbq_tablename = "test." + tablename
    df.columns = underscored_names

    # try:
    df.to_gbq(valid_gbq_tablename, "some_project", if_exists="append", verbose=True, chunksize=10000)
    # print("Finished Exporting")
    # except Exception as error:
    #     print("unable to export due to: ")
    #     print(error)
    #     print()


def data_handler(channel, method, properties, body):
    body = json.loads(body)

    thread = threading.Thread(target=process_export, args=(body["csvURL"], body["tablename"]))
    thread.start()
    while thread.is_alive():
        channel._channel.sleep(1.0)
    print('Back from thread')
    channel.basic_ack(delivery_tag=method.delivery_tag)


def main():
    params = pika.ConnectionParameters(host='localhost', heartbeat=60)
    connection = pika.BlockingConnection(params)
    channel = connection.channel()
    channel.queue_declare(queue="some_queue", durable=True)
    channel.basic_qos(prefetch_count=1)
    channel.basic_consume(data_handler, queue="some_queue")
    try:
        channel.start_consuming()
    except KeyboardInterrupt:
        channel.stop_consuming()
    channel.close()


if __name__ == '__main__':
    main()
```

**Comment by GWSzeto** [comment]
It works now, thank you so much for your help

**Comment by lukebakken** [comment]
Thanks @gmr

**Comment by vitaly-krugl** [comment]
`add_callback_threadsafe` in pull request #956 likely offers a more efficient solution without polling.

**Comment by daudn** [comment]
Is it possible to implement a similar heartbeat threading while using channel.basic_get? I need my consumer to consume only 'one' task and then acknowledge before quitting.

**Comment by lukebakken** [comment]
@daudn please post your question to [`pika-python`](https://groups.google.com/forum/?pli=1#!forum/pika-python) and include code that can be reviewed. Thank you for using Pika.
