### ISSUE TITLE
How to get the arguments passed from basic_consume in consumer_callback function?

### ISSUE THREAD

**Issue by northtree** [pika/pika#939]
basic_consume(consumer_callback, queue='', no_ack=False, exclusive=False, consumer_tag=None, arguments=None)
http://pika.readthedocs.io/en/latest/modules/channel.html#pika.channel.Channel.basic_consume

I had passed **arguments={'k':'v'}**. My question is how to get them from consumer_callback function?

**Comment by lukebakken** [comment]
Those are arguments to RabbitMQ, not to your callback. Please see #158 for solutions to what you're trying to do.

**Comment by northtree** [comment]
Thanks @lukebakken 

BTW, I suggest to update the document as it's quite confusing.
> arguments (dict) – Custom key/value pair arguments for the consumer

**Comment by lukebakken** [comment]
We would gladly accept a pull request with suggested changes. Thanks!
