### ISSUE TITLE
Inconsistent logging level when connecting fails

### ISSUE THREAD

**Issue by RasmusWL** [pika/pika#943]
In the function `_create_and_connect_to_socket` if there is a problem connecting, if it is a timeout an ERROR will be logged, but if there is any other problem a WARNING will be logged. This seems inconsistent. (also, if there is SSL problem, this is logged as ERROR)

https://github.com/pika/pika/blob/a7fed210bd5e0611961a6f94063866f0a04010b2/pika/adapters/base_connection.py#L210-L235

**Comment by lukebakken** [comment]
We would welcome a PR to change this, thanks!
