### ISSUE TITLE
BlockingChannel.basic_qos hanging on non-integer parameters

### ISSUE THREAD

**Issue by maggyero** [pika/pika#944]
Under Python 3.6.4 and Pika 0.11.2, the `BlockingChannel.basic_qos` method hangs when setting its `prefetch_size` or `prefetch_count` parameter to a non-integer value.

Input:

```
$ python3 <<EOF
import pika
with pika.BlockingConnection() as connection:
    channel = connection.channel()
    channel.basic_qos(prefetch_size="hello")
EOF
```

**Comment by lukebakken** [comment]
We would be happy to accept a PR to address this. Please include tests.

**Comment by michaelklishin** [comment]
Looks like this has been addressed in method_completed, message_delivered, message_acked, and message_nacked.
