### ISSUE TITLE
Support for AMQP 1.0

### ISSUE THREAD

**Issue by ronaldddilley** [pika/pika#950]
Wasn't sure where to ask this question...

Do you plan on supporting AMPQ 1.0 in a future version?

**Comment by lukebakken** [comment]
Hi Ronald -

Without a lot of demand or community help in implementing AMQP 1.0, I doubt that Pika will support it. AMQP 1.0 is a brand-new protocol and is in no way a successor to AMQP 0.9.1.

You may find [this list](https://github.com/xinchen10/awesome-amqp#libraries-and-clients) helpful to track down a Python client you can use.

I'm going to close this issue, but @gmr may wish to add input.

**Comment by ronaldddilley** [comment]
Thanks for your quick response.
