### ISSUE TITLE
Channel.basic_consume doesn't support consume-ok/completion callback

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#953]
[Channel.basic_consume](https://github.com/pika/pika/blob/3d3b95d31b67dfeaf5ef43650c162e25169336e6/pika/channel.py#L263) doesn't provide an argument for specifying the completion callback to be called upon [consume-ok](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.consume-ok). (the callback arg that it presently supports is for consuming incoming messages).

A client's logic might need to know that the `basic-consume` request succeeded before initiating other operations (e.g., when requesting exclusive access). Lack of the completion callback prevents the application from doing so easily.

Implementation notes:
1. Rename `Channel.basic_consume`'s consumer callback (presently named `callback`) to `consumer_callback`, `message_callback`, `message_rx_callback`, or similar, and name the completion callback `callback` to follow the recently-established convention for naming of completion callbacks. Also rename the consumer callback arg in `BlockingChannel.basic_consume` for consistency with `Channel.basic_consume`.
2. If completion callback isn't specified, auto-generate and return the consumer tag  following the legacy behavior. If completion callback is specified, return None from `Channel.basic_consume` and let the server generate the consumer tag and return it via [consume-ok](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.consume-ok). Update the docstring in `Channel.basic_consume` to reflect this.
3. Make sure pika's [Channel._generate_consumer_tag](https://github.com/pika/pika/blob/3d3b95d31b67dfeaf5ef43650c162e25169336e6/pika/channel.py#L323) doesn't generate consumer tags that can potentially collide with server-generated ones by prefixing "pika" into the consumer tag name that `Channel._generate_consumer_tag` generates.

**Comment by vitaly-krugl** [comment]
cc @lukebakken

**Comment by lukebakken** [comment]
@vitaly-krugl I'm wondering about how I can replace the [existing behavior](https://github.com/pika/pika/blob/master/pika/channel.py#L303-L312) with regard to consumer tag with a server-generated one, in the case where a completion callback is provided. As you can see, the code remembers the Pika-generated consumer tag for use later on. I _think_ I should be able to generate a "temporary" consumer tag and then replace that with the server-generated one when the `basic.consume-ok` message comes back, but I thought I'd ask in case you can think of issues that could cause.

**Comment by vitaly-krugl** [comment]
> I'm wondering about how I can replace the existing behavior with regard to consumer tag with a server-generated one ...
@lukebakken, I supposed the easiest for now is to continue to generate the consumer tag in pika as we do presently.

**Comment by lukebakken** [comment]
> Still, continuing to generate the consumer tag in pika seems like the safest and simplest approach with no apparent downside

Agreed, I'll do that.

**Comment by lukebakken** [comment]
@vitaly-krugl - what do you think of naming callback parameters in the same style as in [`asyncio`](https://docs.python.org/3/library/asyncio-protocol.html#connection-callbacks)? For instance, instead of a generic `callback` parameter on method completion, it would be called `method_completed` (i.e. for `basic.consume-ok`). Likewise, `ack_nack_callback` would be split up into `message_acked` and `message_nacked`, in in the `basic.consume` case, we could call it `message_delivered`

**Comment by vitaly-krugl** [comment]
`method_completed`, `message_acked`,  and `message_nacked` all sound like booleans. Truthfully, I am also not crazy about naming something generically just `callback`, as it's not sufficiently self-documenting. Using completion as an example, we could probably adopt an existing convention from elsewhere - e.g., `on_completion`, `completion_callback`, `completion_cb`.  And for others - e.g., `on_message`, `delivery_cb`, `on_message_ack`, `message_ack_cb`, `msg_ack_cb`, etc.

Regarding splitting `ack_nack_callback` into two callbacks, I am not averse to it.
