### ISSUE TITLE
Remove stop_ioloop_on_close arg from adapter constructors for the 1.0 release

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#961]
Some time ago, the `stop_ioloop_on_close=True` constructor arg slipped into all the asynchronous adapters. I think that the presence of this arg is overly-opinionated. An asynchronous app is likely to have other logic besides a single pika connection running on the same IOLoop (tornado, asyncio, etc.), so having ioloop-stopping logic in pika adapters is too pika-centric, unnecessary, non-orthogonal, and likely error-prone. Especially when it's brain-dead easy for the app to pass `on_close_callback`- having the signature `on_close_callback(connection, reason_code, reason_text)` - to the adapter constructor and call `connection.ioloop.stop()` itself if needed.

I think we should remove the `stop_ioloop_on_close` args everywhere in pika as well as any logic dealing with stopping the ioloop in pika adapters.

**Comment by vitaly-krugl** [comment]
cc @lukebakken

**Comment by lukebakken** [comment]
👍 from me

**Comment by hushenbeg** [comment]
yes, it should be removed from pika
