### ISSUE TITLE
Ungraceful connection of asynchronous connection (Select & Tornado) in v0.11 onward

### ISSUE THREAD

**Issue by banjoh** [pika/pika#972]
From **v0.11** onward, closing a connection produces the warning log below on the server side.
```
=WARNING REPORT==== 23-Feb-2018::09:42:09 ===
closing AMQP connection <0.575.0> (172.17.0.1:45156 -> 172.17.0.2:5672, vhost: '/', user: 'guest'):
client unexpectedly closed TCP connection
```
I reproduced this on *v3.6.15* and *v3.7.3* of rabbitmq-server. I'm running this on a *Ubuntu 16.04* server. My suspicion is that the client side closes the TCP connection before the AMQP connection is properly closed. Could the client perhaps be closing the socket before sending the *Close-OK* handshake to the server?

The warning is very consistent ruling out a race condition.

```python
import logging
from pika import SelectConnection, URLParameters, TornadoConnection
from threading import Thread
from time import sleep
from argparse import ArgumentParser

class AsyncConnection():
    def __init__(self, host):
        self.connection_params = URLParameters('amqp://guest:guest@{}:5672/%2F'.format(host))
        self.log = logging.getLogger(self.__class__.__name__)
        self._connection = None
        
    def connect(self):
        # return TornadoConnection(parameters=self.connection_params,
        return SelectConnection(parameters=self.connection_params,
                                on_close_callback=self.on_connection_close,
                                stop_ioloop_on_close=False)

    def on_connection_close(self, connection, reply_code, reply_text):
        self.log.info('Connection closed')
        self._connection.ioloop.stop()

    def run(self):
        self._connection = self.connect()
        self._connection.ioloop.start()
        self._connection.close()
        self.log.info('IO loop stopped')

    def scheduled_close(self):
        # Added this method for testing asynchronous close
        self._connection.close()

    def stop(self):
        self.log.info('Stopping')
        self._connection.ioloop.stop()
        # Scheduling "close" and stopping the IO loop once the "on_close_callback"
        # cb is called seems to close the connection gracefully. Its a bit un-intuitive though.
        #
        # self._connection.add_timeout(0, self.scheduled_close)


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)

    parser = ArgumentParser()
    parser.add_argument('--host', required=True)

    args = parser.parse_args()
    connection = AsyncConnection(host=args.host)

    def work():
        connection.run()

    t = Thread(target=work)
    t.daemon = True
    t.start()

    try:
        print("Press Ctrl-C to stop")
        while True:
            sleep(1)
    except KeyboardInterrupt:
        connection.stop()
        t.join(timeout=10)
```

And obviously, to run the code use :)

```
python -m client --host N.N.N.N
```

**Comment by lukebakken** [comment]
Hello,

Please see [this code](https://gist.github.com/lukebakken/f95c348f950eb70d958ebefdff25e6d9) which works correctly. I tested it using Python 3.6.4 and the `master` branch of Pika, which will become version `1.0.0` within the next few weeks.

**Comment by banjoh** [comment]
Your approach of closing the connection when stop is called isn't thread safe. I know pika is not thread safe, but his particular use case allows crossing the thread boundary according to [this issue](https://github.com/pika/pika/issues/620).

**Comment by banjoh** [comment]
> Note that it is unusual to close a connection without having done anything with it, like start a consumer.

I stripped off my business logic not to have the issue convoluted. I noticed this in a full-fledged application that's creating queues, binding to queue, publishing to exchanges.. the full works.

**Comment by banjoh** [comment]
Side note: I noticed that ```stop_ioloop_on_close``` constructor parameter has been removed. Has that functionality been deprecated or is there a new API?

Pardon my ignorance if it's an obvious question. I've not taken a look at the new changes coming up but noticed your change.

**Comment by lukebakken** [comment]
> Side note: I noticed that stop_ioloop_on_close constructor parameter has been removed. Has that functionality been deprecated or is there a new API?

Yes, please note that I tested using `master` which will become `1.0.0`. There are quite a few API changes that will be documented.
