### ISSUE TITLE
1.0.0 API changes could raise helpful exceptions

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#977]
If an API change resulted in a parameter order change where the user could pass a callable where it is not intended, Pika could raise `TypeError` with a helpful message.

See the discussion at the end of issues #963 and #945

**Comment by lukebakken** [comment]
We've had one user (@adah1972) characterize the proposed API changes as ["dangerous"](https://github.com/pika/pika/issues/963#issuecomment-368320003). #951 contains discussion with regard to the merits of backwards-compatibility and the amount of hand-holding that Pika will provide with regard to the rename of `no_ack` to `auto_ack`.

**Comment by adah1972** [comment]
I understand fully most of your pro-change arguments. But there is one gotcha. When there are API changes, traditional libraries often will have a separate release to ensure compatibility is not broken, and those releases can be installed and used side by side without conflicts. I suppose Pika will remain ‘pika’ in PyPI, right? In that case, people may incidentally install the wrong version…

So a helpful exception will definitely help. (Unless you want to change to a new package name in PyPI.)
