### ISSUE TITLE
Change pika to accept ssl.SSLContext instead of dict or homegrown SSLOptions attributes for 1.0.0

### ISSUE THREAD

**Issue by vitaly-krugl** [pika/pika#986]
Pre 1.0.0, pika accepts either a dict or a homegrown `pika.connection.SSLOptions` instance and then [converts it to `ssl.SSLContext` (in case of `SSLOptions`) or passes the dict as kwargs to `ssl.wrap_socket()`](https://github.com/pika/pika/blob/09270712bf5912566df8af10ae68a1ddaea4f4e1/pika/adapters/base_connection.py#L512-L539).

I can't think of a good reason to march on to 1.0.0 with this status quo. It's unnecessary and limiting. User's should just be able to pass an `ssl.SSLContext` instance which gives them most flexibility, including the ability to cache ssl contexts. For example, `asyncio` in Python 3 accepts only `ssl.SSLContext` instances.

Proposal for pika 1.0.0:
1. Modify `pika.connection.SSLOptions` constructor to accept only a non-None `ssl.SSLContext` instance and an optional `server_hostname` arg
2. `server_hostname` defaults to None and is used for CN validation - see discussion in issue #464.

**Comment by vitaly-krugl** [comment]
cc @lukebakken

**Comment by michaelklishin** [comment]
Makes sense to me.
