### ISSUE TITLE
Callback naming consistency

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#988]
Following up on @vitaly-krugl's [comment](https://github.com/pika/pika/issues/953#issuecomment-365001220), we're going to use the `on_` prefix with an action verb for all callback parameter names.

**Comment by vitaly-krugl** [comment]
@lukebakken, are you planning to make another sweep and rename all callbacks in pika, or is this something else?

**Comment by lukebakken** [comment]
That's what I'm planning, if you still think the idea is a good one.

**Comment by vitaly-krugl** [comment]
Making the callback names more descriptive would help with making the API more self-documenting. But things are not bad now, so I'm not certain it's worth the extra effort. I'm okay to keep as they are.

**Comment by lukebakken** [comment]
Great, I'll start on some API notes and will make sure all the docstrings are accurate.

**Comment by vitaly-krugl** [comment]
@lukebakken, regarding documentation comment in https://github.com/pika/pika/issues/988#issuecomment-370978795, I was hoping to get the apps away from accessing the connection's internal ioloop, which is often an adapter on top of the native I/O loop. I would not want them to depend on any connection.ioloop API (that's should really be just for the benefit of adapter implementations), calling it's start method, etc. (it shouldn't be even providing a `start()` method). Instead, apps should be interacting with the native I/O loop directly - calling the native loop's `start()`, `run_forever()`, etc.

I started going on this path in my WIP PR https://github.com/pika/pika/pull/982.
