### ISSUE TITLE
DEFAULT_SOCKET_TIMEOUT too short

### ISSUE THREAD

**Issue by kevcampb** [pika/pika#995]
DEFAULT_SOCKET_TIMEOUT is set to 250ms which is non-intuitive. Whilst this may be a sensible value for certain use cases, the default is going to cause real confusion to users who are testing against a remote server.

Effectively similar to the fabled 500 mile email story
  https://www.ibiblio.org/harris/500milemail.html

Set in commit a8c592a4e4ae925f2ca1a3be04621cccef6a4021

**Comment by lukebakken** [comment]
> DEFAULT_SOCKET_TIMEOUT is set to 250ms which is non-intuitive.

Why? What is a better default? Could you provide examples from other popular open-source projects? Simply opening a GitHub issue with an observation isn't very constructive. Even better would be to provide a pull request with your suggested changes and research, data or even anecdotes to back up the change.

**Comment by michaelklishin** [comment]
Bunny uses [30 second timeouts](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/transport.rb#L23). In general any value under the heartbeat timeout makes sense.

5-15 seconds is the range I'd start with.

**Comment by vitaly-krugl** [comment]
After the initial connection establishment in pika, the connection's socket is set to be non-blocking. Non-blocking sockets don't pay attention to socket timeout. So, I am guessing that this issue concerns only the connection-establishment phase, right?

**Comment by michaelklishin** [comment]
@vitaly-krugl that's my reading of the 500 Mile Email story (I wish all users collected data to report first, like that statistics department head!)
