### ISSUE TITLE
error code 505

### ISSUE THREAD

**Issue by vahidmohsseni** [pika/pika#997]
when my clients trying to create new connections to rabbit using blocking connection one client that listens to other clients got this error:
505, 'UNEXPECTED_FRAME - expected method frame, got non method frame instead'
using pika version 0.11.2. also in version 0.10.0 i got this error too

**Comment by lukebakken** [comment]
Please be sure you are connecting to the correct RabbitMQ port which, by default, is `5672`. If you can provide code to reproduce this issue, please attach it here and re-open this GitHub issue (#997)

**Comment by vahidmohsseni** [comment]
yes i`m sure about connecting to the right port. also in my first execution of my script it works good. but in continuous unexpectedly this error happens:
505, 'UNEXPECTED_FRAME - expected method frame, got non method frame instead'
I`m using bad solution now that i try to close previous connection and make new one. but this is not good solution for a pika error!

**Comment by lukebakken** [comment]
Are you using threads or the `multiprocessing` module?

**Comment by vahidmohsseni** [comment]
yes. i'm using threads. but for each thread i have Lock object on sending message.

**Comment by lukebakken** [comment]
Pika is not thread safe and what you're seeing with framing errors is a symptom. Without your code I can't suggest anything other than to open a new connection per thread. It won't affect performance (it might even help performance).

**Comment by vahidmohsseni** [comment]
Ok then. I try to use connections per thread.
I will give thanks to you if you give me some information about what happenning exactly that this error occurs.

**Comment by ichippa96** [comment]
I know this issue has been closed, but I' am getting the same error. I'm using a multiprocessing pool to call a process asynchronously and use basic_publish to push to a single queue from all the async processes.

**Comment by vahidmohsseni** [comment]
> I know this issue has been closed, but I' am getting the same error. I'm using a multiprocessing pool to call a process asynchronously and use basic_publish to push to a single queue from all the async processes.

Try to use independent connections and channels for each thread or process. Your connection and variables **could not be shared** among processes and threads even if you use mutexes.
Just remember that pika is not thread-safe!

**Comment by ichippa96** [comment]
> > I know this issue has been closed, but I' am getting the same error. I'm using a multiprocessing pool to call a process asynchronously and use basic_publish to push to a single queue from all the async processes.
> 
> Try to use independent connections and channels for each thread or process. Your connection and variables **could not be shared** among processes and threads even if you use mutexes.
> Just remember that pika is not thread-safe!

So I should be creating connections and channels inside the async process calls themselves?

**Comment by vahidmohsseni** [comment]
> > > I know this issue has been closed, but I' am getting the same error. I'm using a multiprocessing pool to call a process asynchronously and use basic_publish to push to a single queue from all the async processes.
> > 
> > 
> > Try to use independent connections and channels for each thread or process. Your connection and variables **could not be shared** among processes and threads even if you use mutexes.
> > Just remember that pika is not thread-safe!
> 
> So I should be creating connections and channels inside the async process calls themselves?
Yes Absolutely.

**Comment by ichippa96** [comment]
Thanks a lot :)
