### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by Tobi73** [pika/pika#999]
We are having this issue on multiple consumers

`Traceback (most recent call last):   File "/fileparser/fileparser/app.py", line 65, in parse_files     self.rabbit_worker.publish_data(tid, self.parse_notify)   File "/fileparser/queuehandler/rabbit_mq.py", line 102, in publish_data     properties=pika.BasicProperties(content_encoding=self.encoding, delivery_mode=2))   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish     mandatory, immediate)   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 2164, in publish     self._flush_output()   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output     *waiters)   File "/usr/local/lib/python3.6/dist-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output     result.reason_text) pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")`

**Comment by lukebakken** [comment]
That is not enough information to work with here. "Connection reset by peer" means that either RabbitMQ terminated the TCP connection unexpectedly (a crash, maybe?) or something between your application and RabbitMQ terminated it (like a proxy - this is more likely).

Please post this to the [RabbitMQ users mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users), along with the following information:

* Timestamp of this event
* RabbitMQ, Erlang and operating system version
* Environment details (cloud provider, proxy between application and RabbitMQ, etc)
* Complete log files from RabbitMQ
